#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_MEMSET 1
#define HAVE_STRDUP 1
#define HAVE_STRINGIZE 1
#define FRIBIDI_ENTRY
#define FRIBIDI_LIB_STATIC 1
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_VOID_P 8
