/*
 * MiniAndroid Runtime v0.1 - Software Rendering Pipeline Implementation
 * EXP-005: Minimal Software Renderer
 */

#include "software_renderer.h"
#include "runtime/object_model.h"
#include <fstream>
#include <chrono>
#include <cstring>
#include <cstdlib>
// EXP-086 Phase 3 (B1 FIX): zlib for proper PNG IDAT compression
#include <zlib.h>
// CAMPAIGN 010 R1: libpng for PNG decode (was: hand-written decoder) + encode
#include <png.h>
#include <csetjmp>
#include <algorithm>

// EXP-097 §5/§6: Image codec libraries.
// libwebp is Google's reference WebP decoder (BSD) — AOSP's Bitmap region
// decoder and Skia both delegate to it for WebP.
// libjpeg (IJG) is the JPEG reference decoder — Android ships libjpeg-turbo
// (a drop-in replacement using the same API).
#include <webp/decode.h>
#include <webp/demux.h>

extern "C" {
#include <stdio.h>
#include <jpeglib.h>
#include <setjmp.h>
}

namespace miniandroid {
namespace renderer {

// ============================================================================
// Bitmap Font Data (8x16 pixel glyphs) — EXP-092
// ============================================================================
//
// The font data is auto-generated by /home/z/my-project/scripts/gen_bitmap_font.py
// from the DejaVuSansMono TTF. It covers all 95 printable ASCII chars (32..126).
//
// Each glyph is 16 bytes (one per row), each byte's 8 bits (MSB first)
// indicating which columns are dark. The previous hand-coded font only had
// 13 glyphs (and was mis-indexed — 'H' was overwritten by 'A' in slot 33).
// All other chars fell through to a "dot in the middle" default bitmap.
//
// To regenerate (e.g. after changing the font source or size):
//   python3 /home/z/my-project/scripts/gen_bitmap_font.py
//
#include "bitmap_font_data.h"

// ============================================================================
// BitmapFont Implementation
// ============================================================================

BitmapFont::BitmapFont() {
    initialize_ascii_glyphs();
}

void BitmapFont::initialize_ascii_glyphs() {
    // EXP-092: Initialize glyphs_ from the auto-generated bitmap_font_table.
    // Table index i corresponds to ASCII char (i + 32).
    for (int i = 0; i < 95; i++) {
        const auto& entry = miniandroid::renderer::bitmap_font_table[i];
        glyphs_[i] = {entry.character, entry.width, entry.height, entry.advance, entry.bitmap};
    }
    fill_remaining_glyphs();
}

void BitmapFont::fill_remaining_glyphs() {
    // EXP-092: With the auto-generated table, every slot is already populated.
    // This function is kept for API compatibility with the previous design,
    // but it is now effectively a no-op — every glyph already has its
    // character/bitmap/advance set correctly.
    //
    // Safety check: if any glyph is still '\0' (shouldn't happen, but
    // defends against future regressions), fill it with the space bitmap
    // so we never dereference a null `bitmap` pointer.
    static const uint8_t fallback_bitmap[16] = {
        0x00, 0x00, 0x00, 0x00, 0x18, 0x18, 0x18, 0x18,
        0x18, 0x18, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
    };
    for (int i = 0; i < 95; i++) {
        if (glyphs_[i].character == '\0') {
            char c = static_cast<char>(i + 32);
            glyphs_[i] = {c, 5, 16, 6, fallback_bitmap};
        }
    }
}

const BitmapFont::Glyph* BitmapFont::get_glyph(char c) const {
    if (c >= 32 && c <= 126) {
        return &glyphs_[c - 32];
    }
    return &glyphs_[0];  // Return space for unknown chars
}

BitmapFont::TextMetrics BitmapFont::measure_text(const std::string& text) const {
    TextMetrics metrics{0, 16, 12, 4};
    
    for (char c : text) {
        const Glyph* glyph = get_glyph(c);
        metrics.width += glyph->advance;
    }
    
    return metrics;
}

json BitmapFont::to_info_json() const {
    return {
        {"font_name", "MiniAndroid_Bitmap_8x16"},
        {"glyph_count", 95},
        {"line_height", get_line_height()},
        {"baseline_offset", get_baseline_offset()},
        {"supported_range", "ASCII 32-126"}
    };
}

// ============================================================================
// LayoutNode Implementation
// ============================================================================

json LayoutNode::to_json() const {
    json j;
    j["object_id"] = object_id;
    j["view_class"] = view_class;
    j["bounds"] = bounds.to_json();
    if (!children.empty()) {
        json children_arr = json::array();
        for (const auto& child : children) {
            children_arr.push_back(child.to_json());
        }
        j["children"] = children_arr;
    }
    return j;
}

// ============================================================================
// SoftwareCanvas Implementation
// ============================================================================

SoftwareCanvas::SoftwareCanvas(FrameBuffer* framebuffer)
    : framebuffer_(framebuffer), command_sequence_(0) {}

void SoftwareCanvas::draw_color(RGBA color) {
    framebuffer_->clear(color);
    
    CanvasCommand cmd;
    cmd.type = "drawColor";
    cmd.sequence = ++command_sequence_;
    cmd.params["color"] = color.to_json();
    commands_.push_back(cmd);
}

void SoftwareCanvas::draw_rect(float left, float top, float right, float bottom, RGBA color) {
    int x1 = static_cast<int>(std::round(left));
    int y1 = static_cast<int>(std::round(top));
    int x2 = static_cast<int>(std::round(right));
    int y2 = static_cast<int>(std::round(bottom));
    
    for (int y = y1; y < y2 && y < framebuffer_->get_height(); y++) {
        for (int x = x1; x < x2 && x < framebuffer_->get_width(); x++) {
            if (x >= 0 && y >= 0) {
                framebuffer_->set_pixel(x, y, color);
            }
        }
    }
    
    CanvasCommand cmd;
    cmd.type = "drawRect";
    cmd.sequence = ++command_sequence_;
    cmd.params["rect"] = {{"left", x1}, {"top", y1}, {"right", x2}, {"bottom", y2}};
    cmd.params["color"] = color.to_json();
    commands_.push_back(cmd);
}

void SoftwareCanvas::draw_text(const std::string& text, float x, float y, RGBA color,
                               const BitmapFont* font) {
    const BitmapFont* use_font = font ? font : &default_font_;
    
    auto metrics = use_font->measure_text(text);
    int start_x = static_cast<int>(std::round(x));
    int start_y = static_cast<int>(std::round(y)) - use_font->get_baseline_offset();
    
    // Render each character
    int current_x = start_x;
    for (char c : text) {
        const BitmapFont::Glyph* glyph = use_font->get_glyph(c);
        
        // Render glyph bitmap
        for (int row = 0; row < glyph->height; row++) {
            uint8_t bitmap_row = glyph->bitmap[row];
            for (int col = 0; col < 8; col++) {
                if (bitmap_row & (0x80 >> col)) {
                    framebuffer_->set_pixel(current_x + col, start_y + row, color);
                }
            }
        }
        
        current_x += glyph->advance;
    }
    
    CanvasCommand cmd;
    cmd.type = "drawText";
    cmd.sequence = ++command_sequence_;
    cmd.params["text"] = text;
    cmd.params["position"] = {{"x", start_x}, {"y", start_y}};
    cmd.params["color"] = color.to_json();
    cmd.params["measured_width"] = metrics.width;
    cmd.params["measured_height"] = metrics.height;
    commands_.push_back(cmd);
}

json SoftwareCanvas::to_trace_json() const {
    json trace;
    trace["total_commands"] = command_sequence_;
    trace["commands"] = json::array();
    for (const auto& cmd : commands_) {
        trace["commands"].push_back(cmd.to_json());
    }
    return trace;
}

// ============================================================================
// EXP-088 Phase A4: SoftwareCanvas::draw_image
//
// Draws an RGBA pixel buffer (decoded from a PNG via PNGDecoder) into the
// framebuffer at (dst_x, dst_y). Optional scaling to dst_w x dst_h.
//
// Uses nearest-neighbour sampling for scaling — no fancy interpolation,
// because the source PNGs we care about (simplestopwatch icons) are tiny
// and need to render at their natural size anyway.
//
// Pixels with alpha < 255 are alpha-blended onto the existing framebuffer
// pixel using the standard "over" compositing operator. This is essential
// because:
//   - simplestopwatch's lock.png is grayscale+alpha with partial transparency
//   - if we just stomped (R,G,B,0) over the framebuffer we'd lose the icon
// ============================================================================

void SoftwareCanvas::draw_image(const uint8_t* src_rgba, int src_w, int src_h,
                                int dst_x, int dst_y,
                                int dst_w, int dst_h) {
    if (!src_rgba || src_w <= 0 || src_h <= 0) return;
    if (dst_w <= 0)  dst_w = src_w;
    if (dst_h <= 0)  dst_h = src_h;

    int fb_w = framebuffer_->get_width();
    int fb_h = framebuffer_->get_height();

    for (int dy = 0; dy < dst_h; dy++) {
        int sy = (dy * src_h) / dst_h;  // nearest-neighbour
        if (sy < 0 || sy >= src_h) continue;
        for (int dx = 0; dx < dst_w; dx++) {
            int sx = (dx * src_w) / dst_w;
            if (sx < 0 || sx >= src_w) continue;

            const uint8_t* p = src_rgba + (sy * src_w + sx) * 4;
            RGBA src(p[0], p[1], p[2], p[3]);

            int x = dst_x + dx;
            int y = dst_y + dy;
            if (x < 0 || x >= fb_w || y < 0 || y >= fb_h) continue;

            // Alpha-blend with existing pixel
            RGBA dst = framebuffer_->get_pixel(x, y);
            RGBA out = blend(src, dst);
            framebuffer_->set_pixel(x, y, out);
        }
    }

    CanvasCommand cmd;
    cmd.type = "drawImage";
    cmd.sequence = ++command_sequence_;
    cmd.params["src_size"] = {{"w", src_w}, {"h", src_h}};
    cmd.params["dst_pos"]   = {{"x", dst_x}, {"y", dst_y}};
    cmd.params["dst_size"]  = {{"w", dst_w}, {"h", dst_h}};
    commands_.push_back(cmd);
}

// ============================================================================
// PNG Decoder — CAMPAIGN 010 R1: libpng-backed (replaces the EXP-088 A4
// hand-written decoder after a differential benchmark over 7,036 real APK
// PNGs showed the custom decoder failing 206 files (bit_depth 1/2/4) and
// mis-decoding 3 tRNS files, while libpng decoded 100% byte-identically to
// stb_image v2.30 and 1.65x faster than the custom code.
//
// libpng is the reference PNG implementation (libpng.org) and is the same
// decoder Android's own stack uses (libjpeg-turbo + libpng inside Skia).
// Coverage now includes everything the old code rejected:
//   - bit depths 1/2/4/8/16 (16 stripped to 8 per Android Bitmap ARGB_8888)
//   - color types 0/2/3/4/6 (palette via png_set_palette_to_rgb)
//   - tRNS transparency (png_set_expand)  [the 3-file custom-decoder bug]
//   - Adam7 interlacing (png_set_interlace_handling)
// Output contract unchanged: RGBA8 buffer, .color_type_name mirrors the
// source color type, .ok=false with descriptive error on failure.
// ============================================================================

namespace {

// libpng memory reader (whole-file buffer context)
struct PngMemCtx { const uint8_t* data; size_t size; size_t off; };

void png_mem_read(png_structp png, png_bytep out, png_size_t n) {
    PngMemCtx* c = static_cast<PngMemCtx*>(png_get_io_ptr(png));
    if (c->off + n > c->size) {
        png_error(png, "read past end of PNG buffer");
        return;
    }
    std::memcpy(out, c->data + c->off, n);
    c->off += n;
}

const char* png_color_type_name(png_byte ct) {
    switch (ct) {
        case 0: return "gray";
        case 2: return "rgb";
        case 3: return "palette→rgba";
        case 4: return "ga";
        case 6: return "rgba";
        default: return "unknown";
    }
}

}  // namespace

DecodedImage PNGDecoder::decode(const std::vector<uint8_t>& png_bytes) {
    DecodedImage result;
    if (png_bytes.size() < 8) {
        result.error = "PNG too small";
        return result;
    }
    static const uint8_t SIG[8] = {137, 80, 78, 71, 13, 10, 26, 10};
    if (std::memcmp(png_bytes.data(), SIG, 8) != 0) {
        result.error = "bad PNG signature";
        return result;
    }

    png_structp png = png_create_read_struct(PNG_LIBPNG_VER_STRING,
                                             nullptr, nullptr, nullptr);
    if (!png) {
        result.error = "png_create_read_struct failed";
        return result;
    }
    png_infop info = png_create_info_struct(png);
    if (!info) {
        png_destroy_read_struct(&png, nullptr, nullptr);
        result.error = "png_create_info_struct failed";
        return result;
    }

    PngMemCtx ctx{png_bytes.data(), png_bytes.size(), 0};
    if (setjmp(png_jmpbuf(png))) {
        png_destroy_read_struct(&png, &info, nullptr);
        result.error = "libpng: invalid or corrupted PNG stream";
        return result;
    }

    png_set_read_fn(png, &ctx, png_mem_read);
    png_read_info(png, info);

    png_byte orig_ct = png_get_color_type(png, info);
    result.color_type_name = png_color_type_name(orig_ct);

    // Android Bitmap contract: everything expands to ARGB_8888.
    png_set_palette_to_rgb(png);
    if (png_get_bit_depth(png, info) < 8) png_set_packing(png);
    if (png_get_bit_depth(png, info) == 16) png_set_strip_16(png);
    if (orig_ct == PNG_COLOR_TYPE_GRAY || orig_ct == PNG_COLOR_TYPE_GRAY_ALPHA)
        png_set_gray_to_rgb(png);
    // tRNS → full alpha channel. NOTE: png_set_expand alone does NOT expand
    // tRNS for 8-bit RGB/gray (caught by the a4 fixture test) —
    // png_set_tRNS_to_alpha covers palette/gray/RGB tRNS per PNG spec §11.3.2.
    png_set_tRNS_to_alpha(png);
    png_set_filler(png, 0xFF, PNG_FILLER_AFTER);
    png_set_interlace_handling(png);
    png_read_update_info(png, info);

    result.width  = static_cast<int>(png_get_image_width(png, info));
    result.height = static_cast<int>(png_get_image_height(png, info));
    size_t rowbytes = png_get_rowbytes(png, info);
    result.rgba.resize(rowbytes * result.height);
    std::vector<png_bytep> rows(result.height);
    for (int y = 0; y < result.height; y++)
        rows[y] = result.rgba.data() + static_cast<size_t>(y) * rowbytes;

    png_read_image(png, rows.data());
    png_read_end(png, nullptr);
    png_destroy_read_struct(&png, &info, nullptr);

    result.ok = true;
    return result;
}

DecodedImage PNGDecoder::decode_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate);
    if (!f.is_open()) {
        DecodedImage r;
        r.error = "cannot open file: " + path;
        return r;
    }
    auto sz = f.tellg();
    f.seekg(0, std::ios::beg);
    std::vector<uint8_t> buf(sz);
    f.read(reinterpret_cast<char*>(buf.data()), sz);
    return decode(buf);
}

// ============================================================================
// Helper Functions
// ============================================================================

std::string stage_to_string(RenderStage stage) {
    switch (stage) {
        case RenderStage::IDLE: return "IDLE";
        case RenderStage::LAYOUT: return "LAYOUT";
        case RenderStage::MEASURE: return "MEASURE";
        case RenderStage::DRAW: return "DRAW";
        case RenderStage::COMPLETE: return "COMPLETE";
        case RenderStage::ERROR: return "ERROR";
        default: return "UNKNOWN";
    }
}

// ============================================================================
// RenderStatistics Implementation
// ============================================================================

json RenderStatistics::to_json() const {
    return {
        {"total_views_processed", total_views_processed},
        {"text_views_rendered", text_views_rendered},
        {"total_commands_issued", total_commands_issued},
        {"pixels_written", pixels_written},
        {"timing", {
            {"layout_ms", layout_time_ms},
            {"measure_ms", measure_time_ms},
            {"draw_ms", draw_time_ms},
            {"total_ms", total_time_ms}
        }}
    };
}

// ============================================================================
// RenderPipeline Implementation
// ============================================================================

RenderPipeline::RenderPipeline(int width, int height)
    : framebuffer_(width, height), canvas_(&framebuffer_)
    , stage_(RenderStage::IDLE), frame_number_(0) {}

bool RenderPipeline::render(runtime::EnhancedObjectHeap& heap, const std::string& activity_text) {
    auto total_start = std::chrono::high_resolution_clock::now();
    
    stage_ = RenderStage::LAYOUT;
    
    // Stage 1: Layout
    auto layout_start = std::chrono::high_resolution_clock::now();
    bool layout_ok = perform_layout(heap);
    auto layout_end = std::chrono::high_resolution_clock::now();
    stats_.layout_time_ms = std::chrono::duration<double, std::milli>(layout_end - layout_start).count();
    
    if (!layout_ok) {
        stage_ = RenderStage::ERROR;
        return false;
    }
    
    // Stage 2: Measure
    stage_ = RenderStage::MEASURE;
    auto measure_start = std::chrono::high_resolution_clock::now();
    bool measure_ok = perform_measurement();
    auto measure_end = std::chrono::high_resolution_clock::now();
    stats_.measure_time_ms = std::chrono::duration<double, std::milli>(measure_end - measure_start).count();
    
    if (!measure_ok) {
        stage_ = RenderStage::ERROR;
        return false;
    }
    
    // Stage 3: Draw
    stage_ = RenderStage::DRAW;
    auto draw_start = std::chrono::high_resolution_clock::now();
    bool draw_ok = perform_draw(heap, activity_text);
    auto draw_end = std::chrono::high_resolution_clock::now();
    stats_.draw_time_ms = std::chrono::duration<double, std::milli>(draw_end - draw_start).count();
    
    if (!draw_ok) {
        stage_ = RenderStage::ERROR;
        return false;
    }
    
    // Complete
    auto total_end = std::chrono::high_resolution_clock::now();
    stats_.total_time_ms = std::chrono::duration<double, std::milli>(total_end - total_start).count();
    stats_.pixels_written = framebuffer_.get_draw_count();
    stats_.total_commands_issued = static_cast<int>(canvas_.get_command_count());
    
    stage_ = RenderStage::COMPLETE;
    frame_number_++;
    
    return true;
}

bool RenderPipeline::perform_layout(runtime::EnhancedObjectHeap& heap) {
    // Find Activity and build layout tree from it
    auto activity_ids = heap.get_objects_by_class("android.app.Activity");
    
    if (activity_ids.empty()) {
        // No Activity found, try to build from all objects
        auto all_ids = heap.get_all_ids();
        if (!all_ids.empty()) {
            layout_tree_ = build_layout_tree(all_ids[0], heap);
            return true;
        }
        return false;
    }
    
    layout_tree_ = build_layout_tree(activity_ids[0], heap);
    
    // Apply initial layout to root (full screen)
    layout_view(layout_tree_, 0, 0, framebuffer_.get_width(), framebuffer_.get_height());
    
    stats_.total_views_processed++;
    
    return true;
}

bool RenderPipeline::perform_measurement() {
    // Measure text views in the layout tree
    // This is handled during draw phase with actual text content
    return true;
}

bool RenderPipeline::perform_draw(runtime::EnhancedObjectHeap& heap, const std::string& activity_text) {
    // Clear background
    canvas_.draw_color(Colors::GREY_200);  // Light grey background like Android
    
    // Draw Activity background (optional - could be transparent)
    // For now, just draw the TextView with the activity text
    
    // Find TextView objects and render them
    auto tv_ids = heap.get_objects_by_class("android.widget.TextView");
    
    for (uint32_t tv_id : tv_ids) {
        auto* tv = heap.get_as<runtime::TextViewRuntimeObject>(tv_id);
        if (tv) {
            std::string text_to_render = tv->get_text().empty() ? activity_text : tv->get_text();
            
            // Get bounds from layout tree or use defaults
            int text_x = 50;  // Margin from left
            int text_y = 100; // Position from top
            
            // Draw text
            canvas_.draw_text(text_to_render, text_x, text_y + font_.get_line_height(), 
                            Colors::GREY_800, &font_);
            
            stats_.text_views_rendered++;
        }
    }
    
    // If no TextView found, still render the text (for demo purposes)
    if (stats_.text_views_rendered == 0 && !activity_text.empty()) {
        canvas_.draw_text(activity_text, 50, 100 + font_.get_line_height(), 
                        Colors::GREY_800, &font_);
        stats_.text_views_rendered = 1;
    }
    
    return true;
}

LayoutNode RenderPipeline::build_layout_tree(uint32_t object_id, runtime::EnhancedObjectHeap& heap, int depth) {
    LayoutNode node;
    node.object_id = object_id;
    
    auto* obj = heap.get(object_id);
    if (obj) {
        node.view_class = obj->get_runtime_class();
        
        // Try to get geometry from View/TextView objects
        auto* view_obj = dynamic_cast<const runtime::ViewRuntimeObject*>(obj);
        if (view_obj) {
            auto geom = view_obj->get_geometry();
            node.bounds.set(geom.left, geom.top, geom.width, geom.height);
        }
        
        // For Activity, find child TextViews and add them as children
        if (node.view_class == "android.app.Activity") {
            auto tv_ids = heap.get_objects_by_class("android.widget.TextView");
            for (uint32_t tv_id : tv_ids) {
                LayoutNode child_node = build_layout_tree(tv_id, heap, depth + 1);
                node.children.push_back(child_node);
            }
        }
    }
    
    // Limit depth to prevent infinite loops
    if (depth > 10) {
        return node;
    }
    
    return node;
}

void RenderPipeline::layout_view(LayoutNode& node, int parent_left, int parent_top, 
                                 int parent_width, int parent_height) {
    if (node.bounds.is_empty()) {
        // Default: use full parent size for Activity, reasonable size for others
        if (node.view_class == "android.app.Activity") {
            node.bounds.set(parent_left, parent_top, parent_width, parent_height);
        } else if (node.view_class.find("TextView") != std::string::npos) {
            // TextView gets centered area with padding
            int padding = 40;
            int text_height = font_.get_line_height() + 20;
            node.bounds.set(parent_left + padding, parent_top + 100, 
                          parent_width - 2 * padding, text_height);
        } else {
            node.bounds.set(parent_left + 10, parent_top + 10, 
                          parent_width - 20, parent_height - 20);
        }
    }
    
    // Layout children
    for (auto& child : node.children) {
        layout_view(child, node.bounds.left, node.bounds.top, 
                   node.bounds.width(), node.bounds.height());
    }
}

// ============================================================================
// Render Pipeline Trace Methods
// ============================================================================

json RenderPipeline::get_layout_trace() const {
    json trace;
    trace["stage"] = "LAYOUT";
    trace["layout_tree"] = layout_tree_.to_json();
    trace["timestamp_ms"] = stats_.layout_time_ms;
    return trace;
}

json RenderPipeline::get_measure_trace() const {
    json trace;
    trace["stage"] = "MEASURE";
    trace["measurements"] = json::array();
    
    for (const auto& [id, metrics] : text_metrics_cache_) {
        json m;
        m["object_id"] = id;
        m["width"] = metrics.width;
        m["height"] = metrics.height;
        m["ascent"] = metrics.ascent;
        m["descent"] = metrics.descent;
        trace["measurements"].push_back(m);
    }
    
    trace["font_info"] = font_.to_info_json();
    trace["timestamp_ms"] = stats_.measure_time_ms;
    return trace;
}

json RenderPipeline::get_canvas_trace() const {
    json trace;
    trace["stage"] = "CANVAS_COMMANDS";
    trace["canvas_trace"] = canvas_.to_trace_json();
    return trace;
}

json RenderPipeline::get_render_trace() const {
    json trace;
    trace["experiment"] = "EXP-005";
    trace["pipeline_status"] = stage_to_string(stage_);
    trace["frame_number"] = frame_number_;
    trace["statistics"] = stats_.to_json();
    trace["framebuffer_info"] = framebuffer_.to_info_json();
    trace["layout"] = get_layout_trace();
    trace["canvas"] = get_canvas_trace();
    return trace;
}

json RenderPipeline::get_text_render_trace() const {
    json trace;
    trace["stage"] = "TEXT_RENDERING";
    trace["text_views_rendered"] = stats_.text_views_rendered;
    trace["font_used"] = font_.to_info_json();
    
    // Extract text-related commands from canvas
    json text_commands = json::array();
    for (const auto& cmd : canvas_.get_commands()) {
        if (cmd.type == "drawText") {
            text_commands.push_back(cmd.to_json());
        }
    }
    trace["text_commands"] = text_commands;
    
    return trace;
}

// ============================================================================
// PNG Writer — CAMPAIGN 010 R1: libpng-backed (replaces the hand-written
// chunk/zlib encoder; same pixel content, standard libpng byte stream).
// ============================================================================

bool PNGWriter::write_png(const std::string& filename, const FrameBuffer& fb) {
    std::ofstream file(filename, std::ios::binary);
    if (!file.is_open()) {
        return false;
    }
    file.close();

    int width = fb.get_width();
    int height = fb.get_height();

    FILE* fp = std::fopen(filename.c_str(), "wb");
    if (!fp) return false;

    png_structp png = png_create_write_struct(PNG_LIBPNG_VER_STRING,
                                              nullptr, nullptr, nullptr);
    if (!png) { std::fclose(fp); return false; }
    png_infop info = png_create_info_struct(png);
    if (!info) {
        png_destroy_write_struct(&png, nullptr);
        std::fclose(fp);
        return false;
    }
    if (setjmp(png_jmpbuf(png))) {
        png_destroy_write_struct(&png, &info);
        std::fclose(fp);
        return false;
    }
    png_init_io(png, fp);
    // Same output pixel contract as the custom encoder: 8-bit RGB.
    png_set_IHDR(png, info, width, height, 8, PNG_COLOR_TYPE_RGB,
                 PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_DEFAULT,
                 PNG_FILTER_TYPE_DEFAULT);
    png_write_info(png, info);

    std::vector<uint8_t> row(size_t(width) * 3);
    for (int y = 0; y < height; y++) {
        for (int x = 0; x < width; x++) {
            RGBA pixel = fb.get_pixel(x, y);
            row[size_t(x) * 3 + 0] = pixel.r;
            row[size_t(x) * 3 + 1] = pixel.g;
            row[size_t(x) * 3 + 2] = pixel.b;
        }
        png_write_row(png, row.data());
    }
    png_write_end(png, info);
    png_destroy_write_struct(&png, &info);
    std::fclose(fp);
    return true;
}


json PNGWriter::generate_screenshot_info(const FrameBuffer& fb, 
                                        const RenderPipeline& pipeline,
                                        const std::string& text_content) {
    json info;
    info["filename"] = "screenshot.png";
    info["format"] = "PNG";
    info["width"] = fb.get_width();
    info["height"] = fb.get_height();
    info["frame_number"] = pipeline.get_frame_number();
    info["rendered_objects"] = pipeline.get_statistics()["text_views_rendered"];
    info["text_content"] = text_content;
    info["pipeline_stage"] = stage_to_string(pipeline.get_stage());
    info["total_commands"] = pipeline.get_canvas().get_command_count();
    info["pixels_written"] = fb.get_draw_count();
    info["generation_timestamp"] = std::chrono::duration_cast<std::chrono::milliseconds>(
        std::chrono::system_clock::now().time_since_epoch()
    ).count();
    
    return info;
}

} // namespace renderer
} // namespace miniandroid

// ============================================================================
// EXP-097 §5: WebPDecoder — libwebp-backed WebP → RGBA decoder.
//
// Per AOSP `BitmapFactory.nativeDecodeByteArray`:
//   1. Validate WebP RIFF header (libwebp's WebPGetInfo does this).
//   2. Allocate output buffer of width * height * 4 bytes (RGBA).
//   3. Call WebPDecodeRGBA which delegates to the right internal decoder
//      (VP8 lossy, VP8L lossless, or VP8X extended). For animated WebPs
//      the FIRST frame is returned (animation is a separate concern).
//   4. Free libwebp's allocated buffer via WebPFree after copying.
//
// We mirror that flow exactly. The runtime's PNGDecoder returns RGBA in
// the same DecodedImage shape — so the renderer's draw_image() works with
// either decoder without specialization.
// ============================================================================
namespace miniandroid {
namespace renderer {

DecodedImage WebPDecoder::decode(const std::vector<uint8_t>& webp_bytes) {
    DecodedImage result;
    if (webp_bytes.size() < 12) {
        result.error = "WebP too small (need at least 12 bytes for RIFF header)";
        return result;
    }
    // Per WebP Container Spec §2: signature is 'RIFF' + 4-byte size + 'WEBP'
    if (webp_bytes[0] != 'R' || webp_bytes[1] != 'I' ||
        webp_bytes[2] != 'F' || webp_bytes[3] != 'F' ||
        webp_bytes[8] != 'W' || webp_bytes[9] != 'E' ||
        webp_bytes[10] != 'B' || webp_bytes[11] != 'P') {
        result.error = "bad WebP signature (expected RIFF...WEBP)";
        return result;
    }

    int w = 0, h = 0;
    // WebPGetInfo validates the bitstream and returns width/height.
    if (!WebPGetInfo(webp_bytes.data(), webp_bytes.size(), &w, &h)) {
        result.error = "WebPGetInfo failed (corrupt or unsupported WebP)";
        return result;
    }
    if (w <= 0 || h <= 0 || w > 65536 || h > 65536) {
        result.error = "WebP invalid dimensions: " + std::to_string(w) + "x" + std::to_string(h);
        return result;
    }

    // Decode to RGBA. The returned pointer is libwebp-owned; we copy.
    uint8_t* rgba = WebPDecodeRGBA(webp_bytes.data(), webp_bytes.size(), &w, &h);
    if (rgba == nullptr) {
        result.error = "WebPDecodeRGBA failed (decoder rejected bitstream)";
        return result;
    }

    // Verify width/height didn't change during decode (shouldn't happen).
    size_t pixel_count = static_cast<size_t>(w) * h * 4;
    result.rgba.assign(rgba, rgba + pixel_count);
    WebPFree(rgba);

    result.ok = true;
    result.width = w;
    result.height = h;
    // Determine format from VP8 chunk type for diagnostics.
    char fmt[5] = {0, 0, 0, 0, 0};
    if (webp_bytes.size() >= 16) {
        std::memcpy(fmt, webp_bytes.data() + 12, 4);
    }
    result.color_type_name = std::string("webp-") + fmt;
    return result;
}

DecodedImage WebPDecoder::decode_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        DecodedImage r;
        r.error = "cannot open file: " + path;
        return r;
    }
    return decode(std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                                       std::istreambuf_iterator<char>()));
}

// ============================================================================
// EXP-097 §6: JPEGDecoder — libjpeg-backed JPEG → RGBA decoder.
//
// Per AOSP `BitmapFactory.nativeDecodeByteArray`: libjpeg's standard
// jpeg_decompress_struct flow:
//   1. jpeg_create_decompress
//   2. jpeg_mem_src (read from memory)
//   3. jpeg_read_header
//   4. Set output color space to JCS_EXT_RGBA (libjpeg-turbo) — but base
//      libjpeg only supports JCS_RGB. We request RGB and expand to RGBA
//      ourselves so both libjpeg and libjpeg-turbo work.
//   5. jpeg_start_decompress
//   6. Read scanlines into a row buffer
//   7. jpeg_finish_decompress + jpeg_destroy_decompress
//
// libjpeg uses setjmp/longjmp for fatal error recovery; we install a
// jmp_buf and a custom error_exit handler so a corrupt JPEG returns
// ok=false instead of aborting the whole process.
// ============================================================================

namespace {
struct JpegErrorCtx {
    jpeg_error_mgr pub;  // libjpeg's standard error manager
    jmp_buf setjmp_buf;  // fatal-error escape hatch
    std::string error_msg;
};

void jpeg_error_exit(j_common_ptr cinfo) {
    auto* ctx = reinterpret_cast<JpegErrorCtx*>(cinfo->err);
    // Format the libjpeg error message for diagnostics.
    char buf[JMSG_LENGTH_MAX];
    (*ctx->pub.format_message)(cinfo, buf);
    ctx->error_msg = std::string("libjpeg error: ") + buf;
    longjmp(ctx->setjmp_buf, 1);
}
}  // namespace

DecodedImage JPEGDecoder::decode(const std::vector<uint8_t>& jpeg_bytes) {
    DecodedImage result;
    if (jpeg_bytes.size() < 2 ||
        jpeg_bytes[0] != 0xFF || jpeg_bytes[1] != 0xD8) {
        result.error = "bad JPEG signature (expected FF D8)";
        return result;
    }

    struct jpeg_decompress_struct cinfo;
    JpegErrorCtx jerr;
    cinfo.err = jpeg_std_error(&jerr.pub);
    jerr.pub.error_exit = jpeg_error_exit;

    if (setjmp(jerr.setjmp_buf)) {
        // Fatal libjpeg error: cleanup and return.
        jpeg_destroy_decompress(&cinfo);
        result.error = jerr.error_msg;
        return result;
    }

    jpeg_create_decompress(&cinfo);
    jpeg_mem_src(&cinfo, jpeg_bytes.data(), jpeg_bytes.size());

    if (jpeg_read_header(&cinfo, TRUE) != JPEG_HEADER_OK) {
        jpeg_destroy_decompress(&cinfo);
        result.error = "jpeg_read_header failed (not a valid JPEG)";
        return result;
    }

    // Force RGB output (works with both libjpeg and libjpeg-turbo).
    cinfo.out_color_space = JCS_RGB;

    if (!jpeg_start_decompress(&cinfo)) {
        jpeg_destroy_decompress(&cinfo);
        result.error = "jpeg_start_decompress failed";
        return result;
    }

    int w = static_cast<int>(cinfo.output_width);
    int h = static_cast<int>(cinfo.output_height);
    if (w <= 0 || h <= 0) {
        jpeg_destroy_decompress(&cinfo);
        result.error = "JPEG invalid dimensions";
        return result;
    }

    // Read scanlines into a temporary RGB buffer, then expand to RGBA.
    result.rgba.assign(static_cast<size_t>(w) * h * 4, 0xFF);  // default alpha=255
    std::vector<uint8_t> row_buf(static_cast<size_t>(w) * 3);
    while (cinfo.output_scanline < static_cast<JDIMENSION>(h)) {
        JSAMPROW row = row_buf.data();
        JSAMPARRAY rows = &row;
        jpeg_read_scanlines(&cinfo, rows, 1);
        size_t y = cinfo.output_scanline - 1;
        for (int x = 0; x < w; x++) {
            result.rgba[(y * w + x) * 4 + 0] = row_buf[x * 3 + 0];
            result.rgba[(y * w + x) * 4 + 1] = row_buf[x * 3 + 1];
            result.rgba[(y * w + x) * 4 + 2] = row_buf[x * 3 + 2];
            // alpha left at 0xFF (set above)
        }
    }

    jpeg_finish_decompress(&cinfo);
    jpeg_destroy_decompress(&cinfo);

    result.ok = true;
    result.width = w;
    result.height = h;
    result.color_type_name = (cinfo.num_components == 1) ? "jpeg-gray→rgba" : "jpeg-rgb→rgba";
    return result;
}

DecodedImage JPEGDecoder::decode_file(const std::string& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        DecodedImage r;
        r.error = "cannot open file: " + path;
        return r;
    }
    return decode(std::vector<uint8_t>((std::istreambuf_iterator<char>(f)),
                                       std::istreambuf_iterator<char>()));
}

// ============================================================================
// EXP-097 §7: RLottieDecoder — rlottie-backed Lottie JSON → RGBA renderer.
// ============================================================================
extern "C" {
#include <rlottie_capi.h>
}

RLottieDecoder::DecodedAnim RLottieDecoder::decode(const std::string& json_str,
                                                    int target_w, int target_h,
                                                    int max_frames) {
    DecodedAnim result;
    if (json_str.empty()) {
        result.error = "empty Lottie JSON";
        return result;
    }
    if (target_w <= 0 || target_h <= 0) {
        result.error = "invalid render dimensions: " +
                       std::to_string(target_w) + "x" + std::to_string(target_h);
        return result;
    }

    // rlottie requires the JSON be null-terminated. We append a NUL — the
    // input string_view's data() may already be NUL-terminated if it came
    // from a std::string with capacity, but we ensure it explicitly.
    std::string json_nul = json_str;
    if (json_nul.back() != '\0') json_nul.push_back('\0');

    // key is an opaque cache identifier — rlottie uses it for caching
    // parsed animations. We pass a synthetic key derived from the JSON size.
    std::string key = "exp097_" + std::to_string(json_str.size());

    Lottie_Animation* anim = lottie_animation_from_data(json_nul.data(),
                                                        key.c_str(), "");
    if (anim == nullptr) {
        result.error = "lottie_animation_from_data failed (invalid JSON or unsupported)";
        return result;
    }

    // Query the animation's intrinsic size and frame count.
    size_t anim_w = 0, anim_h = 0;
    lottie_animation_get_size(anim, &anim_w, &anim_h);
    size_t total = lottie_animation_get_totalframe(anim);
    double fps = lottie_animation_get_framerate(anim);
    result.width = target_w;
    result.height = target_h;
    result.total_frames = static_cast<int>(total);
    result.frame_rate = fps;

    int frames_to_render = (max_frames < 0)
                              ? static_cast<int>(total)
                              : std::min(static_cast<int>(total), max_frames);
    if (frames_to_render <= 0) frames_to_render = 1;

    size_t pixels_per_frame = static_cast<size_t>(target_w) * target_h;
    size_t bytes_per_frame = pixels_per_frame * 4;
    result.frames_rgba.resize(pixels_per_frame * frames_to_render);

    bool any_nonzero = false;
    for (int i = 0; i < frames_to_render; i++) {
        uint32_t* buf = reinterpret_cast<uint32_t*>(
            result.frames_rgba.data() + i * pixels_per_frame);
        // Zero the buffer first (rlottie writes pixels with alpha — transparent
        // areas should be 0 not garbage).
        std::memset(buf, 0, bytes_per_frame);
        lottie_animation_render(anim, static_cast<size_t>(i), buf,
                                static_cast<size_t>(target_w),
                                static_cast<size_t>(target_h),
                                static_cast<size_t>(target_w) * 4);
        // Sample a few pixels to detect non-empty render
        for (size_t p = 0; p < std::min<size_t>(pixels_per_frame, 1024); p++) {
            if (buf[p] != 0) { any_nonzero = true; break; }
        }
    }

    lottie_animation_destroy(anim);

    if (!any_nonzero) {
        result.error = "rlottie rendered 0 non-zero pixels across " +
                       std::to_string(frames_to_render) + " frames";
        // Still return ok=true — the animation may legitimately render to
        // transparent pixels in its first frames (e.g. fade-in animations).
        // Callers can inspect frames_rgba for verification.
    }
    result.ok = true;
    return result;
}

RLottieDecoder::DecodedAnim RLottieDecoder::decode_file(const std::string& path,
                                                        int target_w, int target_h,
                                                        int max_frames) {
    std::ifstream f(path);
    if (!f) {
        DecodedAnim r;
        r.error = "cannot open file: " + path;
        return r;
    }
    std::string json((std::istreambuf_iterator<char>(f)),
                      std::istreambuf_iterator<char>());
    return decode(json, target_w, target_h, max_frames);
}

} // namespace renderer
} // namespace miniandroid
