#!/usr/bin/env python3
"""
EXP-026 REAL EXECUTION RUNNER
==============================
Executes APKs through the ACTUAL MiniAndroid runtime binary.

THIS IS NOT SIMULATION.
This uses the compiled build/miniandroid binary for real DEX execution.

Golden Debug Protocol:
- Every result comes from actual runtime execution
- No simulation mode allowed
- No projected results
- Evidence files are generated by real runtime

Author: EXP-026 Campaign
Date: 2026-08-13
"""

import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
import zipfile
from dataclasses import dataclass, asdict, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Any, Tuple


# ============================================================================
# Configuration — Points to REAL binary
# ============================================================================

class Config:
    """Configuration pointing to real runtime."""
    
    BASE_DIR = Path(__file__).parent.parent
    RUNTIME_BINARY = BASE_DIR / "build" / "miniandroid"
    DOWNLOAD_DIR = BASE_DIR / "download" / "apks"
    RUN_DIR = BASE_DIR / "run" / "exp026"
    RESULTS_DIR = RUN_DIR / "results"
    TRACES_DIR = RUN_DIR / "traces"
    REGISTRY_PATH = BASE_DIR / "database" / "exp025_apk_registry.json"
    
    @classmethod
    def ensure_dirs(cls):
        cls.RUN_DIR.mkdir(parents=True, exist_ok=True)
        cls.RESULTS_DIR.mkdir(parents=True, exist_ok=True)
        cls.TRACES_DIR.mkdir(parents=True, exist_ok=True)
    
    @classmethod
    def verify_runtime(cls) -> Tuple[bool, str]:
        """Verify runtime binary exists and is executable."""
        if not cls.RUNTIME_BINARY.exists():
            return False, f"Runtime binary not found: {cls.RUNTIME_BINARY}"
        if not os.access(cls.RUNTIME_BINARY, os.X_OK):
            return False, f"Runtime binary not executable: {cls.RUNTIME_BINARY}"
        return True, f"Runtime verified: {cls.RUNTIME_BINARY}"


# ============================================================================
# Strict Execution Status (No Simulation)
# ============================================================================

class RealExecutionStatus(Enum):
    """
    STRICT status from REAL execution only.
    
    These are the ONLY valid statuses - all from actual runtime behavior.
    """
    EXECUTED_PASS = "EXECUTED_PASS"         # Runtime returned SUCCESS
    EXECUTED_PARTIAL = "EXECUTED_PARTIAL"   # Runtime completed with warnings
    EXECUTED_FAIL = "EXECUTED_FAIL"         # Runtime returned FAILURE or crashed
    PARSE_ERROR = "PARSE_ERROR"             # APK could not be parsed by runtime
    RUNTIME_ERROR = "RUNTIME_ERROR"         # Runtime itself failed (segfault, etc.)
    NOT_EXECUTED = "NOT_EXECUTED"           # Could not attempt execution


# ============================================================================
# Data Structures for Real Execution Results
# ============================================================================

@dataclass
class RealExecutionResult:
    """Result from ACTUAL runtime execution (not simulation)."""
    
    # Identification
    apk_name: str
    package_name: str
    execution_id: str
    timestamp: str
    
    # Status (from real execution)
    status: RealExecutionStatus
    real_execution: bool  # Always True for this runner
    
    # Runtime info
    runtime_version: str
    runtime_path: str
    
    # Timing
    start_time: str
    end_time: str
    duration_ms: int
    
    # APK Analysis (from runtime)
    apk_sha256: str
    dex_loaded: bool
    entry_activity: str
    dex_files: List[str]
    
    # Execution Metrics (from runtime output)
    instructions_executed: int
    api_calls: List[Dict[str, Any]]
    frames_rendered: int
    
    # Missing/Failed items
    missing_opcodes: List[str]
    missing_apis: List[str]
    
    # Errors from runtime
    runtime_errors: List[str]
    runtime_warnings: List[str]
    crash_log: Optional[str]
    
    # Evidence files (generated by runtime)
    trace_file: str
    api_trace_file: str
    screenshot_file: str
    report_file: str
    output_directory: str
    
    # Notes
    notes: str
    
    def to_dict(self) -> dict:
        result = asdict(self)
        result['status'] = self.status.value
        return result


# ============================================================================
# Real Execution Engine — Uses Actual Binary
# ============================================================================

class RealExecutionEngine:
    """
    Executes APKs using the REAL MiniAndroid runtime binary.
    
    NO SIMULATION. Only actual subprocess calls to build/miniandroid.
    """
    
    def __init__(self):
        Config.ensure_dirs()
        
        # Verify runtime exists
        self.runtime_ok, self.runtime_msg = Config.verify_runtime()
        if not self.runtime_ok:
            print(f"[FATAL] {self.runtime_msg}")
            raise RuntimeError(f"Runtime not available: {self.runtime_msg}")
        
        self.runtime_path = str(Config.RUNTIME_BINARY)
        self.runtime_version = self._get_runtime_version()
        
        print(f"[INIT] Real Execution Engine ready")
        print(f"       Runtime: {self.runtime_path}")
        print(f"       Version: {self.runtime_version}")
    
    def _get_runtime_version(self) -> str:
        """Get runtime version string."""
        try:
            result = subprocess.run(
                [self.runtime_path, 'version'],
                capture_output=True,
                text=True,
                timeout=10
            )
            return result.stdout.strip()[:100]
        except Exception as e:
            return f"Unknown (error: {e})"
    
    def _calculate_sha256(self, path: Path) -> str:
        """Calculate SHA256 of a file."""
        h = hashlib.sha256()
        with open(path, 'rb') as f:
            for chunk in iter(lambda: f.read(8192), b''):
                h.update(chunk)
        return h.hexdigest()
    
    def execute_apk(self, apk_path: Path, output_dir: Optional[Path] = None) -> RealExecutionResult:
        """
        Execute an APK through the REAL MiniAndroid runtime.
        
        This is NOT simulation. It calls the actual compiled binary.
        """
        
        start_time = datetime.now()
        execution_id = f"real_{start_time.strftime('%Y%m%d_%H%M%S')}_{apk_path.stem}"
        
        if output_dir is None:
            output_dir = Config.TRACES_DIR / execution_id
        
        output_dir.mkdir(parents=True, exist_ok=True)
        
        print(f"\n{'='*60}")
        print(f"[REAL EXECUTE] {apk_path.name}")
        print(f"  ID: {execution_id}")
        print(f"  Mode: REAL (no simulation)")
        print(f"{'='*60}")
        
        # Initialize result structure
        result = RealExecutionResult(
            apk_name=apk_path.name,
            package_name="unknown",
            execution_id=execution_id,
            timestamp=start_time.isoformat(),
            status=RealExecutionStatus.NOT_EXECUTED,
            real_execution=True,  # ALWAYS TRUE for this runner
            runtime_version=self.runtime_version,
            runtime_path=self.runtime_path,
            start_time=start_time.isoformat(),
            end_time="",
            duration_ms=0,
            apk_sha256="",
            dex_loaded=False,
            entry_activity="",
            dex_files=[],
            instructions_executed=0,
            api_calls=[],
            frames_rendered=0,
            missing_opcodes=[],
            missing_apis=[],
            runtime_errors=[],
            runtime_warnings=[],
            crash_log=None,
            trace_file="",
            api_trace_file="",
            screenshot_file="",
            report_file="",
            output_directory=str(output_dir),
            notes=""
        )
        
        try:
            # Verify APK exists
            if not apk_path.exists():
                raise FileNotFoundError(f"APK not found: {apk_path}")
            
            # Calculate SHA256
            result.apk_sha256 = self._calculate_sha256(apk_path)
            print(f"  [SHA256] {result.apk_sha256[:32]}...")
            
            # Execute using REAL runtime
            print(f"  [RUN] Calling runtime...")
            exec_start = time.time()
            
            proc = subprocess.run(
                [
                    self.runtime_path,
                    'run',
                    '-o', str(output_dir),
                    str(apk_path)
                ],
                capture_output=True,
                text=True,
                timeout=120  # 2 minute timeout per APK
            )
            
            exec_duration_ms = int((time.time() - exec_start) * 1000)
            result.duration_ms = exec_duration_ms
            
            end_time = datetime.now()
            result.end_time = end_time.isoformat()
            
            # Capture stdout/stderr
            stdout_text = proc.stdout
            stderr_text = proc.stderr
            
            print(f"\n  [STDOUT]")
            for line in stdout_text.split('\n')[:20]:  # First 20 lines
                if line.strip():
                    print(f"    {line}")
            
            if stderr_text.strip():
                print(f"  [STDERR]")
                for line in stderr_text.split('\n')[:10]:
                    if line.strip():
                        print(f"    {line}")
            
            # Parse runtime output for metrics
            self._parse_runtime_output(result, stdout_text, proc.returncode)
            
            # Collect evidence files
            self._collect_evidence(result, output_dir)
            
            # Determine final status based on REAL execution
            result.status = self._classify_real_result(proc.returncode, result)
            
            print(f"\n  [STATUS] {result.status.value} ({exec_duration_ms}ms)")
            
        except subprocess.TimeoutExpired:
            result.status = RealExecutionStatus.EXECUTED_FAIL
            result.runtime_errors.append("Execution timed out (120s limit)")
            result.end_time = datetime.now().isoformat()
            result.duration_ms = 120000
            print(f"\n  [TIMEOUT] Execution exceeded time limit")
            
        except FileNotFoundError as e:
            result.status = RealExecutionStatus.NOT_EXECUTED
            result.runtime_errors.append(str(e))
            print(f"\n  [ERROR] {e}")
            
        except Exception as e:
            result.status = RealExecutionStatus.RUNTIME_ERROR
            result.runtime_errors.append(f"Unexpected error: {str(e)}")
            result.end_time = datetime.now().isoformat()
            print(f"\n  [ERROR] {e}")
        
        # Save trace
        trace_path = Config.TRACES_DIR / f"{execution_id}_result.json"
        with open(trace_path, 'w') as f:
            json.dump(result.to_dict(), f, indent=2, default=str)
        result.trace_file = str(trace_path)
        
        return result
    
    def _parse_runtime_output(self, result: RealExecutionResult, stdout: str, returncode: int):
        """Parse runtime output to extract metrics."""
        
        lines = stdout.lower()
        
        # Look for success/failure indicators
        if 'success' in lines or '✓' in stdout or returncode == 0:
            pass  # Will be classified as PASS or PARTIAL based on other factors
        
        if 'error' in lines or 'fail' in stdout:
            result.runtime_errors.append("Runtime reported errors")
        
        if 'warning' in lines:
            result.runtime_warnings.append("Runtime reported warnings")
        
        # Try to extract package name from output
        if 'package' in stdout:
            import re
            pkg_match = re.search(r'package[_\s]*(name)?["\s:]+([a-z0-9_.]+)', stdout, re.IGNORECASE)
            if pkg_match:
                result.package_name = pkg_match.group(2)
        
        # Check for DEX loading indicators
        if 'dex' in lines or 'classes.dex' in lines:
            result.dex_loaded = True
            result.dex_files.append("classes.dex")
        
        # Check for activity indicators
        if 'activity' in lines:
            result.entry_activity = "detected"
    
    def _collect_evidence(self, result: RealExecutionResult, output_dir: Path):
        """Collect evidence files generated by runtime."""
        
        expected_files = {
            'api_trace': 'api_trace.json',
            'crash_log': 'crash.log', 
            'report': 'report.md',
            'screenshot': 'screenshot.ppm'
        }
        
        for key, filename in expected_files.items():
            file_path = output_dir / filename
            if file_path.exists():
                if key == 'api_trace':
                    result.api_trace_file = str(file_path)
                    # Try to parse API trace
                    try:
                        with open(file_path, 'r') as f:
                            api_data = json.load(f)
                            if isinstance(api_data, list):
                                result.api_calls = api_data
                            elif isinstance(api_data, dict):
                                result.api_calls = api_data.get('calls', [])
                    except:
                        pass
                
                elif key == 'crash_log':
                    with open(file_path, 'r') as f:
                        content = f.read().strip()
                        if content and content != 'No crash':
                            result.crash_log = content
                            result.runtime_errors.append(f"Crash: {content[:200]}")
                
                elif key == 'screenshot':
                    result.screenshot_file = str(file_path)
                    result.frames_rendered = 1  # Screenshot means frame was rendered
                
                elif key == 'report':
                    result.report_file = str(file_path)
    
    def _classify_real_result(self, returncode: int, result: RealExecutionResult) -> RealExecutionStatus:
        """Classify result based on REAL execution evidence."""
        
        # If there's a crash log, it's a FAIL
        if result.crash_log:
            return RealExecutionStatus.EXECUTED_FAIL
        
        # If there are critical errors, it's a FAIL
        critical_errors = [e for e in result.runtime_errors if 'crash' in e.lower() or 'fatal' in e.lower()]
        if critical_errors:
            return RealExecutionStatus.EXECUTED_FAIL
        
        # If we have API calls and/or screenshots, execution proceeded
        if result.api_calls or result.screenshot_file:
            if result.runtime_warnings:
                return RealExecutionStatus.EXECUTED_PARTIAL
            else:
                return RealExecutionStatus.EXECUTED_PASS
        
        # If return code is non-zero but no clear failure
        if returncode != 0:
            if result.dex_loaded:
                return RealExecutionStatus.EXECUTED_PARTIAL
            else:
                return RealExecutionStatus.PARSE_ERROR
        
        # Default to PASS if we got here with returncode 0
        if returncode == 0:
            return RealExecutionStatus.EXECUTED_PASS
        
        return RealExecutionStatus.EXECUTED_FAIL


# ============================================================================
# Campaign Runner — Executes All APKs Through Real Runtime
# ============================================================================

class EXP026CampaignRunner:
    """
    Runs EXP-026 campaign with REAL execution (no simulation).
    """
    
    def __init__(self):
        self.engine = RealExecutionEngine()
        self.results: List[Dict] = []
        self.registry: List[Dict] = []
        
        # Statistics (from REAL executions only)
        self.stats = {
            'total_apks': 0,
            'executed_pass': 0,
            'executed_partial': 0,
            'executed_fail': 0,
            'parse_error': 0,
            'runtime_error': 0,
            'not_executed': 0,
            'total_execution_time_ms': 0,
            'real_api_frequency': {},
            'real_opcode_usage': {},
            'runtime_failures': []
        }
    
    def load_registry(self):
        """Load APK registry from EXP-025 or scan download directory."""
        registry_path = Config.REGISTRY_PATH
        download_dir = Config.DOWNLOAD_DIR
        
        # Try loading from registry first
        if registry_path.exists():
            with open(registry_path, 'r') as f:
                raw_data = json.load(f)
            
            # Registry can be dict (package->info) or list
            if isinstance(raw_data, dict):
                self.registry = list(raw_data.values())
            elif isinstance(raw_data, list):
                self.registry = raw_data
            else:
                self.registry = []
            
            # Filter to only APKs that were actually downloaded and exist
            verified = [
                apk for apk in self.registry 
                if apk.get('status') in ['verified', 'downloaded'] 
                and apk.get('local_path')
                and Path(apk['local_path']).exists()
            ]
            
            if verified:
                self.registry = verified
                print(f"\n[INFO] Loaded {len(self.registry)} verified APKs from registry")
                return
        
        # Fallback: Scan download directory for APK files
        print(f"\n[INFO] Scanning {download_dir} for APK files...")
        
        if download_dir.exists():
            self.registry = []
            for apk_file in sorted(download_dir.glob('*.apk')):
                apk_info = {
                    'name': apk_file.stem,
                    'package': f'generated.{apk_file.stem.lower()}',
                    'version': '1.0',
                    'source': 'local',
                    'status': 'verified',
                    'local_path': str(apk_file),
                    'category': 'Generated',
                    'tier': 1
                }
                self.registry.append(apk_info)
            
            print(f"[INFO] Found {len(self.registry)} APK files in download directory")
        else:
            print(f"\n[WARN] No APKs found!")
            self.registry = []
    
    def run_campaign(self):
        """Execute campaign with REAL runtime on all APKs."""
        
        print("\n" + "=" * 70)
        print("  EXP-026 REAL EXECUTION CAMPAIGN")
        print("  NO SIMULATION — ONLY REAL RUNTIME EXECUTION")
        print("=" * 70)
        print(f"  Time: {datetime.now().isoformat()}")
        print(f"  Runtime: {self.engine.runtime_version}")
        print("=" * 70)
        
        # Load APKs
        self.load_registry()
        
        if not self.registry:
            print("[ERROR] No APKs in registry!")
            return
        
        self.stats['total_apks'] = len(self.registry)
        
        print(f"\n[CAMPAIGN] Executing {len(self.registry)} APKs through REAL runtime\n")
        
        # Execute each APK
        for i, apk_info in enumerate(self.registry, 1):
            apk_path = Path(apk_info.get('local_path', ''))
            
            if not apk_path.exists():
                print(f"\n[{i}/{len(self.registry)}] SKIP: {apk_info.get('name', '?')} — file not found")
                self.results.append({
                    'apk_info': apk_info,
                    'status': 'NOT_EXECUTED',
                    'error': 'APK file not found',
                    'real_execution': False
                })
                self.stats['not_executed'] += 1
                continue
            
            print(f"\n[{i}/{len(self.registry)}] Processing: {apk_info.get('name', '?')}")
            
            # Execute through REAL runtime
            result = self.engine.execute_apk(apk_path)
            result_dict = result.to_dict()
            result_dict['apk_info'] = apk_info
            self.results.append(result_dict)
            
            # Update statistics
            status_str = result.status.value
            stat_key = status_str.lower()
            if stat_key in self.stats:
                self.stats[stat_key] += 1
            
            self.stats['total_execution_time_ms'] += result.duration_ms
            
            # Collect real API frequency
            self._update_api_frequency(result)
            
            # Small delay between executions
            time.sleep(0.5)
        
        # Generate report
        self._generate_report()
    
    def _update_api_frequency(self, result: RealExecutionResult):
        """Update API frequency from REAL execution data."""
        
        for api_call in result.api_calls:
            if isinstance(api_call, dict):
                # Extract API identifier
                class_name = api_call.get('class', '')
                method_name = api_call.get('method', '')
                
                if class_name and method_name:
                    api_key = f"{class_name}.{method_name}"
                    
                    if api_key not in self.stats['real_api_frequency']:
                        self.stats['real_api_frequency'][api_key] = {
                            'count': 0,
                            'apps': [],
                            'success_count': 0,
                            'fail_count': 0
                        }
                    
                    self.stats['real_api_frequency'][api_key]['count'] += 1
                    self.stats['real_api_frequency'][api_key]['apps'].append(
                        result.package_name or result.apk_name
                    )
                    
                    if api_call.get('success', True):
                        self.stats['real_api_frequency'][api_key]['success_count'] += 1
                    else:
                        self.stats['real_api_frequency'][api_key]['fail_count'] += 1
        
        # Record failures
        if result.status in [RealExecutionStatus.EXECUTED_FAIL, RealExecutionStatus.PARSE_ERROR]:
            failure = {
                'package': result.package_name or result.apk_name,
                'status': result.status.value,
                'errors': result.runtime_errors[:3],
                'has_crash_log': bool(result.crash_log),
                'timestamp': result.timestamp
            }
            self.stats['runtime_failures'].append(failure)
    
    def _generate_report(self):
        """Generate final campaign report."""
        
        print("\n" + "=" * 70)
        print("  REAL EXECUTION RESULTS")
        print("=" * 70)
        
        print(f"\n  Total APKs:     {self.stats['total_apks']}")
        print(f"  EXECUTED_PASS:  {self.stats['executed_pass']}")
        print(f"  EXECUTED_PARTIAL: {self.stats['executed_partial']}")
        print(f"  EXECUTED_FAIL:  {self.stats['executed_fail']}")
        print(f"  PARSE_ERROR:    {self.stats['parse_error']}")
        print(f"  RUNTIME_ERROR:  {self.stats['runtime_error']}")
        print(f"  NOT_EXECUTED:   {self.stats['not_executed']}")
        
        # Calculate TRUE compatibility score (only from real executions)
        total_executed = (
            self.stats['executed_pass'] + 
            self.stats['executed_partial'] + 
            self.stats['executed_fail']
        )
        
        if total_executed > 0:
            true_score = (
                (self.stats['executed_pass'] * 100) +
                (self.stats['executed_partial'] * 50)
            ) / total_executed
            
            print(f"\n  TRUE COMPATIBILITY SCORE (from {total_executed} REAL executions):")
            print(f"    Score: {true_score:.1f}/100")
            print(f"    Pass Rate: {(self.stats['executed_pass']/total_executed)*100:.1f}%")
            print(f"    Partial Rate: {(self.stats['executed_partial']/total_executed)*100:.1f}%")
            print(f"    Fail Rate: {(self.stats['executed_fail']/total_executed)*100:.1f}%")
        else:
            true_score = 0
            print(f"\n  COMPATIBILITY SCORE: N/A (no apps executed)")
        
        # Top APIs used
        print(f"\n  TOP APIs (from REAL execution):")
        sorted_apis = sorted(
            self.stats['real_api_frequency'].items(),
            key=lambda x: x[1]['count'],
            reverse=True
        )[:10]
        
        for i, (api, data) in enumerate(sorted_apis, 1):
            print(f"    {i}. {api}: {data['count']} calls ({len(data['apps'])} apps)")
        
        print("=" * 70)
        
        # Save results
        self._save_results(true_score, total_executed)
    
    def _save_results(self, score: float, executed_count: int):
        """Save all results to disk."""
        
        # Full results
        results_path = Config.RESULTS_DIR / "exp026_real_execution_results.json"
        with open(results_path, 'w') as f:
            json.dump(self.results, f, indent=2, default=str)
        
        # Summary with TRUE score
        summary = {
            'experiment': 'EXP-026',
            'phase': 'REAL_EXECUTION_COMPLETE',
            'timestamp': datetime.now().isoformat(),
            'mode': 'REAL_EXECUTION',  # NOT SIMULATION!
            'runtime_version': self.engine.runtime_version,
            'score': {
                'value': round(score, 2),
                'max_possible': 100,
                'based_on': 'REAL_EXECUTION_ONLY',  # Critical distinction
                'total_executed': executed_count,
                'formula': '(PASS*100 + PARTIAL*50) / executed',
                'honesty_note': 'This score is from REAL runtime execution, not simulation'
            },
            'statistics': self.stats,
            'golden_debug_protocol': {
                'simulation_used': False,
                'all_results_from_real_runtime': True,
                'evidence_files_generated_by_runtime': True,
                'no_projected_scores': True
            }
        }
        
        summary_path = Config.RUN_DIR / "exp026_true_compatibility_score.json"
        with open(summary_path, 'w') as f:
            json.dump(summary, f, indent=2, default=str)
        
        # Real API usage database
        api_db_path = Config.BASE_DIR / "database" / "exp026_real_api_usage.json"
        with open(api_db_path, 'w') as f:
            json.dump(self.stats['real_api_frequency'], f, indent=2)
        
        # Failure database
        failure_db_path = Config.BASE_DIR / "database" / "exp026_runtime_failures.json"
        with open(failure_db_path, 'w') as f:
            json.dump(self.stats['runtime_failures'], f, indent=2)
        
        print(f"\n[SAVED] Results: {results_path}")
        print(f"[SAVED] TRUE Score: {summary_path}")
        print(f"[SAVED] API Usage: {api_db_path}")
        print(f"[SAVED] Failures: {failure_db_path}")


def main():
    """Main entry point for EXP-026 real execution campaign."""
    
    print("=" * 70)
    print("  EXP-026 REAL MINIANDROID RUNTIME ACTIVATION")
    print("  TRUE APK EXECUTION — NO SIMULATION ALLOWED")
    print("=" * 70)
    
    runner = EXP026CampaignRunner()
    runner.run_campaign()
    
    # Return based on whether we got any real executions
    total_executed = (
        runner.stats['executed_pass'] +
        runner.stats['executed_partial'] +
        runner.stats['executed_fail']
    )
    
    if total_executed >= 5:
        print(f"\n[RESULT] ✅ SUCCESS — {total_executed} APKs really executed")
        return 0
    elif total_executed > 0:
        print(f"\n[RESULT] ⚠️  PARTIAL — {total_executed} APKs executed (target was 5+)")
        return 0
    else:
        print(f"\n[RESULT] ❌ FAILED — No APKs successfully executed")
        return 1


if __name__ == "__main__":
    sys.exit(main())
