#!/usr/bin/env python3
"""
EXP-087 Phase 3 — Layout Cache Generator.

For each APK, generates a layout_cache.json that maps:
  resource_id (int) → {view_tree, text_values, layout_params}

This cache is loaded by the C++ runtime when setContentView(int) is called,
enabling real AXML view inflation without reimplementing AXML parsing in C++.

The cache is generated by the proven Python AXML parser from EXP-075.
"""

from __future__ import annotations

import json
import os
import struct
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path("/home/z/my-project/MiniAndroid-Compatibility-Runtime")


# ============================================================================
# Binary AXML Parser (pure Python, from EXP-075/EXP-080)
# ============================================================================

class AXMLDecoder:
    """Minimal binary AXML parser — extracts tag names and attributes."""

    def __init__(self, data: bytes):
        self.data = data
        self.pos = 0
        self.strings = []
        self.resource_ids = []
        self._parse()

    def _u16(self, off):
        return struct.unpack_from("<H", self.data, off)[0]

    def _u32(self, off):
        return struct.unpack_from("<I", self.data, off)[0]

    def _i32(self, off):
        return struct.unpack_from("<i", self.data, off)[0]

    def _parse(self):
        if len(self.data) < 8:
            return
        magic = self._u16(0)
        if magic != 0x0003:
            return
        # header_size = self._u16(2)
        # file_size = self._u32(4)
        # String pool chunk
        sp_off = 8
        sp_type = self._u16(sp_off)
        if sp_type != 0x0001:
            return
        sp_size = self._u32(sp_off + 4)
        string_count = self._u32(sp_off + 8)
        flags = self._u32(sp_off + 16)
        strings_offset = self._u32(sp_off + 20)
        is_utf8 = (flags & (1 << 8)) != 0

        # Read string offsets
        offsets = []
        for i in range(string_count):
            offsets.append(self._u32(sp_off + 28 + i * 4))

        strings_start = sp_off + strings_offset
        self.strings = []
        for off in offsets:
            pos = strings_start + off
            if is_utf8:
                n_chars = self.data[pos]
                if n_chars & 0x80:
                    n_chars = ((n_chars & 0x7f) << 8) | self.data[pos + 1]
                    pos += 2
                else:
                    pos += 1
                n_bytes = self.data[pos]
                if n_bytes & 0x80:
                    n_bytes = ((n_bytes & 0x7f) << 8) | self.data[pos + 1]
                    pos += 2
                else:
                    pos += 1
                s = self.data[pos:pos + n_bytes].decode("utf-8", errors="replace")
            else:
                n_chars = self._u16(pos)
                if n_chars & 0x8000:
                    n_chars = ((n_chars & 0x7fff) << 16) | self._u16(pos + 2)
                    pos += 4
                else:
                    pos += 2
                s = self.data[pos:pos + n_chars * 2].decode("utf-16-le", errors="replace")
            self.strings.append(s)

        # Resource IDs chunk
        off = sp_off + sp_size
        if off + 8 <= len(self.data):
            chunk_type = self._u16(off)
            chunk_size = self._u32(off + 4)
            if chunk_type == 0x0180:
                count = (chunk_size - 8) // 4
                for i in range(count):
                    self.resource_ids.append(self._u32(off + 8 + i * 4))
                off += chunk_size

    def get_string(self, idx):
        if 0 <= idx < len(self.strings):
            return self.strings[idx]
        return ""

    def parse_view_tree(self):
        """Parse the AXML and return a view tree dict."""
        # Walk XML_START_ELEMENT chunks
        sp_off = 8
        sp_size = self._u32(sp_off + 4)
        off = sp_off + sp_size

        # Skip resource IDs
        if off + 8 <= len(self.data):
            chunk_type = self._u16(off)
            chunk_size = self._u32(off + 4)
            if chunk_type == 0x0180:
                off += chunk_size

        root = None
        stack = []

        while off + 8 <= len(self.data):
            chunk_type = self._u16(off)
            chunk_size = self._u32(off + 4)
            if chunk_size == 0:
                break

            if chunk_type == 0x0102:  # START_ELEMENT
                name_idx = self._i32(off + 20)
                attr_start = self._u16(off + 24)
                attr_size = self._u16(off + 26)
                attr_count = self._u16(off + 28)
                tag_name = self.get_string(name_idx)

                # Parse attributes
                attrs = {}
                attr_off = off + 8 + attr_start  # +8 for chunk header + line/comment
                # Actually the header is: chunk(8) + line_number(4) + comment(4) = 16
                # Then ns(4) + name(4) + rawValue(4) + size(2) + res0(1) + type(1) + data(4) = 20
                attr_off = off + 16 + attr_start  # attr_start is relative to after chunk header+line+comment
                # Wait — the header_size field tells us. Let me use the standard layout.
                # XML_START_ELEMENT = chunk_header(8) + line_number(4) + comment(4) + ns(4) + name(4) + attr_start(2) + attr_size(2) + attr_count(2) + id(2) + class(2) + style(2) = 36
                # attrs start at off + header_size + attr_start (where header_size is chunk_header.header_size)
                header_size = self._u16(off + 2)
                attr_base = off + header_size + attr_start

                for i in range(attr_count):
                    a_ns = self._i32(attr_base + i * attr_size)
                    a_name = self._i32(attr_base + i * attr_size + 4)
                    a_raw = self._i32(attr_base + i * attr_size + 8)
                    a_type = self.data[attr_base + i * attr_size + 15]
                    a_data = self._u32(attr_base + i * attr_size + 16)

                    attr_name = self.get_string(a_name)
                    # Resolve value
                    if a_type == 0x03:  # STRING
                        val = self.get_string(a_raw) if a_raw >= 0 else self.get_string(a_data)
                    elif a_type == 0x01:  # REFERENCE
                        val = f"@0x{a_data:08x}"
                    elif a_type == 0x10:  # INT
                        val = str(self._i32(attr_base + i * attr_size + 16))
                    elif a_type == 0x12:  # INT_BOOLEAN
                        val = "true" if a_data != 0 else "false"
                    else:
                        val = self.get_string(a_raw) if a_raw >= 0 else str(a_data)

                    attrs[attr_name] = val

                node = {
                    "tag": tag_name,
                    "attributes": attrs,
                    "children": [],
                }
                if not stack:
                    root = node
                else:
                    stack[-1]["children"].append(node)
                stack.append(node)

            elif chunk_type == 0x0103:  # END_ELEMENT
                if stack:
                    stack.pop()

            off += chunk_size

        return root


def generate_layout_cache(apk_path: Path) -> dict:
    """Generate a layout cache for one APK."""
    cache = {
        "apk_path": str(apk_path),
        "layouts": {},
        "strings": {},
    }

    # Try to load ARSC parser for resource resolution
    arsc_parser = None
    try:
        import sys
        sys.path.insert(0, str(REPO_ROOT / "miniandroid" / "tools"))
        from exp063_arsc_parser import ARSCParser
        with zipfile.ZipFile(apk_path, "r") as z:
            arsc_data = z.read("resources.arsc")
        arsc_parser = ARSCParser(arsc_data)
    except Exception as e:
        print(f"  WARN: ARSC parser not available: {e}")

    def resolve_resource_ref(val: str) -> str:
        """Resolve @0x7fXXXXXX references via ARSC."""
        if not isinstance(val, str):
            return val
        if val.startswith("@0x") or val.startswith("@0X"):
            try:
                res_id = int(val[1:], 16)
                if arsc_parser:
                    # Try string resolution first (for @string/ references)
                    resolved = arsc_parser.resolve_string(res_id)
                    if isinstance(resolved, str) and resolved:
                        return resolved
                    # Try layout path resolution (for @layout/ references)
                    layout_path = arsc_parser.resolve_layout_path(res_id)
                    if isinstance(layout_path, str) and layout_path:
                        return layout_path
            except (ValueError, AttributeError, TypeError):
                pass
        return val

    def resolve_tree_attrs(node):
        """Recursively resolve resource references in attributes."""
        attrs = node.get("attributes", {})
        for k, v in list(attrs.items()):
            if isinstance(v, str) and v.startswith("@0x"):
                try:
                    resolved = resolve_resource_ref(v)
                    attrs[k] = resolved
                    if k == "text" and resolved != v:
                        cache["strings"][v] = resolved
                except Exception:
                    pass  # Skip unresolvable references
        for child in node.get("children", []):
            resolve_tree_attrs(child)

    try:
        with zipfile.ZipFile(apk_path, "r") as z:
            # Find all layout XMLs
            layout_files = [n for n in z.namelist()
                          if n.startswith("res/layout") and n.endswith(".xml")]
            # Also check res/layout-* (config-specific)
            layout_files += [n for n in z.namelist()
                           if n.startswith("res/layout-") and n.endswith(".xml")]

            for layout_path in layout_files:
                try:
                    data = z.read(layout_path)
                    decoder = AXMLDecoder(data)
                    view_tree = decoder.parse_view_tree()
                    if view_tree:
                        layout_name = Path(layout_path).stem
                        # Resolve resource references
                        resolve_tree_attrs(view_tree)
                        cache["layouts"][layout_name] = {
                            "path": layout_path,
                            "view_tree": view_tree,
                        }
                except Exception as e:
                    sys.stderr.write(f"PARSE ERROR {layout_path}: {e}\n")

    except Exception as e:
        cache["error"] = str(e)

    # Build resource ID → layout name mapping via ARSC
    if arsc_parser:
        try:
            # Try a range of resource IDs to find layout entries
            # Layout IDs are typically 0x7fXX0000 where XX is the type index
            for type_byte in range(0x01, 0x20):
                for entry in range(0x100):
                    rid = 0x7f000000 | (type_byte << 16) | entry
                    layout_path = arsc_parser.resolve_layout_path(rid)
                    if layout_path:
                        # Match to our cached layouts by filename stem (not exact path)
                        # because config-specific layouts (res/layout-v5/) have different
                        # directory prefixes but the same filename.
                        target_stem = Path(layout_path).stem
                        for layout_name, layout_info in cache["layouts"].items():
                            cached_stem = Path(layout_info["path"]).stem
                            if cached_stem == target_stem and "resource_id_int" not in layout_info:
                                layout_info["resource_id"] = f"0x{rid:08x}"
                                layout_info["resource_id_int"] = rid
                                break
        except Exception:
            pass

    return cache


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("apk", help="APK path")
    ap.add_argument("-o", "--output", help="Output JSON path")
    args = ap.parse_args()

    apk_path = Path(args.apk)
    if not apk_path.exists():
        print(f"ERROR: APK not found: {apk_path}")
        sys.exit(1)

    print(f"Generating layout cache for {apk_path.name}...")
    cache = generate_layout_cache(apk_path)

    layout_count = len(cache["layouts"])
    string_count = len(cache["strings"])
    print(f"  Found {layout_count} layouts, {string_count} strings")

    # Print first few layouts
    for name, info in list(cache["layouts"].items())[:5]:
        print(f"  Layout: {name} ({info['path']})")
        vt = info["view_tree"]
        print(f"    Root: <{vt['tag']}> attrs={list(vt['attributes'].keys())[:5]}")
        print(f"    Children: {len(vt['children'])}")

    # Determine output path
    if args.output:
        out_path = Path(args.output)
    else:
        # Default: alongside APK in download dir
        out_path = apk_path.parent / "layout_cache.json"

    out_path.write_text(json.dumps(cache, indent=2, default=str), encoding="utf-8")
    print(f"\nLayout cache saved to {out_path}")


if __name__ == "__main__":
    main()
