/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.probe.oracle12;

public final class R {
  public static final class attr {
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int action=0x7f010000;
    /**
     * <p>May be a floating point value, such as "<code>1.2</code>".
     */
    public static final int alpha=0x7f010001;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int argType=0x7f010002;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int data=0x7f010003;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int dataPattern=0x7f010004;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int destination=0x7f010005;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int enterAnim=0x7f010006;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int exitAnim=0x7f010007;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int font=0x7f010008;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fontProviderAuthority=0x7f010009;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int fontProviderCerts=0x7f01000a;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fontProviderFallbackQuery=0x7f01000b;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>async</td><td>1</td><td>The async font fetch works as follows.
     * First, check the local cache, then if the requested font is not cached, trigger a
     * request the font and continue with layout inflation. Once the font fetch succeeds, the
     * target text view will be refreshed with the downloaded font data. The
     * fontProviderFetchTimeout will be ignored if async loading is specified.</td></tr>
     * <tr><td>blocking</td><td>0</td><td>The blocking font fetch works as follows.
     * First, check the local cache, then if the requested font is not cached, request the
     * font from the provider and wait until it is finished.  You can change the length of
     * the timeout by modifying fontProviderFetchTimeout.  If the timeout happens, the
     * default typeface will be used instead.</td></tr>
     * </table>
     */
    public static final int fontProviderFetchStrategy=0x7f01000c;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>forever</td><td>ffffffff</td><td>A special value for the timeout. In this case, the blocking font fetching will not
     * timeout and wait until a reply is received from the font provider.</td></tr>
     * </table>
     */
    public static final int fontProviderFetchTimeout=0x7f01000d;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fontProviderPackage=0x7f01000e;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fontProviderQuery=0x7f01000f;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fontProviderSystemFontFamily=0x7f010010;
    /**
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>italic</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     */
    public static final int fontStyle=0x7f010011;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int fontVariationSettings=0x7f010012;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int fontWeight=0x7f010013;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int graph=0x7f010014;
    /**
     * <p>May be a floating point value, such as "<code>1.2</code>".
     */
    public static final int lStar=0x7f010015;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int launchSingleTop=0x7f010016;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int mimeType=0x7f010017;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int navGraph=0x7f010018;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int nestedScrollViewStyle=0x7f010019;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int nullable=0x7f01001a;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int popEnterAnim=0x7f01001b;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int popExitAnim=0x7f01001c;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int popUpTo=0x7f01001d;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int popUpToInclusive=0x7f01001e;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int popUpToSaveState=0x7f01001f;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int queryPatterns=0x7f010020;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int restoreState=0x7f010021;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int route=0x7f010022;
    /**
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     */
    public static final int shortcutMatchRequired=0x7f010023;
    /**
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     */
    public static final int startDestination=0x7f010024;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int targetPackage=0x7f010025;
    /**
     * <p>May be an integer value, such as "<code>100</code>".
     */
    public static final int ttcIndex=0x7f010026;
    /**
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     */
    public static final int uri=0x7f010027;
  }
  public static final class color {
    public static final int androidx_core_ripple_material_light=0x7f020000;
    public static final int androidx_core_secondary_text_default_material_light=0x7f020001;
    public static final int call_notification_answer_color=0x7f020002;
    public static final int call_notification_decline_color=0x7f020003;
    public static final int notification_action_color_filter=0x7f020004;
    public static final int notification_icon_bg_color=0x7f020005;
    public static final int vector_tint_color=0x7f020006;
    public static final int vector_tint_theme_color=0x7f020007;
  }
  public static final class dimen {
    public static final int compat_button_inset_horizontal_material=0x7f030000;
    public static final int compat_button_inset_vertical_material=0x7f030001;
    public static final int compat_button_padding_horizontal_material=0x7f030002;
    public static final int compat_button_padding_vertical_material=0x7f030003;
    public static final int compat_control_corner_material=0x7f030004;
    public static final int compat_notification_large_icon_max_height=0x7f030005;
    public static final int compat_notification_large_icon_max_width=0x7f030006;
    public static final int notification_action_icon_size=0x7f030007;
    public static final int notification_action_text_size=0x7f030008;
    public static final int notification_big_circle_margin=0x7f030009;
    public static final int notification_content_margin_start=0x7f03000a;
    public static final int notification_large_icon_height=0x7f03000b;
    public static final int notification_large_icon_width=0x7f03000c;
    public static final int notification_main_column_padding_top=0x7f03000d;
    public static final int notification_media_narrow_margin=0x7f03000e;
    public static final int notification_right_icon_size=0x7f03000f;
    public static final int notification_right_side_padding_top=0x7f030010;
    public static final int notification_small_icon_background_padding=0x7f030011;
    public static final int notification_small_icon_size_as_large=0x7f030012;
    public static final int notification_subtext_size=0x7f030013;
    public static final int notification_top_pad=0x7f030014;
    public static final int notification_top_pad_large_text=0x7f030015;
  }
  public static final class drawable {
    public static final int ic_call_answer=0x7f040000;
    public static final int ic_call_answer_low=0x7f040001;
    public static final int ic_call_answer_video=0x7f040002;
    public static final int ic_call_answer_video_low=0x7f040003;
    public static final int ic_call_decline=0x7f040004;
    public static final int ic_call_decline_low=0x7f040005;
    public static final int notification_action_background=0x7f040006;
    public static final int notification_bg=0x7f040007;
    public static final int notification_bg_low=0x7f040008;
    public static final int notification_bg_low_normal=0x7f040009;
    public static final int notification_bg_low_pressed=0x7f04000a;
    public static final int notification_bg_normal=0x7f04000b;
    public static final int notification_bg_normal_pressed=0x7f04000c;
    public static final int notification_icon_background=0x7f04000d;
    public static final int notification_oversize_large_icon_bg=0x7f04000e;
    public static final int notification_template_icon_bg=0x7f04000f;
    public static final int notification_template_icon_low_bg=0x7f040010;
    public static final int notification_tile_bg=0x7f040011;
    public static final int notify_panel_notification_icon_bg=0x7f040012;
  }
  public static final class id {
    public static final int accessibility_action_clickable_span=0x7f050000;
    public static final int accessibility_custom_action_0=0x7f050001;
    public static final int accessibility_custom_action_1=0x7f050002;
    public static final int accessibility_custom_action_10=0x7f050003;
    public static final int accessibility_custom_action_11=0x7f050004;
    public static final int accessibility_custom_action_12=0x7f050005;
    public static final int accessibility_custom_action_13=0x7f050006;
    public static final int accessibility_custom_action_14=0x7f050007;
    public static final int accessibility_custom_action_15=0x7f050008;
    public static final int accessibility_custom_action_16=0x7f050009;
    public static final int accessibility_custom_action_17=0x7f05000a;
    public static final int accessibility_custom_action_18=0x7f05000b;
    public static final int accessibility_custom_action_19=0x7f05000c;
    public static final int accessibility_custom_action_2=0x7f05000d;
    public static final int accessibility_custom_action_20=0x7f05000e;
    public static final int accessibility_custom_action_21=0x7f05000f;
    public static final int accessibility_custom_action_22=0x7f050010;
    public static final int accessibility_custom_action_23=0x7f050011;
    public static final int accessibility_custom_action_24=0x7f050012;
    public static final int accessibility_custom_action_25=0x7f050013;
    public static final int accessibility_custom_action_26=0x7f050014;
    public static final int accessibility_custom_action_27=0x7f050015;
    public static final int accessibility_custom_action_28=0x7f050016;
    public static final int accessibility_custom_action_29=0x7f050017;
    public static final int accessibility_custom_action_3=0x7f050018;
    public static final int accessibility_custom_action_30=0x7f050019;
    public static final int accessibility_custom_action_31=0x7f05001a;
    public static final int accessibility_custom_action_4=0x7f05001b;
    public static final int accessibility_custom_action_5=0x7f05001c;
    public static final int accessibility_custom_action_6=0x7f05001d;
    public static final int accessibility_custom_action_7=0x7f05001e;
    public static final int accessibility_custom_action_8=0x7f05001f;
    public static final int accessibility_custom_action_9=0x7f050020;
    public static final int action_container=0x7f050021;
    public static final int action_divider=0x7f050022;
    public static final int action_image=0x7f050023;
    public static final int action_text=0x7f050024;
    public static final int actions=0x7f050025;
    public static final int androidx_compose_ui_view_compose_view_context=0x7f050026;
    public static final int androidx_compose_ui_view_composition_context=0x7f050027;
    public static final int async=0x7f050028;
    public static final int auto_clear_focus_behavior_tag=0x7f050029;
    public static final int blocking=0x7f05002a;
    public static final int chronometer=0x7f05002b;
    public static final int compose_prefetch_scheduler=0x7f05002c;
    public static final int compose_view_saveable_id_tag=0x7f05002d;
    public static final int consume_window_insets_tag=0x7f05002e;
    public static final int dialog_button=0x7f05002f;
    public static final int edit_text_id=0x7f050030;
    public static final int forever=0x7f050031;
    public static final int hide_graphics_layer_in_inspector_tag=0x7f050032;
    public static final int hide_ime_id=0x7f050033;
    public static final int hide_in_inspector_tag=0x7f050034;
    public static final int icon=0x7f050035;
    public static final int icon_group=0x7f050036;
    public static final int info=0x7f050037;
    public static final int inspection_slot_table_set=0x7f050038;
    public static final int is_pooling_container_tag=0x7f050039;
    public static final int italic=0x7f05003a;
    public static final int line1=0x7f05003b;
    public static final int line3=0x7f05003c;
    public static final int nav_controller_view_tag=0x7f05003d;
    public static final int normal=0x7f05003e;
    public static final int notification_background=0x7f05003f;
    public static final int notification_main_column=0x7f050040;
    public static final int notification_main_column_container=0x7f050041;
    public static final int pooling_container_listener_holder_tag=0x7f050042;
    public static final int report_drawn=0x7f050043;
    public static final int right_icon=0x7f050044;
    public static final int right_side=0x7f050045;
    public static final int tag_accessibility_actions=0x7f050046;
    public static final int tag_accessibility_clickable_spans=0x7f050047;
    public static final int tag_accessibility_heading=0x7f050048;
    public static final int tag_accessibility_pane_title=0x7f050049;
    public static final int tag_compat_insets_dispatch=0x7f05004a;
    public static final int tag_on_apply_window_listener=0x7f05004b;
    public static final int tag_on_receive_content_listener=0x7f05004c;
    public static final int tag_on_receive_content_mime_types=0x7f05004d;
    public static final int tag_screen_reader_focusable=0x7f05004e;
    public static final int tag_state_description=0x7f05004f;
    public static final int tag_system_bar_state_monitor=0x7f050050;
    public static final int tag_transition_group=0x7f050051;
    public static final int tag_unhandled_key_event_manager=0x7f050052;
    public static final int tag_unhandled_key_listeners=0x7f050053;
    public static final int tag_window_insets_animation_callback=0x7f050054;
    public static final int text=0x7f050055;
    public static final int text2=0x7f050056;
    public static final int time=0x7f050057;
    public static final int title=0x7f050058;
    public static final int view_tree_disjoint_parent=0x7f050059;
    public static final int view_tree_lifecycle_owner=0x7f05005a;
    public static final int view_tree_navigation_event_dispatcher_owner=0x7f05005b;
    public static final int view_tree_on_back_pressed_dispatcher_owner=0x7f05005c;
    public static final int view_tree_saved_state_registry_owner=0x7f05005d;
    public static final int view_tree_view_model_store_owner=0x7f05005e;
    public static final int wrapped_composition_tag=0x7f05005f;
  }
  public static final class integer {
    public static final int m3c_window_layout_in_display_cutout_mode=0x7f060000;
    public static final int status_bar_notification_info_maxnum=0x7f060001;
  }
  public static final class layout {
    public static final int custom_dialog=0x7f070000;
    public static final int ime_base_split_test_activity=0x7f070001;
    public static final int ime_secondary_split_test_activity=0x7f070002;
    public static final int notification_action=0x7f070003;
    public static final int notification_action_tombstone=0x7f070004;
    public static final int notification_template_custom_big=0x7f070005;
    public static final int notification_template_icon_group=0x7f070006;
    public static final int notification_template_part_chronometer=0x7f070007;
    public static final int notification_template_part_time=0x7f070008;
  }
  public static final class string {
    public static final int androidx_compose_foundation_autofill=0x7f080000;
    public static final int androidx_compose_ui_autofill=0x7f080001;
    public static final int androidx_startup=0x7f080002;
    public static final int call_notification_answer_action=0x7f080003;
    public static final int call_notification_answer_video_action=0x7f080004;
    public static final int call_notification_decline_action=0x7f080005;
    public static final int call_notification_hang_up_action=0x7f080006;
    public static final int call_notification_incoming_text=0x7f080007;
    public static final int call_notification_ongoing_text=0x7f080008;
    public static final int call_notification_screening_text=0x7f080009;
    public static final int close_drawer=0x7f08000a;
    public static final int close_sheet=0x7f08000b;
    public static final int default_error_message=0x7f08000c;
    public static final int default_popup_window_title=0x7f08000d;
    public static final int dropdown_menu=0x7f08000e;
    public static final int in_progress=0x7f08000f;
    public static final int indeterminate=0x7f080010;
    public static final int m3c_bottom_sheet_collapse_description=0x7f080011;
    public static final int m3c_bottom_sheet_dismiss_description=0x7f080012;
    public static final int m3c_bottom_sheet_drag_handle_description=0x7f080013;
    public static final int m3c_bottom_sheet_expand_description=0x7f080014;
    public static final int m3c_bottom_sheet_pane_title=0x7f080015;
    public static final int m3c_date_input_headline=0x7f080016;
    public static final int m3c_date_input_headline_description=0x7f080017;
    public static final int m3c_date_input_invalid_for_pattern=0x7f080018;
    public static final int m3c_date_input_invalid_not_allowed=0x7f080019;
    public static final int m3c_date_input_invalid_year_range=0x7f08001a;
    public static final int m3c_date_input_label=0x7f08001b;
    public static final int m3c_date_input_no_input_description=0x7f08001c;
    public static final int m3c_date_input_title=0x7f08001d;
    public static final int m3c_date_picker_headline=0x7f08001e;
    public static final int m3c_date_picker_headline_description=0x7f08001f;
    public static final int m3c_date_picker_navigate_to_year_description=0x7f080020;
    public static final int m3c_date_picker_no_selection_description=0x7f080021;
    public static final int m3c_date_picker_scroll_to_earlier_years=0x7f080022;
    public static final int m3c_date_picker_scroll_to_later_years=0x7f080023;
    public static final int m3c_date_picker_switch_to_calendar_mode=0x7f080024;
    public static final int m3c_date_picker_switch_to_day_selection=0x7f080025;
    public static final int m3c_date_picker_switch_to_input_mode=0x7f080026;
    public static final int m3c_date_picker_switch_to_next_month=0x7f080027;
    public static final int m3c_date_picker_switch_to_previous_month=0x7f080028;
    public static final int m3c_date_picker_switch_to_year_selection=0x7f080029;
    public static final int m3c_date_picker_title=0x7f08002a;
    public static final int m3c_date_picker_today_description=0x7f08002b;
    public static final int m3c_date_picker_year_picker_pane_title=0x7f08002c;
    public static final int m3c_date_range_input_invalid_range_input=0x7f08002d;
    public static final int m3c_date_range_input_title=0x7f08002e;
    public static final int m3c_date_range_picker_day_in_range=0x7f08002f;
    public static final int m3c_date_range_picker_end_headline=0x7f080030;
    public static final int m3c_date_range_picker_scroll_to_next_month=0x7f080031;
    public static final int m3c_date_range_picker_scroll_to_previous_month=0x7f080032;
    public static final int m3c_date_range_picker_start_headline=0x7f080033;
    public static final int m3c_date_range_picker_title=0x7f080034;
    public static final int m3c_dialog=0x7f080035;
    public static final int m3c_dropdown_menu_collapsed=0x7f080036;
    public static final int m3c_dropdown_menu_expanded=0x7f080037;
    public static final int m3c_dropdown_menu_toggle=0x7f080038;
    public static final int m3c_floating_toolbar_collapse=0x7f080039;
    public static final int m3c_floating_toolbar_expand=0x7f08003a;
    public static final int m3c_search_bar_search=0x7f08003b;
    public static final int m3c_snackbar_dismiss=0x7f08003c;
    public static final int m3c_snackbar_pane_title=0x7f08003d;
    public static final int m3c_suggestions_available=0x7f08003e;
    public static final int m3c_time_input_dialog_title=0x7f08003f;
    public static final int m3c_time_picker_am=0x7f080040;
    public static final int m3c_time_picker_dialog_title=0x7f080041;
    public static final int m3c_time_picker_hour=0x7f080042;
    public static final int m3c_time_picker_hour_24h_suffix=0x7f080043;
    public static final int m3c_time_picker_hour_selection=0x7f080044;
    public static final int m3c_time_picker_hour_suffix=0x7f080045;
    public static final int m3c_time_picker_hour_text_field=0x7f080046;
    public static final int m3c_time_picker_minute=0x7f080047;
    public static final int m3c_time_picker_minute_selection=0x7f080048;
    public static final int m3c_time_picker_minute_suffix=0x7f080049;
    public static final int m3c_time_picker_minute_text_field=0x7f08004a;
    public static final int m3c_time_picker_period_toggle_description=0x7f08004b;
    public static final int m3c_time_picker_pm=0x7f08004c;
    public static final int m3c_time_picker_toggle_keyboard=0x7f08004d;
    public static final int m3c_time_picker_toggle_touch=0x7f08004e;
    public static final int m3c_tooltip_long_press_label=0x7f08004f;
    public static final int m3c_tooltip_pane_description=0x7f080050;
    public static final int m3c_wide_navigation_rail_close_rail=0x7f080051;
    public static final int m3c_wide_navigation_rail_pane_title=0x7f080052;
    public static final int navigation_menu=0x7f080053;
    public static final int not_selected=0x7f080054;
    public static final int range_end=0x7f080055;
    public static final int range_start=0x7f080056;
    public static final int selected=0x7f080057;
    public static final int snackbar_pane_title=0x7f080058;
    public static final int state_empty=0x7f080059;
    public static final int state_off=0x7f08005a;
    public static final int state_on=0x7f08005b;
    public static final int status_bar_notification_info_overflow=0x7f08005c;
    public static final int switch_role=0x7f08005d;
    public static final int tab=0x7f08005e;
    public static final int template_percent=0x7f08005f;
    public static final int tooltip_description=0x7f080060;
    public static final int tooltip_label=0x7f080061;
  }
  public static final class style {
    public static final int DialogWindowTheme=0x7f090000;
    public static final int EdgeToEdgeFloatingDialogTheme=0x7f090001;
    public static final int EdgeToEdgeFloatingDialogWindowTheme=0x7f090002;
    public static final int FloatingDialogWindowTheme=0x7f090003;
    public static final int TextAppearance_Compat_Notification=0x7f090004;
    public static final int TextAppearance_Compat_Notification_Info=0x7f090005;
    public static final int TextAppearance_Compat_Notification_Line2=0x7f090006;
    public static final int TextAppearance_Compat_Notification_Time=0x7f090007;
    public static final int TextAppearance_Compat_Notification_Title=0x7f090008;
    public static final int Widget_Compat_NotificationActionContainer=0x7f090009;
    public static final int Widget_Compat_NotificationActionText=0x7f09000a;
  }
  public static final class styleable {
    /**
     * Attributes that can be used with a ActivityNavigator.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #ActivityNavigator_android_name android:name}</code></td><td></td></tr>
     * <tr><td><code>{@link #ActivityNavigator_action com.probe.oracle12:action}</code></td><td></td></tr>
     * <tr><td><code>{@link #ActivityNavigator_data com.probe.oracle12:data}</code></td><td></td></tr>
     * <tr><td><code>{@link #ActivityNavigator_dataPattern com.probe.oracle12:dataPattern}</code></td><td></td></tr>
     * <tr><td><code>{@link #ActivityNavigator_targetPackage com.probe.oracle12:targetPackage}</code></td><td></td></tr>
     * </table>
     * @see #ActivityNavigator_android_name
     * @see #ActivityNavigator_action
     * @see #ActivityNavigator_data
     * @see #ActivityNavigator_dataPattern
     * @see #ActivityNavigator_targetPackage
     */
    public static final int[] ActivityNavigator={
      0x01010003, 0x7f010000, 0x7f010003, 0x7f010004, 
      0x7f010025
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#name}
     * attribute's value can be found in the {@link #ActivityNavigator} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name android:name
     */
    public static final int ActivityNavigator_android_name=0;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#action}
     * attribute's value can be found in the {@link #ActivityNavigator} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:action
     */
    public static final int ActivityNavigator_action=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#data}
     * attribute's value can be found in the {@link #ActivityNavigator} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:data
     */
    public static final int ActivityNavigator_data=2;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#dataPattern}
     * attribute's value can be found in the {@link #ActivityNavigator} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:dataPattern
     */
    public static final int ActivityNavigator_dataPattern=3;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#targetPackage}
     * attribute's value can be found in the {@link #ActivityNavigator} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:targetPackage
     */
    public static final int ActivityNavigator_targetPackage=4;
    /**
     * Attributes that can be used with a Capability.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #Capability_queryPatterns com.probe.oracle12:queryPatterns}</code></td><td></td></tr>
     * <tr><td><code>{@link #Capability_shortcutMatchRequired com.probe.oracle12:shortcutMatchRequired}</code></td><td></td></tr>
     * </table>
     * @see #Capability_queryPatterns
     * @see #Capability_shortcutMatchRequired
     */
    public static final int[] Capability={
      0x7f010020, 0x7f010023
    };
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#queryPatterns}
     * attribute's value can be found in the {@link #Capability} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:queryPatterns
     */
    public static final int Capability_queryPatterns=0;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#shortcutMatchRequired}
     * attribute's value can be found in the {@link #Capability} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.probe.oracle12:shortcutMatchRequired
     */
    public static final int Capability_shortcutMatchRequired=1;
    /**
     * Attributes that can be used with a ColorStateListItem.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #ColorStateListItem_android_color android:color}</code></td><td></td></tr>
     * <tr><td><code>{@link #ColorStateListItem_android_alpha android:alpha}</code></td><td></td></tr>
     * <tr><td><code>{@link #ColorStateListItem_android_lStar android:lStar}</code></td><td></td></tr>
     * <tr><td><code>{@link #ColorStateListItem_alpha com.probe.oracle12:alpha}</code></td><td></td></tr>
     * <tr><td><code>{@link #ColorStateListItem_lStar com.probe.oracle12:lStar}</code></td><td></td></tr>
     * </table>
     * @see #ColorStateListItem_android_color
     * @see #ColorStateListItem_android_alpha
     * @see #ColorStateListItem_android_lStar
     * @see #ColorStateListItem_alpha
     * @see #ColorStateListItem_lStar
     */
    public static final int[] ColorStateListItem={
      0x010101a5, 0x0101031f, 0x01010647, 0x7f010001, 
      0x7f010015
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#color}
     * attribute's value can be found in the {@link #ColorStateListItem} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name android:color
     */
    public static final int ColorStateListItem_android_color=0;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#alpha}
     * attribute's value can be found in the {@link #ColorStateListItem} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:alpha
     */
    public static final int ColorStateListItem_android_alpha=1;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#lStar}
     * attribute's value can be found in the {@link #ColorStateListItem} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:lStar
     */
    public static final int ColorStateListItem_android_lStar=2;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#alpha}
     * attribute's value can be found in the {@link #ColorStateListItem} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name com.probe.oracle12:alpha
     */
    public static final int ColorStateListItem_alpha=3;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#lStar}
     * attribute's value can be found in the {@link #ColorStateListItem} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name com.probe.oracle12:lStar
     */
    public static final int ColorStateListItem_lStar=4;
    /**
     * Attributes that can be used with a FontFamily.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderAuthority com.probe.oracle12:fontProviderAuthority}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderCerts com.probe.oracle12:fontProviderCerts}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderFallbackQuery com.probe.oracle12:fontProviderFallbackQuery}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderFetchStrategy com.probe.oracle12:fontProviderFetchStrategy}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderFetchTimeout com.probe.oracle12:fontProviderFetchTimeout}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderPackage com.probe.oracle12:fontProviderPackage}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderQuery com.probe.oracle12:fontProviderQuery}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamily_fontProviderSystemFontFamily com.probe.oracle12:fontProviderSystemFontFamily}</code></td><td></td></tr>
     * </table>
     * @see #FontFamily_fontProviderAuthority
     * @see #FontFamily_fontProviderCerts
     * @see #FontFamily_fontProviderFallbackQuery
     * @see #FontFamily_fontProviderFetchStrategy
     * @see #FontFamily_fontProviderFetchTimeout
     * @see #FontFamily_fontProviderPackage
     * @see #FontFamily_fontProviderQuery
     * @see #FontFamily_fontProviderSystemFontFamily
     */
    public static final int[] FontFamily={
      0x7f010009, 0x7f01000a, 0x7f01000b, 0x7f01000c, 
      0x7f01000d, 0x7f01000e, 0x7f01000f, 0x7f010010
    };
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderAuthority}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderAuthority
     */
    public static final int FontFamily_fontProviderAuthority=0;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderCerts}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:fontProviderCerts
     */
    public static final int FontFamily_fontProviderCerts=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderFallbackQuery}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderFallbackQuery
     */
    public static final int FontFamily_fontProviderFallbackQuery=2;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderFetchStrategy}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>async</td><td>1</td><td>The async font fetch works as follows.
     * First, check the local cache, then if the requested font is not cached, trigger a
     * request the font and continue with layout inflation. Once the font fetch succeeds, the
     * target text view will be refreshed with the downloaded font data. The
     * fontProviderFetchTimeout will be ignored if async loading is specified.</td></tr>
     * <tr><td>blocking</td><td>0</td><td>The blocking font fetch works as follows.
     * First, check the local cache, then if the requested font is not cached, request the
     * font from the provider and wait until it is finished.  You can change the length of
     * the timeout by modifying fontProviderFetchTimeout.  If the timeout happens, the
     * default typeface will be used instead.</td></tr>
     * </table>
     *
     * @attr name com.probe.oracle12:fontProviderFetchStrategy
     */
    public static final int FontFamily_fontProviderFetchStrategy=3;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderFetchTimeout}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>forever</td><td>ffffffff</td><td>A special value for the timeout. In this case, the blocking font fetching will not
     * timeout and wait until a reply is received from the font provider.</td></tr>
     * </table>
     *
     * @attr name com.probe.oracle12:fontProviderFetchTimeout
     */
    public static final int FontFamily_fontProviderFetchTimeout=4;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderPackage}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderPackage
     */
    public static final int FontFamily_fontProviderPackage=5;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderQuery}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderQuery
     */
    public static final int FontFamily_fontProviderQuery=6;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderSystemFontFamily}
     * attribute's value can be found in the {@link #FontFamily} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderSystemFontFamily
     */
    public static final int FontFamily_fontProviderSystemFontFamily=7;
    /**
     * Attributes that can be used with a FontFamilyFont.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #FontFamilyFont_android_font android:font}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_android_fontWeight android:fontWeight}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_android_fontStyle android:fontStyle}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_android_ttcIndex android:ttcIndex}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_android_fontVariationSettings android:fontVariationSettings}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_font com.probe.oracle12:font}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_fontStyle com.probe.oracle12:fontStyle}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_fontVariationSettings com.probe.oracle12:fontVariationSettings}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_fontWeight com.probe.oracle12:fontWeight}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyFont_ttcIndex com.probe.oracle12:ttcIndex}</code></td><td></td></tr>
     * </table>
     * @see #FontFamilyFont_android_font
     * @see #FontFamilyFont_android_fontWeight
     * @see #FontFamilyFont_android_fontStyle
     * @see #FontFamilyFont_android_ttcIndex
     * @see #FontFamilyFont_android_fontVariationSettings
     * @see #FontFamilyFont_font
     * @see #FontFamilyFont_fontStyle
     * @see #FontFamilyFont_fontVariationSettings
     * @see #FontFamilyFont_fontWeight
     * @see #FontFamilyFont_ttcIndex
     */
    public static final int[] FontFamilyFont={
      0x01010532, 0x01010533, 0x0101053f, 0x0101056f, 
      0x01010570, 0x7f010008, 0x7f010011, 0x7f010012, 
      0x7f010013, 0x7f010026
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#font}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name android:font
     */
    public static final int FontFamilyFont_android_font=0;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#fontWeight}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name android:fontWeight
     */
    public static final int FontFamilyFont_android_fontWeight=1;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#fontStyle}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>italic</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name android:fontStyle
     */
    public static final int FontFamilyFont_android_fontStyle=2;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#ttcIndex}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name android:ttcIndex
     */
    public static final int FontFamilyFont_android_ttcIndex=3;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#fontVariationSettings}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name android:fontVariationSettings
     */
    public static final int FontFamilyFont_android_fontVariationSettings=4;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#font}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:font
     */
    public static final int FontFamilyFont_font=5;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontStyle}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>italic</td><td>1</td><td></td></tr>
     * <tr><td>normal</td><td>0</td><td></td></tr>
     * </table>
     *
     * @attr name com.probe.oracle12:fontStyle
     */
    public static final int FontFamilyFont_fontStyle=6;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontVariationSettings}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontVariationSettings
     */
    public static final int FontFamilyFont_fontVariationSettings=7;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontWeight}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.probe.oracle12:fontWeight
     */
    public static final int FontFamilyFont_fontWeight=8;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#ttcIndex}
     * attribute's value can be found in the {@link #FontFamilyFont} array.
     *
     * <p>May be an integer value, such as "<code>100</code>".
     *
     * @attr name com.probe.oracle12:ttcIndex
     */
    public static final int FontFamilyFont_ttcIndex=9;
    /**
     * Attributes that can be used with a FontFamilyProviderFallback.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #FontFamilyProviderFallback_fontProviderQuery com.probe.oracle12:fontProviderQuery}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyProviderFallback_fontProviderSystemFontFamily com.probe.oracle12:fontProviderSystemFontFamily}</code></td><td></td></tr>
     * <tr><td><code>{@link #FontFamilyProviderFallback_fontVariationSettings com.probe.oracle12:fontVariationSettings}</code></td><td></td></tr>
     * </table>
     * @see #FontFamilyProviderFallback_fontProviderQuery
     * @see #FontFamilyProviderFallback_fontProviderSystemFontFamily
     * @see #FontFamilyProviderFallback_fontVariationSettings
     */
    public static final int[] FontFamilyProviderFallback={
      0x7f01000f, 0x7f010010, 0x7f010012
    };
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderQuery}
     * attribute's value can be found in the {@link #FontFamilyProviderFallback} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderQuery
     */
    public static final int FontFamilyProviderFallback_fontProviderQuery=0;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontProviderSystemFontFamily}
     * attribute's value can be found in the {@link #FontFamilyProviderFallback} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontProviderSystemFontFamily
     */
    public static final int FontFamilyProviderFallback_fontProviderSystemFontFamily=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#fontVariationSettings}
     * attribute's value can be found in the {@link #FontFamilyProviderFallback} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:fontVariationSettings
     */
    public static final int FontFamilyProviderFallback_fontVariationSettings=2;
    /**
     * Attributes that can be used with a GradientColor.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #GradientColor_android_startColor android:startColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_endColor android:endColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_type android:type}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_centerX android:centerX}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_centerY android:centerY}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_gradientRadius android:gradientRadius}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_tileMode android:tileMode}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_centerColor android:centerColor}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_startX android:startX}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_startY android:startY}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_endX android:endX}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColor_android_endY android:endY}</code></td><td></td></tr>
     * </table>
     * @see #GradientColor_android_startColor
     * @see #GradientColor_android_endColor
     * @see #GradientColor_android_type
     * @see #GradientColor_android_centerX
     * @see #GradientColor_android_centerY
     * @see #GradientColor_android_gradientRadius
     * @see #GradientColor_android_tileMode
     * @see #GradientColor_android_centerColor
     * @see #GradientColor_android_startX
     * @see #GradientColor_android_startY
     * @see #GradientColor_android_endX
     * @see #GradientColor_android_endY
     */
    public static final int[] GradientColor={
      0x0101019d, 0x0101019e, 0x010101a1, 0x010101a2, 
      0x010101a3, 0x010101a4, 0x01010201, 0x0101020b, 
      0x01010510, 0x01010511, 0x01010512, 0x01010513
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#startColor}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name android:startColor
     */
    public static final int GradientColor_android_startColor=0;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#endColor}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name android:endColor
     */
    public static final int GradientColor_android_endColor=1;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#type}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>linear</td><td>0</td><td></td></tr>
     * <tr><td>radial</td><td>1</td><td></td></tr>
     * <tr><td>sweep</td><td>2</td><td></td></tr>
     * </table>
     *
     * @attr name android:type
     */
    public static final int GradientColor_android_type=2;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#centerX}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     * <p>May be a fractional value, which is a floating point number appended with
     * either % or %p, such as "<code>14.5%</code>".
     * The % suffix always means a percentage of the base size;
     * the optional %p suffix provides a size relative to some parent container.
     *
     * @attr name android:centerX
     */
    public static final int GradientColor_android_centerX=3;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#centerY}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     * <p>May be a fractional value, which is a floating point number appended with
     * either % or %p, such as "<code>14.5%</code>".
     * The % suffix always means a percentage of the base size;
     * the optional %p suffix provides a size relative to some parent container.
     *
     * @attr name android:centerY
     */
    public static final int GradientColor_android_centerY=4;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#gradientRadius}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     * <p>May be a dimension value, which is a floating point number appended with a
     * unit such as "<code>14.5sp</code>".
     * Available units are: px (pixels), dp (density-independent pixels),
     * sp (scaled pixels based on preferred font size), in (inches), and
     * mm (millimeters).
     * <p>May be a fractional value, which is a floating point number appended with
     * either % or %p, such as "<code>14.5%</code>".
     * The % suffix always means a percentage of the base size;
     * the optional %p suffix provides a size relative to some parent container.
     *
     * @attr name android:gradientRadius
     */
    public static final int GradientColor_android_gradientRadius=5;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#tileMode}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>Must be one of the following constant values.</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Constant</th><th>Value</th><th>Description</th></tr>
     * <tr><td>clamp</td><td>0</td><td></td></tr>
     * <tr><td>disabled</td><td>ffffffff</td><td></td></tr>
     * <tr><td>mirror</td><td>2</td><td></td></tr>
     * <tr><td>repeat</td><td>1</td><td></td></tr>
     * </table>
     *
     * @attr name android:tileMode
     */
    public static final int GradientColor_android_tileMode=6;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#centerColor}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name android:centerColor
     */
    public static final int GradientColor_android_centerColor=7;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#startX}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:startX
     */
    public static final int GradientColor_android_startX=8;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#startY}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:startY
     */
    public static final int GradientColor_android_startY=9;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#endX}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:endX
     */
    public static final int GradientColor_android_endX=10;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#endY}
     * attribute's value can be found in the {@link #GradientColor} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:endY
     */
    public static final int GradientColor_android_endY=11;
    /**
     * Attributes that can be used with a GradientColorItem.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #GradientColorItem_android_color android:color}</code></td><td></td></tr>
     * <tr><td><code>{@link #GradientColorItem_android_offset android:offset}</code></td><td></td></tr>
     * </table>
     * @see #GradientColorItem_android_color
     * @see #GradientColorItem_android_offset
     */
    public static final int[] GradientColorItem={
      0x010101a5, 0x01010514
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#color}
     * attribute's value can be found in the {@link #GradientColorItem} array.
     *
     * <p>May be a color value, in the form of "<code>#<i>rgb</i></code>",
     * "<code>#<i>argb</i></code>", "<code>#<i>rrggbb</i></code>", or
     * "<code>#<i>aarrggbb</i></code>".
     *
     * @attr name android:color
     */
    public static final int GradientColorItem_android_color=0;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#offset}
     * attribute's value can be found in the {@link #GradientColorItem} array.
     *
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:offset
     */
    public static final int GradientColorItem_android_offset=1;
    /**
     * Attributes that can be used with a NavAction.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #NavAction_android_id android:id}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_destination com.probe.oracle12:destination}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_enterAnim com.probe.oracle12:enterAnim}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_exitAnim com.probe.oracle12:exitAnim}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_launchSingleTop com.probe.oracle12:launchSingleTop}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_popEnterAnim com.probe.oracle12:popEnterAnim}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_popExitAnim com.probe.oracle12:popExitAnim}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_popUpTo com.probe.oracle12:popUpTo}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_popUpToInclusive com.probe.oracle12:popUpToInclusive}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_popUpToSaveState com.probe.oracle12:popUpToSaveState}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavAction_restoreState com.probe.oracle12:restoreState}</code></td><td></td></tr>
     * </table>
     * @see #NavAction_android_id
     * @see #NavAction_destination
     * @see #NavAction_enterAnim
     * @see #NavAction_exitAnim
     * @see #NavAction_launchSingleTop
     * @see #NavAction_popEnterAnim
     * @see #NavAction_popExitAnim
     * @see #NavAction_popUpTo
     * @see #NavAction_popUpToInclusive
     * @see #NavAction_popUpToSaveState
     * @see #NavAction_restoreState
     */
    public static final int[] NavAction={
      0x010100d0, 0x7f010005, 0x7f010006, 0x7f010007, 
      0x7f010016, 0x7f01001b, 0x7f01001c, 0x7f01001d, 
      0x7f01001e, 0x7f01001f, 0x7f010021
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#id}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name android:id
     */
    public static final int NavAction_android_id=0;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#destination}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:destination
     */
    public static final int NavAction_destination=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#enterAnim}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:enterAnim
     */
    public static final int NavAction_enterAnim=2;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#exitAnim}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:exitAnim
     */
    public static final int NavAction_exitAnim=3;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#launchSingleTop}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.probe.oracle12:launchSingleTop
     */
    public static final int NavAction_launchSingleTop=4;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#popEnterAnim}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:popEnterAnim
     */
    public static final int NavAction_popEnterAnim=5;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#popExitAnim}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:popExitAnim
     */
    public static final int NavAction_popExitAnim=6;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#popUpTo}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:popUpTo
     */
    public static final int NavAction_popUpTo=7;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#popUpToInclusive}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.probe.oracle12:popUpToInclusive
     */
    public static final int NavAction_popUpToInclusive=8;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#popUpToSaveState}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.probe.oracle12:popUpToSaveState
     */
    public static final int NavAction_popUpToSaveState=9;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#restoreState}
     * attribute's value can be found in the {@link #NavAction} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.probe.oracle12:restoreState
     */
    public static final int NavAction_restoreState=10;
    /**
     * Attributes that can be used with a NavArgument.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #NavArgument_android_name android:name}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavArgument_android_defaultValue android:defaultValue}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavArgument_argType com.probe.oracle12:argType}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavArgument_nullable com.probe.oracle12:nullable}</code></td><td></td></tr>
     * </table>
     * @see #NavArgument_android_name
     * @see #NavArgument_android_defaultValue
     * @see #NavArgument_argType
     * @see #NavArgument_nullable
     */
    public static final int[] NavArgument={
      0x01010003, 0x010101ed, 0x7f010002, 0x7f01001a
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#name}
     * attribute's value can be found in the {@link #NavArgument} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name android:name
     */
    public static final int NavArgument_android_name=0;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#defaultValue}
     * attribute's value can be found in the {@link #NavArgument} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     * <p>May be an integer value, such as "<code>100</code>".
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     * <p>May be a floating point value, such as "<code>1.2</code>".
     *
     * @attr name android:defaultValue
     */
    public static final int NavArgument_android_defaultValue=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#argType}
     * attribute's value can be found in the {@link #NavArgument} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:argType
     */
    public static final int NavArgument_argType=2;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#nullable}
     * attribute's value can be found in the {@link #NavArgument} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name com.probe.oracle12:nullable
     */
    public static final int NavArgument_nullable=3;
    /**
     * Attributes that can be used with a NavDeepLink.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #NavDeepLink_android_autoVerify android:autoVerify}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavDeepLink_action com.probe.oracle12:action}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavDeepLink_mimeType com.probe.oracle12:mimeType}</code></td><td></td></tr>
     * <tr><td><code>{@link #NavDeepLink_uri com.probe.oracle12:uri}</code></td><td></td></tr>
     * </table>
     * @see #NavDeepLink_android_autoVerify
     * @see #NavDeepLink_action
     * @see #NavDeepLink_mimeType
     * @see #NavDeepLink_uri
     */
    public static final int[] NavDeepLink={
      0x010104ee, 0x7f010000, 0x7f010017, 0x7f010027
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#autoVerify}
     * attribute's value can be found in the {@link #NavDeepLink} array.
     *
     * <p>May be a boolean value, such as "<code>true</code>" or
     * "<code>false</code>".
     *
     * @attr name android:autoVerify
     */
    public static final int NavDeepLink_android_autoVerify=0;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#action}
     * attribute's value can be found in the {@link #NavDeepLink} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:action
     */
    public static final int NavDeepLink_action=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#mimeType}
     * attribute's value can be found in the {@link #NavDeepLink} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:mimeType
     */
    public static final int NavDeepLink_mimeType=2;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#uri}
     * attribute's value can be found in the {@link #NavDeepLink} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:uri
     */
    public static final int NavDeepLink_uri=3;
    /**
     * Attributes that can be used with a NavGraphNavigator.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #NavGraphNavigator_startDestination com.probe.oracle12:startDestination}</code></td><td></td></tr>
     * </table>
     * @see #NavGraphNavigator_startDestination
     */
    public static final int[] NavGraphNavigator={
      0x7f010024
    };
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#startDestination}
     * attribute's value can be found in the {@link #NavGraphNavigator} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:startDestination
     */
    public static final int NavGraphNavigator_startDestination=0;
    /**
     * Attributes that can be used with a NavHost.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #NavHost_navGraph com.probe.oracle12:navGraph}</code></td><td></td></tr>
     * </table>
     * @see #NavHost_navGraph
     */
    public static final int[] NavHost={
      0x7f010018
    };
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#navGraph}
     * attribute's value can be found in the {@link #NavHost} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:navGraph
     */
    public static final int NavHost_navGraph=0;
    /**
     * Attributes that can be used with a NavInclude.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #NavInclude_graph com.probe.oracle12:graph}</code></td><td></td></tr>
     * </table>
     * @see #NavInclude_graph
     */
    public static final int[] NavInclude={
      0x7f010014
    };
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#graph}
     * attribute's value can be found in the {@link #NavInclude} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name com.probe.oracle12:graph
     */
    public static final int NavInclude_graph=0;
    /**
     * Attributes that can be used with a Navigator.
     * <p>Includes the following attributes:</p>
     * <table>
     * <colgroup align="left" />
     * <colgroup align="left" />
     * <tr><th>Attribute</th><th>Description</th></tr>
     * <tr><td><code>{@link #Navigator_android_label android:label}</code></td><td></td></tr>
     * <tr><td><code>{@link #Navigator_android_id android:id}</code></td><td></td></tr>
     * <tr><td><code>{@link #Navigator_route com.probe.oracle12:route}</code></td><td></td></tr>
     * </table>
     * @see #Navigator_android_label
     * @see #Navigator_android_id
     * @see #Navigator_route
     */
    public static final int[] Navigator={
      0x01010001, 0x010100d0, 0x7f010022
    };
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#label}
     * attribute's value can be found in the {@link #Navigator} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name android:label
     */
    public static final int Navigator_android_label=0;
    /**
     * <p>This symbol is the offset where the {@link android.R.attr#id}
     * attribute's value can be found in the {@link #Navigator} array.
     *
     * <p>May be a reference to another resource, in the form
     * "<code>@[+][<i>package</i>:]<i>type</i>/<i>name</i></code>" or a theme
     * attribute in the form
     * "<code>?[<i>package</i>:]<i>type</i>/<i>name</i></code>".
     *
     * @attr name android:id
     */
    public static final int Navigator_android_id=1;
    /**
     * <p>This symbol is the offset where the {@link com.probe.oracle12.R.attr#route}
     * attribute's value can be found in the {@link #Navigator} array.
     *
     * <p>May be a string value, using '\\;' to escape characters such as
     * '\\n' or '\\uxxxx' for a unicode character;
     *
     * @attr name com.probe.oracle12:route
     */
    public static final int Navigator_route=2;
  }
}