/*
 * UNIFIED_007 — Audio subsystem test.
 *
 * REAL fixtures: generated by scripts/gen_audio_fixtures.sh via ffmpeg
 * (sine tones, 3 formats). Tests:
 *   1. decode mp3/wav/ogg → PCM ok, duration within 10% of expected
 *   2. MediaPlayer full legal path: IDLE→INITIALIZED→PREPARED→STARTED→
 *      PLAYBACK_COMPLETED (THE previously-buggy transition) — with
 *      onCompletion listener firing exactly once
 *   3. Illegal transitions rejected (start before setDataSource etc.)
 *   4. seekTo away from end re-arms completion
 *   5. SoundPool load/play/stop; AudioTrack write/play/stop/drain
 *
 * Exit 0 = ALL PASS.
 */

#include "../src/audio/audio_engine.h"

#include <cmath>
#include <cstdio>
#include <string>
#include <vector>

using namespace miniandroid::audio;

static int g_pass = 0, g_fail = 0;
#define CHECK(cond, msg) do { \
    if (cond) { g_pass++; std::printf("PASS: %s\n", msg); } \
    else { g_fail++; std::printf("FAIL: %s\n", msg); } \
} while (0)

static bool approx(double a, double b, double tol) {
    return std::fabs(a - b) <= tol * b;
}

int main() {
    const char* fixtures[] = {
        "tests/fixtures/audio/sine_2s.mp3",
        "tests/fixtures/audio/sine_2s.wav",
        "tests/fixtures/audio/sine_2s.ogg",
    };

    // ---- 1. Real decoding of all 3 formats ----
    for (const char* fx : fixtures) {
        DecodedPcm pcm = decode_audio_file(fx);
        std::string label = std::string("decode ") + fx;
        CHECK(pcm.ok(), label.c_str());
        std::string dur_label = std::string("duration≈2s ") + fx;
        CHECK(pcm.ok() && approx(pcm.duration_sec, 2.0, 0.10),
              dur_label.c_str());
    }

    // ---- 2. MediaPlayer legal path → PLAYBACK_COMPLETED ----
    {
        MediaPlayer mp;
        CHECK(mp.state() == MpState::IDLE, "initial state IDLE");
        CHECK(mp.set_data_source("tests/fixtures/audio/sine_2s.wav"),
              "setDataSource legal");
        CHECK(mp.prepare(), "prepare (real decode)");
        CHECK(mp.state() == MpState::PREPARED, "state PREPARED after prepare");
        CHECK(mp.duration_msec() > 1500 && mp.duration_msec() < 2500,
              "duration in 1.5–2.5s window");
        int completions = 0;
        mp.on_completion = [&completions]() { completions++; };
        CHECK(mp.start(), "start legal");
        CHECK(mp.state() == MpState::STARTED, "state STARTED");
        // Advance clock past duration in steps.
        MpState st = MpState::IDLE;
        for (int i = 0; i < 30; ++i) st = mp.advance_clock_msec(100);
        CHECK(st == MpState::PLAYBACK_COMPLETED,
              "advance → PLAYBACK_COMPLETED (THE FIX)");
        CHECK(completions == 1, "onCompletion fired exactly once");
        // Extra clock ticks must not re-fire.
        mp.advance_clock_msec(500);
        CHECK(completions == 1, "no duplicate completion fire");
        // start() after completion replays (AOSP-legal).
        CHECK(mp.start(), "start after PLAYBACK_COMPLETED legal");
        CHECK(mp.state() == MpState::STARTED, "replay STARTED");
        st = mp.advance_clock_msec(3000);
        CHECK(st == MpState::PLAYBACK_COMPLETED, "second pass completes");
        CHECK(completions == 2, "second completion fired");
    }

    // ---- 3. Illegal transitions rejected ----
    {
        MediaPlayer mp;
        CHECK(!mp.start(), "start from IDLE rejected");
        CHECK(mp.state() == MpState::ERROR, "state ERROR after illegal start");
        CHECK(!mp.set_data_source("tests/fixtures/audio/sine_2s.wav"),
              "setDataSource from ERROR rejected");
    }
    {
        MediaPlayer mp;
        mp.set_data_source("tests/fixtures/audio/sine_2s.wav");
        CHECK(!mp.pause(), "pause from INITIALIZED rejected");
    }

    // ---- 4. seekTo re-arms completion ----
    {
        MediaPlayer mp;
        mp.set_data_source("tests/fixtures/audio/sine_2s.wav");
        mp.prepare();
        int completions = 0;
        mp.on_completion = [&completions]() { completions++; };
        mp.start();
        mp.advance_clock_msec(5000);  // completes
        CHECK(completions == 1, "first pass completes");
        CHECK(mp.seek_to(0), "seekTo(0) from PLAYBACK_COMPLETED legal");
        CHECK(mp.start(), "start after seek");
        mp.advance_clock_msec(5000);
        CHECK(completions == 2, "completion re-armed and fired again");
    }

    // ---- 5. SoundPool ----
    {
        SoundPool sp;
        int sid = sp.load("tests/fixtures/audio/sine_2s.wav");
        CHECK(sid > 0, "SoundPool load returns soundID");
        CHECK(sp.is_sample_loaded(sid), "sample loaded");
        int stream = sp.play(sid);
        CHECK(stream > 0, "play returns streamID");
        CHECK(sp.stream_state(stream) == SpStreamState::PLAYING,
              "stream PLAYING");
        sp.pause(stream);
        CHECK(sp.stream_state(stream) == SpStreamState::PAUSED, "stream PAUSED");
        sp.resume(stream);
        CHECK(sp.stream_state(stream) == SpStreamState::PLAYING,
              "stream resumed");
        sp.stop(stream);
        CHECK(sp.stream_state(stream) == SpStreamState::STOPPED,
              "stream STOPPED");
        CHECK(sp.play(9999) == 0, "play unknown soundID → 0");
    }

    // ---- 6. AudioTrack ----
    {
        AudioTrack at;
        CHECK(at.init(44100, 2), "AudioTrack init");
        std::vector<int16_t> chunk(44100 * 2 / 10, 500);
        size_t w = at.write(chunk.data(), chunk.size() / 2);
        CHECK(w == chunk.size() / 2, "write accepted frames");
        CHECK(at.state() == AtState::PLAYING, "write implies PLAYING");
        CHECK(at.stop(), "stop drains");
        CHECK(at.state() == AtState::STOPPED, "state STOPPED");
        CHECK(at.buffered_frames() == 0, "buffer drained");
        at.release();
        CHECK(at.state() == AtState::RELEASED, "state RELEASED");
    }

    // ---- 7. MP3 end-to-end through MediaPlayer ----
    {
        MediaPlayer mp;
        CHECK(mp.set_data_source("tests/fixtures/audio/sine_2s.mp3"),
              "mp3 setDataSource");
        CHECK(mp.prepare(), "mp3 prepare (mpg123 decode)");
        CHECK(mp.duration_msec() > 1500, "mp3 duration > 1.5s");
        mp.start();
        MpState st = mp.advance_clock_msec(2500);
        CHECK(st == MpState::PLAYBACK_COMPLETED, "mp3 playback completes");
    }

    std::printf("\nAUDIO TESTS: %d PASS, %d FAIL\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
