// framework_theme_attrs.h — S68 W2 (A1/A10): FRAMEWORK theme-attr defaults.
//
// LAW (AOSP frameworks/base core/res): ?android:attr/name (TypedValue
// TYPE_ATTRIBUTE, id 0x01xxxxxx) resolves through the app theme; when the
// theme chain lacks the attr, the value is the framework theme default.
// Flavor (dark=Theme.Material vs light=Theme.Material.Light) follows the
// framework's own *.Light naming convention on the resolved theme parent
// chain — generic framework contract, never app-specific.
// State-list text colors are hand-expanded to their enabled-state item
// (colorForeground × contentAlpha) per res/color/*.xml law.
//
// GENERATED by scripts/s68_gen_framework_theme_attrs.py from AOSP
// oreo-release law files (regenerate, never hand-edit):
//   public.xml  sha256=aae0d8b5addc7a844314e1159385c991
//   themes_material.xml  sha256=9cb656535492fc807f9f6cfaebe9eea1
//   colors_material.xml  sha256=0c39ceffa7fd34729d52d9d9d6c62f1c
//   colors.xml  sha256=9e1529faa7e064e5318f48b9f8966f36
//   colors_holo.xml  sha256=97a208e98f34590f9ba12419fcf1f29b
//   colors_legacy.xml  sha256=b490ae2fd08aca079d934c8f19e3f7d3

#pragma once
#include <cstdint>
#include <cstddef>

namespace miniandroid { namespace resources {

struct FrameworkThemeAttr { const char* name; uint32_t id; uint32_t dark; uint32_t light; };

// dark  = Theme.Material       value (AOSP law)
// light = Theme.Material.Light value (AOSP law)
inline const FrameworkThemeAttr FRAMEWORK_THEME_ATTRS[] = {
    {"colorPrimary", 0x01010433u, 0xff212121u, 0xfff5f5f5u},
    {"colorPrimaryDark", 0x01010434u, 0xff000000u, 0xff757575u},
    {"colorAccent", 0x01010435u, 0xff80cbc4u, 0xff009688u},
    {"textColorPrimary", 0x01010036u, 0xffffffffu, 0xde000000u},
    {"textColorSecondary", 0x01010038u, 0xb2ffffffu, 0x8a000000u},
    {"textColorTertiary", 0x01010212u, 0xb3ffffffu, 0x8a000000u},
    {"textColorPrimaryInverse", 0x01010039u, 0xde000000u, 0xffffffffu},
    {"textColorSecondaryInverse", 0x0101003au, 0x8a000000u, 0xb3ffffffu},
    {"textColorTertiaryInverse", 0x01010213u, 0x8a000000u, 0xb3ffffffu},
    {"textColorHintInverse", 0x0101003fu, 0xff000000u, 0xffffffffu},
    {"textColorHint", 0x0101009au, 0xffffffffu, 0xff000000u},
    {"colorForeground", 0x01010030u, 0xffffffffu, 0xff000000u},
    {"colorForegroundInverse", 0x01010206u, 0xff000000u, 0xffffffffu},
    {"colorBackground", 0x01010031u, 0xff303030u, 0xfffafafau},
    {"windowBackground", 0x01010054u, 0xff303030u, 0xfffafafau},
    {"windowFullscreen", 0x0101020du, 0x00000000u, 0x00000000u},
    {"navigationBarColor", 0x01010452u, 0xff000000u, 0xff000000u},
    {"statusBarColor", 0x01010451u, 0xff000000u, 0xff757575u},
    {"colorControlNormal", 0x01010429u, 0xb2ffffffu, 0x8a000000u},
    {"colorControlActivated", 0x0101042au, 0xff80cbc4u, 0xff009688u},
    {"colorControlHighlight", 0x0101042cu, 0xffffffffu, 0xff000000u},
    {"disabledAlpha", 0x01010033u, 0x00002666u, 0x00002148u},
};
inline const size_t FRAMEWORK_THEME_ATTR_COUNT = sizeof(FRAMEWORK_THEME_ATTRS) / sizeof(FRAMEWORK_THEME_ATTRS[0]);

} } // namespace miniandroid::resources
