#!/usr/bin/env python3
# cont37_registry.py — add F-NEW-298 to root_registry.json (606 -> 607),
# dedup-checked.
import json

REG = "/home/z/my-project/root_registry.json"
with open(REG) as f:
    r = json.load(f)

ids = [x.get("id") for x in r["roots"]]
assert "F-NEW-298" not in ids, "dedup check failed — F-NEW-298 already present"
assert ids[-1] == "F-NEW-297", f"unexpected tail: {ids[-1]}"

e = {
    "id": "F-NEW-298",
    "status": "ROOT_CAUSED_FIXED",
    "title": "COMPOSE TEXT STILL INVISIBLE + THE FRAME WIPE: THREE COORDINATED "
             "GENERIC ROOTS, ONE SEMANTIC FAMILY (the paint/present contract). "
             "(a) Canvas.getClipBounds(Rect) had NO engine law — the unhandled-"
             "bridge typed-default answered FALSE — and the Compose paragraph "
             "paint funnel (R8: Lg6.d, decoded from AOSP AndroidParagraph.paint "
             "→ layout.paint(nativeCanvas) → Layout.draw) gates the ENTIRE "
             "Layout.draw on `if (!canvas.getClipBounds(r)) return;` — every "
             "paragraph paint silently aborted BEFORE Layout.draw (AOSP: the "
             "initial clip is the whole surface, never empty). (b) the "
             "StaticLayout$Builder law's 'setText' PREFIX match conflated "
             "AOSP Builder.setText(CharSequence, start, end) with "
             "setTextDirection(TextDirectionHeuristic) — Compose's builder "
             "chain calls setTextDirection, whose heuristic argument OVERWROTE "
             "the obtain-stored source — build() laid out an EMPTY string "
             "(chars=0, [F298-BUILD] source_len=0) and the paint-side text law "
             "drew nothing ([F-NEW-297] text_len=0). (c) THE FRAME WIPE: an "
             "in-draw halt (F084 wall-clock or the [HALT-LOOP] spin guard) "
             "unwinds the draw window with the frame INCOMPLETE, but the "
             "compositor still cleared the framebuffer with the theme "
             "background and PRESENTED it — every late-halting app's first "
             "real frame was erased by its own next-frame background "
             "(composeStopwatch: frame 1 drew 265 ops INCLUDING all three "
             "texts, replayed, then frames 2-6 halted and wiped it to the "
             "(13,15,18) fill; dooz: the 250-gray 'anchor' was the dishonest "
             "presentation of an unfinished frame — the CONT-36 §6 decode, "
             "recorded PENDING). ART/SurfaceFlinger law: an unfinished frame "
             "is NEVER presented; the display keeps the last complete frame.",
    "priority": "P0",
    "layer": "framework/canvas-clip + framework/text-builder + "
             "compositor/frame-honesty",
    "root_cause": "OP-LEVEL DECODE CHAIN (2026-10-10, run/cont37, androguard + "
                  "env-gated bounded engine diags on 054b9bd52fa695fc): "
                  "(1) the APK's SINGLE Luv;->I dispatch site is Loc0.c pc=106; "
                  "the text painters Lte1/Lod1 (implements Luv; — the draw-block "
                  "interface) are created ONLY by the ModifierNodeElement "
                  "factories Lqe1.d/Lld1.d via the base-class virtual "
                  "Ltk0;->d() from Lio0.b — the [UV-DISPATCH] watch proved "
                  "Lte1.I IS dispatched (r=1, coordinator l set — the "
                  "attach-gate theory DEAD), [LTE1-SEL] proved the resolution "
                  "SUCCEEDS (best=(Loc0;)V, cands=9) — the body runs. "
                  "(2) [F298-GCB]: Lg6.d's getClipBounds gate — unhandled → "
                  "typed-default false → silent abort before Layout.draw. "
                  "(3) [F298-OBTAIN]/[F298-BUILD]/[F298-SETTER]: obtain stores "
                  "text.len=17/2/2, the setter chain (setTextDirection first!) "
                  "clobbers source via the prefix match, build reads "
                  "source_len=0 chars=0. (4) frame trace: frame 1 "
                  "[C013-ONDRAW] ops=265 REPLAYED (rp=265) with the text ops "
                  "interleaved in the op stream ([S109-DRAWTEXT] replay rows "
                  "present) — then frames 2-6 halt in-window and the "
                  "unconditional fb.clear(win_bg)+present erased it all. "
                  "PROBE fixtures/fnew298_probe (real toolchain; frame 1 "
                  "drawColor green + frame 2 a DEX busy loop the loop guard "
                  "halts mid-draw): PRE ×3 on ddc37884601ca802 (the wave "
                  "changes stashed, Makefile -g0 kept): corner=(48,48,48) — "
                  "the green marker WIPED — runner-side KEEP-CORNER FAIL ×3; "
                  "POST ×3 on a181d7b317e015c8: corner=(0,255,0) ×3, "
                  "KEEP=5/frame, [F298-KEEP] presentation-skip rows ×5/run.",
    "fix": "THREE coordinated generic points, one semantic family, no app "
           "knowledge: (1) CanvasShadow gains the getClipBounds law (AOSP "
           "Canvas.java: the CURRENT clip bounds in device coords, true when "
           "non-empty; the tracked clip_ state when active, else the device "
           "bounds canvas_w_/canvas_h_; int fields via set_object_int_field). "
           "(2) the StaticLayout$Builder setter law keys the source store on "
           "the EXACT 'setText' name (setTextDirection/setTextLocale store "
           "their own fields — textDir opaque — never the text payload). "
           "(3) the FRAME-HONESTY law: the engine sets "
           "draw_window_budget_halted_ when ANY halt unwinds through the draw "
           "window (dalvik_engine.cpp callee-halt unwind site); the compositor "
           "re-arms frame_honesty_begin() at each frame entry and SKIPS the "
           "fb→framebuffer_ presentation when frame_honesty_keep_prev() "
           "([F298-KEEP] row) — the last COMPLETE frame survives; P1-6 "
           "extension (P1-6 covered render FAILURES; this covers in-draw "
           "halts). Build-config note: dalvik_engine.cpp outgrew the -g "
           "cc1plus peak on the 4 GB host (repeated OOM kills); the Makefile "
           "gains a per-file rule building it -O2 -g0 (SAME optimizer, debug "
           "sections only dropped; recorded in the Makefile comment).",
    "evidence": "evidence/cont37/FRAME_HONESTY_FRONTIER.md; runs run/cont37/"
                "{csw_k0watch,csw_attwatch,csw_rflag,csw_iface,csw_f281c2,"
                "csw_lte1sel,csw_lookup,csw_clipfix,csw_gcb,csw_sldraw,"
                "csw_obtain,csw_build2,csw_setter,csw_fix1,csw_s109,csw_color,"
                "csw_honest,csw_target_r1..3,f298_pre_r1..3,f298_post_r1..3,"
                "anchor_dooz,regression}; probe fixtures/fnew298_probe "
                "committed + wired into scripts/w4_build_probes.sh and "
                "scripts/cont37_regression.sh (standing battery, runner-side "
                "KEEP-CORNER pixel row). POST ×3: 19/0 PASS ×3 with the green "
                "corner kept ×3. Target ×3: composeStopwatch frame "
                "9afb2bd2606f303e → bbaf8f76308dc267 ×3 (the app's OWN first "
                "frame — 265 ops incl. the three StaticLayout texts — finally "
                "presented; [F298-KEEP] ×5/frame). dooz anchor MOVED "
                "d602648e8e401895 → 31ddd4d5b8e6d18e ×3 (the honest keep-empty "
                "state — the boot composition needs ~15.3 s and never "
                "completes; the old 250-gray was the wiped-frame lie). "
                "FULL REGRESSION at a181d7b317e015c8: 7/8 anchors ×3 "
                "BYTE-IDENTICAL (microtimer da73010a37dd0189, unote "
                "4f1a9e4e8f64fae8, gmdice f3b483fe7b7cf51b, opencalc "
                "a976d2f9fb675cb3, tttdeluxe af6094295ecb50e3, flappycow "
                "13cf47464d9787f4, g2048 59ca1526611c4622 — ZERO drift, "
                "KEEP=0: the law never fires for completing apps), battery == "
                "CONT-28..36 records EXACTLY (fcol 140/0, f259 49/0, f259g "
                "84/7-known, f266 42/0, f268 96/0, fnew253 147/0, fnew286 "
                "10/0, fnew289 28/0, fnew252 56/0, fnew290 56/0, fnew291 "
                "56/0, fnew292 70/0, fnew293 56/0, fnew294 77/0, fnew295 "
                "49/0, fnew296 42/0, fnew297 42/0) + fnew298 19/0, simplecalc "
                "×3 rc=0 7960bce447ac6d8f FULL SUCCESS retained.",
    "bounds": "composeStopwatch's texts now REACH the framebuffer (the frame "
              "carries them at the app's own positions/sizes: title "
              "(1025,80.976) size 60.375, digits (753,974.976) size 236.25 and "
              "(753,1092.98) size 157.5) but their COLOR is the layout-paint "
              "default BLACK on the app's black surface — the Compose "
              "draw-brush (Lbo1) color application to the layout TextPaint is "
              "the next divergence in the chain (the TextPaints receive "
              "setColor(0xff000000) — [F298-SETCOLOR]; the app-visible white/"
              "gray text colors flow through the draw brush, whose "
              "application point in the R8 DEX is not yet decoded). The dooz "
              "boot-budget face is now HONESTLY visible (keep-empty white): "
              "its first composition needs ~15.3 s of engine time — the "
              "15 s budget cannot complete it; recorded PENDING (a "
              "composition-cost wave, not a paint law). STREAM-OPEN message "
              "spelling: PENDING (unchanged). Standing: F-NEW-288 (Track A "
              "TextUnit spin); SimpleCalc input-pump (Track B); the "
              "Fragment/Preference family (own probe cycle, build on "
              "F-NEW-234).",
}
r["roots"].append(e)
r["total"] = len(r["roots"])
with open(REG, "w") as f:
    json.dump(r, f, indent=2, ensure_ascii=False)
print("registry updated:", r["baseline_head"], "roots:", len(r["roots"]))
