#!/usr/bin/env python3
"""CONT-27 registry update: F-NEW-281, F-NEW-282, F-NEW-283 (589 -> 592)."""
import json

PATH = "/home/z/my-project/root_registry.json"
d = json.load(open(PATH))
ids = [r["id"] for r in d["roots"]]
assert "F-NEW-281" not in ids and "F-NEW-282" not in ids and "F-NEW-283" not in ids, "dedup: rows exist"

d["roots"].append({
    "id": "F-NEW-281",
    "status": "ROOT-CAUSED-FIXED",
    "title": "INTERFACE DISPATCH MUST SELECT BY EXACT (NAME, DESCRIPTOR) — the F-091b descriptor-only walk picked the first same-shape method regardless of name: CompositionLocalAccessorScope.getCurrentValue(CompositionLocal) on a PersistentCompositionLocalHashMap receiver dispatched the raw PersistentMap.get override (invoke-super + check-cast ValueHolder + return) answering a ValueHolder where the accessor law demands readValue()'s value; the real implementation is the inherited interface DEFAULT PersistentCompositionLocalMap.getCurrentValue = read(this) (getOrElse(key){defaultValueHolder}.readValue(this)). Three arms landed: (281) exact (name, descriptor) walk — receiver class chain first, then interface-hierarchy DEFAULT bodies (BFS, bounded 16); (281b) token-referent law — a heap java.lang.Class token receiver resolves to its __referent_desc for every Class-bridge method (getAnnotation/getName/… queried Ljava/lang/Class; instead of the referent); (281c) strict (name, proto) gate on the F-068 runtime-class-first arm — a same-name WRONG-shape overload (InitializerViewModelFactory.create(Class,extras) picked for the Factory.create(KClass,extras) call site) must not win via the legacy lenient selection before the interface-default search runs.",
    "priority": "P0",
    "layer": "dex/invoke-interface-dispatch",
    "root_cause": "PROVEN AT RUNTIME (2026-10-09, real-Compose oracle 1.11.4 rebuild sha16 3359ed00e3add03d size-exact 8,233,173 bytes, binary 1ff06737f7b12ad4): method trace shows lambda$0 enter → INTERFACE-SIG → PersistentHashMap.get/TrieNode walk → valueAtKeyIndex → INTERFACE-SIG-done, with ZERO rows for the lambda tail (check-cast HostDefaultProvider @0x000a + invoke-interface getHostDefault @0x000c — disassembled via scripts/cont27_disasm.py) and control resuming in NavHost; ISE 'NavHost requires a ViewModelStoreOwner' at NavHostKt.NavHost pc=1780. DEX ground truth: PersistentCompositionLocalHashMap declares TWO get methods (7-unit raw get = invoke-super; 13-unit value get) and the interface default getCurrentValue (5 units, read(this)) lives on PersistentCompositionLocalMap; upstream law = JVMS 5.4.3.4 (name+descriptor candidates) + CompositionLocalMap.kt/CompositionLocal.kt 1.11.4 sources.",
    "fix": "dalvik_engine.cpp only, zero app/package knowledge: (1) F-NEW-281 exact-name+descriptor arms inside the f91b_dex_interface block (class-chain walk + interface-hierarchy DEFAULT BFS bounded 16, MINIANDROID_F281_TRACE env-gated diagnostics); (2) F-NEW-281b receiver-referent resolution for Ljava/lang/Class; heap tokens in the Class-bridge (read-only __referent_desc fallback); (3) F-NEW-281c dex-exact gate before the runtime-class-first try_recursive_invoke when a concrete proto is available (empty proto keeps legacy behavior).",
    "runtime_evidence": "Oracle post-fix: the NavHost ISE is GONE; [F281-IFACE-DEFAULT] PersistentCompositionLocalMap.getCurrentValue → REAL DEX dispatched; ViewModelStoreOwner resolves via the view-tree tag (view_tree_view_model_store_owner 2131034206); NavControllerViewModelInitializer factory matches; the composition advances through LaunchedEffect/produceState coroutines INTO LayoutNode.draw$ui / AndroidComposeView.dispatchDraw (205 GraphicsLayerImpl rows — the real draw pipeline). Regression at final binary 6823170ebd443118: 24/24 anchor runs byte-identical x3 (dooz/microtimer/unote/gmdice/opencalc/tttdeluxe/flappycow/g2048), probe battery fcol 140/0, f259 49/0, f259g 84/7 (same known-honest F259-L row), f266 42/0, f268 96/0.",
    "next_divergence": "GraphicsLayer created WITHOUT executing its <init> (impl field null → GraphicsLayer.setPosition f141-null-recv NPE inside LayoutNode.draw$ui, caught by compose's own catch-alls, rethrown by rethrowWithComposeStackTrace → APP BOUNDARY): the ctor-skip family — SAME family as Simple Calculator's Toolbar ctor-context face (F-NEW-283 fixed the inflate-gate side; the GraphicsLayer allocation path needs its own decode — AndroidGraphicsContext.createGraphicsLayer (109 units, SDK>=29 → new GraphicsLayerV29) never entered per the method trace).",
}),
d["roots"].append({
    "id": "F-NEW-282",
    "status": "ROOT-CAUSED-FIXED",
    "title": "CLASS_REF TOKEN MATERIALIZATION AT REFERENCE BOUNDARIES (F-103 completion): a CLASS_REF-typed register value (const-class / KClass literal) is NOT a heap reference; the frame machinery only carries OBJECT_REF values intact across nested DEX calls, so a raw CLASS_REF argument degraded to REGISTER_UNSET/zero by the time the callee stored or compared it. Live face: ClassReference.<init>(Ljava/lang/Class;)V bound the token as p1={t=CLASS_REF} at frame entry (MINIANDROID_PARAM_TRACE) yet the body's iput-object v2, v1, jClass stored <unset> — every later consumer (getJClass/equals/isInstance/getQualifiedName) saw null and ViewModelProvider.get(KClass) could not match its registered initializer (IAE 'No initializer set for given class null' → APP BOUNDARY, real-Compose oracle NavControllerViewModel face).",
    "priority": "P0",
    "layer": "dex/frame-arg-boundary",
    "root_cause": "PROVEN AT RUNTIME (2026-10-09): PARAM-TRACE read-back shows v1={t=7 obj=...} v2={t=6} at ctor ENTRY; FIELD-TRACE shows the iput-object storing <unset>; three ClassReference objects constructed with jClass unset (obj#2288/3951/3962) or a wrong-typed object (obj#3966 ← obj#3962). The engine already mints heap-backed Class tokens (F-103 class_token_ids_, F-NEW-218 token-backing validation, F-NEW-249 stable Object.getClass) — the gap was that raw CLASS_REF register values crossing a callee frame boundary were not normalized to those tokens.",
    "fix": "dalvik_engine.cpp only: (1) execute_method_internal materializes every CLASS_REF arg to its heap token OBJECT_REF (F-069 identity map; allocates + records __referent_desc when unseen) before write_p; (2) execute_iput_object materializes CLASS_REF sources to the same token on the store side. MINIANDROID_F282_TRACE env-gated, bounded 24.",
    "runtime_evidence": "Post-fix PARAM-TRACE: a1={t=7 obj=3970 cls=Ljava/lang/Class;} at ctor entry; FIELD-TRACE put-obj jClass obj#3971 value=obj#3970 and obj#3982 ALSO obj#3970 (stable per-descriptor identity — the initializer match now compares the SAME token). ViewModelProvider.get(KClass) matches; NavControllerViewModel created; oracle advances into the draw pipeline. Registry-adjacent: after F-NEW-281b the getQualifiedName/getCanonicalName chain resolves the real name (cache keyed by Class.getName string).",
    "next_divergence": "None for this family — equals/getOrCreateKotlinClass/getQualifiedName all verified live.",
}),
d["roots"].append({
    "id": "F-NEW-283",
    "status": "ROOT-CAUSED-FIXED",
    "title": "DEX-EXISTENCE CONSTRUCTOR AUTHORITY IN THE INFLATE GATE: is_app_class_descriptor suppressed the whole Landroid/ tree, so support-v7/androidx classes shipped in the APK DEX never executed their real <init> — the inflater built them as shadow-only views and every ctor-initialized field stayed null. Live face (Simple Calculator com.simplemobiletools.calculator vc8 sha 68da25fd9fdf54b4): Landroid/support/v7/widget/Toolbar; <init> never ran → measure-scratch int[] fields null → Toolbar.onMeasure pc=152 aput-null NPE + onLayout pc=44 aput-null NPE → 2 uncaught → rc=1 → white-screen verdict (the SAME law family the ADDITIONAL-AUDIT P1-3 note already established for com.google.android.*: the AOSP authority is 'does the class exist in the APK DEX', NOT the package prefix).",
    "priority": "P0",
    "layer": "resources/layout-inflater",
    "root_cause": "PROVEN AT RUNTIME (2026-10-09, binary 5a7e47b274a04b7e): MINIANDROID_METHOD_TRACE shows ZERO Toolbar.<init> METHOD-IN rows while Toolbar getters run (getWrapper/getTitle/...); DEX ground truth (scripts/cont27_disasm.py): Toolbar.<init>(Context,AttributeSet,int) 349 units allocates the int[2] scratch at pc=0x0021 (new-array [I + iput f@2571); the engine's dex_class_exists_hook_ was already installed (execution_engine.cpp V4-TAG law) but the ctor gate at layout_inflater.cpp:998 used only the prefix rule.",
    "fix": "layout_inflater.cpp only: the inflate ctor gate becomes prefix-rule OR dex_class_exists_hook_ (probe result cached thread_local per descriptor — classes cannot disappear). Framework views (Landroid/view/View etc., absent from app DEX) keep byte-identical behavior; every support/androidx class bundled in an APK DEX now gets its real constructor with the F-NEW-197 XML-AttributeSet law intact.",
    "runtime_evidence": "Post-fix Simple Calculator x3 (r2/r3/r4): rc=0, Status SUCCESS (main.cpp law: exit 0 ONLY on full SUCCESS), uncaught 2→0, aput-null 0 occurrences, Toolbar measure/layout completes; the rendered tree is the app's OWN layout — ActionBarOverlayLayout→ContentFrameLayout→LinearLayout(7) with the calculator display TextView text='0' and the real keypad Buttons text='mod','^','√','C','7','8','9','÷','4','5','6','*','1','2','3','-' at the correct 270x262 grid positions; screenshot 7960bce447ac6d8f x3 (byte-identical to the CONT-26 recorded sha — NOTE: CONT-26's evidence described that sha as 'white/blank'; pixel analysis (121 unique sampled colors: 6fa8dc blue keypad, fafafa background, f68630 orange accent) CORRECTS that description — the content was already present pre-fix; the fix's effect is rc 1→0 with the NPE family eliminated, not a pixel change). Regression at final binary 6823170ebd443118: 24/24 anchors x3 byte-identical (incl. dooz/opencalc — other support/androidx consumers unaffected), flappycow Surface/GL + g2048/tttdeluxe Canvas intact, probe battery green, positive control fnew253_probe sha 7602563f52cce823 + 147 PASS/0 FAIL.",
    "next_divergence": "None recorded for Simple Calculator at the 5-frame/15s sweep protocol — its first full SUCCESS. Deeper interaction (calculator button presses → display updates) is the next frontier class (input-pump family).",
})

d["summary"]["last_updated"] = ("CONT-27: F-NEW-281 ROOT-CAUSED-FIXED (interface dispatch exact name+descriptor law — 3 arms: "
                                "exact-name walk/interface-hierarchy defaults/token-referent Class-bridge; oracle NavHost ISE GONE, "
                                "composition reaches the real draw pipeline) + F-NEW-282 ROOT-CAUSED-FIXED (CLASS_REF heap-token "
                                "materialization at frame-arg boundary + iput store side; ClassReference.jClass identity verified live) "
                                "+ F-NEW-283 ROOT-CAUSED-FIXED (DEX-existence constructor authority in the inflate gate; Simple Calculator "
                                "first FULL SUCCESS rc=0 x3 with the app's own keypad rendered). Regression at binary 6823170ebd443118: "
                                "24/24 anchors x3 byte-identical, probe battery green, fnew253 control green. Registry 589→592.")
d["total"] = len(d["roots"])
json.dump(d, open(PATH, "w"), indent=1, ensure_ascii=False)
print("registry rows:", len(d["roots"]), "| total field:", d["total"])
