#!/usr/bin/env python3
"""CONT-28 registry update: F-NEW-284, F-NEW-285 (592 -> 594)."""
import json

PATH = "/home/z/my-project/root_registry.json"
d = json.load(open(PATH))
ids = [r["id"] for r in d["roots"]]
assert "F-NEW-284" not in ids and "F-NEW-285" not in ids, "dedup: rows exist"

d["roots"].append({
    "id": "F-NEW-284",
    "status": "ROOT-CAUSED-FIXED",
    "title": "SUPER-DISPATCH MUST CARRY THE CALL-SITE PROTO (F-023 completion on the invoke-super arm): execute_invoke_super resolved proto_35c and used it for EXP-095 signature-aware arg conversion, but did NOT pass it to try_recursive_invoke — every super-call selected overloads by SHAPE (arity/bytecode) instead of the (name, descriptor) pair (JVMS 5.4.5). Live face (real-Compose oracle, draw pipeline): NodeCoordinator declares TWO same-name 32-unit overloads placeAt-f8xVGno(JF, Landroidx/compose/ui/graphics/layer/GraphicsLayer;)V and placeAt-f8xVGno(JF, Lkotlin/jvm/functions/Function1;)V; LayoutModifierNodeCoordinator.placeAt(JF, Function1)V invoke-super'd without a descriptor, the loose shape loop hit the GraphicsLayer body first, its `layer` param register received the Function1 lambda (PlaceableKt$DefaultLayerBlock$1 obj#1605), placeSelf-MLgxB_4 carried the lambda into the explicitLayer slot (PARAM-TRACE: a3=NULL a4=lambda — the Function1 call must produce a3=lambda a4=NULL), AndroidComposeView.createLayer took the explicitLayer!=null branch and GraphicsLayerOwnerLayer.<init> bound the lambda as its graphicsLayer (PARAM-TRACE a1=obj#1605 cls=PlaceableKt$DefaultLayerBlock$1). Every later GraphicsLayer.setPosition/record on that object ran REAL bytecode reading f@29742 (impl) on the lambda — null — the f141-null-recv NPE recorded by CONT-27 as 'GraphicsLayer ctor-skip'.",
    "priority": "P0",
    "layer": "dex/invoke-super-dispatch",
    "root_cause": "PROVEN AT RUNTIME (2026-10-09, oracle rebuild size-exact 8,233,173 bytes at baseline binary 6823170ebd443118): (1) CONT-27's recorded GraphicsLayer face reproduced (rc=1, PARTIAL, sha16 b5a7a35d5fe0564b); (2) DEX scan (scripts/cont28_newinst_scan.py — correct-width instruction walker) proves the ONLY new-instance GraphicsLayer site lives inside AndroidGraphicsContext.createGraphicsLayer (109 units) and that method NEVER entered (no RET-BEFORE row, uncapped instrument), while GraphicsLayer.<init> also never entered — the receiver had to be an engine-side substitute; (3) PARAM-TRACE pinned the substitute: PlaceableKt$DefaultLayerBlock$1 in the graphicsLayer slot of GraphicsLayerOwnerLayer.<init> and in explicitLayer of createLayer; (4) new MINIANDROID_OVERLOAD_TRACE diagnostics (env-gated, bounded 120) captured the mispick live: '[OVERLOAD-PICK] Landroidx/compose/ui/node/NodeCoordinator; want=placeAt-f8xVGno exact_desc=absent' with both 32-unit overloads as candidates — descriptor ABSENT because the super-dispatch arm dropped it.",
    "fix": "dalvik_engine.cpp only (execute_invoke_super), zero app knowledge: hoist proto_35c to dispatch scope (empty when unresolvable — legacy behavior preserved) and pass it as try_recursive_invoke's exact-descriptor authority, completing F-023/F-280 on the super arm. Plus the generic MINIANDROID_OVERLOAD_TRACE=<method-substr> diagnostic (selection site, bounded 120 rows) and MINIANDROID_ALLOC_TRACE=<class-substr> (DalvikHeap::allocate, bounded 200) — both read-only, env-gated, zero app knowledge.",
    "runtime_evidence": "Post-fix (binary 9c42dd61+2 laws): the explicitLayer/lambda misalignment is GONE — createLayer takes the real createGraphicsLayer branch; GraphicsLayerV29 objects materialize through the REAL factory chain (GraphicsLayerV29 receivers live in LIFEWIN rows; GraphicsLayer.<init> + GraphicsLayerV29.<init> run real DEX); GraphicsLayerV29.record receives a REAL GraphicsLayer (obj#7255 cls=...layer/GraphicsLayer;) as parentLayer; GraphicsLayerV29.setPosition/setInvalidated/recordInternal execute; BackgroundNode.drawRect reaches PC=10/68 (real content draw inside the layer). The f141-null-recv GraphicsLayer face count: >200 pre-fix → 0. Regression at final binary: 24/24 anchor runs byte-identical x3 (dooz/microtimer/unote/gmdice/opencalc/tttdeluxe/flappycow/g2048), probe battery green (fcol 140/0, f259 49/0, f259g 84/7-known, f266 42/0, f268 96/0), Simple Calculator FULL SUCCESS retained.",
    "next_divergence": "Compositing: GraphicsLayer.draw$ui_graphics returns early (before @0x0132 invoke-interface GraphicsLayerImpl.draw → V29.draw → Canvas.drawRenderNode) — the layer-recorded ops (BackgroundNode background) reach the frame only through the direct-fill path; the frame-truth gate still reads DEFAULT_BACKGROUND_ONLY.",
}),
d["roots"].append({
    "id": "F-NEW-285",
    "status": "ROOT-CAUSED-FIXED",
    "title": "RENDERNODE SHADOW CLAIM GATE MUST MATCH ITS DISPATCH MATCHER: CanvasShadow::handles_class claimed only Landroid/view/RenderNode; while CanvasShadow::dispatch() already implements the beginRecording/endRecording/setPosition law for ANY '*RenderNode;' class (cls.find(\"RenderNode;\")). The real-Compose oracle (GraphicsLayerV29.record, ui 1.11.4) calls Landroid/graphics/RenderNode;.beginRecording()Landroid/graphics/RecordingCanvas; (AOSP's SDK>=29 graphics-side RenderNode). Unclaimed, the invoke fell through bridge_to_api and answered VOID: move-result-object left the register <unset>, GraphicsLayerV29.record stored it via CanvasHolder.getAndroidCanvas().setInternalCanvas(<unset>) (FIELD-TRACE put-obj ... obj#7248 value=<unset> OVERWRITING the valid obj#537), and every recorded draw op died f141-null-recv 'Attempt to invoke Landroid/graphics/Canvas;.drawRect on a null object reference' at AndroidCanvas.drawRect pc=10 → APP BOUNDARY. AOSP authority: android.graphics.RenderNode.beginRecording() returns the node's RecordingCanvas — identical law to the android.view variant the shadow already served.",
    "priority": "P0",
    "layer": "framework/canvas-shadow-claim",
    "root_cause": "PROVEN AT RUNTIME (2026-10-09): after F-NEW-284 the first divergence MOVED to the canvas chain; FIELD-TRACE (MINIANDROID_FIELD_TRACE=internalCanvas) shows the put of obj#537 by AndroidCanvas.<init> then the OVERWRITING put value=<unset> by setInternalCanvas on obj#7248; DEX ground truth (scripts/cont28_disasm.py): GraphicsLayerV29.record @0x0002 invoke-virtual Landroid/graphics/RenderNode;.beginRecording()Landroid/graphics/RecordingCanvas; → @0x0016 setInternalCanvas with that result; CanvasShadow.handles_class (canvas_shadow.h:191-192) claimed only the android.view variant while dispatch (canvas_shadow.cpp:857-876) serves the whole family — the registry gate is narrower than the implemented law.",
    "fix": "canvas_shadow.h only: handles_class adds cls.find(\"RenderNode;\") != std::string::npos — claiming the family the dispatch already serves. No dispatch logic changed; Landroid/graphics/Canvas;/Paint;/Path; claims untouched.",
    "runtime_evidence": "Post-fix: beginRecording returns a REAL Landroid/graphics/RecordingCanvas; heap object (CanvasShadow get_or_create law); the setInternalCanvas(<unset>) overwrite is GONE; AndroidCanvas.drawRect executes for real (BackgroundNode.drawRect PC=10/68, 1M+ instruction draw); crash.log TOTAL ERRORS: 0 — the oracle run is exception-free for the first time in the draw pipeline; the frame carries the app's OWN Material3 theme surface color fef7ff (full-PNG decode, single uniform fill — app-owned pixels from the real draw path, honestly NOT yet full content: text/buttons not yet composited).",
    "next_divergence": "GraphicsLayer.draw$ui_graphics early-return before the @0x0132 GraphicsLayerImpl.draw interface call (V29.draw → Canvas.drawRenderNode never enters; drawRenderNode 0 rows) — the layer-recorded ops need the drawRenderNode compositing step to reach the frame.",
})

d["total_roots"] = len(d["roots"])
d["total"] = len(d["roots"])
d["count"] = len(d["roots"])
d["generated"] = "CONT-28 (2026-10-09)"
json.dump(d, open(PATH, "w"), indent=1, ensure_ascii=False)
print("registry updated:", len(d["roots"]), "rows")
