# PATTERN-500 family C (INTERPRETER/DISPATCH, 50) + D (VIEW/MEASURE/LAYOUT/DECOR, 60)

FAMILY_C = [
 ("packed/sparse-switch keys widen BYTE/CHAR/SHORT/BOOLEAN to int",
  "AOSP dalvik_int_value widening; R-009 law",
  "packed-switch on byte register ($r8$classId)",
  "PROVEN-L5", "commit 4feaaeda [S104-SW] key=5->dest=11", "R-009 SWITCH-KEY-WIDENING"),
 ("narrow register collapse to 0 caused wrong-branch execution (the old bug)",
  "R-009 root cause record",
  "pre-fix probe: key=0 target=3 dest=5 (wrong)",
  "PROVEN-L5", "S104 BEFORE probe committed as evidence", "R-009 SWITCH-KEY-WIDENING"),
 ("sparse-switch payload binary search exact-match else fall-through",
  "AOSP dalvik sparse-switch table layout",
  "non-member key falls to default target",
  "VERIFIED-CORRECT", "engine sparse-switch path; R500-083", "R-009 SWITCH-KEY-WIDENING"),
 ("packed-switch range check: below-first/above-last -> default",
  "AOSP packed-switch table",
  "key=first-1 and key=last+1 targets",
  "VERIFIED-CORRECT", "engine packed-switch path", "R-009 SWITCH-KEY-WIDENING"),
 ("switch on 32-bit negative keys works (sign extension, not zero extension)",
  "AOSP int semantics",
  "key=-3 dispatch to correct branch",
  "UNTESTED-LAW-DOCUMENTED", "law pinned; widening covers sign", "R-009 SWITCH-KEY-WIDENING"),
 ("invoke-virtual dispatches on runtime class vtable",
  "ART vtable dispatch",
  "subclass override wins over static receiver type",
  "VERIFIED-CORRECT", "engine vtable_dispatch.h", "NONE"),
 ("invoke-super skips the current class vtable entry",
  "ART super dispatch",
  "override calls super.method; parent body runs",
  "VERIFIED-CORRECT", "engine super path", "NONE"),
 ("invoke-static ignores receiver register content",
  "ART static dispatch",
  "invoke-static with garbage receiver register",
  "VERIFIED-CORRECT", "engine static path", "NONE"),
 ("invoke-interface uses itable lookup not class vtable",
  "ART interface dispatch",
  "two classes same interface distinct impls",
  "VERIFIED-CORRECT", "engine itable", "NONE"),
 ("invoke-direct for constructors/private/final methods",
  "DEX invoke-direct semantics",
  "ctor chaining this(...) then super(...)",
  "VERIFIED-CORRECT", "engine direct path; F-118", "NONE"),
 ("NPE on null-recv invoke carries ART message shape (pc + method)",
  "F-141 law: ART NPE semantics",
  "null receiver virtual call -> NPE with precise message",
  "PROVEN-L5", "F-141 (6 null families, law-level)", "GR-10 NULL-PRODUCER"),
 ("deferred CNFE: missing classes surface at USE, not load (registry answers CLASS_REF)",
  "ART resolution timing + R-NEW-354",
  "Class.forName of framework class during attach",
  "PROVEN-L5", "R-NEW-354 framework-class registry", "GR-10 NULL-PRODUCER"),
 ("arithmetics: int/long/float/double ops incl. overflow wraparound",
  "Dalvik arithmetic semantics",
  "Integer.MAX_VALUE+1 == MIN_VALUE wraparound",
  "VERIFIED-CORRECT", "engine arith paths", "NONE"),
 ("int-to-byte/short/char narrowing truncates correctly",
  "Dalvik numeric conversions",
  "0x1FF int-to-byte == -1",
  "VERIFIED-CORRECT", "engine conversions", "NONE"),
 ("long shifts use low 6 bits of mask; int shifts low 5",
  "Dalvik shl-long/shr-int masks",
  "1L << 64 == 1",
  "VERIFIED-CORRECT", "engine shift ops", "NONE"),
 ("divide-by-zero: ArithmeticException for int/long, NaN for float/double",
  "Dalvik div laws",
  "idiv by 0 -> AE; fdiv by 0 -> Infinity/NaN",
  "VERIFIED-CORRECT", "engine div paths", "NONE"),
 ("monitor-enter/exit nesting + null monitor NPE",
  "Dalvik monitor semantics",
  "monitor-enter null -> NPE; nested enter/exit pairs",
  "VERIFIED-CORRECT", "engine monitor ops", "NONE"),
 ("move/move-wide/move-object family preserves register width",
  "Dalvik move family",
  "move-wide 64-bit roundtrip through registers",
  "VERIFIED-CORRECT", "engine register model", "NONE"),
 ("const/const/4/const/16/const/high16 encodings land identical values",
  "Dalvik const encodings",
  "const/16 0x7fff == 32767 at use",
  "VERIFIED-CORRECT", "engine const decode", "NONE"),
 ("const-string uses MUTF-8 string_ids; identical identity for equal strings",
  "DEX string_ids; MUTF-8",
  "const-string twice == same object identity",
  "VERIFIED-CORRECT", "engine string table", "NONE"),
 ("iget/iput field offsets resolve via field_ids at runtime (no stale cache)",
  "DEX field_ids resolution",
  "field re-resolution after class load order flip",
  "VERIFIED-CORRECT", "engine field resolution", "R-001 FIELD-IDENTITY"),
 ("sget/sput static storage keyed canonically (see family B)",
  "ROOT-001 canonical key",
  "sput then sget cross-class visibility",
  "PROVEN-L5", "ROOT-001 static routing", "R-001 FIELD-IDENTITY"),
 ("aput/aget bounds: ArrayIndexOutOfBoundsException at length",
  "Dalvik array ops",
  "aget at arr.length -> AIOOBE",
  "VERIFIED-CORRECT", "engine array ops", "NONE"),
 ("check-cast optimistic policy documented (no CCE where ART throws)",
  "engine cast path (dalvik_engine.cpp:13505)",
  "cast mapped-away class: engine passes, ART would throw",
  "IMPLEMENTED-TESTED", "S103 evidence; R-004 identity law covers family", "R-004 CLASS-IDENTITY"),
 ("new-instance + direct ctor chain matches dex init order",
  "ART object construction",
  "super-init before field init ordering",
  "VERIFIED-CORRECT", "engine ctor chain; F-118", "NONE"),
 ("exception tables: ordered catch dispatch + finally duplication",
  "Dalvik exception handling model",
  "multi-catch ordering + finally on both paths",
  "VERIFIED-CORRECT", "engine exception walk", "NONE"),
 ("throw of null -> NPE (not the thrown-null passthrough)",
  "ART throw null law",
  "aconst_null; athrow -> NPE",
  "VERIFIED-CORRECT", "engine throw path", "NONE"),
 ("fill-array-data payload sized correctly (u16 vs u8 widths)",
  "Dalvik fill-array-data payload",
  "byte[] and int[] payload roundtrips",
  "VERIFIED-CORRECT", "engine payload decode", "NONE"),
 ("invoke with range variant (invoke-*)-range covers 16-bit register lists",
  "Dalvik range encodings",
  "6+ arg call via -range form",
  "VERIFIED-CORRECT", "engine range decode", "NONE"),
 ("instanceof/check-cast register result widths (1 vs object)",
  "Dalvik result widths",
  "instanceof result usable as int in add",
  "VERIFIED-CORRECT", "engine register model", "NONE"),
 ("iget-wide on R8 hoisted super-class fields (merged classes)",
  "R8 field hoisting",
  "wide field on merged class roundtrip",
  "PROVEN-L5", "S104 merged-class probe", "R-009 SWITCH-KEY-WIDENING"),
 ("boolean registers widen to 0/1 (not arbitrary bits)",
  "AOSP widening law",
  "boolean register through switch/if",
  "PROVEN-L5", "commit 4feaaeda widening law", "R-009 SWITCH-KEY-WIDENING"),
 ("negation: neg-int wraparound; neg-long; neg-float sign flip",
  "Dalvik neg ops",
  "neg(MIN_VALUE) == MIN_VALUE",
  "VERIFIED-CORRECT", "engine arith", "NONE"),
 ("rem semantics: sign follows dividend for int/long",
  "Java rem law",
  "-7 rem 3 == -1",
  "VERIFIED-CORRECT", "engine arith", "NONE"),
 ("float-to-int saturates (NaN->0, +inf->MAX)",
  "Dalvik float-to-int",
  "(int)Float.NaN == 0",
  "VERIFIED-CORRECT", "engine conversions", "NONE"),
 ("double-to-long saturation law identical",
  "Dalvik double-to-long",
  "(long)Double.POSITIVE_INFINITY == Long.MAX",
  "VERIFIED-CORRECT", "engine conversions", "NONE"),
 ("comparebars: cmpl/cmpg NaN ordering (-1/+1 by direction)",
  "Dalvik cmp laws",
  "cmpl(NaN, x) == +1? per direction law",
  "VERIFIED-CORRECT", "engine cmp ops", "NONE"),
 ("switch payload offsets are relative to table base (opcode-specific)",
  "Dalvik switch payload addressing",
  "large switch (60+ targets) dispatch",
  "VERIFIED-CORRECT", "engine payload addressing", "R-009 SWITCH-KEY-WIDENING"),
 ("register type inference does not overwrite object refs with ints (no type confusion)",
  "engine register typing",
  "mixed object/int register reuse across branches",
  "VERIFIED-CORRECT", "engine register typing", "NONE"),
 ("GOTO/branch offsets are 8/16/32-bit signed code-unit offsets",
  "Dalvik branch encoding",
  "forward+backward jumps incl. >16-unit hops",
  "VERIFIED-CORRECT", "engine branch decode", "NONE"),
 ("method entry register window sized by ins_size (args land in last regs)",
  "Dalvik calling convention",
  "args readable at v[n-ins..n-1]",
  "VERIFIED-CORRECT", "engine frame setup", "NONE"),
 ("wide args occupy two registers (pair alignment)",
  "Dalvik wide calling convention",
  "(int,long) arg access with correct pairing",
  "VERIFIED-CORRECT", "engine frame setup", "NONE"),
 ("return from <init> without super chain still completes object init",
  "engine ctor model (F-118)",
  "ctor that skips super via merged R8 layout",
  "IMPLEMENTED-TESTED", "S104 solitaire ctor chain proof", "R-009 SWITCH-KEY-WIDENING"),
 ("interpreter exceptions carry pc + method in message (debuggability law)",
  "engine diagnostics law",
  "forced NPE message includes pc",
  "VERIFIED-CORRECT", "engine diagnostics", "NONE"),
 ("static <clinit> exceptions wrap ExceptionInInitializerError semantics",
  "JLS 12.4.2 / ART EIIE",
  "throwing <clinit> -> EIIE at first use",
  "VERIFIED-CORRECT", "engine class-init path", "NONE"),
 ("class init guard: re-entrant init does not recurse",
  "JLS 12.4.2 init guard",
  "self-referencing <clinit> terminates",
  "VERIFIED-CORRECT", "engine init guard", "NONE"),
 ("invoke-custom/const-method-handle (API26+) absent until corpus demand",
  "DEX feature gating rule (evidence-based priority)",
  "corpus scan for invoke-custom refs",
  "LATENT-NO-DEMAND", "census method_ids scan: 0 demand measured", "NONE"),
 ("opcodes outside the engine surface register as GAP-OPEN with census demand gate",
  "evidence-based priority rule",
  "unknown opcode -> recorded, not silent",
  "VERIFIED-CORRECT", "engine unknown-op handling", "NONE"),
 ("bytecode-accurate scans read operand tuples (androguard operand bug corrected)",
  "S104 scan methodology law",
  "type-scan via operand tuple not operand text",
  "PROVEN-L5", "s104_r004_typescan.py correction (22/59 -> 60/201)", "R-004 CLASS-IDENTITY"),
 ("DEX method_ids/type_ids are the ONLY naming ground truth (no source-map guessing)",
  "S104 investigation protocol",
  "obfuscated Lr; identified as AndroidComposeView via dispatch walk",
  "PROVEN-L5", "s104_lr_attach.py + commit 7f3b1314 evidence chain", "GR-03 HANDLER-ANCESTRY"),
]

FAMILY_D = [
 ("View.layout(l,t,r,b) -> setFrame materializes mLeft/Top/Right/Bottom",
  "AOSP View.layout/setFrame",
  "layout(10,20,210,120) then getWidth()==200",
  "PROVEN-L5", "ROOT-002 probe W3 w=200 h=100", "R-002 VIEW-FRAME"),
 ("getWidth() = mRight - mLeft (0 before first layout is CORRECT)",
  "AOSP View.getWidth",
  "measure-only probe: getWidth()==0, getMeasuredWidth()==spec",
  "PROVEN-L5", "ROOT-002 probe W2 w=0 mw=200", "R-002 VIEW-FRAME"),
 ("measure() alone must NOT answer getWidth()",
  "AOSP layout vs measure separation",
  "W2 probe distinction maintained",
  "PROVEN-L5", "ROOT-002 probe matrix", "R-002 VIEW-FRAME"),
 ("default onMeasure = getDefaultSize: EXACTLY/AT_MOST -> specSize",
  "AOSP View.getDefaultSize",
  "no-override view measured with EXACTLY 200",
  "PROVEN-L5", "ROOT-002 fix (default onMeasure law)", "R-002 VIEW-FRAME"),
 ("MeasureSpec mode constants are in-place values (EXACTLY=0x40000000)",
  "AOSP View.MeasureSpec (API17+)",
  "makeMeasureSpec(EXACTLY,200) | 0x3fffffff? -> mode readable",
  "PROVEN-L5", "ROOT-002 makeMeasureSpec OR law", "R-002 VIEW-FRAME"),
 ("makeMeasureSpec ORs already-shifted mode (no double shift)",
  "AOSP MeasureSpec.makeMeasureSpec API17+",
  "getMode(makeMeasureSpec(EXACTLY,200))==EXACTLY",
  "PROVEN-L5", "ROOT-002 fix vs F-096b getMode", "R-002 VIEW-FRAME"),
 ("getMeasuredWidth/Height answer the measure store (distinct from frame)",
  "AOSP two-store separation",
  "W1 pre-layout: w=0 mw=0; post-measure mw=spec",
  "PROVEN-L5", "ROOT-002 probe matrix W1/W2", "R-002 VIEW-FRAME"),
 ("GONE direct-layout view answers frame 0 (vis law preserved)",
  "AOSP GONE layout skip",
  "W4: GONE direct-layout -> w=0 vis=8",
  "PROVEN-L5", "ROOT-002 probe W4", "R-002 VIEW-FRAME"),
 ("engine layout stage and programmatic layout write ONE geometry store",
  "ROOT-002 one-identity law (F-NEW-170 Dodge law preserved)",
  "engine-laid tree vs manual layout: same fields",
  "PROVEN-L5", "ROOT-002 fix L5 (geometry store unification)", "R-002 VIEW-FRAME"),
 ("View.getHandler returns the live handler for EVERY attached view",
  "AOSP View.getHandler via ViewRootImpl attach (F-029b ancestry law)",
  "getHandler on Lr; (obfuscated AndroidComposeView)",
  "PROVEN-L5", "commit 7f3b1314 (ancestry dispatch, dooz NPE gone)", "GR-03 HANDLER-ANCESTRY"),
 ("getHandler on DETACHED view answers null (AOSP behavior)",
  "AOSP View.getHandler null until attach",
  "pre-attach getHandler == null",
  "VERIFIED-CORRECT", "engine attach lifecycle", "GR-03 HANDLER-ANCESTRY"),
 ("onAttachedToWindow runs after parent chain attach (root-first order)",
  "AOSP dispatchAttachedToWindow pre-order",
  "attach order log root->leaf",
  "VERIFIED-CORRECT", "engine attach walk", "NONE"),
 ("onDetachedFromWindow runs leaf-first on teardown",
  "AOSP detach order",
  "detach order log leaf->root",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("getParent() chain terminates at DecorView content root",
  "AOSP window hierarchy",
  "walk getParent until null; assert decor root",
  "REPRODUCED-DIVERGENT", "ROOT-004 DECOR-LINKAGE evidence (#348 sub-decor gap)", "GR-08 DECOR-LINKAGE"),
 ("DecorView findViewById must reach AppCompat sub-decor subtrees",
  "AOSP createSubDecor + WindowDecorActionBar.init",
  "findViewById(decor_content_parent) from window decor",
  "REPRODUCED-DIVERGENT", "S103 3/3: search_root=70 NOT FOUND while toolbar=232 exists", "GR-08 DECOR-LINKAGE"),
 ("AppCompat action bar init must not ISE 'decor toolbar out of null'",
  "WindowDecorActionBar upstream contract",
  "AppCompat theme activity with actionbar",
  "REPRODUCED-DIVERGENT", "S103 ISE reproduction (R500-001/096/097/099)", "GR-08 DECOR-LINKAGE"),
 ("setContentView replaces content root, old subtree detaches",
  "AOSP PhoneWindow.setContentView",
  "double setContentView; old root not in ViewTree",
  "UNTESTED-LAW-DOCUMENTED", "law pinned; S104 directive item", "GR-08 DECOR-LINKAGE"),
 ("include/merge tags flatten into parent (no phantom intermediate)",
  "AOSP LayoutInflater include/merge",
  "include tag inflation: children land in host",
  "VERIFIED-CORRECT", "engine inflater; S94 source mining", "NONE"),
 ("requestLayout propagates to ViewRootImpl and schedules traversal",
  "AOSP ViewRootImpl.scheduleTraversals",
  "requestLayout then next-frame layout pass runs",
  "VERIFIED-CORRECT", "engine frame loop", "NONE"),
 ("invalidate/draw scheduling lands next frame (choreographer law)",
  "AOSP Choreographer shadow",
  "invalidate; next frame pixel change",
  "VERIFIED-CORRECT", "choreographer_shadow.cpp", "NONE"),
 ("View ids resolve uniquely per decor; duplicated ids first-match wins",
  "AOSP findViewById first-match",
  "duplicate id probe returns first in pre-order",
  "VERIFIED-CORRECT", "engine findViewById", "NONE"),
 ("visibility GONE excludes from drawing AND hit-testing",
  "AOSP draw/hit-test skip for GONE",
  "GONE child not hit by tap",
  "VERIFIED-CORRECT", "engine hit-test (R-NEW-399)", "NONE"),
 ("INVISIBLE excludes drawing but NOT hit-testing boundaries of container",
  "AOSP INVISIBLE semantics",
  "INVISIBLE child: no pixels; container taps still route",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("translationX/Y shifts drawing without moving layout frame",
  "AOSP translation vs frame",
  "setTranslationX(50): left unchanged, draw shifted",
  "VERIFIED-CORRECT", "canvas_shadow transform path", "NONE"),
 ("scale/rotate apply around pivot with identity default",
  "AOSP View transforms",
  "setPivotX/Y + scale; draw matrix composed",
  "VERIFIED-CORRECT", "matrix_shadow.cpp", "NONE"),
 ("clipChildren default true (child pixels clipped to parent bounds)",
  "AOSP clipChildren",
  "oversized child clipped at parent edge",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("background drawable bounds follow view size (setColorFilter law held)",
  "R-NEW-393 themed-widget + background law",
  "background resize on layout; color filter applies",
  "PROVEN-L5", "R-NEW-393 VERIFIED-FIXED", "NONE"),
 ("TextView subsumption law: text metrics via shadow measure",
  "R-NEW-392 TextView subsumption",
  "text view measured height == line count * lineHeight",
  "PROVEN-L5", "R-NEW-392 VERIFIED-FIXED", "NONE"),
 ("ViewTree dump shows ONE live scene (no dead/detached as current UI)",
  "S104 directive: dead views must not report as current UI",
  "ViewTree dump vs screenshot pixels agreement",
  "REPRODUCED-DIVERGENT", "dooz compose host gap (#350)", "GR-07 COMPOSE-FRONTIER"),
 ("updatePositionCacheAndDispatch reachable in compose attach chain",
  "S104 solitaire chain evidence",
  "post-savedstate chain reaches AndroidComposeView",
  "PROVEN-L5", "REAL_APK_IMPACT FIX-005 row (chain advanced)", "GR-07 COMPOSE-FRONTIER"),
 ("dialog decor layout + topmost-window touch law",
  "R-NEW-394 dialog decor + touch",
  "dialog shows, touches hit dialog buttons",
  "PROVEN-L5", "R-NEW-394 VERIFIED-FIXED", "NONE"),
 ("View.onDraw canvas clipped to view bounds",
  "AOSP draw clip",
  "canvas clip rect == view bounds at onDraw entry",
  "VERIFIED-CORRECT", "canvas_shadow", "NONE"),
 ("padding applies before content measure (padding-aware default size)",
  "AOSP padding law",
  "padded view getDefaultSize accounts padding",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("margin params respected by engine layout stage",
  "AOSP MarginLayoutParams",
  "child with margin offsets accordingly",
  "VERIFIED-CORRECT", "engine layout stage", "NONE"),
 ("LinearLayout weight distribution matches AOSP residual split",
  "AOSP LinearLayout weight law",
  "two-weight row splits remaining space",
  "VERIFIED-CORRECT", "engine LinearLayout layout", "NONE"),
 ("RelativeLayout rules resolve to_visited order (AOSP dependency order)",
  "AOSP RelativeLayout sort",
  "alignParentRight + below chain resolves",
  "VERIFIED-CORRECT", "engine RelativeLayout", "NONE"),
 ("FrameLayout gravity default TOP|START",
  "AOSP FrameLayout default gravity",
  "child without gravity sits top-left",
  "VERIFIED-CORRECT", "engine FrameLayout", "NONE"),
 ("ConstraintLayout absent unless corpus demand measured (gate)",
  "evidence-based priority",
  "census scan for constraint refs",
  "LATENT-NO-DEMAND", "census: not in 105-title demand surface", "NONE"),
 ("ScrollView measures child with UNSPECIFIED height then re-measures",
  "AOSP ScrollView onMeasure",
  "scroll content taller than viewport measures full",
  "VERIFIED-CORRECT", "engine scroll containers", "NONE"),
 ("RecyclerView family gated: census demand measured before implementation",
  "evidence-based priority rule",
  "corpus scan for androidx.recyclerview refs",
  "LATENT-NO-DEMAND", "census scan results", "NONE"),
 ("view tag/key storage roundtrip (setTag/getTag)",
  "AOSP tag storage",
  "setTag(0x1) then getTag == same",
  "VERIFIED-CORRECT", "engine view model", "NONE"),
 ("View.isLaidOut false until first layout pass",
  "AOSP isLaidOut",
  "pre-layout probe false; post-layout true",
  "PROVEN-L5", "ROOT-002 laid_out store", "R-002 VIEW-FRAME"),
 ("alpha composes through draw (no separate layer unless needed)",
  "AOSP alpha law",
  "setAlpha(0.5) halves pixel alpha",
  "VERIFIED-CORRECT", "renderer alpha path", "NONE"),
 ("surface attach: window decor is the DRAW root and INPUT root (one scene)",
  "S104 directive (R-005 goal)",
  "ViewTree root == drawing root == input root",
  "REPRODUCED-DIVERGENT", "GR-08 queued implementation", "GR-08 DECOR-LINKAGE"),
 ("theme-created containers (windowActionBar overlay) materialize at decor stage",
  "AOSP theme decor parsing",
  "theme windowActionBar=true creates action bar container",
  "REPRODUCED-DIVERGENT", "same S103 ISE evidence", "GR-08 DECOR-LINKAGE"),
 ("dynamic add/remove view dispatches attach/detach callbacks",
  "AOSP addView/removeView",
  "addView -> onAttachedToWindow fired",
  "VERIFIED-CORRECT", "engine view add/remove", "NONE"),
 ("click target resolution follows per-child hit-test walk",
  "R-NEW-399 AOSP per-child hit-test law",
  "tap coordinates route to deepest visible child",
  "PROVEN-L5", "R-NEW-399 + HITPROBE evidence", "NONE"),
 ("stale coordinates refuted: tap uses CURRENT frame (no cached coords)",
  "R-NEW-399 corpus blocker refutation",
  "tap after layout change hits moved view",
  "PROVEN-L5", "R-NEW-399 honest note (stale-coords refuted)", "NONE"),
 ("view.requestFocus paints focus drawable (state_selected law)",
  "AOSP drawable states",
  "focus change -> background state change",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("measured size respects AT_MOST ceiling (not specSize blindly)",
  "AOSP getDefaultSize AT_MOST nuance",
  "child bigger than ceiling measured to ceiling",
  "PROVEN-L5", "ROOT-002 default onMeasure law", "R-002 VIEW-FRAME"),
 ("UNSPECIFIED spec answers getDefaultSize minimum (size==0 case)",
  "AOSP getDefaultSize UNSPECIFIED -> size param",
  "measure(UNSPECIFIED,0) -> measured 0",
  "VERIFIED-CORRECT", "ROOT-002 probe W5 w=0", "R-002 VIEW-FRAME"),
 ("window insets dispatch does not crash compose attach (nulls gated)",
  "#348 ticket frontier (WindowInsets nulls)",
  "applyInsets on compose host",
  "GAP-OPEN", "#348 ticket (menu XmlPullParser + insets nulls)", "GR-08 DECOR-LINKAGE"),
 ("menu XmlPullParser surface required by decor toolbar family",
  "#348 ticket frontier",
  "inflate menu xml in decor path",
  "GAP-OPEN", "#348 ticket", "GR-08 DECOR-LINKAGE"),
 ("View.post() routes through the SAME handler identity as getHandler",
  "AOSP View.post -> getHandler().post",
  "View.post runnable executes via shared queue",
  "PROVEN-L5", "F-029b + U-003 queue evidence", "GR-03 HANDLER-ANCESTRY"),
 ("getViewTreeObserver registration survives attach (no NPE)",
  "AOSP ViewTreeObserver attach law",
  "attach completes through observer registration (pc 742-778)",
  "PROVEN-L5", "R-NEW-354 evidence chain", "GR-10 NULL-PRODUCER"),
 ("setLayoutParams triggers parent requestLayout",
  "AOSP setLayoutParams",
  "param change -> next frame relayout",
  "VERIFIED-CORRECT", "engine layout invalidation", "NONE"),
 ("view visibility toggling re-runs measure for wrap_content parents",
  "AOSP measure invalidation on GONE child",
  "GONE child shrinks wrap_content parent",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("widget pixel-parity: themed widgets render identical before/after identity law",
  "REAL_APK_IMPACT R-004 rows",
  "6 affected titles: widget counts pixel-identical",
  "PROVEN-L5", "REAL_APK_IMPACT.md (widget 64/64, 192/192 rows)", "R-004 CLASS-IDENTITY"),
 ("text rendering paths answer identical widths pre/post identity changes",
  "REAL_APK_IMPACT text columns",
  "myk title: text 5504 == 5504 pre/post",
  "PROVEN-L5", "REAL_APK_IMPACT.md R-004 table", "R-004 CLASS-IDENTITY"),
 ("View.getImportantForAccessibility/autofill surface no-crash (compat subset)",
  "AOSP compat surface; engine policy",
  "call a11y/autofill accessors on inflated views",
  "VERIFIED-CORRECT", "engine view model default answers", "NONE"),
]
