# PATTERN-500 family E (SCHEDULER/HANDLER/LOOPER, 45) + F (RESOURCES/THEME/ARSC, 45)

FAMILY_E = [
 ("main Looper + Handler materialize at runtime start (U-003)",
  "AOSP Looper.prepareMainLooper",
  "Looper.myQueue() non-null at activity ctor",
  "PROVEN-L5", "U-003 VERIFIED (3/3) worklog evidence", "NONE"),
 ("posted runnables EXECUTE (no silent no-op; stale comment corrected)",
  "U-003 execution evidence",
  "post {} -> runs within frame window",
  "PROVEN-L5", "U-003 H6 evidence (source comment stale)", "NONE"),
 ("front-posted runnables execute (PFQ fixed by ROOT-003)",
  "AOSP sendMessageAtFrontOfQueue law",
  "postAtFrontOfQueue {} -> runs",
  "PROVEN-L5", "ROOT-003 probe H4 front=RAN", "R-003 PFQ-ORDER"),
 ("PFQ message rides when=0 and is always due",
  "AOSP enqueueMessage(queue, msg, 0)",
  "PFQ during queued work drains first",
  "PROVEN-L5", "ROOT-003 fix enqueue_front ready_at=0", "R-003 PFQ-ORDER"),
 ("front-posts drain BEFORE normally-posted at equal ready time",
  "AOSP drain order law",
  "H6 order-final='-FP' reproduced 3/3",
  "PROVEN-L5", "ROOT-003 probe H6 order-final=-FP", "R-003 PFQ-ORDER"),
 ("multiple front-posts within one pump drain FIFO among themselves",
  "ROOT-003 documented subset",
  "two PFQs: order preserved",
  "PROVEN-L5", "ROOT-003 documented-subset law", "R-003 PFQ-ORDER"),
 ("postDelayed ready_at = now + delay (virtual clock)",
  "AOSP Handler.postDelayed",
  "postDelayed 100ms does not run before tick",
  "VERIFIED-CORRECT", "engine scheduler", "NONE"),
 ("removeCallbacks cancels pending post",
  "AOSP Handler.removeCallbacks",
  "post then remove -> never runs",
  "VERIFIED-CORRECT", "engine queue removal", "NONE"),
 ("Message.obtain/recycle pool identity (no leak semantics)",
  "AOSP Message pool",
  "obtain twice returns distinct messages",
  "VERIFIED-CORRECT", "engine message model", "NONE"),
 ("Handler() default ctor binds creating thread's looper",
  "AOSP Handler ctor law",
  "ctor on non-looper thread throws 'no looper'",
  "VERIFIED-CORRECT", "engine handler binding", "NONE"),
 ("Handler(Looper) explicit binding overrides thread",
  "AOSP explicit looper ctor",
  "cross-thread handler posts to given looper",
  "VERIFIED-CORRECT", "engine handler model", "NONE"),
 ("choreographer frame callbacks run before message queue drain per frame",
  "AOSP Choreographer scheduling",
  "frame callback then posted runnable ordering",
  "VERIFIED-CORRECT", "choreographer_shadow.cpp", "NONE"),
 ("Frame callbacks fire at vsync cadence (frames law)",
  "AOSP vsync model",
  "--frames N produces N traversal passes",
  "VERIFIED-CORRECT", "engine frame loop", "NONE"),
 ("worker threads: spawned threads run to completion (no premature exit)",
  "AOSP thread lifecycle",
  "Thread.start/join roundtrip",
  "VERIFIED-CORRECT", "executor_shadow/locks shadow", "NONE"),
 ("synchronized blocks release on exception (monitor exit path)",
  "JLS monitor exit on throw",
  "throw inside synchronized; second thread proceeds",
  "VERIFIED-CORRECT", "locks_shadow", "NONE"),
 ("Atomic* compareAndSet loop law (F CAS surface)",
  "libcore Atomic*",
  "CAS fail/retry increments exactly once",
  "VERIFIED-CORRECT", "atomic_shadow", "NONE"),
 ("Executor family: queued tasks run in submission order (single thread)",
  "AOSP Executors.newSingleThreadExecutor",
  "submit 3 tasks; FIFO order observed",
  "VERIFIED-CORRECT", "executor_shadow", "NONE"),
 ("countdownlatch/join synchronization semantics",
  "java.util.concurrent law",
  "await releases only after countDown",
  "VERIFIED-CORRECT", "locks shadow", "NONE"),
 ("Thread.sleep advances virtual clock deterministically",
  "AOSP sleep under virtual time",
  "sleep 1000 advances scheduler clock",
  "VERIFIED-CORRECT", "engine virtual clock", "NONE"),
 ("SystemClock.uptimeMillis monotonic within run (no backwards)",
  "AOSP monotonic clock law",
  "sample twice; non-decreasing",
  "VERIFIED-CORRECT", "engine clock", "NONE"),
 ("compose AndroidUiDispatcher.Main materializes via SynchronizedLazyImpl",
  "compose runtime upstream",
  "getWindowRecomposer reaches dispatcher",
  "PROVEN-L5", "S103 U-006 chain evidence", "GR-07 COMPOSE-FRONTIER"),
 ("recomponer awaits frame clock ticks (BroadcastFrameClock downstream)",
  "compose recomposer upstream",
  "frame tick releases awaited composition",
  "GAP-OPEN", "S103 downstream list (BroadcastFrameClock)", "GR-07 COMPOSE-FRONTIER"),
 ("coroutine worker spin: Lsr;.run loop must terminate or yield",
  "kotlinx.coroutines worker law",
  "dooz Lsr;.run spin observation 3-run",
  "REPRODUCED-DIVERGENT", "S104-r2 NEXT-ACTION queue (worker spin)", "GR-07 COMPOSE-FRONTIER"),
 ("Dispatchers.Main routes to android main looper (compose path)",
  "kotlinx-coroutines-android law",
  "withContext(Dispatchers.Main) on main queue",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "GR-07 COMPOSE-FRONTIER"),
 ("HandlerThread owns private looper (getLooper blocks until ready)",
  "AOSP HandlerThread",
  "HandlerThread looper usable from other thread",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("postAtTime with absolute uptime dispatches at that uptime",
  "AOSP postAtTime",
  "postAtTime(t+100) runs after t+100 tick",
  "VERIFIED-CORRECT", "engine scheduler", "NONE"),
 ("queue idle handler invoked when queue empty",
  "AOSP addIdleHandler",
  "idle handler runs after drain",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("PFQ during attach advances compose ViewTreeOwner chain (dooz proof)",
  "commit 7f3b1314 measured impact",
  "attach PFQ NPE gone; chain advances to recomposition",
  "PROVEN-L5", "S104-r2 dooz 18->17", "GR-03 HANDLER-ANCESTRY"),
 ("message ordering across normal/delayed/front mixes is deterministic 3-run",
  "engine determinism gate",
  "mixed-post probe; 3 identical run traces",
  "PROVEN-L5", "3-run determinism protocol (S103/S104 gates)", "R-003 PFQ-ORDER"),
 ("runOnUiThread dispatches to main when on worker",
  "AOSP Activity.runOnUiThread",
  "worker thread UI op routed to main",
  "VERIFIED-CORRECT", "engine activity shadow", "NONE"),
 ("AsyncTask-style executor+handler pattern completes (corpus pattern)",
  "AOSP AsyncTask contract",
  "doInBackground then onPostExecute on main",
  "VERIFIED-CORRECT", "census titles using async patterns", "NONE"),
 ("timer/scheduled executor virtual-time dispatch",
  "java.util.Timer law",
  "schedule 500ms task fires at tick",
  "VERIFIED-CORRECT", "executor shadow", "NONE"),
 ("FutureTask get() blocks until completion (no premature return)",
  "java.util.concurrent FutureTask",
  "get after run returns computed value",
  "VERIFIED-CORRECT", "locks shadow", "NONE"),
 ("volatile write/read visibility within single-thread semantics",
  "JMM single-thread subset (engine determinism)",
  "volatile flag roundtrip",
  "VERIFIED-CORRECT", "engine memory model", "NONE"),
 ("no thread starvation: round-robin progress across queued work",
  "engine fairness law",
  "two threads interleaved progress",
  "VERIFIED-CORRECT", "engine scheduler", "NONE"),
 ("quit() ends looper; subsequent posts no-op/throw per API",
  "AOSP Looper.quit",
  "quit then post -> runnable never runs",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("looper.getMainLooper() == looper.myLooper() on main thread",
  "AOSP main looper identity",
  "identity probe on main",
  "VERIFIED-CORRECT", "engine looper", "NONE"),
 ("message what/arg1/arg2/obj payload roundtrip via Handler.handleMessage",
  "AOSP Message payload",
  "sendEmptyMessage(7) -> handleMessage what==7",
  "VERIFIED-CORRECT", "engine message dispatch", "NONE"),
 ("postWithCallback executes callback then runnable (order law)",
  "AOSP post with callback",
  "callback sees runnable complete",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("scheduler drains due work before frame end (no work starvation at exit)",
  "engine frame-boundary law",
  "all due runnables completed by run exit",
  "VERIFIED-CORRECT", "engine run loop", "NONE"),
 ("deterministic thread scheduling under --max-seconds (3-run SHA proof)",
  "engine determinism gate",
  "3 runs -> identical scheduler trace SHA",
  "PROVEN-L5", "3-run evidence protocol (S103/S104)", "NONE"),
 ("handler null-producer families eliminated at LAW level (not per-class)",
  "GR-03/GR-10 law-level policy",
  "any attached view getHandler works (obfuscated or not)",
  "PROVEN-L5", "commit 7f3b1314 ancestry law", "GR-10 NULL-PRODUCER"),
 ("queue snapshot diagnostics (PCFG) available for divergence audits",
  "engine diagnostics law",
  "PCFG snapshot in failure dumps",
  "VERIFIED-CORRECT", "engine diagnostics", "NONE"),
 ("frame-delay pacing deterministic (no wall-clock drift in trace)",
  "engine pacing law",
  "--frame-delay 300 yields fixed trace timing",
  "VERIFIED-CORRECT", "engine run protocol", "NONE"),
 ("scheduler exception containment: runnable throw does not kill engine",
  "AOSP uncaught handler model",
  "throwing runnable logged; queue continues",
  "VERIFIED-CORRECT", "engine exception containment", "NONE"),
]

FAMILY_F = [
 ("ARSC FLAG_SPARSE supported and parsed",
  "AOSP ResourceTypes.h sparse entries",
  "sparse arsc title resolves resources",
  "VERIFIED-CORRECT", "S103 arsc_flagscan.py results", "R-006 ARSC-ENCODING"),
 ("FLAG_OFFSET16 unhandled (u16 tables would misread as u32) — latent",
  "AOSP ResourceTypes.h OFFSET16 layout",
  "synthetic OFFSET16 parse probe",
  "LATENT-NO-DEMAND", "corpus scan 0/54 use flags (measured)", "R-006 ARSC-ENCODING"),
 ("FLAG_COMPACT unhandled — latent, zero corpus demand",
  "AOSP compact resource entries",
  "synthetic compact parse probe",
  "LATENT-NO-DEMAND", "corpus scan 0/54", "R-006 ARSC-ENCODING"),
 ("theme-backed TypedArray producer (F-NEW-175) resolves style attrs",
  "AOSP Theme.obtainStyledAttributes",
  "attr resolution from theme vs layout priority",
  "PROVEN-L5", "R500-106 + F-NEW-175 (fresh ballbreak consumption)", "GR-09 THEME-PRODUCER"),
 ("style resolution order: layout > style > theme (AOSP precedence)",
  "AOSP styleable resolution",
  "same attr at 3 levels; highest wins",
  "PROVEN-L5", "R500-107/110/111/112 (S95-S101 L5)", "GR-09 THEME-PRODUCER"),
 ("dimension values: dp/px/sp conversions at density",
  "AOSP TypedValue.applyDimension",
  "100dp at density 2 -> 200px",
  "PROVEN-L5", "S95-S101 theme/resources L5 rows", "GR-09 THEME-PRODUCER"),
 ("color resolution: named/theme/attr chains",
  "AOSP color state list basic",
  "theme color attr -> resolved ARGB",
  "PROVEN-L5", "R500-112 L5", "GR-09 THEME-PRODUCER"),
 ("string resources: format args + plurals selection",
  "AOSP plurals quantity rules",
  "plurals one/other selection with count",
  "VERIFIED-CORRECT", "engine string resource path", "NONE"),
 ("resource id stability: 0xPPTTEEEE mapping per package",
  "AOSP resource id layout",
  "id from name lookup stable across runs",
  "VERIFIED-CORRECT", "engine arsc loader", "NONE"),
 ("drawable mipmaps resolve by density bucket",
  "AOSP density selection",
  "hdpi/xhdpi asset pick by runtime density",
  "VERIFIED-CORRECT", "engine asset manager", "NONE"),
 ("assets/ vs res/ namespace separation",
  "AOSP AssetManager vs Resources",
  "open asset by path; resource by id",
  "VERIFIED-CORRECT", "engine storage split", "NONE"),
 ("raw resource streaming (openRawResource)",
  "AOSP Resources.openRawResource",
  "raw file byte-identical read",
  "VERIFIED-CORRECT", "engine raw streaming", "NONE"),
 ("layout inflation honors android:theme on subtree",
  "AOSP LayoutInflater theme wrapping",
  "subtree theme overrides window theme",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "GR-09 THEME-PRODUCER"),
 ("attr-set resolution from AttributeSet XML (styled attrs in layout)",
  "AOSP obtainStyledAttributes(set)",
  "layout-provided attr wins over style",
  "PROVEN-L5", "S95-S101 styled-attr L5", "GR-09 THEME-PRODUCER"),
 ("default values when attr absent (defStyleAttr chain)",
  "AOSP obtainStyledAttributes defStyleAttr",
  "absent attr falls to defStyle then theme",
  "VERIFIED-CORRECT", "engine resolution chain", "GR-09 THEME-PRODUCER"),
 ("locale qualifier selection (en defaults; values- folders)",
  "AOSP config selection",
  "values-en picked when locale=en",
  "VERIFIED-CORRECT", "engine config match", "NONE"),
 ("night-mode qualifier latent (corpus demand measured low)",
  "AOSP uiMode selection",
  "values-night demand scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("9-patch padding box parsing",
  "AOSP NinePatch chunk",
  "9patch padding affects content area",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("PNG decode exactness (stb-based, byte-verified titles)",
  "PNG spec; engine decoder",
  "decoded pixels == reference for corpus PNGs",
  "PROVEN-L5", "visual contracts (9 HUMAN_VISIBLE titles)", "NONE"),
 ("WEBP decode via MINIANDROID_HAVE_WEBP path",
  "WEBP spec; build flag",
  "webp asset decodes on webp titles",
  "IMPLEMENTED-TESTED", "Makefile MINIANDROID_HAVE_WEBP; corpus titles", "NONE"),
 ("vector drawable path rendering subset gated by demand",
  "AOSP VD path grammar",
  "census vector usage scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("app icon/label resolution from manifest",
  "AOSP ApplicationInfo",
  "label from string resource fallback to raw",
  "VERIFIED-CORRECT", "engine manifest reader", "NONE"),
 ("APK signature-scheme-agnostic resource loading (v1/v2 both load)",
  "APK sig handling; loading law",
  "v2-signed APKs load resources fine",
  "VERIFIED-CORRECT", "corpus loader evidence (201 titles)", "NONE"),
 ("arsc string pool UTF-8/UTF-16 both decode",
  "AOSP string pool encodings",
  "UTF-16 pool title strings resolve",
  "VERIFIED-CORRECT", "engine pool decoder", "NONE"),
 ("res table package count >1 (framework package overlay)",
  "AOSP multi-package arsc",
  "titles with library resources resolve",
  "VERIFIED-CORRECT", "engine multi-package load", "NONE"),
 ("dynamic reference (?attr/) resolution at inflate time",
  "AOSP theme attribute references",
  "?attr/colorPrimary resolves via theme",
  "PROVEN-L5", "F-NEW-175 theme producer", "GR-09 THEME-PRODUCER"),
 ("@android: style parent chains resolve to framework styles",
  "AOSP style inheritance",
  "platform style parent resolved or absent-skip",
  "VERIFIED-CORRECT", "engine style walker", "NONE"),
 ("fraction/percent dimension handling",
  "AOSP TypedValue fraction",
  "50% dimension resolves relative to base",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("boolean/int resource typing strictness (wrong type = clear error)",
  "AOSP TypedValue type law",
  "int expected, string present -> typed error not silent",
  "VERIFIED-CORRECT", "engine type checks", "NONE"),
 ("array resources (string-array) typed access",
  "AOSP array resources",
  "string-array entries listed in order",
  "VERIFIED-CORRECT", "engine array resource", "NONE"),
 ("resource caching: repeated lookups stable identity (no re-parse drift)",
  "engine determinism",
  "same resource fetched twice identical",
  "VERIFIED-CORRECT", "engine cache", "NONE"),
 ("obfuscated resources.arsc (AndResGuard) tolerated if pool valid",
  "R8/AndResGuard corpus reality",
  "obfuscated-title resources resolve",
  "VERIFIED-CORRECT", "corpus obfuscated titles evidence", "NONE"),
 ("multi-density configuration switching fixed at run start (determinism)",
  "engine config law",
  "no mid-run density flip; trace stable 3-run",
  "VERIFIED-CORRECT", "3-run protocol", "NONE"),
 ("theme null safety: obtaining attrs with null theme -> clear error not crash",
  "engine error law",
  "null theme probe -> controlled error",
  "VERIFIED-CORRECT", "engine guards", "NONE"),
 ("styleable index mapping matches R8-obfuscated $ indexes (dex truth)",
  "S104 dex-truth protocol",
  "obfuscated styleable arrays resolve by dex ids",
  "VERIFIED-CORRECT", "S104 merged-class scan", "NONE"),
 ("layout resource aliasing (alias tags) resolves",
  "AOSP resource alias",
  "alias id resolves to target",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("xml resource parsing (XmlPullParser) for non-layout XML",
  "AOSP XmlPullParser surface",
  "preferences/xml asset parsed",
  "VERIFIED-CORRECT", "engine xml path", "NONE"),
 ("menu XML parse gated behind decor family (#348)",
  "S104 #348 frontier ticket",
  "menu inflation currently GAP until decor work",
  "GAP-OPEN", "#348 ticket (menu XmlPullParser)", "GR-08 DECOR-LINKAGE"),
 ("attr coordinate: package-local vs android: namespace split",
  "AOSP attr namespace",
  "android:id vs app: custom attr resolution",
  "VERIFIED-CORRECT", "engine inflate parse", "NONE"),
 ("theme applying AFTER super.onCreate respects AOSP ordering",
  "AOSP Activity.setTheme timing",
  "setTheme before setContentView applies",
  "VERIFIED-CORRECT", "engine activity chain", "GR-09 THEME-PRODUCER"),
 ("configuration objects expose density/fontScale (shadow-consistent)",
  "AOSP Configuration",
  "Configuration.densityDpi matches runtime density",
  "VERIFIED-CORRECT", "engine config shadow", "NONE"),
 ("arbitrary package resource table (split APKs) demand-gated",
  "AOSP split APK loading",
  "census split-APK demand scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("resource id collision between app and library packages resolves app-first",
  "AOSP library merge order",
  "same id in library: app table wins",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("raw XML assets byte-preserving read (no re-encode)",
  "AOSP asset read law",
  "asset read bytes == file bytes",
  "VERIFIED-CORRECT", "engine asset IO", "NONE"),
 ("resources determinism: 3-run same resolution trace (SHA protocol)",
  "engine determinism gate",
  "resource trace SHA identical 3-run",
  "PROVEN-L5", "3-run SHA evidence protocol", "NONE"),
]
