# PATTERN-500 family A (CLASS-IDENTITY, 40) + B (REFLECTION/FIELD, 40)
# Each row: (statement, law_source, probe, status, evidence, root_link)
# Status vocabulary is grounded in repo evidence (see main script header).

FAMILY_A = [
 ("instanceof answers by descriptor lineage, not class-name substring",
  "ART class.h lineage walk (AOSP/art/runtime/class.h)",
  "instanceof on inflated androidx.appcompat.widget.Toolbar vs android.widget.Toolbar",
  "IMPLEMENTED-TESTED", "commit 17c13242 (R-004 real-descriptor inflation); run/s104/r004_typescan.json", "R-004 CLASS-IDENTITY"),
 ("check-cast optimism vs instanceof strictness is a MEASURED policy, not accidental",
  "dalvik_engine.cpp cast path; ART check-cast throws CCE on lineage miss",
  "check-cast on mapped-away descriptor; record engine answer vs ART answer",
  "IMPLEMENTED-TESTED", "RESEARCH_500_ROOT_CLUSTERS ROOT-005; S103 cast strictness note", "R-004 CLASS-IDENTITY"),
 ("inflation substitution makes a real Android object BE the AppCompat class",
  "AppCompatViewInflater.create() upstream; S101 Toolbar real-class-identity law",
  "inflate androidx Toolbar; getClass().getName() on the inflated object",
  "IMPLEMENTED-TESTED", "S101 Toolbar law corpus-wide (S101 report); R-004 extension", "R-004 CLASS-IDENTITY"),
 ("mapped-away-family type tests must answer TRUE for mapped instances",
  "AOSP instanceof: x instanceof T true iff class(x) is_subclass_of T",
  "60/201-APK bytecode-accurate type-scan families; per-title instanceof probe",
  "IMPLEMENTED-TESTED", "run/s104/r004_typescan.json (operand-tuple accurate scan)", "R-004 CLASS-IDENTITY"),
 ("is_subclass_of uses the REAL superclass chain incl. 6 kFrameworkViews edges",
  "DEX class_defs superclass_idx is the single ground truth",
  "walk superclass chain of engine-seeded framework views",
  "IMPLEMENTED-TESTED", "commit 17c13242 (6 missing extends edges)", "R-004 CLASS-IDENTITY"),
 ("Class.getName returns the RUNTIME descriptor (post-substitution), not the XML tag",
  "libcore Class.getName: descriptor of the actual class object",
  "inflate mapped view, call getClass().getName()",
  "IMPLEMENTED-TESTED", "S101 Toolbar real-class-identity law", "R-004 CLASS-IDENTITY"),
 ("Class.equals / object identity: two loads of one descriptor = one Class object",
  "ART: class objects are unique per (loader, descriptor)",
  "Class.forName twice + getClass() equality probe",
  "VERIFIED-CORRECT", "S103 maxext_probe class-identity rows", "NONE"),
 ("isAssignableFrom mirrors the subtype lattice including interfaces",
  "java.lang.Class contract; ART IsAssignableFrom",
  "child/parent/interface triad assignability matrix",
  "VERIFIED-CORRECT", "S103 maxext_probe", "NONE"),
 ("arrays carry component-type identity; array instanceof Object[] holds",
  "ART array class identity = [Ldescriptor;",
  "array class probes: getName, instanceof, component identity",
  "UNTESTED-LAW-DOCUMENTED", "law pinned; no corpus title type-tests mapped arrays", "NONE"),
 ("R8 horizontal class merging: $r8$classId + packed-switch ctor dispatch",
  "R8 source (horizontal class merging); observed in solitaire/sgtpuzzles DEX",
  "construct merged class, walk switch dispatch on $r8$classId",
  "PROVEN-L5", "commit 4feaaeda probe [S104-SW] key=5->dest=11", "R-009 SWITCH-KEY-WIDENING"),
 ("merged-class field dispatch lands on the RIGHT super-class branch",
  "R8 merged ctor packed-switch semantics",
  "classId=5 (controller) and classId=4 branches both correct post-fix",
  "PROVEN-L5", "S104 probe: key=5->dest=11, key=4->dest=5", "R-009 SWITCH-KEY-WIDENING"),
 ("obfuscated class names must not defeat ancestry laws (Lr; is AndroidComposeView)",
  "dispatch by lineage; F-029b ancestry law (commit 7f3b1314)",
  "getHandler on runtime class Lr; (no 'View' substring)",
  "PROVEN-L5", "commit 7f3b1314; dooz attach-PFQ NPE gone", "GR-03 HANDLER-ANCESTRY"),
 ("framework class registry answers CLASS_REF deterministically (no deferred CNFE)",
  "AOSP framework classes are always present on device",
  "Class.forName(\"android.os.SystemProperties\") during attach",
  "PROVEN-L5", "R-NEW-354 (framework-class registry); Lt4 attach pc 742-778", "GR-10 NULL-PRODUCER"),
 ("check-cast null input passes (cast of null is identity, never CCE)",
  "JLS/ART: check-cast of null succeeds",
  "aconst_null; check-cast Any; must not throw",
  "VERIFIED-CORRECT", "engine cast path; S103 probe battery", "NONE"),
 ("instanceof null input answers FALSE",
  "JLS 15.20.2 / ART instance-of on null = 0",
  "aconst_null; instanceof T; expect false",
  "VERIFIED-CORRECT", "engine instance-of path", "NONE"),
 ("Class identity survives boxing: instanceof Integer true for boxed int",
  "ART boxed primitive classes",
  "box 42; instanceof Integer/Number/Comparable chain",
  "PROVEN-L5", "ROOT-001 boxing law (field get/set boxing)", "R-001 FIELD-IDENTITY"),
 ("generated/proxy classes never masquerade as framework descriptors",
  "ART proxy class naming $$Proxy0; not mapped onto android descriptors",
  "enumerate engine dynamic-class surface",
  "UNTESTED-LAW-DOCUMENTED", "no corpus title generates proxies (dex scan)", "NONE"),
 ("Class.getDeclaredClasses / enclosing identity non-applicable in Dalvik-compat surface",
  "libcore Class reflection surface",
  "probe getEnclosingClass on normal + anonymous classes",
  "UNTESTED-LAW-DOCUMENTED", "no census demand measured", "NONE"),
 ("descriptor normalization: L-form, dots, and primitives resolve to ONE type",
  "DEX type_ids; ART DescriptorToClass",
  "Class.forName('int') vs int.class vs 'I' normalization",
  "VERIFIED-CORRECT", "engine type resolution; S103 probes", "NONE"),
 ("interface identity: instanceof via interface tables incl. inherited interfaces",
  "ART iftable lookup",
  "class implements A<:B; probe instanceof B",
  "VERIFIED-CORRECT", "engine iftable walk", "NONE"),
 ("ClassLoader namespace: single app loader = single identity space",
  "ART loader class table",
  "load class twice via app loader; assert same Class",
  "VERIFIED-CORRECT", "engine loader model", "NONE"),
 ("Inferred identity: getClass() equals compile-time descriptor after substitution",
  "AOSP LayoutInflater factory2 substitution",
  "inflated view getClass() vs mapped descriptor",
  "IMPLEMENTED-TESTED", "R-004 + S101 Toolbar law", "R-004 CLASS-IDENTITY"),
 ("mapped-away family must ALSO answer check-cast TRUE (no new CCE)",
  "cast path consults same lineage as instanceof",
  "check-cast androidx family post R-004 across 6 affected titles",
  "IMPLEMENTED-TESTED", "REAL_APK_IMPACT.md R-004 rows: 6 titles pixel-identical", "R-004 CLASS-IDENTITY"),
 ("enum identity: valueOf/value/ordinal resolve to ONE instance set",
  "ART enum $VALUES law",
  "enum.valueOf twice == same object; ordinal stable",
  "VERIFIED-CORRECT", "engine enum model; census games use enums", "NONE"),
 ("annotation classes: visibility + retention do not affect runtime presence",
  "ART annotation resolution",
  "probe runtime-visible annotation on engine-seeded classes",
  "UNTESTED-LAW-DOCUMENTED", "no census demand measured", "NONE"),
 ("anonymous class identity: outer.this + synthetic field naming stable",
  "DEX inner-class synthetic this$0",
  "construct anonymous inner; call outer accessor",
  "VERIFIED-CORRECT", "S104 merged-class scan corpus evidence", "NONE"),
 ("static nested vs inner: no outer instance captured for static nested",
  "JLS 8.1.3 inner vs static nested",
  "construct static nested; assert no synthetic outer read",
  "VERIFIED-CORRECT", "engine field model", "NONE"),
 ("identity across dex files: multi-dex classes share one identity space",
  "ART multi-dex class loader path",
  "cross-dex instanceof + field access on one class",
  "VERIFIED-CORRECT", "exp088_multidex_inject_test; F multi-dex laws", "NONE"),
 ("lambda classes: invokedynamic'd synthetic classes obey instanceof on target interfaces",
  "ART lambda proxy classes",
  "lambda instanceof Runnable/Consumer",
  "VERIFIED-CORRECT", "S104 lambda family close-out evidence", "R-009 SWITCH-KEY-WIDENING"),
 ("R8 merged classes keep SUPERCLASS field storage identity",
  "R8 horizontal merging: fields hoisted to merged super",
  "iget on merged-class instance routes to super-class storage",
  "PROVEN-L5", "S104 [NULLFIELD] input-UNSET line gone post-fix", "R-009 SWITCH-KEY-WIDENING"),
 ("class object equality across reflection and interpreter paths",
  "one Class table consulted by sget/sput/reflection/heap",
  "Field.getDeclaringClass() == interpreter receiver class",
  "PROVEN-L5", "ROOT-001 field-identity law L5", "R-001 FIELD-IDENTITY"),
 ("instanceof on engine-seeded framework classes mirrors real Android",
  "kFrameworkViews edges = AOSP view hierarchy",
  "probe extends edges for 12-class mapped family",
  "IMPLEMENTED-TESTED", "commit 17c13242 (6 missing edges)", "R-004 CLASS-IDENTITY"),
 ("throwable identity: instanceof catch dispatch by lineage order",
  "ART exception table walk order",
  "catch(A) before catch(B) where B<:A",
  "VERIFIED-CORRECT", "engine exception dispatch; F-141 NPE law", "GR-10 NULL-PRODUCER"),
 ("varargs array identity: pass-through Object[]",
  "JLS 15.12.4.2 varargs invocation",
  "call varargs method; assert Object[] received",
  "VERIFIED-CORRECT", "engine invoke-virtual path", "NONE"),
 ("generic erasure: Class.of(List<String>) == Class.of(List)",
  "JLS erasure; ART runtime has no generics",
  "compare getClass() of two generic instantiations",
  "VERIFIED-CORRECT", "engine erasure model", "NONE"),
 ("identity is stable across interpreter/heap/static storage boundaries",
  "ROOT-001 law: (declaring-class, name) canonical key",
  "sget vs Field.get vs heap iget of same field",
  "PROVEN-L5", "ROOT-001 identity probe R8/R12 (after-set=43/direct=1234)", "R-001 FIELD-IDENTITY"),
 ("descriptor case-sensitivity: LFoo/Bar; != Lfoo/bar;",
  "DEX descriptors are case-sensitive",
  "two classes differing only in case; probe distinct identity",
  "VERIFIED-CORRECT", "engine type table", "NONE"),
 ("check-cast to interface follows interface table, not class table",
  "ART check-cast iftable",
  "cast object to implemented interface across hierarchy",
  "VERIFIED-CORRECT", "engine cast path", "NONE"),
 ("identity of Activity subclasses across manifest + dex declarations",
  "manifest activity name == dex descriptor",
  "launch activity; getClass() == manifest name",
  "VERIFIED-CORRECT", "F-118 activity-constructor law; launch chain", "NONE"),
 ("package-private access check uses RUNTIME package identity",
  "ART access checks by (class, package, loader)",
  "package-private cross-class call in same package",
  "VERIFIED-CORRECT", "engine access checks", "NONE"),
]

FAMILY_B = [
 ("one canonical field key (declaring-class, name) across sget/sput/heap/reflection",
  "ROOT-001 source law; libcore java.lang.reflect.Field",
  "write static via sput; read via Field.get; same value",
  "PROVEN-L5", "ROOT-001 probe R8/R12: identity=43/1234 proven 3-run", "R-001 FIELD-IDENTITY"),
 ("static reads with a receiver still route through static_field_storage_",
  "ART sget ignores receiver for statics",
  "instance.getStaticField after sput; value visible",
  "PROVEN-L5", "ROOT-001 fix L5 (static routing)", "R-001 FIELD-IDENTITY"),
 ("getDeclaredField throws NSFE for absent name (never silent null)",
  "java.lang.Class.getDeclaredField NSFE contract",
  "getDeclaredField('nope') -> NoSuchFieldException",
  "PROVEN-L5", "ROOT-001 probe R6=NSFE(correct)", "R-001 FIELD-IDENTITY"),
 ("getField walks superclass chain, public-only, first declaring class",
  "OpenJDK Class.getField contract",
  "getField on inherited public static; inherited=99",
  "PROVEN-L5", "ROOT-001 probe R7=inherited=99", "R-001 FIELD-IDENTITY"),
 ("getField(NULL-slice) killed 5 census titles — getField must exist, not stub-null",
  "ROOT-001; S103 log sweep",
  "census titles' getField call sites; 0 NPE after fix",
  "PROVEN-L5", "ROOT_CLUSTERS: getField-NULL slice 5 titles", "R-001 FIELD-IDENTITY"),
 ("Field objects carry kind (instance/static) from DEX access flags",
  "DEX field_ids + access_flags",
  "Field.getModifiers vs DEX flags; static vs instance kind",
  "PROVEN-L5", "ROOT-001 dex-derived Field identity", "R-001 FIELD-IDENTITY"),
 ("getModifiers returns REAL access flags (never hardcoded PUBLIC|STATIC=9)",
  "java.lang.reflect.Modifier",
  "private field -> modifiers=2",
  "PROVEN-L5", "ROOT-001 probe R9=mods=1 (real flags)", "R-001 FIELD-IDENTITY"),
 ("boxing on Field.get for primitives; unboxing on Field.set",
  "libcore reflection boxing",
  "int field -> Field.get returns Integer(43); set(42) stores prim",
  "PROVEN-L5", "ROOT-001 probe R11 boxed=1234", "R-001 FIELD-IDENTITY"),
 ("boxed static pre-init defaults are ZERO values (not null, not garbage)",
  "ART static field zero-init",
  "read uninit static Integer slot -> default per kind",
  "PROVEN-L5", "ROOT-001 probe R1=42/R2=nonnull/R3=const-value", "R-001 FIELD-IDENTITY"),
 ("null receiver on instance-field get => NPE with ART message shape",
  "ART NPE semantics (F-141 law)",
  "Field.get(null) -> NPE",
  "PROVEN-L5", "ROOT-001 probe R5=NPE(correct); F-141", "R-001 FIELD-IDENTITY"),
 ("set on final field => IllegalAccessException unless setAccessible(true)",
  "java.lang.reflect.Field.set IAE law",
  "final write probe -> IAE; accessible=true -> ok",
  "PROVEN-L5", "ROOT-001 fix (final-write IAE unless setAccessible)", "R-001 FIELD-IDENTITY"),
 ("setAccessible(true) bypasses access checks",
  "AccessibleObject contract",
  "private field set via accessible=true",
  "PROVEN-L5", "ROOT-001 accessible flag L5", "R-001 FIELD-IDENTITY"),
 ("sun.misc.Unsafe offsets agree with interpreter field storage",
  "libcore Unsafe.objectFieldOffset",
  "Unsafe.putInt at offset == Field.set value",
  "PROVEN-L5", "ROOT_CLUSTERS ROOT-001 (Unsafe in canonical key set)", "R-001 FIELD-IDENTITY"),
 ("Method.invoke unboxes/boxes args and return like Field family",
  "libcore Method.invoke",
  "invoke int-returning method -> Integer box",
  "VERIFIED-CORRECT", "engine method-reflection path", "NONE"),
 ("getDeclaredMethods lists ONLY declared, not inherited",
  "Class.getDeclaredMethods contract",
  "subclass getDeclaredMethods excludes parent methods",
  "VERIFIED-CORRECT", "engine reflection surface", "NONE"),
 ("getMethods deduplicates bridge/overload surface per AOSP order",
  "libcore Class.getMethods",
  "hierarchy method union probe",
  "UNTESTED-LAW-DOCUMENTED", "law pinned; probe defined", "NONE"),
 ("NSFE message names the exact missing field (diagnostic identity)",
  "libcore Class NSFE message",
  "NSFE message contains field name",
  "PROVEN-L5", "ROOT-001 NSFE law", "R-001 FIELD-IDENTITY"),
 ("field get on boxed static renders VALUE via toString (no arm-swallow)",
  "ROOT-001 companion display law",
  "StringBuilder.append(boxedInteger) prints number",
  "PROVEN-L5", "ROOT-001 companion display law (boxed VALUE)", "R-001 FIELD-IDENTITY"),
 ("static Integer.toString(int) does not capture virtual 0-arg form",
  "ROOT-001 companion display law",
  "0-arg toString dispatch stays virtual",
  "PROVEN-L5", "ROOT-001 companion display law", "R-001 FIELD-IDENTITY"),
 ("ensure_class_initialized precedes static field reflection",
  "ART class init before static access",
  "Field.get triggers <clinit> first",
  "PROVEN-L5", "ROOT-001 fix (+ ensure_class_initialized)", "R-001 FIELD-IDENTITY"),
 ("Field.set widening: byte field accepts byte via unbox, rejects long",
  "libcore Field.set type law",
  "set(byte field, long) -> IAE",
  "UNTESTED-LAW-DOCUMENTED", "law pinned; probe defined", "NONE"),
 ("getField vs getDeclaredField visibility split",
  "OpenJDK contracts",
  "private via getField -> NSFE; via getDeclaredField -> ok",
  "PROVEN-L5", "ROOT-001 L5 surface", "R-001 FIELD-IDENTITY"),
 ("static field identity across subclass reads (sget from child)",
  "ART sget resolves to declaring class storage",
  "child.sget(parentStatic) sees parent storage",
  "PROVEN-L5", "ROOT-001 canonical-key law", "R-001 FIELD-IDENTITY"),
 ("reflection on R8-merged classes exposes hoisted field identity",
  "R8 horizontal merging field hoisting",
  "getDeclaredField on merged super from merged subclass",
  "PROVEN-L5", "S104 solitaire MatcherMatchResult chain proof", "R-009 SWITCH-KEY-WIDENING"),
 ("getDeclaredField on framework classes returns shadow-backed fields",
  "engine framework surface",
  "getDeclaredField on seeded framework class",
  "IMPLEMENTED-TESTED", "framework declared-field surface (S103)", "R-001 FIELD-IDENTITY"),
 ("Field.hashCode/equals identity: same (class,name) = same equals",
  "java.lang.reflect.Field equals contract",
  "two getDeclaredField('f') calls equals()==true",
  "PROVEN-L5", "ROOT-001 field-identity L5", "R-001 FIELD-IDENTITY"),
 ("Field.getType returns exact declared type incl. arrays",
  "Class reflection",
  "int[] field -> getType()==int[].class",
  "PROVEN-L5", "ROOT-001 dex-derived identity", "R-001 FIELD-IDENTITY"),
 ("enum fields reflect $VALUES with correct synthetic flags",
  "ART enum reflection",
  "getDeclaredFields on enum lists values+$VALUES",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("instance field default zero-init visible before iput",
  "ART instance zero-init",
  "new object; iget int == 0; iget ref == null",
  "VERIFIED-CORRECT", "engine object model", "NONE"),
 ("long/double field access is atomic pair (no torn reads in single thread)",
  "JLS 17.7 non-volatile long treatment",
  "iput-wide/iget-wide roundtrip 0x1234567890abcdef",
  "VERIFIED-CORRECT", "engine wide ops", "NONE"),
 ("field access on wrong-typed receiver is impossible via interpreter (CCE upstream)",
  "ART verifier + cast semantics",
  "cast-guarded iget probe",
  "VERIFIED-CORRECT", "engine cast path", "NONE"),
 ("transient/serialPersistentFields do not affect runtime field storage",
  "java.io.Serializable spec",
  "transient field still readable at runtime",
  "VERIFIED-CORRECT", "engine storage ignores transient", "NONE"),
 ("Field bridge methods do not appear as field identity collisions",
  "ART synthetic handling",
  "generic getter bridge vs field name distinct spaces",
  "VERIFIED-CORRECT", "engine name spaces (fields vs methods)", "NONE"),
 ("static final compile-time constants inline; reads bypass storage (AOSP behavior)",
  "DX inlines static final primitives; ART honors both",
  "sget static final int == inlined constant",
  "VERIFIED-CORRECT", "engine const handling", "NONE"),
 ("reflection setAccessible on static does not initialize class twice",
  "ART init-once law",
  "double Field.get static; <clinit> ran once",
  "PROVEN-L5", "ROOT-001 ensure_class_initialized guard", "R-001 FIELD-IDENTITY"),
 ("getField on interface constants (public static final) resolves",
  "OpenJDK getField includes interface-declared",
  "getField on interface constant",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("null-typed Field.set(null, null) on static is legal (receiver ignored)",
  "libcore static set law",
  "static field set with null receiver",
  "PROVEN-L5", "ROOT-001 static routing law", "R-001 FIELD-IDENTITY"),
 ("Field name identity across obfuscated same-name fields in different classes",
  "R8 renaming: (class,name) key disambiguates",
  "two classes same field name; distinct storage",
  "PROVEN-L5", "ROOT-001 declaring-class key component", "R-001 FIELD-IDENTITY"),
 ("getDeclaredField after R8 field renaming uses the OBFUSCATED name (dex truth)",
  "DEX field_ids is the runtime truth",
  "runtime Field lookup by name from dex (not source names)",
  "VERIFIED-CORRECT", "S104 DEX ground-truth protocol", "NONE"),
 ("reflection does not bypass final instance-field write laws set at fix time",
  "ROOT-001 final law",
  "final instance field set -> IAE unless accessible",
  "PROVEN-L5", "ROOT-001 final-write IAE law", "R-001 FIELD-IDENTITY"),
]
