# PATTERN-500 family K (STORAGE/IO/NET, 30) + L (TEXT/UTIL/JSON/CRYPTO, 25) + M (AUDIO/MEDIA/SENSORS, 20)

FAMILY_K = [
 ("SQLite real backend (F-ROOM-CHAIN) — real queries not mocks",
  "S100 M3 F-ROOM-CHAIN law",
  "app DB create/insert/query roundtrip",
  "IMPLEMENTED-TESTED", "Makefile LIBS sqlite3; S100 report", "NONE"),
 ("SharedPreferences persistence (shared_prefs.cpp)",
  "AOSP SharedPreferences",
  "putString -> commit -> getString after reload",
  "IMPLEMENTED-TESTED", "shared_prefs.cpp + census usage", "NONE"),
 ("File.getAbsoluteFile path law (R-NEW-390)",
  "AOSP File path resolution",
  "relative -> absolute normalization",
  "PROVEN-L5", "R-NEW-390 ROOT-CAUSED-FIXED", "NONE"),
 ("File.getCanonicalFile/Path law (R-NEW-391)",
  "AOSP canonicalization",
  "../ collapse + symlink-free canonical",
  "PROVEN-L5", "R-NEW-391 ROOT-CAUSED-FIXED", "NONE"),
 ("File IO: create/read/write/delete in app data dir",
  "AOSP File APIs",
  "roundtrip bytes identical",
  "VERIFIED-CORRECT", "engine storage layer", "NONE"),
 ("internal storage isolation per app (--data-root sandbox)",
  "engine sandbox law",
  "app A cannot see app B files",
  "VERIFIED-CORRECT", "engine data-root sandbox", "NONE"),
 ("assets byte-exact streaming (AssetManager.open)",
  "AOSP asset access",
  "asset hash == packed hash",
  "VERIFIED-CORRECT", "engine asset IO", "NONE"),
 ("OpenSSL-backed TLS (NET-001: BoringSSL lineage)",
  "S100 NET-001 law",
  "HTTPS GET to well-known host succeeds",
  "IMPLEMENTED-TESTED", "Makefile -lssl -lcrypto", "NONE"),
 ("HTTP client surface (http_client.cpp)",
  "engine network layer",
  "plain HTTP GET returns body",
  "IMPLEMENTED-TESTED", "http_client.cpp", "NONE"),
 ("URL/URI parsing edge cases (encoding, ports, paths)",
  "java.net URL/URI laws",
  "encoded path roundtrip",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("JSON: org.json surface parity (JSONObject/JSONArray)",
  "AOSP org.json",
  "parse/stringify roundtrip equal",
  "VERIFIED-CORRECT", "engine json (nlohmann-backed)", "NONE"),
 ("JSON strictness: duplicate keys last-wins (AOSP behavior)",
  "AOSP org.json duplicate law",
  "duplicate key parse -> last value",
  "VERIFIED-CORRECT", "engine json", "NONE"),
 ("ObjectOutputStream/Serialization demand-gated",
  "evidence-based priority",
  "census serialization usage scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("Zip/Jar APK-level reading (zip central directory)",
  "APK container law",
  "entries listed; deflate/inflate exact",
  "VERIFIED-CORRECT", "apk_parser.cpp", "NONE"),
 ("gzip/deflate streams roundtrip",
  "java.util.zip",
  "compress->decompress identity",
  "VERIFIED-CORRECT", "engine zip layer", "NONE"),
 ("crypto: SHA/AES surface via OpenSSL (documented scope)",
  "engine crypto policy",
  "digest roundtrip known vectors",
  "IMPLEMENTED-TESTED", "engine crypto via -lcrypto", "NONE"),
 ("SecureRandom determinism policy (seeded for reproducibility)",
  "engine determinism law",
  "seeded runs byte-identical",
  "VERIFIED-CORRECT", "3-run protocol", "NONE"),
 ("Base64 encode/decode variants (default/url-safe/nopad)",
  "AOSP Base64",
  "roundtrip across flags",
  "VERIFIED-CORRECT", "engine base64", "NONE"),
 ("UUID/Random deterministic subsetting",
  "engine determinism law",
  "seeded Random sequence stable",
  "VERIFIED-CORRECT", "engine random", "NONE"),
 ("room/database library family demand-gated (census scan)",
  "evidence-based priority",
  "room usage census",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("content resolver/uris shadow (no cross-app content)",
  "engine scope note",
  "resolver calls answered by shadow, no crash",
  "HOST-ONLY", "android_shadows", "NONE"),
 ("atomic file writes (rename-swap law)",
  "AOSP AtomicFile",
  "failed write leaves prior file intact",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("file permissions model: single-user engine (documented)",
  "engine policy",
  "no chmod semantics divergence",
  "HOST-ONLY", "engine scope", "NONE"),
 ("network on-main-thread strictness DISABLED (engine policy documented)",
  "engine policy vs AOSP NetworkOnMainThread",
  "main-thread HTTP allowed; policy note",
  "VERIFIED-CORRECT", "engine policy record", "NONE"),
 ("TLS certificate validation on (secure default)",
  "NET-001 secure default",
  "bad-cert host fails closed",
  "IMPLEMENTED-TESTED", "OpenSSL default verify", "NONE"),
 ("database encryption surface absent (census demand 0)",
  "evidence-based priority",
  "SQLCipher-family census",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("app dir layout: files/cache/databases subdirs materialized",
  "AOSP context dirs",
  "getFilesDir/getCacheDir paths exist",
  "VERIFIED-CORRECT", "engine data-root", "NONE"),
 ("classpath resource loading from APK dex-adjacent assets",
  "engine loader",
  "getResourceAsStream from app package",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("large file streaming (no full-buffer requirement)",
  "engine IO law",
  "10MB asset streamed without OOM",
  "VERIFIED-CORRECT", "engine asset streaming", "NONE"),
 ("IO exception taxonomy: FileNotFoundException/IOException shapes",
  "java.io law",
  "missing file -> FNFE with path in message",
  "VERIFIED-CORRECT", "engine IO errors", "NONE"),
]

FAMILY_L = [
 ("String concatenation via StringBuilder identity (value not identity)",
  "S103 display law",
  "boxed value renders value in concat",
  "PROVEN-L5", "ROOT-001 companion display law", "R-001 FIELD-IDENTITY"),
 ("String.format locale subset (default locale US-equivalent)",
  "java.util.Formatter",
  "%d %s %f roundtrip",
  "VERIFIED-CORRECT", "engine formatter", "NONE"),
 ("String split/replace/trim edge semantics (regex subset)",
  "java.lang.String",
  "split with regex special chars",
  "VERIFIED-CORRECT", "engine string ops", "NONE"),
 ("kotlin stdlib: apply/let/also/run scoping nullability",
  "kotlin stdlib upstream",
  "scope-function chains on nullables",
  "VERIFIED-CORRECT", "S104 merged-class scan corpus evidence", "R-009 SWITCH-KEY-WIDENING"),
 ("kotlin text: MatcherMatchResult family executes post-R-009",
  "S104 solitaire chain",
  "getSavedStateProvider NPE gone; chain passes stdlib site",
  "PROVEN-L5", "S104 DEX ground truth + fix", "R-009 SWITCH-KEY-WIDENING"),
 ("kotlin object/singletons: INSTANCE static identity",
  "kotlin object law",
  "object field set visible globally",
  "PROVEN-L5", "ROOT-001 static storage identity", "R-001 FIELD-IDENTITY"),
 ("kotlin lateinit: unset read -> UninitializedPropertyAccessException",
  "kotlin law",
  "lateinit read before set -> UPAC",
  "VERIFIED-CORRECT", "engine kotlin surface", "NONE"),
 ("kotlin data class equals/hashCode/copy synthesis",
  "kotlin compiler synthesis",
  "equals by component values",
  "VERIFIED-CORRECT", "engine synth methods", "NONE"),
 ("kotlin lambdas: FunctionN invoke + captured vars",
  "kotlin lambda lowering",
  "closure counter increments",
  "VERIFIED-CORRECT", "engine invokedynamic-less lambdas", "NONE"),
 ("kotlin companion: fields via companion identity",
  "kotlin companion law",
  "Companion.X reads instance storage",
  "PROVEN-L5", "ROOT-001 canonical keys", "R-001 FIELD-IDENTITY"),
 ("char encodings: UTF-8 decode strictness (MUTF-8 for dex strings)",
  "DEX MUTF-8 law",
  "emoji in strings roundtrip through dex",
  "VERIFIED-CORRECT", "mutf8_test binary", "NONE"),
 ("Collections: ArrayList/HashMap iteration order documented",
  "java.util laws",
  "HashMap order deterministic within run",
  "VERIFIED-CORRECT", "engine collections", "NONE"),
 ("Collections.sort stability law",
  "java.util.Collections.sort (stable)",
  "equal keys preserve order",
  "VERIFIED-CORRECT", "engine sort", "NONE"),
 ("Comparable/Comparator contract enforcement on bad comparators",
  "java.util contract",
  "inconsistent comparator -> documented behavior",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("BigDecimal/BigInteger subset for game scoring paths",
  "java.math subset",
  "long-scale arithmetic exact",
  "VERIFIED-CORRECT", "engine math", "NONE"),
 ("regex engine subset (Pattern/Matcher core)",
  "java.util.regex subset",
  "common game patterns match",
  "VERIFIED-CORRECT", "engine regex", "NONE"),
 ("Math functions exactness (sin/cos/pow IEEE subset)",
  "java.lang.Math",
  "Math.pow(2,10)==1024.0",
  "VERIFIED-CORRECT", "engine math", "NONE"),
 ("Object.equals/hashCode/toString defaults (identity-based)",
  "java.lang.Object",
  "default hashCode stable within run",
  "VERIFIED-CORRECT", "engine object model", "NONE"),
 ("ThreadLocal isolation across threads",
  "java.lang.ThreadLocal",
  "two threads distinct values",
  "VERIFIED-CORRECT", "engine thread model", "NONE"),
 ("AutoCloseable try-with-resources close ordering (reverse)",
  "JLS try-with-resources",
  "close order reverse declaration",
  "VERIFIED-CORRECT", "engine bytecode close synth", "NONE"),
 ("annotation processing at runtime (getAnnotation subset)",
  "java.lang.reflect annotation",
  "runtime-visible annotation read",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("iterator/removeById fast-fail semantics documented",
  "java.util ConcurrentModification policy",
  "single-thread: CME only per documented paths",
  "VERIFIED-CORRECT", "engine collections", "NONE"),
 ("Optional/functional interfaces surface (API24+ subset)",
  "java.util.Optional",
  "map/filter chains",
  "VERIFIED-CORRECT", "engine jdk surface", "NONE"),
 ("text measurement shared by views+canvas (ONE metrics law)",
  "R-NEW-392 subsumption",
  "Paint vs TextView widths agree",
  "PROVEN-L5", "R-NEW-392", "NONE"),
 ("string determinism: interning behavior per dex string_ids",
  "DEX string identity",
  "same string_id == same object",
  "VERIFIED-CORRECT", "engine string table", "NONE"),
]

FAMILY_M = [
 ("MediaPlayer object lifecycle law (F-155): input->state chain closed",
  "F-155 ROOT-CAUSED-FIXED (S79)",
  "fishrings input->state->changed-frame x2 det",
  "PROVEN-L5", "root_registry S79 summary (R-NEW-400)", "NONE"),
 ("AudioTrack/AudioFlinger producer host-only (rule 7)",
  "ROOT_CLUSTERS out-of-scope family",
  "no real audio producer in engine scope",
  "HOST-ONLY", "ROOT_CLUSTERS host-only list", "GR-12 GL-FRONTIER"),
 ("SoundPool shadow: load IDs valid, no real PCM out",
  "audio shadow scope",
  "load returns id; play no-crash",
  "HOST-ONLY", "android audio shadows", "GR-12 GL-FRONTIER"),
 ("camera/sensor surfaces absent (census demand 0)",
  "evidence-based priority",
  "census sensor usage scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("vibrator shadow no-op with trace (policy)",
  "engine shadow policy",
  "vibrate calls logged not crash",
  "HOST-ONLY", "android_shadows", "NONE"),
 ("notification surface shadow (no system UI)",
  "engine scope note",
  "notify calls no-crash",
  "HOST-ONLY", "android_shadows", "NONE"),
 ("clipboard shadow (locale_insets family neighbor)",
  "clipboard_shadow.cpp",
  "set/get within run",
  "VERIFIED-CORRECT", "clipboard shadow", "NONE"),
 ("connectivity shadow: network state always available",
  "engine policy",
  "isConnected true; titles skip offline branches",
  "VERIFIED-CORRECT", "engine policy", "NONE"),
 ("battery/power shadow: static sane values",
  "engine policy",
  "battery reads fixed value no crash",
  "HOST-ONLY", "android_shadows", "NONE"),
 ("geolocation absent (census 0)",
  "evidence-based priority",
  "census location scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("telephony/SMS absent (census 0)",
  "evidence-based priority",
  "census telephony scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("bluetooth/NFC absent (census 0)",
  "evidence-based priority",
  "census scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("WebView: native chromium absent; JS engine surface documented",
  "S100 browser wave evidence",
  "upload/s100_browser titles status recorded",
  "RESEARCHED-NOT-IMPLEMENTED", "S100 browser artifacts", "GR-12 GL-FRONTIER"),
 ("app-widgets surface absent (census 0)",
  "evidence-based priority",
  "census widget-provider scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("in-app-billing/ads SDK calls fail-soft with trace",
  "engine policy",
  "ads init no-crash, no-ops",
  "HOST-ONLY", "engine policy", "NONE"),
 ("Play-Services family fail-soft (no GMS)",
  "engine policy",
  "GMS API calls return documented failure",
  "HOST-ONLY", "engine policy", "NONE"),
 ("font loading: system fonts + app fonts (freetype/harfbuzz/fribidi)",
  "engine text stack",
  "custom ttf from assets loads",
  "IMPLEMENTED-TESTED", "fonts stack (FONTS_LIBS)", "NONE"),
 ("RTL/bidi via fribidi (locale laws)",
  "fribidi integration",
  "RTL text shaped correctly",
  "IMPLEMENTED-TESTED", "FONTS_LIBS -lfribidi", "NONE"),
 ("input method surface: synthetic text injection only",
  "engine input policy",
  "IME-equivalent injection documented",
  "HOST-ONLY", "engine input", "NONE"),
 ("media codecs: software decode for corpus formats only",
  "engine scope",
  "census codec formats enumerated",
  "VERIFIED-CORRECT", "decoder census", "NONE"),
]
