# PATTERN-500 family G (COMPOSE-HOST, 35) + H (LIFECYCLE/ACTIVITY/SAVEDSTATE, 35)

FAMILY_G = [
 ("AbstractComposeView.onMeasure reached before recomposer ready (chain stage)",
  "S103 U-006 chain map",
  "solitaire trace: onMeasure -> getWindowRecomposer",
  "PROVEN-L5", "worklog U-006 first-divergence pin", "GR-07 COMPOSE-FRONTIER"),
 ("getWindowRecomposer resolves AndroidUiDispatcher.Main lazily",
  "compose ui android upstream",
  "SynchronizedLazyImpl init in trace",
  "PROVEN-L5", "S103 chain evidence", "GR-07 COMPOSE-FRONTIER"),
 ("R8-merged LocalDensity$1 selector executes RIGHT branch post-R-009",
  "ROOT-001+R-009 intersection",
  "noLocalProvidedFor('LocalDensity') ISE gone",
  "PROVEN-L5", "S103 fix + S104 solitaire 0 errors", "R-009 SWITCH-KEY-WIDENING"),
 ("composition requires density/coords providers (LocalDensity provided)",
  "compose CompositionLocal law",
  "withFrameTicks block consumes density",
  "PROVEN-L5", "S103 wrong-branch root fixed; chain advanced", "GR-07 COMPOSE-FRONTIER"),
 ("saved-state wiring completes before compose host (LocalSavedStateRegistryOwnerKt clinit)",
  "FIX-005 measured impact",
  "solitaire: clinit executes; no saved-state NPE",
  "PROVEN-L5", "REAL_APK_IMPACT FIX-005 row", "R-009 SWITCH-KEY-WIDENING"),
 ("AndroidComposeView.updatePositionCacheAndDispatch reachable",
  "FIX-005 chain evidence",
  "trace reaches position-cache dispatch",
  "PROVEN-L5", "REAL_APK_IMPACT FIX-005 row", "GR-07 COMPOSE-FRONTIER"),
 ("compose RECOMPOSITION requires width/height non-null at measure phase",
  "compose measure law (S104-r2 Lt4;.L observation)",
  "dooz: Lt4;.L getWidth NPE pre-fix; GONE post getRootView law",
  "PROVEN-L5", "S104-r3 dooz 3/3: 0 getWidth NPE rows (mix: 17 -> 17, frontier advanced)", "GR-07 COMPOSE-FRONTIER"),
 ("getRootView NEVER returns null (AOSP View.getRootView): unattached view returns ITSELF; attached view walks parent chain to the topmost View",
  "AOSP View.getRootView (View.java): walk getParent while instanceof View; unattached -> this",
  "dooz Lt4;.L caches getRootView() into O0 then getWidth()/getHeight() on it",
  "PROVEN-L5", "S104-r3 GR-07 law (commit f5849b87); getWidth-on-null NPE gone 3/3", "GR-07 COMPOSE-FRONTIER"),
 ("recomposer awaiting frame clock (BroadcastFrameClock) downstream",
  "S103 downstream list",
  "frame tick releases composition await",
  "GAP-OPEN", "S103 downstream frontier", "GR-07 COMPOSE-FRONTIER"),
 ("ViewModelProvider factory resolution in compose chain",
  "S103 downstream list",
  "ViewModelProvider get during compose init",
  "RESEARCHED-NOT-IMPLEMENTED", "S103 downstream list", "GR-07 COMPOSE-FRONTIER"),
 ("LifecycleOwner propagation to composition locals",
  "compose androidx lifecycle local law",
  "LocalLifecycleOwner present during composition",
  "RESEARCHED-NOT-IMPLEMENTED", "S103 downstream list", "GR-07 COMPOSE-FRONTIER"),
 ("ViewTreeOwner chain: attach -> lifecycle -> savedstate -> compose content",
  "compose ViewTreeOwner wiring",
  "dooz attach completes through observer registration",
  "PROVEN-L5", "R-NEW-354 + S104-r2 chain", "GR-03 HANDLER-ANCESTRY"),
 ("compose draw path visually blank until composition executes (honest state)",
  "S104 honest no-visual-claim record",
  "solitaire screenshot blank post-fix (documented)",
  "REPRODUCED-DIVERGENT", "REAL_APK_IMPACT (visual blank honest note)", "GR-07 COMPOSE-FRONTIER"),
 ("snapshot state reads inside composition track invalidation",
  "compose snapshot law",
  "state write -> recomposition scheduled",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "GR-07 COMPOSE-FRONTIER"),
 ("Recomposer.runRecomposeAndApply runs on android dispatcher",
  "compose recomposer upstream",
  "worker executes recompose lambda",
  "REPRODUCED-DIVERGENT", "dooz Lsr;.run worker spin (queued)", "GR-07 COMPOSE-FRONTIER"),
 ("composition applies UI tree into AndroidComposeView children",
  "compose ui node mapping",
  "post-compose ViewTree children == composables",
  "GAP-OPEN", "compose host wiring #350", "GR-07 COMPOSE-FRONTIER"),
 ("measure/layout/draw phases driven by compose when host present",
  "compose host phase law",
  "phase trace on compose title",
  "GAP-OPEN", "#350", "GR-07 COMPOSE-FRONTIER"),
 ("compose text measures via platform font metrics (integration point)",
  "compose text upstream",
  "BasicText measure via shared metrics",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "GR-07 COMPOSE-FRONTIER"),
 ("InputEvent routing to compose (pointer input) downstream",
  "compose input upstream",
  "tap reaches pointerInput modifier",
  "GAP-OPEN", "#350 input slice", "GR-07 COMPOSE-FRONTIER"),
 ("semantics tree not required for render (gated off, demand 0)",
  "evidence-based priority",
  "census semantics demand scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("compose runtime throws CompositionTimeout only on real await failure",
  "compose upstream contract",
  "no premature timeout in traces",
  "VERIFIED-CORRECT", "engine compose traces", "GR-07 COMPOSE-FRONTIER"),
 ("apcompat compose integration: AbstractComposeView extends ViewGroup law",
  "compose ui upstream class hierarchy",
  "instanceof ViewGroup on compose host true",
  "VERIFIED-CORRECT", "R-004 family edges", "R-004 CLASS-IDENTITY"),
 ("setContent resolves composition before first frame (AOSP contract)",
  "compose setContent contract",
  "first frame contains composed tree (real Android)",
  "GAP-OPEN", "dooz/solitaire blank visual (honest)", "GR-07 COMPOSE-FRONTIER"),
 ("dooz remaining 17 errors are compose-frontier only (post GR-03)",
  "S104-r2 measured census",
  "error list classification after getHandler fix",
  "PROVEN-L5", "S104-r2 dooz 18->17 classification", "GR-07 COMPOSE-FRONTIER"),
 ("12 caught CNFE probes are APP-EXPECTED (runCatching/reflection)",
  "S104 FIX-005 evidence",
  "dooz error triage: caught = non-divergence",
  "PROVEN-L5", "REAL_APK_IMPACT dooz row", "GR-10 NULL-PRODUCER"),
 ("compose host reports 0x0 children until composition applies (observed)",
  "dooz Lt4 attach trace",
  "compose 0 children at attach end",
  "REPRODUCED-DIVERGENT", "R-NEW-354-era trace; still at frontier", "GR-07 COMPOSE-FRONTIER"),
 ("frame clock ticks delivered once compose subscribed (ordering)",
  "compose BroadcastFrameClock law",
  "subscribe -> tick -> advance",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "GR-07 COMPOSE-FRONTIER"),
 ("compose preview/livedata family absent (census demand 0)",
  "evidence-based priority",
  "census scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("kotlinx.collections.immutable interop with snapshot lists",
  "upstream kotlinx.collections.immutable in repo",
  "persistent list ops in snapshot context",
  "VERIFIED-CORRECT", "upstream/kotlinx.collections.immutable fetched", "NONE"),
 ("compose font resource loading shares F text metrics law",
  "shared metrics integration",
  "font load via compose path",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("state restore into compose SavedStateHolderRegistry (post FIX-005 OK)",
  "savedstate registry compose bridge",
  "restore path executes w/o NPE",
  "PROVEN-L5", "solitaire post-fix chain", "R-009 SWITCH-KEY-WIDENING"),
 ("compose coroutine scope uses main dispatcher identity (not new thread per call)",
  "dispatcher identity law",
  "same dispatcher instance across frames",
  "VERIFIED-CORRECT", "engine dispatcher model", "GR-07 COMPOSE-FRONTIER"),
 ("composition context carries loads: density, layoutDirection, material theme",
  "compose CompositionLocal defaults",
  "material theme local present when material used",
  "RESEARCHED-NOT-IMPLEMENTED", "S103 downstream list", "GR-07 COMPOSE-FRONTIER"),
 ("side-effect ordering: LaunchedEffect/DisposableEffect lifecycle aware",
  "compose effect law",
  "effects run after apply, before frame end",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "GR-07 COMPOSE-FRONTIER"),
 ("compose host root measurement: Lt4;.L completes after getRootView law (host width answerable)",
  "compose measure contract + AOSP getRootView never-null",
  "post-fix trace: position-cache dispatch returns; no getWidth NPE (3/3)",
  "IMPLEMENTED-TESTED", "S104-r3 dooz 3-run det (SHA 59fdbfcd x3); visual unchanged (honest)", "GR-07 COMPOSE-FRONTIER"),
]

FAMILY_H = [
 ("Activity constructor executes at launch (F-118 law)",
  "F-118 activity-constructor law",
  "launch; <init> side effects visible",
  "PROVEN-L5", "F-118 IMPLEMENTED+TESTED (G08 launches)", "NONE"),
 ("onCreate chain: super first, content after theme (ordering law)",
  "AOSP Activity.onCreate contract",
  "trace order: ctor -> onCreate -> setContentView",
  "PROVEN-L5", "engine lifecycle_controller", "NONE"),
 ("saved-state registry controller init requires right merged branch (R-009)",
  "FIX-005 solitaire proof",
  "getSavedStateProvider NPE gone 3/3",
  "PROVEN-L5", "solitaire 12->0 (3/3, SHA 59fdbfcd)", "R-009 SWITCH-KEY-WIDENING"),
 ("ComponentActivity wiring: registry + lifecycle + viewmodel store",
  "androidx component activity upstream",
  "ctor completes w/o error",
  "PROVEN-L5", "solitaire chain past saved-state wiring", "GR-07 COMPOSE-FRONTIER"),
 ("onStart/onResume ordering after onCreate (AOSP order)",
  "AOSP activity lifecycle",
  "trace order onCreate<onStart<onResume",
  "VERIFIED-CORRECT", "lifecycle_controller", "NONE"),
 ("onPause/onStop at background/focus loss (engine focus model)",
  "AOSP lifecycle",
  "run end dispatches pause/stop trace",
  "VERIFIED-CORRECT", "engine lifecycle", "NONE"),
 ("setContentView before onResume visible at first frame",
  "AOSP frame contract",
  "first rendered frame has content",
  "VERIFIED-CORRECT", "engine first-frame evidence", "NONE"),
 ("AppCompat delegate installs decor before setContentView",
  "AppCompatDelegateImpl upstream",
  "AppCompat titles inflate with decor present",
  "REPRODUCED-DIVERGENT", "GR-08 sub-decor gap", "GR-08 DECOR-LINKAGE"),
 ("manifest exported/launch intent selects entry activity",
  "AOSP intent resolution",
  "launcher activity from manifest chooser",
  "VERIFIED-CORRECT", "manifest_reader entry point", "NONE"),
 ("multi-activity: launched second activity overlays first (backstack law)",
  "AOSP backstack",
  "second activity content on top",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("finish() triggers onDestroy and pops stack",
  "AOSP finish law",
  "finish then next activity visible",
  "VERIFIED-CORRECT", "engine activity stack", "NONE"),
 ("ViewModel survives rotation-equivalent (config change no-op in engine)",
  "viewmodel store law",
  "same ViewModel instance across recreation calls",
  "RESEARCHED-NOT-IMPLEMENTED", "S103 downstream", "GR-07 COMPOSE-FRONTIER"),
 ("SavedStateProvider roundtrip: save -> restore keys identical",
  "androidx savedstate upstream",
  "registry save/restore key set equality",
  "PROVEN-L5", "solitaire post-fix (wiring executes)", "R-009 SWITCH-KEY-WIDENING"),
 ("application onCreate before activity (application_context ordering)",
  "AOSP app init order",
  "trace order app<activity",
  "VERIFIED-CORRECT", "application_context.cpp", "NONE"),
 ("ContentProvider.installContentProviders before activity onCreate",
  "AOSP provider init phase",
  "provider install trace precedes activity",
  "VERIFIED-CORRECT", "engine boot phases", "NONE"),
 ("onActivityResult stubs return per contract (RESULT_CANCELED default)",
  "AOSP activity result law",
  "startActivityForResult default result",
  "VERIFIED-CORRECT", "android_shadows", "NONE"),
 ("permissions: grant-all model documented (host policy)",
  "engine policy record",
  "dangerous permission auto-granted; trace note",
  "VERIFIED-CORRECT", "engine permission model", "NONE"),
 ("application attachBaseContext earliest hook",
  "AOSP attachBaseContext order",
  "context wrap before app onCreate",
  "VERIFIED-CORRECT", "engine boot", "NONE"),
 ("fragment family demand-gated (census demand measured before build-out)",
  "evidence-based priority",
  "census fragment usage scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("dialog show() uses decor + window touch (R-NEW-394)",
  "dialog shadow law",
  "dialog button tap works",
  "PROVEN-L5", "R-NEW-394 VERIFIED-FIXED", "NONE"),
 ("activity theme applies at decor creation (before content)",
  "AOSP theme timing",
  "themed decor attributes visible",
  "VERIFIED-CORRECT", "engine decor stage", "GR-09 THEME-PRODUCER"),
 ("window feature flags (no title/fullscreen) honored at decor",
  "AOSP window features",
  "FLAG_FULLSCREEN sized 1080x1920 no inset",
  "VERIFIED-CORRECT", "engine window shadow", "NONE"),
 ("lifecycle callbacks on main thread only (single-thread determinism)",
  "engine threading law",
  "callback thread id constant",
  "VERIFIED-CORRECT", "engine scheduler", "NONE"),
 ("service/intent-service started executes onStartCommand (shadow)",
  "AOSP service basics (shadow)",
  "startService -> onStartCommand trace",
  "VERIFIED-CORRECT", "android_shadows", "NONE"),
 ("broadcast receivers: registered receiver receives sent broadcast",
  "AOSP broadcast law (shadow)",
  "sendBroadcast -> onReceive invoked",
  "VERIFIED-CORRECT", "engine broadcast shadow", "NONE"),
 ("pendingintent shadow per F surface",
  "pending_intent_shadow.cpp",
  "PI.get* + send no-crash",
  "VERIFIED-CORRECT", "pending_intent_shadow", "NONE"),
 ("activity result + save instance state bundle roundtrip",
  "AOSP onSaveInstanceState",
  "bundle save -> restore same keys",
  "VERIFIED-CORRECT", "engine bundle model", "NONE"),
 ("instrumentation lifecycle gate: activity thread main loop owns frames",
  "AOSP ActivityThread model",
  "frame pump tied to activity thread",
  "VERIFIED-CORRECT", "engine main loop", "NONE"),
 ("manifest meta-data readable at runtime",
  "AOSP ApplicationInfo.metaData",
  "metaData bundle non-null when declared",
  "VERIFIED-CORRECT", "manifest reader", "NONE"),
 ("process death on uncaught exception reproduces Android (crash law)",
  "AOSP crash semantics",
  "uncaught -> process exit code + trace",
  "VERIFIED-CORRECT", "engine crash path", "NONE"),
 ("activity relaunch preserves explicit state only (documented)",
  "engine policy",
  "re-run starts fresh unless state saved",
  "VERIFIED-CORRECT", "engine run protocol", "NONE"),
 ("onConfigurationChanged not fired (fixed config policy)",
  "engine config policy",
  "no mid-run config callbacks",
  "VERIFIED-CORRECT", "engine config", "NONE"),
 ("savedstate restore BEFORE onResume (AOSP order)",
  "androidx savedstate ordering",
  "restore trace precedes resume",
  "PROVEN-L5", "solitaire chain", "R-009 SWITCH-KEY-WIDENING"),
 ("viewmodel provider factory app-provided used (factory law)",
  "androidx viewmodel",
  "custom Factory.create called",
  "RESEARCHED-NOT-IMPLEMENTED", "S103 downstream", "GR-07 COMPOSE-FRONTIER"),
 ("lifecycle state machine monotonic (no backwards transitions)",
  "androidx lifecycle law",
  "state sequence strict",
  "VERIFIED-CORRECT", "engine lifecycle", "NONE"),
]
