# PATTERN-500 family I (INPUT/TOUCH/HIT-TEST, 30) + J (GRAPHICS/CANVAS/GLES, 45)

FAMILY_I = [
 ("tap dispatches DOWN->UP motion event pair at coordinates",
  "AOSP MotionEvent stream",
  "--tap x,y@t produces 2 events",
  "VERIFIED-CORRECT", "engine input pipeline", "NONE"),
 ("per-child hit-test walk routes to deepest VISIBLE child",
  "R-NEW-399 AOSP hit-test law",
  "HITPROBE: nested child receives tap",
  "PROVEN-L5", "R-NEW-399 USED_BY_EXECUTION", "NONE"),
 ("GONE children excluded from hit-test",
  "AOSP hit-test skip",
  "tap under GONE child hits parent",
  "VERIFIED-CORRECT", "engine hit-test", "NONE"),
 ("click listener fires on same view that consumed DOWN+UP pair",
  "AOSP click detection",
  "click_audit.jsonl rows correlate",
  "VERIFIED-CORRECT", "MINIANDROID_CLICK_AUDIT protocol", "NONE"),
 ("touch slop not required for synthetic taps (direct click)",
  "engine input policy",
  "single-frame tap -> click",
  "VERIFIED-CORRECT", "engine tap model", "NONE"),
 ("dialog window is TOPMOST for touch (dialog touch law)",
  "R-NEW-394",
  "tap lands on dialog button not underlying view",
  "PROVEN-L5", "R-NEW-394 VERIFIED-FIXED", "NONE"),
 ("scroll containers consume vertical drag (intercept law)",
  "AOSP onInterceptTouchEvent",
  "drag inside ScrollView scrolls not clicks",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("long-press timing under virtual clock",
  "AOSP long-press law",
  "hold LONG_PRESS_TIMEOUT -> long click",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("multi-touch pointer id stability (secondary pointer streams)",
  "AOSP pointer model",
  "two-finger synthetic stream ids stable",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("input focus: EditText receives IME-equivalent text events",
  "AOSP focus + IME",
  "focus + type -> text appears",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("key events route to focused view then activity fallback",
  "AOSP key dispatch",
  "back key -> activity onBackPressed",
  "VERIFIED-CORRECT", "engine key dispatch", "NONE"),
 ("click audit trail deterministic 3-run",
  "engine determinism gate",
  "click_audit SHA identical",
  "VERIFIED-CORRECT", "3-run protocol", "NONE"),
 ("hit-test uses CURRENT frame (no stale coordinates)",
  "R-NEW-399 blocker refutation",
  "tap after layout move hits new location",
  "PROVEN-L5", "R-NEW-399 honest note", "NONE"),
 ("hit-test respects rotation/translation transforms",
  "AOSP transformed hit-test",
  "rotated button still tappable (inverse map)",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("touchable area includes padding (content + padding hit)",
  "AOSP bounds hit model",
  "tap on padding region clicks",
  "VERIFIED-CORRECT", "engine bounds model", "NONE"),
 ("margin area does NOT hit child (margin outside bounds)",
  "AOSP bounds law",
  "tap in margin region hits parent",
  "VERIFIED-CORRECT", "engine bounds model", "NONE"),
 ("clickable=true required for consumption (else bubbles)",
  "AOSP consumption law",
  "non-clickable parent gets event",
  "VERIFIED-CORRECT", "engine dispatch", "NONE"),
 ("onTouch vs onClick precedence (listener first-consume law)",
  "AOSP TouchListener precedence",
  "onTouch returning true suppresses click",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("disabled view does not click",
  "AOSP enabled law",
  "setEnabled(false) tap -> no click",
  "VERIFIED-CORRECT", "engine dispatch", "NONE"),
 ("window-level touch boundary: outside activity content no crash",
  "engine boundary law",
  "tap at 1079,1919 edge safe",
  "VERIFIED-CORRECT", "engine input bounds", "NONE"),
 ("compose pointer input gated behind compose host (#350)",
  "S104 #350 ticket",
  "compose title tap currently no-op",
  "GAP-OPEN", "#350 input slice", "GR-07 COMPOSE-FRONTIER"),
 ("scroll wheel / axis events latent (demand 0)",
  "evidence-based priority",
  "census axis-event scan",
  "LATENT-NO-DEMAND", "census scan", "NONE"),
 ("gesture detector fill: GestureDetector callbacks wired to event stream",
  "AOSP GestureDetector",
  "fling callback via synthetic stream",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("touch feedback: pressed state drawable changes on DOWN",
  "AOSP pressed state",
  "DOWN -> background pressed drawable",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("hit-test order is reverse draw order (topmost first)",
  "AOSP dispatch order",
  "overlapping children: last drawn wins",
  "VERIFIED-CORRECT", "R-NEW-399 walk", "NONE"),
 ("swipe synthetic events (MOVE interpolation) available",
  "engine input generation",
  "--swipe produces MOVE stream",
  "VERIFIED-CORRECT", "engine input options", "NONE"),
 ("input event timestamps align with frame clock (virtual time)",
  "engine time law",
  "event t within frame window",
  "VERIFIED-CORRECT", "engine virtual time", "NONE"),
 ("click coordinates recorded relative to window (no viewport drift)",
  "engine coordinate law",
  "audit coords == requested coords",
  "VERIFIED-CORRECT", "click audit", "NONE"),
 ("game interaction chains: tap->state->changed-frame evidence (TriPeaks/FishRings)",
  "S65 input->state->frame protocol",
  "3 deterministic interactions recorded",
  "PROVEN-L5", "root_registry S65 summary (det x3)", "NONE"),
 ("input injection does not disturb render determinism (isolated channel)",
  "engine isolation law",
  "tap run vs no-tap run: pre-tap frames identical",
  "VERIFIED-CORRECT", "engine frame compare", "NONE"),
]

FAMILY_J = [
 ("Canvas draw ops route through canvas_shadow to raster",
  "engine graphics pipeline",
  "drawRect visible in frame pixels",
  "VERIFIED-CORRECT", "canvas_shadow.cpp", "NONE"),
 ("Paint flags: anti-alias/style/stroke width honored",
  "AOSP Paint",
  "STROKE vs FILL pixel difference",
  "VERIFIED-CORRECT", "canvas_shadow paint model", "NONE"),
 ("Color int ARGB packing law (0xAARRGGBB)",
  "AOSP Color",
  "color roundtrip through Paint/Canvas",
  "VERIFIED-CORRECT", "engine color model", "NONE"),
 ("Bitmap decode -> draw -> pixels visible (bitmap_shadow)",
  "AOSP Bitmap pipeline",
  "decoded bitmap drawn 1:1",
  "PROVEN-L5", "bitmap titles visual contracts", "NONE"),
 ("Canvas save/restore stack semantics",
  "AOSP save()/restore()",
  "clip+transform restore exact",
  "VERIFIED-CORRECT", "canvas_shadow stack", "NONE"),
 ("Matrix ops: setTranslate/rotate/scale/post/pre composition",
  "AOSP Matrix",
  "matrix chain == expected transform",
  "VERIFIED-CORRECT", "matrix_shadow", "NONE"),
 ("text draw via freetype metrics (F text laws)",
  "engine text stack",
  "text pixels present; widths consistent",
  "PROVEN-L5", "9 HUMAN_VISIBLE titles", "NONE"),
 ("PorterDuff basic modes (SRC_OVER default)",
  "AOSP PorterDuff subset",
  "SRC_OVER compositing visible",
  "VERIFIED-CORRECT", "renderer blend", "NONE"),
 ("Path fill/stroke rendering subset",
  "AOSP Path",
  "polygon paths rasterized",
  "VERIFIED-CORRECT", "canvas path model", "NONE"),
 ("ColorFilter apply law (R-NEW-393)",
  "R-NEW-393",
  "setColorFilter changes widget pixels",
  "PROVEN-L5", "R-NEW-393 VERIFIED-FIXED", "NONE"),
 ("Shader: bitmap/linear-gradient subset",
  "AOSP Shader subset",
  "gradient fill renders",
  "UNTESTED-LAW-DOCUMENTED", "law pinned", "NONE"),
 ("Drawable states + invalidate on state change",
  "AOSP Drawable",
  "state toggle redraws",
  "VERIFIED-CORRECT", "drawable shadow", "NONE"),
 ("hardware-acceleration-independent raster (software model documented)",
  "engine graphics scope note",
  "no HW layer divergence possible",
  "VERIFIED-CORRECT", "GRAPHICS_DO_NOT_REINVENT.md", "NONE"),
 ("GLES10/GLSurfaceView: EGL10 SETUP ONLY (6/54 titles)",
  "GL_NEED_LEDGER measured",
  "EGL initialize/swap without crash on GL titles",
  "IMPLEMENTED-TESTED", "GL_NEED_LEDGER.{json,md}", "GR-12 GL-FRONTIER"),
 ("GLES20+ method refs corpus-wide = 0 (measured gate)",
  "GL_NEED_LEDGER method_ids scan",
  "0 titles demand Java GLES20",
  "LATENT-NO-DEMAND", "s104_gl_need_ledger.py", "GR-12 GL-FRONTIER"),
 ("glTexImage2D/glTexSubImage2D family: PGL implements at C level; bridge absent",
  "ROOT-007 GL-BRIDGE classification",
  "bridge dispatch rows absent (bridge never reached)",
  "GAP-OPEN", "ROOT_CLUSTERS ROOT-007", "GR-12 GL-FRONTIER"),
 ("glReadPixels bridge absent (PGL C-level only)",
  "ROOT-007 classification",
  "no Java->PGL dispatch path",
  "GAP-OPEN", "ROOT_CLUSTERS ROOT-007", "GR-12 GL-FRONTIER"),
 ("framebuffer/texture lifecycle: bridge-absent, demand-gated",
  "ROOT-007 classification",
  "corpus demand scan = 0 refs",
  "LATENT-NO-DEMAND", "GL_NEED_LEDGER", "GR-12 GL-FRONTIER"),
 ("GLSL execution: PGL executes C-function shaders; GLSL stored verbatim",
  "GLES_BACKEND_COMPARISON_010.md",
  "no GLSL compiler in scope; documented frontier",
  "RESEARCHED-NOT-IMPLEMENTED", "ROOT-007 GLSL frontier", "GR-12 GL-FRONTIER"),
 ("compressed textures (ETC1/S3TC/ATC/PVRTC): absent engine-wide",
  "ROOT-007 TEX-COMPRESSION",
  "asset scan gate pending",
  "GAP-OPEN", "ROOT_CLUSTERS ROOT-007", "GR-12 GL-FRONTIER"),
 ("EGL shadow statics (BAD_ALLOC/CONTEXT_LOST/surfaceless) host-only",
  "ROOT-007 EGL-SHADOW",
  "shadow surface semantics only",
  "HOST-ONLY", "ROOT_CLUSTERS ROOT-007 host-only family", "GR-12 GL-FRONTIER"),
 ("libGDX titles render via bundled libgdx.so natives (not Java GLES)",
  "GL_NEED_LEDGER census verdict",
  "JNI/native loading is the true GL frontier",
  "HOST-ONLY", "GL_NEED_LEDGER", "GR-12 GL-FRONTIER"),
 ("native .so loading out of Java-runtime scope (documented blocker)",
  "S104 remaining blockers",
  "GL titles blocked at native load",
  "HOST-ONLY", "S104_REPORT remaining blockers", "GR-12 GL-FRONTIER"),
 ("SurfaceFlinger/BufferQueue/GraphicBuffer producer layers host-only",
  "ROOT-NULL-PRODUCER out-of-scope family",
  "rule 7 classification recorded",
  "HOST-ONLY", "ROOT_CLUSTERS out-of-scope list", "GR-12 GL-FRONTIER"),
 ("screenshot capture is engine raster ground truth (PNG writer)",
  "engine evidence protocol",
  "frame capture SHA-stable 3-run",
  "PROVEN-L5", "3-run SHA evidence (59fdbfcd...)", "NONE"),
 ("visual contracts: observed-confidence model (S92 oracle)",
  "S92 visual contract law",
  "ACCEPT/REJECT battery distinguishes all cases",
  "PROVEN-L5", "battery 105/105 gate", "NONE"),
 ("GIF evidence: representative frames non-uniform (white-frame guard)",
  "S74 §13 PIL frame verification",
  "uniform-white frames rejected by auditor",
  "PROVEN-L5", "worklog S74 CRITICAL-006 row", "NONE"),
 ("choreographer-driven traversal each frame (traversal law)",
  "AOSP traversal",
  "frame N invalidations visible frame N+1",
  "VERIFIED-CORRECT", "choreographer shadow", "NONE"),
 ("window background draw before content (draw order law)",
  "AOSP decor draw order",
  "bg pixels under transparent views",
  "VERIFIED-CORRECT", "engine decor draw", "NONE"),
 ("surface format: RGB888 output buffer (provenance metadata)",
  "engine output law",
  "gfx_provenance.json format rows",
  "VERIFIED-CORRECT", "MINIANDROID_GFX_PROVENANCE", "NONE"),
 ("png/jpeg decode via stb (features/fidelity rows committed)",
  "engine decoder registry",
  "corpus formats decode without error",
  "VERIFIED-CORRECT", "decoder census", "NONE"),
 ("lottie animation surface (MINIANDROID_HAVE_LOTTIE)",
  "build flag; engine lottie path",
  "lottie title frames advance",
  "IMPLEMENTED-TESTED", "Makefile flag + EXECUTED_GIFS.md", "NONE"),
 ("animator shadow: ValueAnimator ticker virtual-time",
  "animator_shadow.cpp",
  "animation progress deterministic",
  "VERIFIED-CORRECT", "animator shadow", "NONE"),
 ("portablegl vendored upstream (do-not-reinvent registry)",
  "GRAPHICS_SOURCE_REGISTRY: PortableGL",
  "PGL builds; bridge gated by demand",
  "VERIFIED-CORRECT", "third_party/portablegl + registry", "GR-12 GL-FRONTIER"),
 ("graphics upstream source-first rule: check AOSP/CTS/Mesa/ANGLE first",
  "S104 directive §5 source-first",
  "GRAPHICS_DO_NOT_REINVENT.md honored in decisions",
  "VERIFIED-CORRECT", "GL_NEED_LEDGER decision trail", "GR-12 GL-FRONTIER"),
 ("screen density affects scaled drawing (density law end-to-end)",
  "AOSP density",
  "dp sizes render at runtime density",
  "VERIFIED-CORRECT", "renderer + config", "NONE"),
 ("view drawing cache/layer type: software layer semantics only",
  "engine scope",
  "LAYER_TYPE_HARDWARE treated as software",
  "VERIFIED-CORRECT", "engine layer model", "NONE"),
 ("canvas clip ops (rect/region) exact",
  "AOSP clip",
  "clipRect excludes pixels outside",
  "VERIFIED-CORRECT", "canvas shadow", "NONE"),
 ("drawText baseline/measure API consistency (Paint.measureText)",
  "text metrics law",
  "measureText width == advance sum",
  "PROVEN-L5", "R-NEW-392 text subsumption", "NONE"),
 ("frame pixel parity after identity/inflation changes (regression law)",
  "REAL_APK_IMPACT R-004 table",
  "pixel-identical before/after rows",
  "PROVEN-L5", "REAL_APK_IMPACT.md", "R-004 CLASS-IDENTITY"),
 ("screenshot pixel SHA determinism 3-run (evidence law)",
  "3-run protocol",
  "SHA identical x3 (solitaire 59fdbfcd...)",
  "PROVEN-L5", "S104 evidence", "NONE"),
 ("rendered-pixel census gate: uniform-frame detection as FAIL signal",
  "census verifier law",
  "FAIL census rows flagged by auditor",
  "PROVEN-L5", "census 14/2/38/7 counts", "NONE"),
 ("graphics API stubs return documented defaults (no invented pixels)",
  "engine honesty law",
  "stub surface enumerated, not guessed",
  "VERIFIED-CORRECT", "android_stubs.h", "NONE"),
 ("frame capture format PNG byte-deterministic (no timestamp embed)",
  "evidence determinism",
  "same pixels -> same PNG bytes",
  "PROVEN-L5", "3-run SHA protocol", "NONE"),
 ("graphics failure surface: decode/inflate errors logged not invented (honesty law)",
  "engine diagnostics law",
  "corrupt image -> logged error + fallback, no fabricated pixels",
  "VERIFIED-CORRECT", "engine decoder error paths", "NONE"),
]
