#!/usr/bin/env python3
"""S125 capability seed — roadmap SS5-SS22 capability names + source-inventory keys.

Status derivation law (honest, per docs/EVIDENCE_RULES.md):
  VERIFIED  -> only via explicit evidence overrides (unit test + control APK +
               real APK + runtime trace refs all present in the override)
  TESTED    -> explicit evidence override with runtime/session refs
  IMPLEMENTED -> source inventory hit only (code exists; NOT runtime proof)
  PENDING   -> no source hit
Grep hits NEVER produce VERIFIED. Percentages in docs/ROADMAP_STATUS.md are
computed from these statuses, never invented.
"""

# layer_id, layer_name -> list of (capability_name, regex_for_src_grep)
LAYERS = [
    ("UI", [
        ("View", r"class ViewShadow|ViewShadow\b"),
        ("ViewGroup", r"ViewGroup"),
        ("Window", r"WindowShadow|class .*Window"),
        ("WindowManager", r"WindowManager"),
        ("DecorView", r"DecorView|decor_view"),
        ("Root View", r"root_view"),
        ("ViewRoot/traversal equivalent", r"traversal|view_root|do_traversal"),
        ("requestLayout", r"requestLayout|request_layout"),
        ("invalidate", r"invalidate"),
        ("MeasureSpec", r"MeasureSpec|measure_spec"),
        ("EXACTLY", r"EXACTLY"),
        ("AT_MOST", r"AT_MOST"),
        ("UNSPECIFIED", r"UNSPECIFIED"),
        ("measured dimensions", r"measured_width|measured_width_"),
        ("setFrame", r"setFrame|set_frame"),
        ("layout/onLayout", r"onLayout|do_layout|view_layout"),
        ("gravity", r"gravity"),
        ("margin", r"margin"),
        ("padding", r"padding"),
        ("MATCH_PARENT", r"MATCH_PARENT"),
        ("WRAP_CONTENT", r"WRAP_CONTENT"),
        ("weight", r"layout_weight|weight_sum"),
        ("draw/onDraw", r"onDraw|do_draw|view_draw"),
        ("dispatchDraw", r"dispatchDraw|dispatch_draw"),
        ("drawChild", r"drawChild|draw_child"),
        ("clipping", r"clip_rect|clipRect|clipping"),
        ("alpha", r"\balpha\b"),
        ("transforms", r"translation_|scale_|rotation_"),
        ("visibility", r"visibility"),
        ("focus", r"focus"),
        ("view state", r"drawable_state|view_state"),
    ]),
    ("RENDERING", [
        ("Canvas", r"CanvasShadow|canvas_shadow"),
        ("Paint", r"PaintShadow|paint_shadow"),
        ("Bitmap", r"BitmapShadow|bitmap_shadow"),
        ("Color", r"ColorShadow|parse_color"),
        ("Rect/RectF", r"\bRect\b|rect_f"),
        ("Path", r"PathShadow|path_shadow"),
        ("Matrix", r"MatrixShadow|matrix_shadow"),
        ("save/restore", r"save_count|canvas_save|save()/restore()|save()\/restore()"),
        ("translate/scale/rotate", r"canvas_translate|translate\(|concat"),
        ("clip", r"canvas_clip|clipRect|clip_"),
        ("drawRect", r"draw_rect"),
        ("drawBitmap", r"draw_bitmap"),
        ("drawPath", r"draw_path"),
        ("drawText", r"draw_text"),
        ("software rasterization", r"raster|software_render"),
        ("framebuffer", r"framebuffer"),
        ("Surface", r"Surface\b|surface_"),
        ("SurfaceHolder", r"SurfaceHolder|surface_holder"),
        ("lockCanvas", r"lock_canvas|lockCanvas"),
        ("unlockCanvasAndPost", r"unlock_canvas|unlockCanvas"),
        ("screenshot", r"screenshot|capture_frame|capture_output"),
    ]),
    ("TEXT", [
        ("TextPaint", r"TextPaint|text_paint"),
        ("Typeface", r"Typeface|typeface"),
        ("font loading", r"load_font|font_load"),
        ("font fallback", r"fallback"),
        ("StaticLayout", r"StaticLayout|static_layout"),
        ("line breaking", r"line_break|break_text"),
        ("baseline", r"baseline"),
        ("alignment", r"text_align|alignment"),
        ("Unicode", r"utf8|utf16|unicode"),
        ("Bidi", r"bidi"),
        ("emoji", r"emoji"),
        ("HarfBuzz", r"harfbuzz|hb_buffer|hb_shape"),
        ("FreeType", r"freetype|FT_"),
        ("ICU", r"icu::|ICU"),
        ("glyph rasterization", r"glyph"),
    ]),
    ("RESOURCES", [
        ("Resources", r"ResourcesShadow|resource_runtime"),
        ("AssetManager", r"AssetManager|asset_manager"),
        ("Theme", r"ThemeEngine|theme_engine"),
        ("TypedArray", r"TypedArray|obtainStyledAttributes|obtain_styled"),
        ("AttributeSet", r"AttributeSet|attribute_set"),
        ("Configuration", r"Configuration|device_config"),
        ("DisplayMetrics", r"DisplayMetrics|display_metrics"),
        ("ColorStateList", r"ColorStateList|color_state"),
        ("BitmapDrawable", r"BitmapDrawable"),
        ("ColorDrawable", r"ColorDrawable"),
        ("GradientDrawable", r"GradientDrawable"),
        ("ShapeDrawable", r"ShapeDrawable"),
        ("StateListDrawable", r"StateList|state_list"),
        ("LayerDrawable", r"LayerDrawable"),
        ("InsetDrawable", r"InsetDrawable"),
        ("VectorDrawable", r"VectorDrawable|vector_drawable"),
        ("AdaptiveIcon", r"AdaptiveIcon|adaptive_icon"),
        ("RippleDrawable", r"Ripple"),
        ("NinePatch", r"NinePatch|nine_patch"),
    ]),
    ("INFLATION", [
        ("LayoutInflater", r"LayoutInflater|layout_inflater"),
        ("XML parsing", r"xml_parse|parse_xml|expat|tinyxml"),
        ("constructor resolution", r"ctor_resolve|view_ctor|constructor"),
        ("custom Views", r"custom_view|custom view"),
        ("include", r"\binclude\b"),
        ("merge", r"\bmerge\b"),
        ("ViewStub", r"ViewStub"),
        ("styles", r"style_res|resolve_style|style="),
        ("themes", r"apply_style|theme_attr"),
        ("attributes", r"resolve_attr|attr_value"),
    ]),
    ("INPUT", [
        ("MotionEvent", r"MotionEvent|motion_event"),
        ("KeyEvent", r"KeyEvent|key_event"),
        ("dispatchTouchEvent", r"dispatch_touch|dispatchTouchEvent"),
        ("onInterceptTouchEvent", r"intercept_touch|onInterceptTouchEvent"),
        ("onTouchEvent", r"on_touch|onTouchEvent"),
        ("TouchTarget", r"touch_target"),
        ("focus", r"focus"),
        ("keyboard", r"keyboard|key_input"),
        ("click", r"perform_click|performClick|on_click"),
        ("long click", r"long_click|longClick"),
        ("multi-touch", r"multi_touch|pointer_count|pointer"),
        ("VelocityTracker", r"VelocityTracker|velocity"),
        ("GestureDetector", r"GestureDetector|gesture"),
        ("TouchDelegate", r"TouchDelegate|touch_delegate"),
    ]),
    ("FRAMES", [
        ("Choreographer", r"Choreographer|choreographer"),
        ("INPUT/ANIMATION/TRAVERSAL callbacks", r"post_frame_callback|postFrameCallback|frame_callback"),
        ("frame pump", r"frame_pump|do_frame|pump_ticks"),
    ]),
    ("ANIMATION", [
        ("ValueAnimator", r"ValueAnimator|value_animator"),
        ("ObjectAnimator", r"ObjectAnimator|object_animator"),
        ("AnimatorSet", r"AnimatorSet|animator_set"),
        ("AnimationHandler", r"AnimationHandler|animation_handler"),
        ("ViewPropertyAnimator", r"ViewPropertyAnimator|view_property"),
        ("Interpolator", r"Interpolator|interpolator"),
        ("layout animation", r"layout_animation"),
    ]),
    ("SCROLLING", [
        ("ScrollView", r"ScrollView|scroll_view"),
        ("HorizontalScrollView", r"HorizontalScrollView|horizontal_scroll"),
        ("Scroller/OverScroller", r"Scroller|scroller"),
        ("scrollTo/scrollBy", r"scroll_to|scrollTo|scroll_by"),
        ("fling", r"fling"),
        ("computeScroll", r"compute_scroll|computeScroll"),
        ("EdgeEffect", r"EdgeEffect|edge_effect"),
        ("nested scrolling", r"nested_scroll|NestedScroll"),
    ]),
    ("THREADING", [
        ("Thread", r"ThreadShadow|thread_shadow|std::thread"),
        ("Runnable", r"Runnable|runnable"),
        ("Looper", r"Looper|looper"),
        ("Handler", r"HandlerShadow|handler_"),
        ("Message/MessageQueue", r"MessageQueue|message_queue|message_"),
        ("HandlerThread", r"HandlerThread"),
        ("main thread", r"main_thread"),
        ("synchronization", r"mutex|condition_variable|wait_notify|volatile"),
        ("UI dispatch", r"post_to_main|run_on_ui|ui_dispatch|post_to_looper"),
    ]),
    ("STORAGE", [
        ("files/cache dirs", r"get_files_dir|files_dir|cache_dir"),
        ("SharedPreferences", r"SharedPreferences|shared_prefs"),
        ("SQLite", r"sqlite3|SQLite"),
        ("Cursor", r"CursorShadow|cursor_shadow"),
        ("ContentValues", r"ContentValues|content_values"),
        ("ContentResolver", r"ContentResolver|content_resolver"),
        ("URI", r"UriShadow|uri_"),
        ("permissions", r"permission"),
    ]),
    ("NETWORK", [
        ("DNS", r"\bDNS\b|dns_|getaddrinfo"),
        ("TCP sockets", r"socket\(|tcp_"),
        ("HTTP/HTTPS", r"http_client|https|curl|http_url"),
        ("URLConnection", r"URLConnection|url_connection"),
        ("TLS", r"\bTLS\b|ssl_"),
        ("connectivity state", r"connectivity|network_state"),
    ]),
    ("WEBVIEW", [
        ("WebView", r"WebViewShadow|webview"),
        ("HTML parsing", r"parse_html|html_"),
        ("CSS", r"\bCSS\b|css_"),
        ("JavaScript", r"javascript|js_interpreter|quickjs"),
        ("DOM", r"\bDOM\b|dom_"),
        ("navigation", r"load_url|loadUrl|navigate"),
        ("cookies", r"cookie"),
        ("local storage", r"local_storage|localstorage"),
        ("JS bridge", r"js_bridge|addJavascriptInterface"),
    ]),
    ("AUDIO", [
        ("AudioTrack", r"AudioTrack|audio_track"),
        ("AudioRecord", r"AudioRecord|audio_record"),
        ("MediaPlayer", r"MediaPlayer|media_player"),
        ("audio focus", r"audio_focus"),
        ("PCM", r"\bPCM\b|pcm_"),
        ("WAV", r"\bWAV\b|wav_"),
        ("MP3/AAC", r"\bmp3\b|\baac\b|dr_mp3"),
        ("mixer/volume", r"mixer|volume"),
        ("streaming", r"stream_"),
    ]),
    ("VIDEO", [
        ("MediaCodec", r"MediaCodec|media_codec"),
        ("MediaExtractor", r"MediaExtractor|media_extractor"),
        ("video decode", r"video_decode|h264|H264|hevc|av1|vp8|vp9"),
        ("frame timing", r"frame_timing|pts"),
        ("Surface output", r"surface_output|video_surface"),
    ]),
    ("GAME", [
        ("SurfaceView games", r"SurfaceViewShadow|surface_view"),
        ("TextureView", r"TextureView|texture_view"),
        ("lockCanvas loop", r"lock_canvas"),
        ("game loops", r"game_loop|frame_loop"),
        ("fixed/variable timestep", r"timestep|time_step"),
        ("sprites", r"sprite"),
        ("OpenGL ES", r"gles|OpenGL|GLES"),
        ("EGL", r"\bEGL\b|egl"),
        ("shaders", r"shader|glCompileShader"),
        ("frame timing", r"frame_time|vsync"),
    ]),
    ("NATIVE", [
        ("JNI", r"jni_env|JNI"),
        ("System.loadLibrary", r"load_library|loadLibrary"),
        ("libc/libm/libdl", r"libc|libm\b|libdl"),
        ("pthread", r"pthread"),
        ("native memory", r"native_alloc|native_memory"),
        ("file descriptors", r"file_descriptor|\bfd\b"),
        ("native callbacks", r"native_callback|jni_callback"),
    ]),
    ("DATABASE", [
        ("SQLiteDatabase", r"SQLiteDatabase|sqlite"),
        ("Cursor", r"CursorShadow|cursor_shadow"),
        ("transactions", r"transaction|BEGIN TRANSACTION"),
        ("prepared statements", r"prepared|sqlite3_prepare"),
        ("indexes", r"CREATE INDEX|index_"),
        ("database lifecycle", r"open_database|close_database|db_open"),
    ]),
]

# (layer, capability) -> (status, [evidence refs])
# Only entries with REAL recorded runtime/session evidence go here. VERIFIED
# requires: unit/control test + real APK + runtime trace + repeated run refs.
CAP_EVIDENCE = {
    ("UI", "View"): ("TESTED", ["evidence/s113_fullgui (hello_smoke/hello_widgets control APKs)", "miniandroid/tests/shadow_registry_invariant_test.cpp"]),
    ("UI", "ViewGroup"): ("TESTED", ["evidence/s113_fullgui", "evidence/s124_theme_base (TableLayout/LinearLayout/FrameLayout themed renders)"]),
    ("UI", "Window"): ("TESTED", ["evidence/s122_harder_games (chess decor+toolbar painted)"]),
    ("UI", "DecorView"): ("TESTED", ["evidence/s122_harder_games chess_full_load_0err_toolbar.jpg"]),
    ("UI", "MeasureSpec"): ("TESTED", ["evidence/s121_full_sessions (5 games full-load with real measure pass)"]),
    ("UI", "setFrame"): ("TESTED", ["R-NEW-419 onSizeChanged/setFrame law", "evidence/s123_themed_apps flappycow1_start_screen_full.jpg", "3-run golden 13cf4746 x3"]),
    ("UI", "gravity"): ("TESTED", ["evidence/s121_full_sessions opmt board relayout (R-NEW-409 addRule)"]),
    ("UI", "draw/onDraw"): ("TESTED", ["evidence/s113_fullgui", "evidence/s119_games (6 games)"]),
    ("UI", "layout/onLayout"): ("TESTED", ["R-NEW-409/410 layout laws", "evidence/s121_full_sessions"]),
    ("RENDERING", "Canvas"): ("TESTED", ["evidence/s117_complete_graphics", "evidence/s119_games"]),
    ("RENDERING", "Paint"): ("TESTED", ["evidence/s117_complete_graphics"]),
    ("RENDERING", "Bitmap"): ("TESTED", ["evidence/s123_themed_apps flappycow drawBitmap dst-Rect chain"]),
    ("RENDERING", "drawText"): ("TESTED", ["evidence/s119_games HUD text (2048 SCORE 84, snake SCORE/BEST)"]),
    ("RENDERING", "screenshot"): ("VERIFIED", ["evidence/s122..s124 3-run byte-identical SHA protocol (calc a169346e x3, flappy 13cf4746 x3) — screenshot+SHA256+pixel metrics are the campaign evidence engine"]),
    ("RENDERING", "Surface"): ("TESTED", ["evidence/s123_themed_apps flappycow2_game_activity_after_play_tap.jpg"]),
    ("RENDERING", "lockCanvas"): ("TESTED", ["surface_view_shadow + evidence/s123 (flappycow Game launch chain)"]),
    ("TEXT", "Typeface"): ("TESTED", ["miniandroid/src/fonts", "docs/SYSTEM_FONTS.md", "evidence/s119_games HUD glyphs"]),
    ("TEXT", "glyph rasterization"): ("TESTED", ["evidence/s119_games (CJK dialog painted snake_deluxe S79)"]),
    ("RESOURCES", "Theme"): ("TESTED", ["S124 theme engine (AOSP AssetManager2 Theme::ApplyStyle port)", "evidence/s124_theme_base 9 JPGs", "heading calc themed render 3-run"]),
    ("RESOURCES", "TypedArray"): ("TESTED", ["F-NEW-175 obtainStyledAttributes shadow + S124 defStyleAttr tier (14 widgets)", "evidence/s124_theme_base notes1/sudoku1"]),
    ("RESOURCES", "StateListDrawable"): ("TESTED", ["miniandroid/src/framework/state_list.cpp", "evidence/s121 opmt selection ring"]),
    ("RESOURCES", "VectorDrawable"): ("TESTED", ["R-NEW-412/413 vector laws", "evidence/s122 chess full-load 0 errors"]),
    ("INFLATION", "LayoutInflater"): ("TESTED", ["inflate stats embedded in view_tree.json (S124)", "evidence/s124_theme_base"]),
    ("INFLATION", "styles"): ("TESTED", ["S124 bag-tier precedence XML > style= > defStyleAttr", "evidence/s124_theme_base notes/sudoku defStyleAttr bags"]),
    ("INFLATION", "themes"): ("TESTED", ["S124 android:theme subtree overlays + framework-res pkg 0x01 router", "dooz Theme.Dooz 355 keys", "evidence/s124_theme_base"]),
    ("INFLATION", "attributes"): ("TESTED", ["S124 resolve_attribute package-routed deref; ?attr/style items one law", "evidence/s124_theme_base"]),
    ("INPUT", "MotionEvent"): ("VERIFIED", ["touch_dispatcher + scripts/autoplay drivers", "evidence/s119_games 6 games real taps", "evidence/s121 opmt/fishrings taps", "3-run reproducible input schedules"]),
    ("INPUT", "click"): ("VERIFIED", ["S123 TAG-TRACE getTag click chain (calc targets 79/80/81)", "evidence/s123_themed_apps calc2_display_after_keypad_input.jpg"]),
    ("INPUT", "onTouchEvent"): ("TESTED", ["R-NEW-417 DEX onTouchEvent override dispatch", "evidence/s122 chess"]),
    ("FRAMES", "Choreographer"): ("TESTED", ["choreographer_shadow + post-lifecycle frame pump (S39 pump law)", "evidence/s123 flappycow G08-LAUNCH"]),
    ("ANIMATION", "ValueAnimator"): ("TESTED", ["animator_shadow.cpp", "evidence/s115_sweep animation fixtures"]),
    ("SCROLLING", "ScrollView"): ("TESTED", ["R-NEW-336 ScrollView-root chain + evidence/s38 wave4 scroll_min fixture"]),
    ("THREADING", "Handler"): ("TESTED", ["locks_shadow/executor_shadow", "evidence/s40 dooz23 real Hilt execution (0-error SUCCESS)"]),
    ("THREADING", "synchronization"): ("VERIFIED", ["R-NEW-337 full atomicfu-via-Unsafe contract (CAS/volatile offsets) — 30 offsets registered, 0 ISE across 3 runs"]),
    ("STORAGE", "SharedPreferences"): ("TESTED", ["evidence/s115_sweep sharedprefs fixtures"]),
    ("DATABASE", "SQLite"): ("TESTED", ["miniandroid/src/storage sqlite", "evidence/s10x database fixtures"]),
    ("GAME", "SurfaceView games"): ("TESTED", ["surface_view_shadow + evidence/s123 flappycow (Game launch); flashlight blank = honest frontier"]),
    ("NATIVE", "JNI"): ("VERIFIED", ["R-NEW-337 Unsafe/JNI contract", "evidence/s40 dooz23 36MB stderr real native interop, 3-run deterministic"]),
}
