#!/usr/bin/env python3
"""S125 — build the canonical control system (MASTER ROADMAP SS3/28/33/37).

Generates, from repo ground truth only (no invented numbers):
  canonical/capability_registry.json   <- SS5-22 names + src inventory + evidence overrides
  canonical/game_registry.json         <- audit 23+64 games mapped to L0-L7 + session overrides
  canonical/app_registry.json          <- curated apps w/ explicit evidence
  canonical/root_cause_registry.json   <- PROJECTION of live root_registry.json (source of truth stays root_registry.json)
  canonical/evidence_registry.json     <- evidence wave index (scanned from evidence/)
  canonical/compatibility_matrix.json  <- title x subsystems, derived from the two registries
  docs/ROADMAP_STATUS.md               <- generated from canonical state
  docs/CAPABILITY_MATRIX.md            <- generated table

Status vocabulary (SS2): IMPLEMENTED TESTED OBSERVED PARTIAL BLOCKED PENDING SUPERSEDED VERIFIED.
A checkbox is VERIFIED only with recorded runtime evidence; grep/source hits max out at IMPLEMENTED.
"""
import json, os, re, subprocess, hashlib, datetime, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from s125_capabilities_seed import LAYERS, CAP_EVIDENCE

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
NOW = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
SRC_DIRS = ["miniandroid/src", "miniandroid/include"]
SRC_FILES = []
for d in SRC_DIRS:
    for base, _, fns in os.walk(d):
        for fn in fns:
            if fn.endswith((".cpp", ".h", ".cc", ".hpp")):
                SRC_FILES.append(os.path.join(base, fn))
BLOB = "\n".join(open(f, errors="ignore").read() for f in SRC_FILES)

def head(title):
    return f"# {title}\n\n> GENERATED by `scripts/s125_build_canonical.py` at {NOW} — do not hand-edit.\n> Numbers are computed from canonical registries, never invented (ROADMAP SS28).\n\n"

# ---------------------------------------------------------------- 1. capabilities
caps = []
for layer_id, layer_name in [(l[0], l[0]) for l in LAYERS]:
    pass
cap_rows = []
for layer_id, items in LAYERS:
    for name, rx in items:
        hits = len(re.findall(rx, BLOB))
        key = (layer_id, name)
        if key in CAP_EVIDENCE:
            st, ev = CAP_EVIDENCE[key]
        else:
            st, ev = ("IMPLEMENTED" if hits > 0 else "PENDING"), []
        cap_rows.append({
            "id": f"CAP-{layer_id}-{len(cap_rows)+1:03d}",
            "layer": layer_id, "name": name,
            "status": st, "src_hits": hits, "evidence": ev,
        })
# layer order for display
LAYER_ORDER = [l[0] for l in LAYERS]

# ---------------------------------------------------------------- 2. root causes (projection)
rr = json.load(open("root_registry.json"))
roots = rr["roots"] if isinstance(rr, dict) and "roots" in rr else rr
from collections import Counter
root_stats = Counter(r.get("status", "?") for r in roots)
proj = {
    "_projection_of": "root_registry.json",
    "_law": "root_registry.json is the single writable store; this file is a generated read model (ROADMAP SS3: no duplicate canonical registries).",
    "generated": NOW, "total": len(roots), "status_counts": dict(root_stats),
    "roots": [{"id": r.get("id"), "title": r.get("title") or r.get("name"), "status": r.get("status"),
               "priority": r.get("priority"), "layer": r.get("layer") or r.get("area")} for r in roots],
}
json.dump(proj, open("canonical/root_cause_registry.json", "w"), indent=1)

# ---------------------------------------------------------------- 3. games
audit = json.load(open("docs/verified_executed_games.json"))
def lmap(evid_row):
    L = {f"L{i}": False for i in range(8)}
    L["L0"] = True
    L["L1"] = bool(evid_row.get("launched", True))
    lvl = str(evid_row.get("level") or evid_row.get("render_level") or "")
    rendered = bool(evid_row.get("rendered", False)) or "RENDER" in lvl.upper() or evid_row.get("evidence_level") in ("E4", "E5")
    if evid_row.get("evidence_level") in ("E4", "E5"):
        L["L2"] = True; L["L3"] = True
        if rendered: L["L4"] = True
        if evid_row.get("interaction"): L["L5"] = True
        if evid_row.get("state_change_evidence"): L["L6"] = True
    else:
        if evid_row.get("launched"): L["L2"] = None
        if evid_row.get("rendered"): L["L4"] = None
    return L

GAME_OVERRIDES = {
    "TicTacToe Deluxe": {"note": "S119 VERIFIED_3RUN HUD-anchored autoplay", "L": {"L6": True}},
    "2048": {"note": "S119 real SCORE 84 HUD-anchored; estimate/HUD delta tracked", "L": {"L6": True}},
    "Snake Deluxe": {"note": "S119 SCORE 2/BEST 2; wrap-wall AI port pending", "L": {}},
    "Mini Tetris": {"note": "S119 7 locks + 10+ stack; tick-drift fix pending", "L": {}},
    "MiniCraft (House Builder)": {"note": "S119 house built via autoplay", "L": {}},
    "Snake Neon": {"note": "S119 score=10 len=4", "L": {}},
    "Vector Pinball (bouncy)": {"note": "S121 menu + root cause; play pending", "L": {"L4": True}},
    "OPMT (One More Time…)": {"note": "S121 selection ring + rules-engine re-skin", "L": {"L6": True}},
    "Fish Rings": {"note": "S121 state change 1860 px/tap, 2x IDENTICAL", "L": {"L6": True}},
    "GameMasterDice": {"note": "S121 full-load + S124 themed menu", "L": {"L6": True}},
    "TriPeaks": {"note": "S121 full-session HUD ledger (flagship)", "L": {"L6": True, "L7": True}},
    "FreeKlondike": {"note": "S122 menu->GameActivity->deck deal (aces rendered)", "L": {"L6": True}},
    "FlappyCow": {"note": "S123/S124 start screen golden 3-run 13cf4746 + G08-LAUNCH Game chain; gameplay blocked by GMS frontier", "L": {"L6": None}},
}
games = []
for g in audit["games"]:
    L = lmap(g)
    ov = GAME_OVERRIDES.get(g["title"], {})
    for k, v in ov.get("L", {}).items():
        if v is not None: L[k] = v
    status = "VERIFIED" if g.get("audit_status") == "VERIFIED" else str(g.get("audit_status"))
    games.append({
        "id": f"GAME-{len(games)+1:03d}", "title": g["title"], "package": g.get("package"),
        "upstream": g.get("upstream"), "evidence_level": g.get("evidence_level"),
        "status": status, "checkpoints": L, "note": ov.get("note", ""),
        "sessions": g.get("sessions"), "evidence_refs": [g.get("execution_protocol", "")],
    })
for g in audit["observed_games"]:
    L = {f"L{i}": False for i in range(8)}
    L["L0"] = True
    L["L1"] = bool(g.get("launched", False))
    games.append({
        "id": f"GAME-{len(games)+1:03d}", "title": g.get("title", "?"), "package": g.get("package"),
        "upstream": g.get("upstream"), "evidence_level": g.get("evidence_level"),
        "status": "OBSERVED", "checkpoints": L, "note": "trace-only (E3); no meaningful visual proof",
        "sessions": g.get("session", ""), "evidence_refs": [],
    })
games.append({"id": f"GAME-{len(games)+1:03d}", "title": "Dooz v23 (Compose)", "package": "ir.dooz",
              "upstream": "real APK (S39-S42)", "evidence_level": "E3",
              "status": "BLOCKED", "note": "real Hilt/DI/composition execution 0-error (S40); first frame blank — Compose Recomposer frontier R-NEW-344. Honest: NOT A RENDER.",
              "checkpoints": {"L0": True, "L1": True, "L2": True, "L3": False, "L4": False, "L5": False, "L6": False, "L7": False},
              "sessions": "S39-S42/S124", "evidence_refs": ["docs/maintenance/worklog.md S40"]})
json.dump({"schema": "miniandroid.game_registry.v1", "generated": NOW, "status_vocabulary":
           ["VERIFIED", "TESTED", "OBSERVED", "PARTIAL", "BLOCKED", "PENDING", "SUPERSEDED"],
           "checkpoint_law": "L0 APK accepted; L1 runtime executes; L2 lifecycle; L3 view tree; L4 rendering; L5 input; L6 state changes; L7 multi-feature interaction; V visual evidence. A checkpoint is true only with recorded evidence; null = partially evidenced.",
           "games": games}, open("canonical/game_registry.json", "w"), indent=1)

# ---------------------------------------------------------------- 4. apps
APPS = [
    ("Heading Calculator", "com.…headingcalc", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "themed interactive VERIFIED_3RUN a169346e x3; TAG-TRACE getTag click chain; R-NEW-422 Pair law", "S123/S124", ["evidence/s123_themed_apps/calc1..2", "evidence/s124_theme_base/s124_calc1"]),
    ("uNote", "…", "TESTED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True},
     "S124 themed menu render (framework-res values lawful)", "S124", ["evidence/s124_theme_base/s124_unote1_menu.jpg"]),
    ("MicroTimer", "…", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "audit VERIFIED (repeated-run) + S124 themed keypad", "S95/S124", ["evidence/s124_theme_base/s124_microtimer1_keypad.jpg"]),
    ("Simple Stopwatch", "…", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "audit VERIFIED repeated-run", "S95", ["docs/verified_executed_games.json"]),
    ("Chess Clock", "…", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "audit VERIFIED", "S95", ["docs/verified_executed_games.json"]),
    ("Notes (billthefarmer)", "…", "TESTED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True},
     "audit VERIFIED + S124 defStyleAttr tier applied", "S95/S124", ["evidence/s124_theme_base/s124_notes1_defstyle.jpg"]),
    ("PMK-61 Calculator", "…", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "audit VERIFIED", "S95", ["docs/verified_executed_games.json"]),
    ("Shopping List Calc", "…", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "audit VERIFIED", "S95", ["docs/verified_executed_games.json"]),
    ("GH4A (GitHub client)", "com.gh4a", "TESTED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": None},
     "audit VERIFIED core; heavy app — levels capped to recorded runs", "S95", ["docs/verified_executed_games.json"]),
    ("OpenCalculator", "…", "PARTIAL", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": None},
     "near-blank A/B byte-identical = SlidingUpPanelLayout gravity idiom frontier; honest: NOT A RENDER", "S124", ["docs/maintenance/worklog.md S124"]),
    ("OpenSudoku", "…", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True, "L6": True},
     "audit VERIFIED + S124 SplashTheme/AppTheme per-activity observation", "S95/S124", ["docs/verified_executed_games.json"]),
    ("Telegram 12.10.1", "org.telegram.messenger", "BLOCKED", {"L0": True, "L1": True, "L2": True, "L3": False},
     "LaunchActivity dispatches deep (invoke_pc 548+); frame = 3 grey colors -> NOT A RENDER (honest); frontier: SvgHelper themed-icon SVG parsing + gms Api builder nulls", "S123/S124", ["evidence/s124_theme_base/s124_telegram1_grey_frontier.jpg"]),
    ("WhatsApp 2.26.38.74", "com.whatsapp", "BLOCKED", {"L0": True, "L1": True, "L2": False, "L3": False},
     "24f = 2 colors black/white -> NOT A RENDER (honest); frontier: AppContext.set injection + INVOKE_RETURN null; A/B byte-identical eb16ab5c", "S123/S124", ["evidence/s124_theme_base/s124_whatsapp1_blackwhite_frontier.jpg"]),
    ("hello_smoke (control)", "in-house", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True},
     "control APK full-paint stable; regression gate", "S38-S124", ["evidence/s113_fullgui"]),
    ("hello_widgets (control)", "in-house", "VERIFIED", {"L0": True, "L1": True, "L2": True, "L3": True, "L4": True, "L5": True},
     "most advanced control render: ImageView+EditText+Button+TableLayout+RelativeLayout; golden 2059104 nonwhite", "S38+", ["docs/maintenance/worklog.md S38"]),
]
apps = []
for i, (title, pkg, status, L, note, sessions, ev) in enumerate(APPS, 1):
    apps.append({"id": f"APP-{i:03d}", "title": title, "package": pkg, "status": status,
                 "checkpoints": dict(L, L7=False), "note": note, "sessions": sessions, "evidence_refs": ev})
json.dump({"schema": "miniandroid.app_registry.v1", "generated": NOW, "status_vocabulary":
           ["VERIFIED", "TESTED", "OBSERVED", "PARTIAL", "BLOCKED", "PENDING", "SUPERSEDED"],
           "checkpoint_law": "L0 APK accepted; L1 runtime executes; L2 lifecycle; L3 view tree; L4 rendering; L5 input; L6 state changes; L7 multi-feature interaction; V visual evidence. Telegram/WhatsApp are honest BLOCKED load frontiers — their frames are NOT renders.",
           "apps": apps}, open("canonical/app_registry.json", "w"), indent=1)

# ---------------------------------------------------------------- 5. evidence waves
waves = []
ev_root = "evidence"
for d in sorted(os.listdir(ev_root)):
    p = os.path.join(ev_root, d)
    if os.path.isdir(p) and not d.startswith("canonical"):
        fns = [f for f in os.listdir(p) if f.lower().endswith((".jpg", ".png", ".json", ".md", ".txt"))]
        waves.append({"wave": d, "files": len(fns)})
eidx = json.load(open("miniandroid/database/EVIDENCE_INDEX.json"))
json.dump({"schema": "miniandroid.evidence_registry.v1", "generated": NOW,
           "law": "Visual evidence: 460px JPG <=100KB, English-only; VERIFIED needs 3-run byte-identical SHA256; blank/grey frames are NOT renders.",
           "canonical_evidence_index": {"total_files": eidx.get("total_files"), "verified_count": eidx.get("verified_count")},
           "waves": waves}, open("canonical/evidence_registry.json", "w"), indent=1)

# ---------------------------------------------------------------- 6. compatibility matrix
def subsystems(cp):
    return {"UI": bool(cp.get("L3")), "Graphics": bool(cp.get("L4")), "Text": bool(cp.get("L4")),
            "Input": bool(cp.get("L5")), "Storage": False, "Network": False, "Audio": False,
            "Video": False, "Native": cp.get("L2") is True and bool(cp.get("L6"))}
matrix = {"schema": "miniandroid.compatibility_matrix.v1", "generated": NOW,
          "apps": [{"id": a["id"], "title": a["title"], "status": a["status"],
                    "checkpoints": a["checkpoints"], "subsystems": subsystems(a["checkpoints"])} for a in apps],
          "games": [{"id": g["id"], "title": g["title"], "status": g["status"],
                     "checkpoints": g["checkpoints"], "subsystems": subsystems(g["checkpoints"])} for g in games]}
json.dump(matrix, open("canonical/compatibility_matrix.json", "w"), indent=1)

# ---------------------------------------------------------------- 7. capability registry + docs
json.dump({"schema": "miniandroid.capability_registry.v1", "generated": NOW,
           "law": "IMPLEMENTED = source inventory hit only. TESTED/VERIFIED require recorded runtime evidence refs. Grep never proves VERIFIED (ROADMAP SS1).",
           "capabilities": cap_rows}, open("canonical/capability_registry.json", "w"), indent=1)

# CAPABILITY_MATRIX.md
with open("docs/CAPABILITY_MATRIX.md", "w") as f:
    f.write(head("CAPABILITY MATRIX — generated from canonical/capability_registry.json"))
    f.write("| Layer | Capabilities | VERIFIED | TESTED | IMPLEMENTED | PENDING |\n|---|---|---|---|---|---|\n")
    for layer in LAYER_ORDER:
        rows = [c for c in cap_rows if c["layer"] == layer]
        f.write(f"| {layer} | {len(rows)} | {sum(c['status']=='VERIFIED' for c in rows)} | {sum(c['status']=='TESTED' for c in rows)} | {sum(c['status']=='IMPLEMENTED' for c in rows)} | {sum(c['status']=='PENDING' for c in rows)} |\n")
    f.write("\n")
    for layer in LAYER_ORDER:
        f.write(f"## {layer}\n\n| ID | Capability | Status | Src hits |\n|---|---|---|---|\n")
        for c in [c for c in cap_rows if c["layer"] == layer]:
            ev = " (+evidence)" if c["evidence"] else ""
            f.write(f"| {c['id']} | {c['name']} | {c['status']}{ev} | {c['src_hits']} |\n")
        f.write("\n")

# ROADMAP_STATUS.md
total_caps = len(cap_rows)
st_counts = Counter(c["status"] for c in cap_rows)
v_games = sum(1 for g in games if g["status"] == "VERIFIED")
partial_games = sum(1 for g in games if g["status"] == "PARTIAL")
blocked_games = sum(1 for g in games if g["status"] == "BLOCKED")
obs_games = sum(1 for g in games if g["status"] == "OBSERVED")
v_apps = sum(1 for a in apps if a["status"] == "VERIFIED")
with open("docs/ROADMAP_STATUS.md", "w") as f:
    f.write(head("ROADMAP STATUS — control panel generated from canonical registries"))
    f.write("## Runtime capability status (computed)\n\n")
    f.write(f"Capabilities tracked: **{total_caps}** — VERIFIED {st_counts['VERIFIED']} · TESTED {st_counts['TESTED']} · IMPLEMENTED {st_counts['IMPLEMENTED']} · PENDING {st_counts['PENDING']}\n\n")
    f.write("| Layer | Tracked | With runtime evidence (V+T) | Source-only | Pending |\n|---|---|---|---|---|\n")
    for layer in LAYER_ORDER:
        rows = [c for c in cap_rows if c["layer"] == layer]
        f.write(f"| {layer} | {len(rows)} | {sum(c['status'] in ('VERIFIED','TESTED') for c in rows)} | {sum(c['status']=='IMPLEMENTED' for c in rows)} | {sum(c['status']=='PENDING' for c in rows)} |\n")
    f.write(f"\n## Titles (computed)\n\n- Games: {len(games)} — VERIFIED {v_games} · PARTIAL {partial_games} · BLOCKED {blocked_games} · OBSERVED {obs_games}\n")
    f.write(f"- Apps: {len(apps)} — VERIFIED {v_apps} · PARTIAL {sum(1 for a in apps if a['status']=='PARTIAL')} · BLOCKED {sum(1 for a in apps if a['status']=='BLOCKED')} · TESTED {sum(1 for a in apps if a['status']=='TESTED')}\n")
    f.write(f"\n## Root causes (projected from root_registry.json)\n\n- Total: {len(roots)} — " + " · ".join(f"{k} {v}" for k, v in sorted(root_stats.items(), key=lambda kv: -kv[1])[:8]) + "\n")
    f.write("\n## Blocked frontiers (honest, NOT renders)\n\n")
    f.write("- Telegram 12.10.1 — grey 3-color frame = NOT A RENDER; SvgHelper themed-icon SVG parsing + gms Api builder nulls\n")
    f.write("- WhatsApp 2.26.38.74 — black/white frame = NOT A RENDER; AppContext.set injection + INVOKE_RETURN null\n")
    f.write("- Dooz v23 (Compose) — 0-error real execution but blank first frame; Recomposer frontier R-NEW-344\n")
    f.write("- Flashlight — SurfaceView family blank (side observation)\n")
    f.write("\n## Highest-fan-out missing capabilities (computed: largest PENDING layers)\n\n")
    pend = sorted(((l, sum(1 for c in cap_rows if c["layer"] == l and c["status"] == "PENDING")) for l in LAYER_ORDER), key=lambda x: -x[1])[:5]
    for l, n in pend:
        f.write(f"- {l}: {n} pending capabilities\n")
    f.write("\n## Load pipeline (the BASE — law, not per-app hacks)\n\n")
    f.write("Every APK runs the same automatic base order (self-knowing: the base decides what loads where):\n\n")
    f.write("1. APK accept + manifest parse (package/activity/theme/action resolve)\n2. DEX parse + class load\n3. framework-res package 0x01 router (ensure_framework_resources) + app ARSC multi-package table\n4. manifest Application bind (AOSP handleBindApplication law)\n5. theme resolve (ThemeEngine: overlay -> base theme -> framework bags)\n6. LayoutInflater inflate (XML attrs > style > defStyleAttr > theme)\n7. measure/layout/draw traversal -> frame capture (SHA256 + pixel metrics)\n8. input dispatch + state probes\n\nAny frame that fails steps 5-7 is reported as a LOAD FRONTIER, never as a render.\n")

print("canonical/ + docs/ generated")
print("caps:", len(cap_rows), dict(Counter(c['status'] for c in cap_rows)))
print("games:", len(games), "apps:", len(apps), "roots:", len(roots))
