#!/usr/bin/env python3
import re
"""S128 MASTER WORKLIST taxonomy — the full 127-category catalog required by the
MASTER BASE COMPLETION campaign. Each category: number, name, subsystem, pipeline layer,
classification regexes, AOSP/upstream reference, existing mature implementation (TOOL-FIRST law).

Layer values = the 19 pipeline nodes: APK DEX RUNTIME APPLICATION ACTIVITY THEME RESOURCES
VIEWTREE LAYOUT TEXT IMAGES DRAWABLE CANVAS SURFACE FRAMEBUFFER SCREENSHOT INPUT STATE REDRAW
(plus NONVISUAL for lifecycle/infra categories; those still map to the nearest node)."""

# (num, name, subsystem, layer, [regex...], aosp_ref, mature_impl)
CATEGORIES = [
 (1,"APK / ZIP / package loading","PACKAGING","APK",[r"\bapk\b.*accept","zip.*central","zip.*entry","apk.*layout","v1/v2"], "AOSP frameworks/base ApkInputs.java / ApkSignatureVerifier; libziparchive (ZipArchive.h)", "libziparchive (AOSP), minizip"),
 (2,"Manifest","PACKAGING","APK",[r"\bmanifest"], "AOSP frameworks/base AssetManager2 + ApkParser (manifest binary XML); frameworks/base/core/res AndroidManifest", "AOSP aapt2 dump, ApkParser"),
 (3,"PackageManager","PACKAGING","APK",[r"packagemanager","getPackageArchive"], "AOSP frameworks/base PackageManagerService / PackageParser2", "PackageParser2 (ApexServiceImpl)"),
 (4,"Resources.arsc / ARSC","RESOURCES","RESOURCES",[r"\barsc","restable","res_table","chunk","stringpool","string pool","compact.*entr","entry.*compact"], "AOSP frameworks/base/libs/androidfw include/androidfw/ResourceTypes.h (ResTable_entry::Compact law)", "androidfw (AOSP)"),
 (5,"Resource IDs","RESOURCES","RESOURCES",[r"resource.*id","\bid\b.*res","0x01.*package","package.*0x01","identifier"], "AOSP androidfw ResTable_package id routing; aapt2 compile id assignment", "androidfw"),
 (6,"Resource qualifiers","RESOURCES","RESOURCES",[r"qualifier","locale","-en","-hdpi","config.*matrix","configuration.*match"], "AOSP androidfw AssetManager2::FindEntry with ResTable_config match", "androidfw"),
 (7,"Framework resources","RESOURCES","RESOURCES",[r"framework.res","framework.res","framework_resources","ensure_framework","0x01 router"], "AOSP framework-res.apk + androidfw package 0x01 routing", "framework-res.apk (verified byte/CRC)"),
 (8,"Drawable resources","RESOURCES","DRAWABLE",[r"drawable","statelist","layer.list","inset","ripple","shape.*drawable","nine.?patch","ninepatch"], "AOSP frameworks/base graphics drawable/ (StateListDrawable, LayerDrawable, InsetDrawable, RippleDrawable)", "AOSP drawable classes; Skia for bitmap backing"),
 (9,"ColorStateList","RESOURCES","DRAWABLE",[r"colorstatelist","color_state","\bcsl\b","primary_text","bright_foreground"], "AOSP android.content.res.ColorStateList + frameworks/base ResTable_color + res/color/*.xml", "AOSP ColorStateList"),
 (10,"XML resources","RESOURCES","RESOURCES",[r"\bxml\b.*resource","xml.*parser","binary xml","axml"], "AOSP androidfw ResXMLTree / XmlBlock", "androidfw ResXMLTree"),
 (11,"Theme","RESOURCES","THEME",[r"\btheme","themeengine","splash.*theme","activity.*theme","default.*theme","s68"], "AOSP AssetManager2 Theme::ApplyStyle + Themes.java (device default overlays)", "androidfw Theme; AppCompat ThemeOverlay"),
 (12,"Style","RESOURCES","THEME",[r"\bstyle","styleable"], "AOSP R.styleable bags; TypedArray obtainStyledAttributes", "androidfw style bags"),
 (13,"Attribute resolution","RESOURCES","THEME",[r"attr.*resol","resolve.*attr",r"\?attr","obtainstyledattr","typedarray"], "AOSP AssetManager2::ResolveAttribute + AttributeResolution.cpp (Token/defStyleAttr precedence)", "androidfw AttributeResolution"),
 (14,"defStyleAttr / defStyleRes","RESOURCES","THEME",[r"defstyleattr","defstyleres"], "AOSP AttributeResolution11/13/14 (defStyleAttr tier, defStyleRes tier)", "androidfw"),
 (15,"Configuration","RESOURCES","RESOURCES",[r"configuration","\bconfig\b","orientation","uimode"], "AOSP ResTable_config; Configuration.java", "androidfw"),
 (16,"Density / dp / sp","RESOURCES","RESOURCES",[r"density","\bdp\b","\bsp\b","displaymetrics","scaledensity"], "AOSP DisplayMetricsDensity; TypedValue.applyDimension COMPLEX_UNIT law", "androidfw"),
 (17,"DEX parsing","EXECUTION","DEX",[r"\bdex\b.*pars","dex.*header","dex.*map","dex.*verify","dex.*checksum"], "AOSP art/libdexfile (DexFileVerifier, DexFile struct laws)", "art libdexfile; dexdump"),
 (18,"DEX execution","EXECUTION","DEX",[r"dex.*exec","interpreter.*opcode","bytecode","dalvik","opcode","instruction.*trace"], "AOSP art/runtime/interpreter/interpreter_switch.cc (mterp semantics)", "ART interpreter"),
 (19,"Class loading","EXECUTION","DEX",[r"class.*load","classloader","clinit","class.*link","class.*resolve"], "AOSP art/runtime/class_linker.cc", "ART ClassLinker"),
 (20,"ART / Dalvik semantics","EXECUTION","DEX",[r"art\b","dalvik.*semant","check.?cast","invoke.*virtual","verifier.*equiv"], "AOSP ART runtime semantics docs + interpreter", "ART"),
 (21,"Java / Kotlin runtime","EXECUTION","DEX",[r"\bkotlinx?\b","coroutine","recomposer","scattermap","copyonwrite","hilt","dagger",r"java\.lang",r"java\.util","string\.format","long.*bridge"], "OpenJDK java.* ; Kotlin stdlib source; kotlinx.coroutines", "OpenJDK (libcore), Kotlin stdlib"),
 (22,"libcore","EXECUTION","DEX",[r"\blibcore\b","concurrent","collections","optional","stream"], "AOSP libcore (OpenJDK derivative)", "OpenJDK/AOSP libcore"),
 (23,"Application lifecycle","LIFECYCLE","APPLICATION",[r"application.*lifecycle","handlebindapplication","application.*attach","oncreate.*application","application.*bind"], "AOSP ActivityThread.handleBindApplication / LoadedApk", "ActivityThread"),
 (24,"Activity lifecycle","LIFECYCLE","ACTIVITY",[r"activity.*lifecycle","activity.*create","onresume","onpause","activitythread","instrumentation","activity.*state"], "AOSP ActivityThread.performLaunchActivity -> Instrumentation.callActivityOnCreate", "ActivityThread"),
 (25,"Fragment/lifecycle infrastructure","LIFECYCLE","ACTIVITY",[r"fragment"], "androidx.fragment FragmentActivity/FragmentController", "androidx.fragment"),
 (26,"Intent","LIFECYCLE","APPLICATION",[r"\bintent"], "AOSP android.content.Intent + ActivityThread Intent resolution", "AOSP"),
 (27,"Component resolution","LIFECYCLE","APPLICATION",[r"component.*resol","activity.*action","main.*activity","resolve.*activity","category"], "AOSP AndroidManifest activity/action/category matching", "AOSP"),
 (28,"Context","LIFECYCLE","APPLICATION",[r"\bcontext\b","appcontext","getapplicationcontext","basecontext"], "AOSP ContextImpl / Application / ContextWrapper law", "AOSP ContextImpl"),
 (29,"Service","LIFECYCLE","APPLICATION",[r"\bservice\b.*launch","service.*lifecycle","onstartcommand","startforeground","service.*oncreate"], "AOSP ActivityThread handleCreateService / handleStartService", "ActivityThread"),
 (30,"BroadcastReceiver","LIFECYCLE","APPLICATION",[r"broadcast","receiver"], "AOSP LoadedApk ReceiverDispatcher; registerReceiver law", "AOSP"),
 (31,"ContentProvider","LIFECYCLE","APPLICATION",[r"contentprovider","contentresolver"], "AOSP ActivityThread installContentProviders", "AOSP"),
 (32,"Handler","THREADING","RUNTIME",[r"\bhandler\b","handler.*createasync","handlerthread"], "AOSP android.os.Handler (createAsync singleton law)", "AOSP Handler/Looper"),
 (33,"Looper","THREADING","RUNTIME",[r"\blooper\b"], "AOSP android.os.Looper (prepare/main loop)", "AOSP"),
 (34,"MessageQueue","THREADING","RUNTIME",[r"messagequeue","enqueue","idlehandler","sync barrier","sync.*barrier",r"next\(\)"], "AOSP android.os.MessageQueue (enqueue order, barriers, IdleHandler, quit)", "AOSP"),
 (35,"Threading","THREADING","RUNTIME",[r"\bthread\b","synchronized","monitor","reentrant","executor"], "AOSP ART monitor + libcore java.util.concurrent", "libcore"),
 (36,"synchronization/concurrency","THREADING","RUNTIME",[r"synchroniz","monitor.*owner","lock","wait.*notify","reentrantlock","concurrent.*map","atomic"], "ART monitor.cc; libcore/juc", "libcore j.u.c"),
 (37,"View","UI","VIEWTREE",[r"\bview\b(?!.*group)","view.*focus","view.*measure(?!.*layout)","onmeasure","view.*draw(?!able)"], "AOSP frameworks/base core/java/android/view/View.java", "AOSP View; ViewRootImpl"),
 (38,"ViewGroup","UI","VIEWTREE",[r"viewgroup","child.*count","getchildat","addview"], "AOSP ViewGroup.java (dispatchDraw/measure children)", "AOSP ViewGroup"),
 (39,"LayoutInflater","INFLATION","VIEWTREE",[r"layoutinflater","inflat"], "AOSP LayoutInflater + LayoutInflaterFactory2 (precedence law)", "AOSP LayoutInflater"),
 (40,"XML inflation","INFLATION","VIEWTREE",[r"\binflat.*xml","createview","factory2"], "AOSP LayoutInflater.createViewFromTag", "AOSP"),
 (41,"measure/layout","UI","LAYOUT",[r"measure.*layout","layout.*pass","onlayout","framelayout","linearlayout.*layout","relativelayout","gravity"], "AOSP ViewRootImpl performTraversals; LinearLayout/FrameLayout onLayout", "AOSP"),
 (42,"onSizeChanged","UI","LAYOUT",[r"onsizechanged","size.*changed"], "AOSP View.setFrame -> onSizeChanged", "AOSP"),
 (43,"ViewTree","UI","VIEWTREE",[r"viewtree","view.*tree","decorview.*tree","traversal","view.*hierarchy"], "AOSP ViewRootImpl + DecorView traversal", "AOSP"),
 (44,"TextView","UI","TEXT",[r"textview","settext","text.*color","text.*size"], "AOSP TextView + Layout (DynamicLayout/StaticLayout)", "AOSP TextView"),
 (45,"EditText","UI","TEXT",[r"edittext"], "AOSP EditText + Editable", "AOSP"),
 (46,"Button","UI","VIEWTREE",[r"\bbutton\b"], "AOSP Button + CompoundButton", "AOSP"),
 (47,"ImageView","UI","IMAGES",[r"imageview","scale.?type"], "AOSP ImageView (scaleType geometry matrix)", "AOSP"),
 (48,"Recycler/List infrastructure","UI","VIEWTREE",[r"recycler","listview","gridview","adapterview","collectionview","adapter"], "AOSP AbsListView/RecyclerView (androidx)", "androidx.recyclerview"),
 (49,"scrolling","UI","STATE",[r"scroll","fling","over.?scroll","edgeeffect","nested"], "AOSP View scrollBy/computeScroll; EdgeEffect; OverScroller", "AOSP"),
 (50,"focus","UI","INPUT",[r"focus"], "AOSP View focus search + FocusFinder", "AOSP"),
 (51,"keyboard/input method","INPUT","INPUT",[r"keyboard","\bime\b","input.*method","key.*event","onkey"], "AOSP InputMethodManager + KeyEvent dispatch", "AOSP"),
 (52,"MotionEvent","INPUT","INPUT",[r"motionevent","pointer","touch.*event"], "AOSP android.view.MotionEvent (pointer id law)", "AOSP"),
 (53,"touch dispatch","INPUT","INPUT",[r"touch.*dispatch","dispatchtouch","ontouch","clickfn","touch.*pipeline","touch.*target","intercepttouch","touchdelegate"], "AOSP ViewGroup.dispatchTouchEvent + TouchTarget law", "AOSP"),
 (54,"gestures","INPUT","INPUT",[r"gesture","gesturedetector","velocitytracker"], "AOSP GestureDetector / VelocityTracker", "AOSP"),
 (55,"click/long-click","INPUT","INPUT",[r"click","long.?click","performclick"], "AOSP View.performClick / CheckForTap", "AOSP"),
 (56,"key events","INPUT","INPUT",[r"keyevent","onkey","dispatchkey"], "AOSP KeyEvent + ViewRootImpl dispatchKey", "AOSP"),
 (57,"state changes","UI","STATE",[r"state.*change","drawable.*state","pressed.*state","state probe"], "AOSP drawable state + View drawableStateChanged", "AOSP"),
 (58,"invalidate/requestLayout","UI","STATE",[r"invalidate","requestlayout","propagat.*inval"], "AOSP ViewRootImpl invalidate child -> dirty region propagation", "AOSP"),
 (59,"redraw/recomposition","RENDERING","REDRAW",[r"redraw","recompos","recompose","choreographer","frame.*schedul","monotonicframeclock"], "AOSP Choreographer + androidx Compose Recomposer/MonotonicFrameClock", "AOSP Choreographer; androidx compose runtime"),
 (60,"Window","WINDOW","FRAMEBUFFER",[r"\bwindow\b","windowmanager.*view","window.*background","decor"], "AOSP ViewRootImpl + Window (windowBackground resolution)", "AOSP"),
 (61,"WindowManager","WINDOW","FRAMEBUFFER",[r"windowmanager"], "AOSP WindowManagerImpl/Global", "AOSP"),
 (62,"DecorView","WINDOW","FRAMEBUFFER",[r"decorview"], "AOSP DecorView + PhoneWindow generateLayout", "AOSP"),
 (63,"Insets","WINDOW","FRAMEBUFFER",[r"insets","system.*bar","status.*bar"], "AOSP WindowInsets (incl. shadows ROOT-059)", "AOSP"),
 (64,"Canvas","RENDERING","CANVAS",[r"\bcanvas\b","draw.*call","clip.*rect","canvas.*state","skia.*canvas"], "AOSP frameworks/base graphics Canvas.cpp + Skia SkCanvas", "Skia (SkCanvas)"),
 (65,"Paint","RENDERING","CANVAS",[r"\bpaint\b","paint.*flag","stroke.*cap","stroke.*join","filterflag"], "AOSP Paint.cpp + SkPaint", "Skia"),
 (66,"Path","RENDERING","CANVAS",[r"\bpath\b","patheffect"], "AOSP Path.cpp + SkPath", "Skia SkPath"),
 (67,"Bitmap","RENDERING","CANVAS",[r"\bbitmap\b","pixelref","premult"], "AOSP Bitmap.cpp + SkBitmap (premultiplied law)", "Skia"),
 (68,"Drawable rendering","RENDERING","DRAWABLE",[r"drawable.*render","draw.*drawable","drawable.*bounds","drawable.*hotspot"], "AOSP Drawable.draw(bounds) law", "AOSP"),
 (69,"PNG","MEDIA","IMAGES",[r"\bpng\b"], "AOSP libpng integration + BitmapFactory", "libpng / Skia PNG"),
 (70,"JPEG","MEDIA","IMAGES",[r"jpe?g"], "AOSP libjpeg-turbo + BitmapFactory", "libjpeg-turbo"),
 (71,"WebP","MEDIA","IMAGES",[r"webp"], "AOSP libwebp (verified present in repo)", "libwebp"),
 (72,"GIF","MEDIA","IMAGES",[r"\bgif\b"], "AOSP AnimatedImageDrawable + giflib", "giflib / Skia"),
 (73,"SVG","MEDIA","IMAGES",[r"\bsvg\b","svghelper","vector.*path.*svg"], "AOSP VectorDrawable (native SVG-like); AndroidSvg (upstream)", "rlottie (tools/rlottie present); androidsvg"),
 (74,"fonts","TEXT","TEXT",[r"\bfont\b","typeface","ttf","otf","system.*font"], "AOSP fonts.xml + FontFamily; minikin", "FreeType"),
 (75,"FreeType","TEXT","TEXT",[r"freetype"], "upstream FreeType (verified integrated)", "FreeType"),
 (76,"HarfBuzz","TEXT","TEXT",[r"harfbuzz","shap"], "upstream HarfBuzz (AOSP minikin uses HarfBuzz)", "HarfBuzz"),
 (77,"text shaping","TEXT","TEXT",[r"shaping","shaper","complex.*script","\brtl\b","bidi","letter.?spacing","tab.*handl"], "AOSP minikin Layout.cpp (bidi + shaping)", "HarfBuzz + ICU"),
 (78,"text measurement","TEXT","TEXT",[r"measure.*text","text.*width","line.*break","break.*text","ellipsize"], "AOSP minikin + StaticLayout line breaking", "ICU line breaking"),
 (79,"anti-aliasing/rendering","RENDERING","CANVAS",[r"anti.?alias","\baa\b","subpixel","hint"], "Skia AA laws (SkPaint kAntiAlias)", "Skia"),
 (80,"software graphics","RENDERING","CANVAS",[r"software.*render","raster","pixel.*pipe","blend"], "Skia raster pipeline", "Skia"),
 (81,"Surface","WINDOW","SURFACE",[r"\bsurface\b(?!view)","surface.*lock","hardware.*buffer"], "AOSP Surface/SurfaceControl + BufferQueue", "AOSP BufferQueue"),
 (82,"SurfaceView","WINDOW","SURFACE",[r"surfaceview","flashlight","surface.*holder"], "AOSP SurfaceView + SurfaceHolder.lockCanvas law", "AOSP"),
 (83,"lockCanvas","RENDERING","SURFACE",[r"lockcanvas","unlockcanvas"], "AOSP Surface.lockCanvas (software canvas on a buffer)", "AOSP"),
 (84,"framebuffer","RENDERING","FRAMEBUFFER",[r"framebuffer","\bfb\b","window.*buffer","backbuffer"], "AOSP FramebufferNativeWindow (legacy) / BufferQueue", "AOSP"),
 (85,"screenshot","EVIDENCE","SCREENSHOT",[r"screenshot","capture.*frame","frame.*capture","sha256.*frame","pixel.*metric"], "project evidence law (SS5-22); AOSP screenrecord analogy", "project pipeline"),
 (86,"pixel provenance","EVIDENCE","SCREENSHOT",[r"provenance"], "project SS pixel-provenance chain", "project pipeline"),
 (87,"graphics state","RENDERING","CANVAS",[r"graphics.*state","save.*layer","clip.*stack","matrix.*canvas","canvas.*restore"], "SkCanvas save/restore/clip-stack/matrix law", "Skia"),
 (88,"animation","RENDERING","STATE",[r"animat","interpolator","valueanimator","animation.*clock","animator"], "AOSP android.view.animation + ValueAnimator (clock law)", "AOSP"),
 (89,"timing/frame scheduling","RENDERING","STATE",[r"frame.*clock","choreographer.*schedul","v?sync","tick.*drift","timestep"], "AOSP Choreographer frame clock; SurfaceFlinger vsync", "AOSP"),
 (90,"audio","MEDIA","RUNTIME",[r"\baudio\b","soundpool","mediaplayer.*audio","audiofocus","audiorecord","audiotrack"], "AAudio/OpenSL ES (AOSP); libmedia", "OpenSL ES / SDL2 audio"),
 (91,"video","MEDIA","RUNTIME",[r"\bvideo\b","mediacodec","mediaextractor","video.*decode","surface.*output"], "AOSP MediaCodec/MediaExtractor + stagefright", "FFmpeg (decoders), libstagefright"),
 (92,"image/video codecs","MEDIA","RUNTIME",[r"codec","decoder.*media"], "AOSP stagefright codecs", "FFmpeg"),
 (93,"multimedia","MEDIA","RUNTIME",[r"multimedia","media.*framework"], "AOSP media framework", "FFmpeg + SDL2"),
 (94,"WebView","WEB","RUNTIME",[r"webview","quickjs","javascript.*bridge"], "upstream WebView engines; quickjs for JS", "Chromium/WebView (FORBIDDEN to rewrite); quickjs present"),
 (95,"HTML","WEB","RUNTIME",[r"\bhtml\b"], "HTML spec; upstream engines", "FORBIDDEN to rewrite browser — reuse Chromium/WebKit/WPE/Servo"),
 (96,"CSS","WEB","RUNTIME",[r"\bcss\b"], "CSS spec; upstream engines", "same"),
 (97,"JavaScript","WEB","RUNTIME",[r"javascript","\bjs\b","ecmascript"], "ECMA-262; quickjs (integrated)", "quickjs"),
 (98,"browser/HTML5 engine integration","WEB","RUNTIME",[r"browser.*engine","html5.*engine","chromium","webkit","gecko","servo","wpe"], "upstream engine embedding docs", "Chromium/WebKit/Gecko/Servo/WPE candidates"),
 (99,"Compose","UI","REDRAW",[r"compose","recomposer","composition","monotonicframe"], "androidx.compose.runtime (Recomposer, ControlledComposition, Snapshot)", "androidx compose runtime"),
 (100,"AndroidX","UI","VIEWTREE",[r"androidx","appcompat.*widget","constraintlayout","viewpager","drawer","speeddial","swiperefresh"], "androidx source (upstream)", "androidx AARs"),
 (101,"support libraries","UI","VIEWTREE",[r"support.*library","v4","v7"], "legacy support libs -> androidx", "androidx"),
 (102,"AppCompat","UI","THEME",[r"appcompat","decor.?toolbar"], "androidx.appcompat (decor-toolbar family F-NEW-170)", "androidx.appcompat"),
 (103,"Material","UI","THEME",[r"material"], "com.google.android.material", "material-components"),
 (104,"SQLite","STORAGE","RUNTIME",[r"sqlite","\bcursor\b.*database","database.*lifecycle","sqlitedatabase"], "AOSP SQLite integration (android.database.sqlite)", "sqlite3 (upstream)"),
 (105,"files","STORAGE","RUNTIME",[r"\bfile\b.*storage","file.*dir","openfileoutput"], "AOSP Context file APIs", "AOSP"),
 (106,"cache","STORAGE","RUNTIME",[r"\bcache\b"], "AOSP context.getCacheDir law", "AOSP"),
 (107,"external storage","STORAGE","RUNTIME",[r"external.*storage","sdcard"], "AOSP Environment.getExternalStorageDirectory", "AOSP"),
 (108,"permissions","STORAGE","RUNTIME",[r"permission"], "AOSP PackageManager permission grant model", "AOSP"),
 (109,"networking","NETWORK","RUNTIME",[r"network","httpurlconnection","okhttp"], "AOSP/conscrypt + OkHttp (upstream)", "OkHttp; libcore net"),
 (110,"sockets/HTTP","NETWORK","RUNTIME",[r"socket","http"], "libcore socket/HTTP stack", "libcore; OkHttp"),
 (111,"JNI","NATIVE","RUNTIME",[r"\bjni\b","jni_bridge","native.*bridge","system.loadlibrary","loadlibrary"], "AOSP ART JNI (jni_internal)", "ART JNI"),
 (112,"native libraries","NATIVE","RUNTIME",[r"native.*lib",r"\.so\b","linker"], "AOSP linkerconfig + ReLinker (upstream)", "AOSP linker"),
 (113,"GMS boundary","GMS","RUNTIME",[r"\bgms\b","google.*service","play.*service","firebase"], "GMS is OUT of AOSP — boundary stubs with honest NOT-A-RENDER labels", "microG (upstream boundary reference)"),
 (114,"OpenGL / graphics APIs","RENDERING","SURFACE",[r"\bgl\b","opengl","egl","gdx","glsurface"], "AOSP EGL/OpenGL ES + EGLContext laws", "Mesa/angle upstream (reference)"),
 (115,"game loop","GAME","STATE",[r"game.*loop","game.*thread"], "AOSP Game SDK / SurfaceView loop laws; GameLoop patterns", "AOSP Game SDK"),
 (116,"game input","GAME","INPUT",[r"game.*input","driver.*input","autoplay"], "project input pipeline laws", "project"),
 (117,"game rendering","GAME","RENDERING",[r"game.*render","sprite"], "SurfaceView/Canvas game render laws", "Skia"),
 (118,"complex games","GAME","STATE",[r"complex.*game","minicraft","libgdx","surge","thextech"], "upstream game engines", "libGDX/Surge/TheXTech upstreams"),
 (119,"Telegram frontier","FRONTIER","VIEWTREE",[r"telegram"], "Telegram upstream source (github.com/DrKLO/Telegram)", "Telegram upstream; SvgHelper needs SVG engine"),
 (120,"WhatsApp frontier","FRONTIER","VIEWTREE",[r"whatsapp"], "WhatsApp (closed; boundary = AppContext.set injection law)", "N/A closed-source; generic Context laws only"),
 (121,"200-title corpus","CORPUS","APK",[r"corpus","cluster.*fail","200.?title","battery"], "project corpus law (CORPUS->CLUSTER->ROOT FIX->RETEST)", "project"),
 (122,"blank/grey/white/black clustering","CORPUS","SCREENSHOT",[r"blank","grey.*frame","gray.*frame","white.*frame","black.*frame","not.?a.?render"], "project honest-frame law", "project"),
 (123,"regression infrastructure","INFRA","SCREENSHOT",[r"regression","golden","battery.*gate","3.?run","ladder","g0.?g11"], "project SS regression law + golden ladder G0-G11", "project"),
 (124,"golden ladder","INFRA","SCREENSHOT",[r"golden ladder","ladder"], "G0-G11 ladder law", "project"),
 (125,"evidence/provenance infrastructure","INFRA","SCREENSHOT",[r"evidence.*infra","evidence.*registry","evidence wave"], "project evidence law", "project"),
 (126,"documentation/registry consistency","INFRA","APK",[r"registry","document","reconcil","canonical","worklist"], "project control system law (S125)", "project"),
 (127,"build/toolchain/bootstrap reliability","INFRA","APK",[r"toolchain","makefile","\bmake\b","build.*restore","bootstrap",r"\.o\b.*link"], "project build law (S126 toolchain restore)", "project"),
 (128,"security/sandbox/keystore/TLS boundary","SECURITY","RUNTIME",[r"keystore","tls","crypto provider","sandbox","seccomp","security","mem-map","seccomp","fortify","hardening"], "AOSP security docs + keystore2 (boundary)", "BoringSSL (boundary; reuse-only)"),
 (129,"IPC/Binder/Parcel boundary","IPC","RUNTIME",[r"\bbinder\b","parcel","transaction.*aidl","uri grant"], "AOSP Binder (libbinder) — out of process substrate; boundary law", "libbinder (boundary reference)"),
]

# Secondary disambiguation pass (probe codes + terse registry idioms).
SECONDARY = [
 (34,[r"\bmq-?\d"]), (36,[r"\blk-?\d"]), (58,[r"\bui-?\d"]),
 (123,[r"fuzz","tooling class","differential harness","hostile corpus","adversarial","confusion corpus"]),
 (64,[r"renderer clip","alpha","draw order","layer law","z law","rounding","min-law","bounds law","parent law","transform"]),
 (8,[r"state_list","state ?list"]),
 (112,[r"elf loader","native sandbox","native parser","oom","native mem"]),
 (129,[r"binder","parcel","uri grant"]),
 (128,[r"keystore","tls","crypto","sandbox"]),
 (19,[r"reflection","access law","visibility law","synthetic","bridge","classloader","noclassdef","dynamic load","multi-dex","in-memory dex","metadata parser","resource-shrunk","dynamic dex","isolation"]),
 (35,[r"interrupt","sleep/wait","ie propagation","thread"]),
 (22,[r"covariant","arraystore"]),
 (17,[r"dex trace","dex"]),
 (81,[r"frame submission","renderthread"]),
 (110,[r"scheme matrix"]),
 (58,[r"invali?dat"]),
 (9,[r"color\(","color law","argb"]),
]

# Pipeline node mapping for the 19-node visual roadmap -> categories
NODE_CATS = {
 "APK":[1,2,3,121,126,127], "DEX":[17,18,19,20], "RUNTIME":[21,22,111,112,113,32,33,34,35,36,90,91,92,93,94,95,96,97,98,104,105,106,107,108,109,110],
 "APPLICATION":[23,26,27,28,29,30,31], "ACTIVITY":[24,25],
 "THEME":[11,12,13,14,102,103], "RESOURCES":[4,5,6,7,10,15,16],
 "VIEWTREE":[37,38,39,40,43,46,48,99,100,101], "LAYOUT":[41,42],
 "TEXT":[44,45,74,75,76,77,78], "IMAGES":[47,69,70,71,72,73],
 "DRAWABLE":[8,9,68], "CANVAS":[64,65,66,67,79,80,87],
 "SURFACE":[81,82,83,114], "FRAMEBUFFER":[60,61,62,63,84],
 "SCREENSHOT":[85,86,122], "INPUT":[50,51,52,53,54,55,56,116],
 "STATE":[49,57,58,88,89,115], "REDRAW":[59],
}

def classify(text):
    """Return (cat_num, matched) for a text blob; best match = longest pattern hit, else None."""
    t = (text or "").lower()
    best, best_len = None, 0
    for (num, name, sub, layer, pats, aosp, impl) in CATEGORIES:
        for p in pats:
            if re.search(p, t):
                if len(p) > best_len:
                    best, best_len = num, len(p)
    if best is None:
        for num, pats in SECONDARY:
            for p in pats:
                if re.search(p, t):
                    return num
    return best
