#!/usr/bin/env python3
"""s131_m16_webview_decision.py — M-16 TOOL-FIRST decision record (law §6 HTML5
"especially important" + §9 high-leverage test + §14 order).

Verdict computed from the MEASURED baseline (not opinion):
  * current engine: src/webview 7,410 LOC (html_dom + canvas2d +
    webview_engine over vendored QuickJS 2024-01-13, JS_Eval/JS_Call wired)
  * S114 HTML5 battery: blockbuster(start+game), mykanji, accelerace,
    sokoban, breakout — real APKs, pixel-verified (battery stage set)
Decision: STAGED REUSE — QuickJS stays (already the substrate); document-class
WebView layout is the litehtml trigger, gated on a measured APK case (law §10:
corpus-driven). No new hand-written DOM/CSS layout code before that trigger.
"""
import json

D = {
    "schema": "m16_webview_decision/1 (S131 REUSE-FIRST LAW §6/§9/§14)",
    "mandate": "M-16 (P0): WebView/HTML5 engine TOOL-FIRST decision",
    "measured_baseline": {
        "engine_loc": 7410,
        "engine_files": ["src/webview/html_dom.{h,cpp}", "src/webview/canvas2d.{h,cpp}", "src/webview/webview_engine.{h,cpp}"],
        "js_engine": "QuickJS 2024-01-13 (vendored, ADOPTED_VENDORED, JS_Eval/JS_Call wired at webview_engine.cpp L220/L2050/L2179)",
        "html5_battery": "S114: blockbuster(start+game), mykanji, accelerace, sokoban, breakout — real APK runs with pixel gates, part of the 124-stage battery (ALL PASS at S131)",
        "regression_gate": "scripts/test/run_test_battery.sh (124 stages, zero FAIL at S131)",
    },
    "candidates_compared": [
        {"id": "current", "what": "hand-rolled html_dom + canvas2d + QuickJS", "verdict": "KEEP for canvas-game-class WebViews (measured: S114 battery)"},
        {"id": "quickjs", "what": "JS engine", "verdict": "ALREADY THE SUBSTRATE — never replace (law §6 JavaScript)"},
        {"id": "litehtml", "what": "HTML4/5 + CSS2.1/3-subset layout, ~30k LOC C++, BSD-3, no JS", "verdict": "ADOPT-TRIGGER: document-class WebView rendering (measured APK case required first)"},
        {"id": "lexbor", "what": "WHATWG HTML5 parser, ~100k LOC C, Apache-2.0", "verdict": "FALLBACK: if litehtml parser subset proves insufficient"},
        {"id": "chromium_webkit_servo", "what": "full engines", "verdict": "REJECTED for now — leverage not yet measured (law §11: large accepted only for massive measured coverage)"},
    ],
    "high_leverage_test": {
        "roots_in_cluster": "MC-094 WebView 12 + MC-095 HTML 1 + MC-097 JavaScript 1 + MC-098 1",
        "if_litehtml_integrated": "document-class layout roots close as a family; canvas-game class already closed by S114 battery",
        "if_current_engine_extended_by_hand": "FORBIDDEN by this decision before the litehtml trigger fires",
    },
    "decision": ("STAGED REUSE. (1) QuickJS remains the JS substrate. (2) The "
                 "S114-proven canvas2d pipeline remains the game-class WebView "
                 "path. (3) litehtml is the PRE-APPROVED component for "
                 "document-class layout — integrate when a corpus APK "
                 "measurably fails on DOM/CSS layout (not on JS/canvas), per "
                 "law §10 corpus-driven reuse. (4) Any new hand-written "
                 "DOM/CSS layout code before that trigger violates M-16."),
    "trigger_evidence_template": ("APK id + failing frame + DOM/CSS trace "
                                  "(--dump-api-trace) + why html_dom cannot "
                                  "serve it + litehtml adapter plan"),
}
import os
os.makedirs("/home/z/my-project/canonical", exist_ok=True)
with open("/home/z/my-project/canonical/m16_webview_decision.json", "w") as f:
    json.dump(D, f, indent=1)

L = []
L.append("# M-16 WEBVIEW/HTML5 ENGINE — TOOL-FIRST DECISION RECORD (S131)")
L.append("")
L.append("> GENERATED by `scripts/s131_m16_webview_decision.py` — machine twin:")
L.append("> `canonical/m16_webview_decision.json`. Law: REUSE-FIRST (§6 HTML5")
L.append("> 'especially important', §9 high-leverage test, §10 corpus-driven, §14).")
L.append("")
L.append("## Measured baseline (evidence, not opinion)")
L.append("")
L.append("| FACT | VALUE |")
L.append("|---|---|")
L.append("| Engine size | 7,410 LOC (html_dom + canvas2d + webview_engine) |")
L.append("| JS substrate | QuickJS 2024-01-13 vendored + wired (JS_Eval/JS_Call) |")
L.append("| HTML5 proof | S114 battery: blockbuster(start+game), mykanji, accelerace, sokoban, breakout — real APKs, pixel gates, inside the 124-stage battery (ALL PASS) |")
L.append("")
L.append("## Candidates")
L.append("")
L.append("| CANDIDATE | WHAT | VERDICT |")
L.append("|---|---|---|")
for c in D["candidates_compared"]:
    L.append(f"| {c['id']} | {c['what']} | {c['verdict']} |")
L.append("")
L.append("## DECISION — STAGED REUSE")
L.append("")
L.append(D["decision"])
L.append("")
L.append("## High-leverage test (§9)")
L.append("")
L.append(f"- Cluster size: {D['high_leverage_test']['roots_in_cluster']}")
L.append(f"- {D['high_leverage_test']['if_litehtml_integrated']}")
L.append(f"- {D['high_leverage_test']['if_current_engine_extended_by_hand']}")
L.append("")
L.append("## Trigger evidence template (§10)")
L.append("")
L.append(D["trigger_evidence_template"])
L.append("")
with open("/home/z/my-project/docs/REUSE_DECISION_WEBVIEW_M16.md", "w") as f:
    f.write("\n".join(L))
print("M-16 decision record: canonical/m16_webview_decision.json + docs/REUSE_DECISION_WEBVIEW_M16.md")
