"""S74 canonical knowledge records (Layer C) — VERIFIED laws + honest open/open-
frontier records + the preserved Dooz false-claim supersession (taskbook §68).
Statuses per taskbook §15: RAW/CANDIDATE/RESEARCHED/OBSERVED/TESTED/VERIFIED/
SUPERSEDED/REJECTED. Only VERIFIED records are canonical semantic laws."""

LAWS = {
    "LAW-MUTF8": {
        "title": "MUTF-8 string encoding in DEX", "domain": "dex", "scope": "generic",
        "statement": "DEX strings use modified UTF-8 (NUL as 0xC0 0x80, surrogate pairs for astral planes); decoding must reproduce exact UTF-16 semantics for constant-pool fidelity.",
        "status": "VERIFIED",
        "source": {"origin": "Dalvik executable format spec / ART", "file": "dex string table decoder in MiniAndroid DEX parser"},
        "test": "battery string stages; corpus-wide constant-string rendering (helloworld app-computed hash)",
        "consumers": ["helloworld", "androidgamesnake", "dooz", "telegram"],
        "issues": [], "capabilities": ["cap-apk-pipeline"],
        "first_discovered": "early DEX era", "last_verified": "S73 (corpus re-run)",
    },
    "LAW-THROW-DEFERRED": {
        "title": "Deferred throw semantics in the interpreter", "domain": "interpreter", "scope": "generic",
        "statement": "Pending exceptions are thrown at the law-governed boundary (not mid-basic-block), matching ART ordering; premature or dropped throws corrupt app control flow.",
        "status": "VERIFIED",
        "source": {"origin": "ART interpreter", "file": "dalvik_engine.cpp throw handling"},
        "test": "battery exception stages; dooz lifecycle reaching onStart/onResume",
        "consumers": ["dooz", "gmdice"],
        "issues": [], "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "interpreter era", "last_verified": "S73",
    },
    "LAW-BOXED-READERS": {
        "title": "Boxed property-reader family (closed with F-141 wave)", "domain": "interpreter", "scope": "generic",
        "statement": "Boxed reader methods must produce non-null receivers per java.lang contract; silent null returns were a null-producer family closed alongside F-141.",
        "status": "VERIFIED",
        "source": {"origin": "OpenJDK/Kotlin stdlib compiled forms", "file": "S72-W3 null-producer closure (commit 048b0e31)"},
        "test": "fixtures 25/25 f141-throws=0", "consumers": ["dooz", "gmdice"],
        "issues": [14], "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "S72-W3", "last_verified": "S73",
    },
    "LAW-FRAGMENTMANAGER-SUBSET": {
        "title": "FragmentManager guarded subset", "domain": "androidx", "scope": "generic",
        "statement": "The exercised FragmentManager subset (transaction lifecycle, ensureExecReady-style guards) implements androidx semantics for the consumer set; gaps beyond the subset are recorded, not faked.",
        "status": "VERIFIED",
        "source": {"origin": "AndroidX fragment", "file": "FragmentManager shadow"},
        "test": "R-NEW-331 family: minesweeper/memory/2048 same generic gate — one fix, 3+ consumers",
        "consumers": ["dooz"], "issues": [], "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "S62", "last_verified": "S73",
    },
    "LAW-VIEW-GETRESOURCES": {
        "title": "View.getResources non-null law", "domain": "framework", "scope": "generic",
        "statement": "View.getResources() answers the hosting Resources instance (never null) per AOSP View contract.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP frameworks/base View.java", "file": "S72-W3 null-producer closure"},
        "test": "fixtures 25/25; unote theme recovery 231120 px", "consumers": ["unote"],
        "issues": [15], "capabilities": ["cap-view-inflate-layout"],
        "first_discovered": "S72-W3", "last_verified": "S73",
    },
    "LAW-THEME-RESOLVEATTRIBUTE": {
        "title": "Theme.resolveAttribute chain", "domain": "framework", "scope": "generic",
        "statement": "Theme attribute resolution follows the AOSP single-resolution-path with typed-value output; getTheme/resolveAttribute must answer real themed values (unote regression recovered via this law).",
        "status": "VERIFIED",
        "source": {"origin": "AOSP frameworks/base", "file": "S72-W3 closure (commit 048b0e31)"},
        "test": "unote themed UI 231120 px recovered", "consumers": ["unote"],
        "issues": [15], "capabilities": ["cap-view-inflate-layout"],
        "first_discovered": "S72-W3", "last_verified": "S73",
    },
    "LAW-F108": {
        "title": "R8 minification identity law (DEX hierarchy over names)", "domain": "compose", "scope": "generic",
        "statement": "Package-prefix identity is not a contract under R8: ComposeView->Lho;, AndroidComposeView->Lt4; (0 androidx/compose names survive). The SURVIVING identity is the DEX hierarchy + the dispatchDraw override contract; draw-path gates must key on chain_overrides_method(class, dispatchDraw) for non-framework classes.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP AbstractComposeView/AndroidComposeView + R8 output of dooz v23 (DEX ground truth scripts/s61_r381_dex_truth.py)", "file": "root_registry.json F-108"},
        "test": "dooz v23 compose pipeline deterministic execution", "consumers": ["dooz"],
        "issues": [14], "capabilities": ["cap-render-software-framebuffer", "cap-dex-interpreter"],
        "first_discovered": "S61", "last_verified": "S73",
    },
    "LAW-F113": {
        "title": "SecureRandom IS-A Random bridge law", "domain": "jvm", "scope": "generic",
        "statement": "bridge_to_api receives the STATIC receiver class; SecureRandom instances never reached the F-086 Random law. OpenJDK law: SecureRandom.java:157 extends java.util.Random, :828 next(int) override supplies the bit stream while Random.nextInt(bound) keeps the contract. Fix: law family += Ljava/security/SecureRandom.",
        "status": "VERIFIED",
        "source": {"origin": "OpenJDK SecureRandom.java:157/:828", "file": "docs/evidence/s63_spotlight/S63_REPORT.md §1"},
        "test": "gmdice dice 6/5/3/2; battery ALL PASS; pixel diff 1,584 px result band; det x3",
        "consumers": ["gmdice"], "issues": [17], "capabilities": ["cap-secure-random"],
        "first_discovered": "S63", "last_verified": "S73",
    },
    "LAW-F114": {
        "title": "SharedPreferences family law", "domain": "storage", "scope": "generic",
        "statement": "(a) getString default is @Nullable (AOSP SharedPreferencesImpl.java:307-313); (b) PreferenceManager.setDefaultValues parses the defaults XML and persists key/defaultValue + _has_set_default_values one-shot flag (:661-673); (c) getDefaultSharedPreferences = <pkg>_preferences.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP/AndroidX PreferenceManager.java:661-673", "file": "docs/evidence/s64_spotlight/S64_REPORT.md §2"},
        "test": "pmk rc=1 NFE -> rc=0 views=179 det x3; second consumer simplestopwatch defaults=24",
        "consumers": ["unote", "gmdice"], "issues": [15, 17], "capabilities": ["cap-persistence-sharedprefs"],
        "first_discovered": "S64", "last_verified": "S73",
    },
    "LAW-F117": {
        "title": "Scheduled input law (--tap x,y[@frame])", "domain": "input", "scope": "generic",
        "statement": "Legacy form (--tap x,y): tap k fires at frame k (byte-identical to stored W4 evidence). Extension (S73): --tap x,y@frame fires the tap AFTER frame k renders (real user cadence between frames). All-or-none CLI validation; recorded fields: target coordinate, target View, frame, event, resulting state change.",
        "status": "VERIFIED",
        "source": {"origin": "MiniAndroid execution engine (implementation-defined cadence law)", "file": "execution_engine.h/.cpp + main.cpp"},
        "test": "legacy byte-identical vs stored W4 frames; snake 23 scheduled taps autonomous session",
        "consumers": ["androidgamesnake", "connectfour", "gmdice", "bouncy"],
        "issues": [13], "capabilities": ["cap-input-dispatch", "cap-autonomous-gameplay"],
        "first_discovered": "S73", "last_verified": "S73",
    },
    "LAW-F118": {
        "title": "Activity constructor law", "domain": "lifecycle", "scope": "generic",
        "statement": "Activity launches run <init> (G08 launches now execute the constructor chain) per AOSP instantiation order.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP Activity instantiation", "file": "root_registry.json F-118 (R-NEW-385)"},
        "test": "G08 launches; 3 consumers day one", "consumers": ["tripeaks", "fishrings", "opmt"],
        "issues": [], "capabilities": ["cap-lifecycle-dispatch"],
        "first_discovered": "S65", "last_verified": "S73",
    },
    "LAW-F120": {
        "title": "Button gravity law", "domain": "framework", "scope": "generic",
        "statement": "Button default gravity follows the AOSP Button (TextView) contract as pinned in upstream_oracle.json.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP Button/TextView", "file": "tools/architecture upstream_oracle.json (grep-verified)"},
        "test": "S70 oracle verification", "consumers": ["androidgamesnake", "gmdice"],
        "issues": [], "capabilities": ["cap-view-inflate-layout"],
        "first_discovered": "S70", "last_verified": "S73",
    },
    "LAW-F135": {
        "title": "OpenJDK Double/Float compare NaN law", "domain": "jvm", "scope": "generic",
        "statement": "Double/Float compare orders NaN per OpenJDK (NaN treated as largest; compare returns <0/>0 per spec), not per C++ default operator ordering.",
        "status": "VERIFIED",
        "source": {"origin": "OpenJDK Double.java/Float.java", "file": "S69 record (commit b88e09d9); upstream_oracle.json"},
        "test": "battery stages at S69+", "consumers": ["dooz"],
        "issues": [], "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "S69", "last_verified": "S73",
    },
    "LAW-F136": {
        "title": "Context/Resources strings single-resolution-path law (ARSC-first)", "domain": "resources", "scope": "generic",
        "statement": "strings resolve ARSC-first per the AOSP single-resolution-path (Context.java:945-978 -> Resources.java:464-592); the legacy name-map is a demoted fallback; receiver-first resid law; formatted overload wired to java_format_walk.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP Context.java:945-978, Resources.java:464-592", "file": "docs/upstream/aosp/CONTEXT_STRING_LAW.md"},
        "test": "f53_getstring 3 law paths PASS 5/5 + determinism x3 byte-identical (8c11659a7ca24512)",
        "consumers": ["bouncy", "androidgamesnake", "gmdice"],
        "issues": [21], "capabilities": ["cap-apk-pipeline"],
        "first_discovered": "S70", "last_verified": "S73",
    },
    "LAW-F137": {
        "title": "Framework ancestry dispatch law", "domain": "framework", "scope": "generic",
        "statement": "framework_ancestor_for_dispatch walks the DEX superclass chain + built-in AOSP platform hierarchy with a single bounded retry at bridge-stub fallthrough; caller-context (not name matching) decides dispatch.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP platform hierarchy + app DEX supers", "file": "S71 record (commit 1271b869)"},
        "test": "gmdice getResources x5 / unote getWindow / dooz getApplicationContext + getClass x2 -> IMPLEMENTED; battery 92/94 (EXT stages environmental)",
        "consumers": ["gmdice", "unote", "dooz"], "issues": [17, 15, 14], "capabilities": ["cap-ancestor-dispatch"],
        "first_discovered": "S71", "last_verified": "S73",
    },
    "LAW-F141": {
        "title": "ART null-receiver invoke NPE law (all 5 instance-invoke paths)", "domain": "interpreter", "scope": "generic",
        "statement": "ART throws NullPointerException when invoke-virtual/super/direct/interface/range executes on a null receiver. MiniAndroid previously executed these silently (F-075 missed NULL_REF), letting poison flow until unrelated crashes. Root-caused and fixed S72-W3; the six null-producer laws (Runtime singleton, boxed-reader family, FragmentManager subset, View.getResources, getTheme/resolveAttribute, String.getClass) closed with it.",
        "status": "VERIFIED",
        "source": {"origin": "ART interpreter entry (null receiver check)", "file": "S72-W3 record commit 048b0e31; root_registry.json F-141"},
        "test": "fixtures 25/25 rc=0 zero f141-throws; dooz 197->23472 px progression at the time; unote theme regression recovered",
        "consumers": ["dooz", "unote", "telegram"], "issues": [14, 15, 16],
        "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "S72-W1 (registered P0)", "last_verified": "S73 (fixtures 25/25)",
        "notes": "CLOSED unless new evidence directly reopens it (taskbook §35). F-146/F-147 are DISTINCT open blockers, not F-141 regressions.",
    },
    "LAW-F142": {
        "title": "RelativeLayout MarginLayoutParams + ImageView onMeasure cap law", "domain": "layout", "scope": "generic",
        "statement": "RL children carry MarginLayoutParams semantics; ImageView onMeasure caps to drawable-intrinsic behavior per AOSP — fishrings board renders on the current binary because of this law.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP RelativeLayout/ImageView", "file": "S72-W2 record (commit f8d5e1e2)"},
        "test": "fishrings real game board (KPI-2 +1, zero regressions)",
        "consumers": ["fishrings"], "issues": [19], "capabilities": ["cap-view-inflate-layout"],
        "first_discovered": "S72-W2", "last_verified": "S73",
    },
    "LAW-F143": {
        "title": "Service-launch family (service-only manifests)", "domain": "lifecycle", "scope": "generic",
        "statement": "An APK whose manifest declares NO launchable Activity (service-only) must not render an Activity UI; the engine-default face is CORRECT. A service-launch capability is required before any UI can exist for such apps.",
        "status": "OBSERVED",
        "source": {"origin": "MiniAndroid manifest census (S72-W1)", "file": "root_registry.json F-143"},
        "test": "stopwatch face byte-identical to no-Activity engine default (0e334abe1b10b592)",
        "consumers": ["stopwatch"], "issues": [22], "capabilities": [],
        "first_discovered": "S72-W1", "last_verified": "S73",
        "notes": "OPEN capability gap (by-design blocker for #22), not a runtime bug.",
    },
    "LAW-F144": {
        "title": "GL surface family (tictactoe-class)", "domain": "rendering", "scope": "generic",
        "statement": "Apps drawing through GL surfaces need a GL compatibility path; tracked P2, does not gate View-based proofs of the same apps.",
        "status": "RESEARCHED",
        "source": {"origin": "S72-W1 triage", "file": "root_registry.json F-144"},
        "test": None, "consumers": ["tictactoe"], "issues": [11],
        "capabilities": [],
        "first_discovered": "S72-W1", "last_verified": "S72-W1",
        "notes": "Research-stage record; no implementation claimed.",
    },
    "LAW-F145": {
        "title": "Dooz visual frontier", "domain": "rendering", "scope": "generic",
        "statement": "Dooz's own UI surface remains unrendered: the only produced face is the engine-default black region. No visual success may be claimed for dooz until a dooz-content frame passes the provenance gate (ViewTree -> Canvas trace -> state -> screenshot).",
        "status": "OBSERVED",
        "source": {"origin": "S73 B4 audit", "file": "docs/evidence/S73/S73_REPORT.md §5"},
        "test": "reclassification evidence: dooz face == no-Activity stopwatch face (0e334abe1b10b592)",
        "consumers": ["dooz"], "issues": [14], "capabilities": ["cap-screenshot-quality-gate"],
        "first_discovered": "S72-W3 (as frontier)", "last_verified": "S73 (sharpened)",
    },
    "LAW-F146": {
        "title": "Dooz g8.a@569 -> ur.e(J) null receiver", "domain": "compose", "scope": "generic",
        "statement": "At dooz onCreate->compose init, g8.a@569 invokes ur.e(J) on a null reference. DISTINCT from F-141 (which is closed): this is the current open first divergence of the dooz composition path.",
        "status": "OBSERVED",
        "source": {"origin": "S72-W3/W4 probes (re-probed UNCHANGED on current binary)", "file": "root_registry.json F-146"},
        "test": "re-probe S72-W4 + S73: same first divergence",
        "consumers": ["dooz"], "issues": [14], "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "S72-W3", "last_verified": "S73 (UNCHANGED)",
    },
    "LAW-F147": {
        "title": "Dooz onCreate@228 -> ViewGroup.getChildAt on null", "domain": "compose", "scope": "generic",
        "statement": "Second dooz divergence: onCreate@228 calls ViewGroup.getChildAt through a null group reference; upstream ViewGroup.getChildAt contract (index-bounded child access on a real group) is the governing law.",
        "status": "OBSERVED",
        "source": {"origin": "AOSP ViewGroup.getChildAt + dooz DEX trace", "file": "root_registry.json F-147"},
        "test": "re-probe S72-W4 + S73: UNCHANGED",
        "consumers": ["dooz"], "issues": [14], "capabilities": ["cap-dex-interpreter"],
        "first_discovered": "S72-W3", "last_verified": "S73 (UNCHANGED)",
    },
    "LAW-F148": {
        "title": "ConstraintLayout anchor family law", "domain": "layout", "scope": "generic",
        "statement": "layout_constraint* anchor family (12 attrs + 2 biases) requires per-axis topological CL measure semantics: MATCH_CONSTRAINT spread, bias, one/no-anchor laws, padding-box parent anchors; layout phase replays the RL contract.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP ConstraintLayout measure pass", "file": "docs/foundation/S72_WAVE4.md (F-148 row)"},
        "test": "snake SnakePanelView EXACTLY 1080x780; biased button pad EXACT (BOTTOM span 799 x 0.5); corpus 10/10 + fixtures 25/25 pixel-SAME",
        "consumers": ["androidgamesnake"], "issues": [13], "capabilities": ["cap-view-inflate-layout"],
        "first_discovered": "S72-W4", "last_verified": "S73",
    },
    "LAW-F149": {
        "title": "DisplayMetrics/applyDimension + device-density unity law", "domain": "layout", "scope": "generic",
        "statement": "Resources.getDisplayMetrics must answer the device law (density 2.625/420, scaledDensity, xdpi/ydpi — never silent null, never singleton density=1.0 contradiction); TypedValue.applyDimension implements the exact AOSP switch over heap fields.",
        "status": "VERIFIED",
        "source": {"origin": "AOSP Resources/DisplayMetrics/TypedValue.applyDimension", "file": "docs/foundation/S72_WAVE4.md (F-149 row)"},
        "test": "SnakePanelView 1080x780 = 20x15dp x 2.625 EXACTLY; buttons 197x118 = 75x45dp; corpus 10/10 pixel-SAME",
        "consumers": ["androidgamesnake", "gmdice", "microtimer"],
        "issues": [13], "capabilities": ["cap-measure-geometry"],
        "first_discovered": "S72-W4", "last_verified": "S73",
    },
    "LAW-F150": {
        "title": "Thread game-loop family law (sleep/start/wake)", "domain": "concurrency", "scope": "generic",
        "statement": "Four stacked roots fixed: (1) ThreadShadow no-op swallowed sleep — sleep now blocks per semantics; (2) javac emits SUBCLASS descriptors for Thread.sleep/start — method_ids ground truth wins over literal types (is_thread_receiver DEX-chain law, 3 sites); (3) starts drained only in parks — frame-boundary start/yield drains (bounded 4/8); (4) no resume for sleep-blocked bodies — wake-time registry (thread->{target,wake}); sleep inside drained bodies records wake without advancing the shared clock. Documented deviations from wall-clock semantics remain in the notes.",
        "status": "VERIFIED",
        "source": {"origin": "OpenJDK Thread.sleep/start semantics + DEX method_ids ground truth", "file": "docs/foundation/S72_WAVE4.md (F-150 row); worklog S72-W4"},
        "test": "snake 2 ticks/frame EXACT; 88 moves; reverse-guard honored; final frame x3 BYTE-IDENTICAL (1a419545419deb3a); corpus 10/10 + fixtures 25/25 pixel-SAME",
        "consumers": ["androidgamesnake", "microtimer"], "issues": [13, 18],
        "capabilities": ["cap-thread-game-loop", "cap-autonomous-gameplay"],
        "first_discovered": "S72-W4", "last_verified": "S73",
        "notes": "Deviation notes (virtual-clock semantics) are part of the record; never claim wall-clock parity.",
    },
    # ---- App-scope laws (NOT generic registry entries — recorded per S73 law) ----
    "APP-SNAKE-WRAP": {
        "title": "Snake wrap law ((19,10) -> (0,10))", "domain": "game/snake", "scope": "app",
        "statement": "AndroidGameSnake wraps at walls: head (19,10) re-enters at (0,10); there is NO wall death in the proven path.",
        "status": "OBSERVED",
        "source": {"origin": "S73 C4 probe (real tap, reverse-guard route)", "file": "docs/evidence/S73/S73_REPORT.md §3; issue #13"},
        "test": "C4 probe on real APK", "consumers": ["androidgamesnake"],
        "issues": [13], "capabilities": ["cap-autonomous-gameplay"],
        "first_discovered": "S73", "last_verified": "S73",
    },
    "APP-SNAKE-REVERSE-GUARD": {
        "title": "Snake reverse-direction rejection", "domain": "game/snake", "scope": "app",
        "statement": "The APP rejects 180-degree turns (LEFT tap while moving RIGHT rejected; heads continued (15,10)->(18,10)) — app-level guard, honored not bypassed.",
        "status": "OBSERVED",
        "source": {"origin": "S73 C4 probe", "file": "docs/evidence/S73/S73_REPORT.md §3"},
        "test": "C4 probe on real APK", "consumers": ["androidgamesnake"],
        "issues": [13], "capabilities": ["cap-autonomous-gameplay"],
        "first_discovered": "S73", "last_verified": "S73",
    },
    "APP-SNAKE-SELFCOLLISION-GAMEOVER": {
        "title": "Snake self-collision game-over", "domain": "game/snake", "scope": "app",
        "statement": "Head re-entry into an occupied cell triggers game-over: panel switches to the game-over surface (1,868,783 px) at frame 94.",
        "status": "OBSERVED",
        "source": {"origin": "S73 C4 probe", "file": "docs/evidence/S73/S73_REPORT.md §3"},
        "test": "C4 probe on real APK", "consumers": ["androidgamesnake"],
        "issues": [13], "capabilities": ["cap-autonomous-gameplay"],
        "first_discovered": "S73", "last_verified": "S73",
    },
    "APP-SNAKE-RESTART-OPEN": {
        "title": "Snake restart-after-game-over NOT observed", "domain": "game/snake", "scope": "app",
        "statement": "Honest negative finding: restart via START after game-over was NOT observed (possibly Dialog-based path, not exercised).",
        "status": "OBSERVED",
        "source": {"origin": "S73 C4b probe", "file": "docs/evidence/S73/S73_REPORT.md §3"},
        "test": "C4b probe (no restart transition observed)", "consumers": ["androidgamesnake"],
        "issues": [13], "capabilities": [],
        "first_discovered": "S73", "last_verified": "S73",
        "notes": "Negative-evidence record; do not upgrade without a proven restart transition.",
    },
    "APP-DOOZ-COMPOSE-CHAIN": {
        "title": "Dooz Compose/coroutine deep chain (RESEARCH-stage)", "domain": "compose", "scope": "app",
        "statement": "DOOZ -> Compose/coroutine -> b2/n -> Segment-like state/queue -> AtomicReferenceArray; measured get ~629k, set ~1, head segment state ~0x40000000. These observations are NOT a complete semantic law without upstream verification (taskbook §40).",
        "status": "RESEARCHED",
        "source": {"origin": "S72-W1 deep-chain probes (commit acad15fd)", "file": "S72_WAVE1.md evidence doc"},
        "test": None, "consumers": ["dooz"], "issues": [14],
        "capabilities": [],
        "first_discovered": "S72-W1", "last_verified": "S72-W1",
    },
    "CLAIM-DOOZ-23472-VISUAL": {
        "title": "FALSE CLAIM: dooz '23,472 px = visual proof' (SUPERSEDED)", "domain": "evidence", "scope": "claim",
        "statement": "The S72-W3/W4 claim that dooz rendered 23,472 px of real content is FALSE: S73 proved those are pure-black pixels forming an engine-default (0,0)-(489,47) region, byte-identical to the no-Activity Stopwatch frame (0e334abe1b10b592). Dooz visual proof remains UNRESOLVED. Determinism facts stand; the INTERPRETATION was corrected.",
        "status": "SUPERSEDED",
        "superseded_by": "LAW-F145 + dated reclassification comment on issue #14 + S73_REPORT §5",
        "source": {"origin": "S73 B4 historical audit", "file": "docs/evidence/S73/S73_REPORT.md §5"},
        "test": "byte-identity comparison vs no-Activity face",
        "consumers": ["dooz"], "issues": [14], "capabilities": ["cap-screenshot-quality-gate"],
        "first_discovered": "S72-W3 (as claim)", "last_verified": "S73 (reclassified)",
        "notes": "PRESERVED as an evidence-quality lesson (taskbook §68): pixel count != semantic visual proof. Never delete; mark SUPERSEDED and link the correction.",
    },
}
