"""S74 app dossier data — part 2 (gmdice..opmt). Same evidence rules as part 1."""

S73 = "docs/evidence/S73/S73_REPORT.md"
FIX25 = "fixtures 25/25 rc=0, f141-throws=0 (run/s73_fixtures, S73 §6)"

APPS_2 = {
    "gmdice": {
        "name": "GM Dice",
        "package": "de.duenndns.gmdice",
        "status": "PARTIAL",
        "issue": 17, "issue_state": "open",
        "source": {"repository": "https://github.com/ge0rg/gamemasterdice", "commit": "6353926f067bd41dd914ec7f530771a586125eb6",
                   "license": "GPLv2", "note": "S63 SOURCE-first spotlight: cloned, built, executed (v1.3 line)"},
        "apk": {"sha256_16": "ee9f7396"},
        "rendering": {"meaningful_frame": "DONE", "pixels": "182628 px", "sha256_16": "a011e9e9eee2cb42"},
        "input": {"tap": "OBSERVED (S63: 5/5 clicks -> real handler; historical at S73 recipe)"},
        "state": {"transitions": "S63 L7: dice rolled by the APP (6/5/3/2) -> changed frame, diff confined to result band (SHA 5312266e->fa1d8612); SecureRandom IS-A Random bridge F-113 was the root"},
        "evidence": {"primary": ["docs/evidence/s63_spotlight/S63_REPORT.md", S73],
                     "screenshot_sha256_16": "a011e9e9eee2cb42", "determinism": "3-run det x3"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "OBSERVED", "C7_state_change": "OBSERVED",
                       "C8_rerender": "OBSERVED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "ladder open: input/state legs proven at S63, not re-run at current HEAD (historical)",
        "next_task": "re-run S63 tap recipe at HEAD; expect result-band-only diff; then C9 (SharedPreferences defaults, F-114 family TESTED engine-side)",
        "links": {"laws": ["LAW-F113", "LAW-F137", "LAW-F136"], "capabilities": ["cap-secure-random", "cap-ancestor-dispatch", "cap-state-change-observability"],
                  "knowledge": [], "evidence_files": []},
    },
    "microtimer": {
        "name": "MicroTimer",
        "package": "dubrowgn.microtimer",
        "status": "PARTIAL",
        "issue": 18, "issue_state": "open",
        "source": {"repository": "F-Droid (dubrowgn.microtimer)", "commit": None, "license": None},
        "rendering": {"meaningful_frame": "DONE", "pixels": "1041437 px", "sha256_16": "e4869001e3638d69"},
        "input": {"tap": "OBSERVED (historical L7 keypad->display)"},
        "evidence": {"primary": [S73, "docs/ACHIEVEMENTS.md"], "screenshot_sha256_16": "e4869001e3638d69", "determinism": "3-run x3"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "OBSERVED", "C7_state_change": "OBSERVED",
                       "C8_rerender": "OBSERVED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "ladder open below render (input legs historical)",
        "next_task": "re-prove keypad->display state change at HEAD; timer thread leg belongs to cap-thread-game-loop consumers",
        "links": {"laws": [], "capabilities": ["cap-render-software-framebuffer", "cap-input-dispatch"],
                  "knowledge": [], "evidence_files": []},
    },
    "fishrings": {
        "name": "FishRings",
        "package": "eu.veldsoft.fish.rings",
        "status": "PARTIAL",
        "issue": 19, "issue_state": "open",
        "source": {"repository": "https://bitbucket.org/gnastler/Fish-Rings-for-Android (vendored)", "commit": "dc3807e7d405843453afc798c6cc02205b65e1fb",
                   "license": None, "note": "upstream clone vendored at upstream/corpus/eu.veldsoft.fish.rings with PROVENANCE.json"},
        "rendering": {"meaningful_frame": "DONE", "pixels": "board 2073360 px (frames 4-8; splash 0 px frames 0-3)",
                      "sha256_16": "19af37b69965fc48"},
        "input": {"tap": "OBSERVED (historical: S65 S10 PROVEN 3 input->state->changed-frame interactions det x3; F-142 board fix)"},
        "state": {"transitions": "S65: 3 input->state->changed-frame interactions, deterministic x3 (S10)"},
        "evidence": {"primary": [S73, "docs/evidence/s65_spotlight/S65_REPORT.md"], "screenshot_sha256_16": "19af37b69965fc48", "determinism": "S65 det x3"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "OBSERVED", "C7_state_change": "OBSERVED",
                       "C8_rerender": "OBSERVED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "game-logic depth (real ring rotation rules) unexercised at HEAD; input legs historical",
        "next_task": "re-run S65 interaction recipe at HEAD; probe one full ring-rotation round via real taps",
        "links": {"laws": ["LAW-F142"], "capabilities": ["cap-view-inflate-layout", "cap-state-change-observability"],
                  "knowledge": [], "evidence_files": []},
    },
    "tripeaks": {
        "name": "TriPeaks",
        "package": "eu.veldsoft.tri.peaks",
        "status": "BLOCKED",
        "issue": 20, "issue_state": "open",
        "source": {"repository": "upstream/corpus/eu.veldsoft.tri.peaks (PROVENANCE.json)", "commit": None, "license": None},
        "rendering": {"meaningful_frame": "PARTIAL", "pixels": "205638 px lobby", "sha256_16": "834928fd671a9560"},
        "input": {"tap": "OBSERVED (historical S7 lobby clicks)"},
        "evidence": {"primary": [S73], "screenshot_sha256_16": "834928fd671a9560"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "PARTIAL", "C4_measure_layout": "PARTIAL",
                       "C5_render": "PARTIAL", "C6_input": "OBSERVED", "C7_state_change": "BLOCKED",
                       "C8_rerender": "BLOCKED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "R-NEW-388 (remeasured S71: generic RL anchor laws PROVEN on f14; TriPeaks blocked at splash = app-specific OBJECT-IDENTITY), visual progression blocked",
        "next_task": "isolate the app-specific object-identity divergence at splash->lobby->game transition; keep generic RL laws out of scope (they are proven)",
        "links": {"laws": [], "capabilities": ["cap-render-software-framebuffer"],
                  "knowledge": [], "evidence_files": []},
    },
    "bouncy": {
        "name": "Bouncy",
        "package": "com.dozingcatsoftware.bouncy",
        "status": "PARTIAL",
        "issue": 21, "issue_state": "open",
        "source": {"repository": "F-Droid (com.dozingcatsoftware.bouncy), source-backed", "commit": None, "license": None},
        "rendering": {"meaningful_frame": "DONE", "pixels": "2073600 px (100% non-background dashboard)", "sha256_16": "108618ac7c58083b"},
        "input": {"tap": "OBSERVED (S62: 6/6 clicks dispatched into REAL DEX XML-onClick handlers: scoreViewClicked, doPreviousTable, doQuit, hideHighScore)"},
        "state": {"transitions": "two distinct UI states proven by frame SHA pair 4219c5116ea2 -> 52e4ddacc8ac (S62 L6)"},
        "evidence": {"primary": ["docs/evidence/s62_r381/", S73], "screenshot_sha256_16": "108618ac7c58083b"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "OBSERVED", "C7_state_change": "OBSERVED",
                       "C8_rerender": "OBSERVED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "PENDING", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "L7 game-loop interaction proof open (physics loop not autonomously driven); R-NEW-389 81-px top-band cross-build divergence is a boundary note, not this app's blocker",
        "next_task": "drive the physics loop with scheduled taps (cap-autonomous-gameplay consumer candidate #2)",
        "links": {"laws": [], "capabilities": ["cap-input-dispatch", "cap-autonomous-gameplay"],
                  "knowledge": [], "evidence_files": []},
    },
    "stopwatch": {
        "name": "Simple Stopwatch",
        "package": "com.github.muellerma.stopwatch",
        "status": "BLOCKED",
        "status_note": "blocked BY DESIGN of the app manifest — engine behavior is CORRECT (S72-W1 F-143 family)",
        "issue": 22, "issue_state": "open",
        "source": {"repository": "F-Droid (com.github.muellerma.stopwatch)", "commit": None, "license": None},
        "rendering": {"meaningful_frame": "BLOCKED", "note": "engine-default black region only; CORRECT for an app with no launchable Activity"},
        "evidence": {"primary": [S73], "determinism": "face byte-identical to dooz engine-default (0e334abe1b10b592) — the shared-face fact is the reclassification evidence"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "BLOCKED",
                       "C3_view_framework": "BLOCKED", "C4_measure_layout": "BLOCKED",
                       "C5_render": "BLOCKED", "C6_input": "BLOCKED", "C7_state_change": "BLOCKED",
                       "C8_rerender": "BLOCKED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "no launchable Activity — service-only manifest (F-143 service-launch family); needs a service-launch/foreground-notification capability before any UI can exist",
        "next_task": "implement service-launch family capability (F-143) or reclassify this dossier target as service-execution-only",
        "links": {"laws": ["LAW-F143"], "capabilities": [],
                  "knowledge": [], "evidence_files": []},
    },
    "opmt": {
        "name": "OPMT (One Plus Minus Three)",
        "package": "one.scarecrow.games.OPMT",
        "status": "PARTIAL",
        "issue": 23, "issue_state": "open",
        "source": {"repository": "upstream/corpus (S65 spotlight)", "commit": None, "license": None},
        "rendering": {"meaningful_frame": "DONE", "pixels": "213286 px", "sha256_16": "60e5611daaf01e58"},
        "input": {"tap": "OBSERVED (historical S6 chain)"},
        "evidence": {"primary": [S73], "screenshot_sha256_16": "60e5611daaf01e58"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "OBSERVED", "C7_state_change": "OBSERVED",
                       "C8_rerender": "OBSERVED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "PENDING", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "app-own IOOBE (OBJECT-IDENTITY class) stops game progression; S65 root: app-own nextInt(0) stopper",
        "next_task": "isolate the app-own IOOBE path; verify whether Random.nextInt(bound=0) semantics (OpenJDK law: IllegalArgumentException) surface as the app's own crash",
        "links": {"laws": [], "capabilities": ["cap-render-software-framebuffer"],
                  "knowledge": [], "evidence_files": []},
    },
}
