"""S74 app dossier data — part 1 (evidence-derived; sources: S73_REPORT.md §2-§5,
docs/ACHIEVEMENTS.md, worklog S72-W3/W4 + S73 records, GitHub issues #10-#23).
Every non-null value traces to a committed evidence artifact. Unknowns stay
null / NOT_OBSERVED (truth over polish — taskbook §66)."""

# Evidence anchor used across dossiers (S73 current-HEAD re-execution)
S73 = "docs/evidence/S73/S73_REPORT.md"
FIX25 = "fixtures 25/25 rc=0, f141-throws=0 (run/s73_fixtures, S73 §6)"

APPS_1 = {
    "helloworld": {
        "name": "HelloWorld (HelloWorldSelfAware)",
        "package": "com.appliberated.helloworldselfaware",
        "status": "DONE",
        "issue": 10, "issue_state": "closed",
        "source": {"repository": "F-Droid (com.appliberated.helloworldselfaware)",
                   "commit": None, "license": None,
                   "note": "APK SHA256 009b4671... (SHA-verified control target, ACHIEVEMENTS §1)"},
        "apk": {"sha256_16": "009b4671"},
        "manifest_summary": "single launchable Activity; typographic self-aware UI (no special permissions recorded)",
        "lifecycle": {"application": "OBSERVED", "activity": "OBSERVED", "service": None,
                      "broadcast_receiver": None, "content_provider": None},
        "rendering": {"backend": "software framebuffer", "meaningful_frame": "DONE",
                      "typography_golden": "EXT-01 9/9 vs upstream phone screenshot"},
        "input": {"tap": "TESTED", "dispatch": "EXT-02 interaction 12/12"},
        "state": {"note": "app-computed hash text rendered — real DEX execution"},
        "evidence": {
            "primary": ["docs/evidence/s54_frames/helloworld_ext01_base.jpg",
                        "docs/evidence/GOLDEN_HELLOWORLD.md"],
            "screenshot_sha256_16": None,
            "determinism": "golden byte-stable (S53->S54 replay proof)"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "DONE", "C7_state_change": "DONE",
                       "C8_rerender": "DONE", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": None,
        "next_task": "optional: persistence/concurrency ladder extension (no open blocker)",
        "links": {"laws": ["LAW-MUTF8", "LAW-F136"], "capabilities": ["cap-apk-pipeline", "cap-dex-interpreter", "cap-lifecycle-dispatch", "cap-view-inflate-layout", "cap-render-software-framebuffer", "cap-input-dispatch"],
                  "knowledge": [], "evidence_files": ["docs/evidence/s54_frames/SHA256SUMS"]},
    },
    "tictactoe": {
        "name": "TicTacToe",
        "package": "com.emmanuelmess.tictactoe",
        "status": "DONE",
        "issue": 11, "issue_state": "closed",
        "source": {"repository": "https://github.com/EmmanuelMess/TicTacToeGame",
                   "commit": None, "license": None,
                   "note": "upstream clone vendored at upstream/corpus/com.emmanuelmess.tictactoe (PROVENANCE per S61 corpus law)"},
        "apk": {"sha256_16": None},
        "manifest_summary": "single launchable Activity game (View-based, no GL surface in the proven path)",
        "lifecycle": {"application": "OBSERVED", "activity": "OBSERVED"},
        "rendering": {"backend": "software framebuffer", "meaningful_frame": "DONE"},
        "input": {"tap": "TESTED", "dispatch": "9-click real chain"},
        "state": {"transitions": "X/O placement state machine; win state reached",
                  "determinism": "deterministic frames x3"},
        "evidence": {"primary": ["docs/testing/VERIFIED_TESTS.md (tictactoe_golden battery section 9/9)"],
                     "determinism": "x3 deterministic"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "DONE", "C7_state_change": "DONE",
                       "C8_rerender": "DONE", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": None,
        "next_task": "none (completed state documented in #11; GL family F-144 tracked separately, does not gate this app)",
        "links": {"laws": [], "capabilities": ["cap-apk-pipeline", "cap-view-inflate-layout", "cap-input-dispatch", "cap-state-change-observability"],
                  "knowledge": [], "evidence_files": []},
    },
    "connectfour": {
        "name": "ConnectFour (golden fixture)",
        "package": None,
        "status": "DONE",
        "issue": 12, "issue_state": "closed",
        "source": {"repository": "in-repo golden fixture", "commit": None, "license": None,
                   "note": "agent-playable 24-step golden; corrected result is canonical (below)"},
        "apk": {"sha256_16": None},
        "rendering": {"backend": "software framebuffer", "meaningful_frame": "DONE"},
        "input": {"tap": "TESTED", "dispatch": "24 scheduled clicks"},
        "state": {"transitions": "22/24 clicks produce meaningful state changes; actual Y win at click 22 (NOT 24); deterministic replay; ID pattern 55->31",
                  "note": "corrected result preserved per taskbook §37 — accuracy over prettier numbers"},
        "evidence": {"primary": ["docs/testing/VERIFIED_TESTS.md", S73],
                     "determinism": "deterministic replay (ID pattern 55->31)"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "DONE", "C7_state_change": "DONE",
                       "C8_rerender": "DONE", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": None,
        "next_task": "none (completed state documented in #12)",
        "links": {"laws": [], "capabilities": ["cap-input-dispatch", "cap-state-change-observability", "cap-determinism-replay"],
                  "knowledge": [], "evidence_files": []},
    },
    "androidgamesnake": {
        "name": "AndroidGameSnake",
        "package": "zhangman.github.snake",
        "status": "OBSERVED",
        "status_note": "autonomous gameplay proven end-to-end (S73); restart-after-game-over honestly NOT observed",
        "issue": 13, "issue_state": "closed",
        "source": {"repository": "https://github.com/zhangman523/AndroidGameSnake",
                   "commit": "b4968c39", "license": "Apache-2.0",
                   "note": "SOURCE-first chain: upstream clone -> aapt2/ECJ/D8 build (no handwritten ARSC/AXML writer)"},
        "apk": {"path": "upload/s72_w4_apks/snake_v1.0_vc1.apk", "sha256_16": "54cf48a9"},
        "build": {"toolchain": "aapt2 + ECJ 3.36.0 + D8/R8 8.3.37 + android-34 stubs",
                  "recipe": "scripts/s72_w4_build_snake.sh"},
        "lifecycle": {"application": "OBSERVED", "activity": "OBSERVED"},
        "view_hierarchy": "ConstraintLayout root (F-148 anchor family, SnakePanelView EXACT 1080x780 = 20x15dp x 2.625) + biased button pad",
        "layout": {"constraint_layout": "F-148: 12 anchor attrs + bias, per-axis topological solver",
                   "display_metrics": "F-149: getDisplayMetrics/applyDimension/device-density 2.625/420"},
        "rendering": {"backend": "software framebuffer; SnakePanelView onDraw, 801 Canvas ops/frame",
                      "meaningful_frame": "DONE (final snake+food frame 122314 px)"},
        "input": {"tap": "TESTED", "scheduled": "F-117 --tap x,y@frame (23 scheduled real taps incl. START (98,839)@frame1)",
                  "dispatch": "canonical TouchDispatcher DOWN/UP path — no injection"},
        "state": {"transitions": "START -> reStartGame -> Thread.start self-run (F-150) -> 2 ticks/frame EXACT; 88 head-advance moves; 22 accepted turns; 1 food capture at frame 34 (snake 3->4, food (0,0)->(9,0)); movement law 1 cell/frame, tap@k effective at frame k+1",
                  "probes": "reverse turn REJECTED by app; WRAP law (19,10)->(0,10); self-collision game-over OBSERVED (frame 94, game-over surface 1,868,783 px); restart after game-over NOT OBSERVED"},
        "concurrency": {"thread": "F-150 game-loop family: sleep de-noop, javac subclass-descriptor receivers, frame-boundary start/yield drains, wake-time registry"},
        "evidence": {
            "primary": ["docs/evidence/s73_snake_autoplay/ (run_01..03, gameplay_trace.json, SHA256SUMS, determinism_proof.json, screenshot_metrics.json, snake_autoplay.gif 39073 bytes)",
                        "docs/evidence/s72_w4_snake/", "docs/foundation/S72_WAVE4.md", S73],
            "screenshot_sha256_16": "1a419545419deb3a",
            "determinism": "3/3 runs byte-identical (90/90 frames per-run PNG sha equality); W4 legacy recipe byte-identical"},
        "regression": {"fixtures": FIX25, "corpus": "10/10 pixel-SAME post-F148/149/150"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "DONE", "C7_state_change": "DONE",
                       "C8_rerender": "DONE", "C9_persistence": "PENDING",
                       "C10_concurrency": "DONE", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "restart-after-game-over path unproven (possibly Dialog-based; not exercised — honest open, recorded in #13)",
        "next_task": "prove restart-after-game-over via real tap on the game-over surface; then C9 persistence ladder if the app persists any state",
        "links": {"laws": ["LAW-F148", "LAW-F149", "LAW-F150", "LAW-F117", "APP-SNAKE-WRAP", "APP-SNAKE-REVERSE-GUARD", "APP-SNAKE-SELFCOLLISION-GAMEOVER", "APP-SNAKE-RESTART-OPEN"],
                  "capabilities": ["cap-view-inflate-layout", "cap-measure-geometry", "cap-input-dispatch", "cap-thread-game-loop", "cap-state-change-observability", "cap-determinism-replay", "cap-autonomous-gameplay"],
                  "knowledge": [], "evidence_files": ["docs/evidence/s73_snake_autoplay/run_01/SHA256SUMS"]},
    },
    "dooz": {
        "name": "Dooz",
        "package": "io.github.yamin8000.dooz",
        "status": "BLOCKED",
        "issue": 14, "issue_state": "open",
        "source": {"repository": "https://github.com/yamin8000/Dooz", "commit": None,
                   "license": None, "note": "v23 executes full Hilt/DI/Compose pipeline deterministically (v18 F-083 fixed earlier)"},
        "apk": {"sha256_16": None},
        "rendering": {"backend": "software framebuffer (Compose -> AndroidComposeView path, F-108 identity laws)",
                      "meaningful_frame": "BLOCKED (F-145 frontier)",
                      "reclassification": "S73 B4 audit: the 23472-px metric is an ENGINE-DEFAULT black region (0,0)-(489,47), byte-identical to the no-Activity Stopwatch frame (sha 0e334abe1b10b592) — NOT dooz content. Determinism facts stand; interpretation corrected (dated comment on #14)."},
        "state": {"transitions": "lifecycle reaches onCreate->onStart->onResume; UI composition blocked by F-146/F-147"},
        "concurrency": {"compose_chain": "Kotlin/coroutines/AtomicFU -> Segment-like state/queue -> AtomicReferenceArray: get ~629k, set ~1, head segment state ~0x40000000 — OBSERVED numbers, NOT yet upstream-verified law"},
        "evidence": {"primary": [S73, "docs/evidence/s72_w3/S72_WAVE3.md" if False else "docs/foundation/S72_WAVE3.md"],
                     "determinism": "x3 byte-identical (0e334abe1b10b592 = engine-default face; honest reclassification)"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "PARTIAL",
                       "C3_view_framework": "PARTIAL", "C4_measure_layout": "BLOCKED",
                       "C5_render": "BLOCKED", "C6_input": "BLOCKED", "C7_state_change": "BLOCKED",
                       "C8_rerender": "BLOCKED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PARTIAL", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "F-146 (g8.a@569 -> ur.e(J) null receiver) and F-147 (onCreate@228 -> ViewGroup.getChildAt on null); visual frontier F-145. F-141 stays CLOSED.",
        "next_task": "root-cause F-146 receiver-null chain (Searchlight: caller->callee->upstream Compose/kotlinx law); engine-default black-region painter is the queued open lead",
        "links": {"laws": ["LAW-F145", "LAW-F146", "LAW-F147", "LAW-F141", "APP-DOOZ-COMPOSE-CHAIN"],
                  "capabilities": ["cap-dex-interpreter", "cap-determinism-replay"],
                  "knowledge": [], "evidence_files": []},
    },
    "unote": {
        "name": "Unote",
        "package": "app.varlorg.unote",
        "status": "PARTIAL",
        "issue": 15, "issue_state": "open",
        "source": {"repository": "F-Droid (app.varlorg.unote)", "commit": None, "license": None},
        "rendering": {"meaningful_frame": "DONE", "pixels": "231120 px themed UI recovered via F-141 theme chain (S72-W3)", "sha256_16": "2928a026c4a88a14"},
        "input": {"tap": "NOT_OBSERVED (unprobed at S73 recipe)"},
        "evidence": {"primary": [S73], "screenshot_sha256_16": "2928a026c4a88a14", "determinism": "3-run x3 (S73 §6)"},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "DONE",
                       "C3_view_framework": "DONE", "C4_measure_layout": "DONE",
                       "C5_render": "DONE", "C6_input": "PENDING", "C7_state_change": "PENDING",
                       "C8_rerender": "PENDING", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "DONE", "C13_regression": "DONE", "C14_evidence": "DONE"},
        "blocker": "execution ladder open below render: input/state-change legs unprobed at current HEAD",
        "next_task": "run input probe (tap FAB/edit path) -> state change -> re-render; then SharedPreferences persistence leg (F-114 family already TESTED engine-side)",
        "links": {"laws": ["LAW-F141", "LAW-F114"], "capabilities": ["cap-persistence-sharedprefs", "cap-render-software-framebuffer"],
                  "knowledge": [], "evidence_files": []},
    },
    "telegram": {
        "name": "Telegram",
        "package": "org.telegram.messenger",
        "status": "PARTIAL",
        "status_note": "historical evidence (EXP-064..071 checkpoint M); not re-run at current HEAD",
        "issue": 16, "issue_state": "open",
        "source": {"repository": "telegram.org / GitHub (official source release)", "commit": None,
                   "license": "GPLv2/Telegram (upstream dual)", "note": "closed-source APK; DEX forensics allowed (S61 source-first law carve-out)"},
        "apk": {"sha256_16": None},
        "rendering": {"meaningful_frame": "OBSERVED (login UI with real WebP images, EXP-064 pixel-proven PhoneView)"},
        "input": {"tap": "OBSERVED (historical: phone number injected + Next clicked, EXP-069; page transition checkpoint M, EXP-071)"},
        "state": {"transitions": "login page transition proven at checkpoint M"},
        "evidence": {"primary": ["docs/runtime/EXP071_AUTH_SENDCODE_CALLGRAPH.md", "docs/runtime/exp042/", "docs/EXP071_GIT_HISTORY.md"],
                     "determinism": None},
        "security": {"permissions_declared": [], "permissions_observed": [], "exported_components": [],
                     "filesystem": "OBSERVED", "network": "NOT_OBSERVED", "sensitive_apis": [],
                     "notes": "native libs + JNI inventory recorded (docs/runtime/exp042/NATIVE_LIBRARIES.json); manifest permission audit pending; no actual network activity observed in runtime runs (declared != used)",},
        "completion": {"C1_apk_load": "DONE", "C2_manifest_lifecycle": "PARTIAL",
                       "C3_view_framework": "PARTIAL", "C4_measure_layout": "PARTIAL",
                       "C5_render": "OBSERVED", "C6_input": "OBSERVED", "C7_state_change": "OBSERVED",
                       "C8_rerender": "OBSERVED", "C9_persistence": "PENDING",
                       "C10_concurrency": "PENDING", "C11_security_sandbox": "OBSERVED",
                       "C12_determinism": "PENDING", "C13_regression": "PENDING", "C14_evidence": "OBSERVED"},
        "blocker": "v12 init budget: burns 540 s inside real init, no frame in budget; not re-run at current HEAD (strategic 20% stress target)",
        "next_task": "re-baseline Telegram at current HEAD with phase timers (PerfKit MINIANDROID_PERF_PHASES=1); attack init budget hot paths",
        "links": {"laws": [], "capabilities": ["cap-apk-pipeline", "cap-dex-interpreter"],
                  "knowledge": [], "evidence_files": ["docs/runtime/exp042/JNI_INVENTORY.json"]},
    },
}
