"""S74 tool/source profiles (Layer B) + capability records (Layer D/E).
Evidence-derived: numbers come from committed sessions (S61/S63/S65/S70/S71/
S72-W4/S73). Provenance classes reuse the canonical taxonomy of
docs/corpus/UPSTREAM_INVENTORY.md (MOTHER/DERIVED/EXTRACTED/REFERENCE/
COMPATIBILITY/ANALYSIS/TEST ORACLE/RESEARCH ONLY)."""

TOOLS = {
    "aosp": {
        "name": "AOSP (frameworks/base + platform frameworks)",
        "url": "https://android.googlesource.com/platform/frameworks/base",
        "license": "Apache-2.0",
        "provenance_class": "MOTHER",
        "provides": "authoritative Android framework semantics: View/ViewGroup measure-layout-draw, LayoutInflater, Context/Resources, SharedPreferences, ConstraintLayout/RelativeLayout layout laws, TypedValue/DisplayMetrics",
        "reused": ["F-148 ConstraintLayout anchor laws (per-axis topological solver mirrors CL measure)",
                   "F-149 DisplayMetrics/applyDimension switch (exact AOSP law)",
                   "F-136 Context.java:945-978 + Resources.java:464-592 single-resolution-path strings law",
                   "F-114 SharedPreferencesImpl.java:307-313 @Nullable default + PreferenceManager.java:661-673 defaults XML",
                   "F-142 RelativeLayout MarginLayoutParams + ImageView onMeasure cap"],
        "laws_learned": ["LAW-F148", "LAW-F149", "LAW-F136", "LAW-F114", "LAW-F142", "LAW-F137", "LAW-F120"],
        "tests_reused": ["f53_getstring (3 law paths, 5/5)", "foundation fixtures f-family (25 pinned)"],
        "consumers": ["androidgamesnake", "unote", "gmdice", "fishrings", "bouncy", "helloworld"],
        "evidence": "docs/foundation/S72_WAVE4.md; docs/upstream/aosp/CONTEXT_STRING_LAW.md; docs/upstream/INDEX.md",
        "limitations": "fetched per-session for each law (tagged); no full framework tree vendored",
    },
    "art": {
        "name": "ART (Android Runtime) interpreter semantics",
        "url": "https://android.googlesource.com/platform/art",
        "license": "Apache-2.0",
        "provenance_class": "MOTHER",
        "provides": "interpreter/bytecode execution semantics: invoke paths, null receiver NPE law, deferred throws, class init order",
        "reused": ["F-141 null-receiver invoke NPE law (all 5 instance-invoke paths) + 6 null-producer closures",
                   "throw_deferred semantics",
                   "ClassLinker::EnsureInitialized init-on-first-active-use + re-entrancy law (S61 measured: 6,453 ensure-calls, 627 cold <clinit>)"],
        "laws_learned": ["LAW-F141", "LAW-THROW-DEFERRED", "LAW-BOXED-READERS", "LAW-FRAGMENTMANAGER-SUBSET", "LAW-VIEW-GETRESOURCES", "LAW-THEME-RESOLVEATTRIBUTE"],
        "tests_reused": ["fixtures 25/25 (f141-throws=0 gate)", "battery stages"],
        "consumers": ["dooz", "telegram", "androidgamesnake"],
        "evidence": "docs/evidence/S72_WAVE3 record (commit 048b0e31); root_registry.json F-141 entry",
        "limitations": "MiniAndroid is NOT an ART fork — per-opcode laws re-derived first-party (UPSTREAM_INVENTORY DERIVED class)",
    },
    "dalvik": {
        "name": "Dalvik executable format (DEX spec)",
        "url": "https://source.android.com/docs/core/runtime/dex-format",
        "license": "CC-BY/Apache-2.0 (AOSP docs)",
        "provenance_class": "MOTHER",
        "provides": "DEX container format, method_ids ground truth, MUTF-8 string encoding, opcode tables",
        "reused": ["MUTF-8 decoding (LAW-MUTF8)",
                   "F-150 ground-truth law: javac emits SUBCLASS descriptors for Thread.sleep/start — method_ids is the authority over literal types",
                   "multi-DEX resolution (F-002-era fix, EXP-065 const-string leak)"],
        "laws_learned": ["LAW-MUTF8", "LAW-F150"],
        "consumers": ["helloworld", "androidgamesnake", "dooz", "telegram"],
        "evidence": "scripts/forensic/dex_method_dump.py + S72-W4 disasm records",
        "limitations": None,
    },
    "openjdk": {
        "name": "OpenJDK / libcore (java.* behavior)",
        "url": "https://github.com/openjdk/jdk (libcore mirror for Android semantics)",
        "license": "GPL-2.0-with-classpath-exception",
        "provenance_class": "MOTHER",
        "provides": "core-class contracts: Double/Float compare, Random/SecureRandom, String, Runtime, collections, atomics",
        "reused": ["F-135 Double/Float compare NaN law",
                   "F-113 SecureRandom.java:157 extends Random + :828 next(int) override (bridge law)",
                   "Runtime.getRuntime() singleton; String.getClass; boxed property-reader family (closed with F-141 wave)"],
        "laws_learned": ["LAW-F135", "LAW-F113", "LAW-BOXED-READERS"],
        "tests_reused": ["gmdice dice 6/5/3/2 result-band determinism"],
        "consumers": ["gmdice", "opmt"],
        "evidence": "docs/evidence/s63_spotlight/S63_REPORT.md §1; upstream_oracle.json (7 grep-verified law records)",
        "limitations": "Android libcore diverges from upstream JDK at edges; divergences recorded per law, not assumed",
    },
    "androidx": {
        "name": "AndroidX (appcompat/fragment/preference)",
        "url": "https://android.googlesource.com/platform/frameworks/support",
        "license": "Apache-2.0",
        "provenance_class": "MOTHER",
        "provides": "FragmentManager lifecycle, PreferenceManager, MultiDex, appcompat theme chains",
        "reused": ["FragmentManager subset (guarded lifecycle; R-NEW-331 family blocked minesweeper/memory/2048 — one fix, 3+ game consumers)",
                   "F-114 PreferenceManager.setDefaultValues XML parse + getDefaultSharedPreferences <pkg>_preferences",
                   "MultiDexApplication chain fires (F-137 ancestry dispatch consumer)"],
        "laws_learned": ["LAW-FRAGMENTMANAGER-SUBSET", "LAW-F114", "LAW-F137"],
        "consumers": ["dooz", "unote", "gmdice"],
        "evidence": "run/s62_mines_trace.log; docs/evidence/s64_spotlight/S64_REPORT.md §2",
        "limitations": "subset only; ensureExecReady-style guards verified where exercised",
    },
    "kotlin": {
        "name": "Kotlin (stdlib + compiled form)",
        "url": "https://github.com/JetBrains/kotlin",
        "license": "Apache-2.0",
        "provenance_class": "MOTHER",
        "provides": "Kotlin metadata, compiled lambda/composable shapes, property-reader patterns that surface in DEX",
        "reused": ["boxed property-reader family closure (F-141 wave)",
                   "j$ desugar-shim law (newKeySet) — S71 resolved UNKNOWNs"],
        "laws_learned": ["LAW-BOXED-READERS"],
        "consumers": ["dooz", "gmdice"],
        "evidence": "S71 forensic triage (136 LIVE-STUB triage; both UNKNOWNs resolved by caller-context evidence)",
        "limitations": "Compose-compiler-generated shapes studied under Compose profile",
    },
    "kotlinx-coroutines-atomicfu": {
        "name": "kotlinx.coroutines + AtomicFU",
        "url": "https://github.com/Kotlin/kotlinx.coroutines",
        "license": "Apache-2.0",
        "provenance_class": "MOTHER",
        "provides": "coroutine dispatchers, Segment/queue machinery built on AtomicReferenceArray",
        "reused": ["Dooz deep chain: Segment-like state/queue -> AtomicReferenceArray — measured get ~629k, set ~1, head segment state ~0x40000000 (OBSERVED, NOT yet upstream-verified law — taskbook §40)"],
        "laws_learned": ["APP-DOOZ-COMPOSE-CHAIN"],
        "consumers": ["dooz"],
        "evidence": "S72-W1 dooz deep-chain root cause (commit acad15fd): arraycopy(null) NPE @ Lid;.K -> PersistentHashMapBuilder.putAll trie walk -> invoke-virtual/range this=NULL",
        "limitations": "observations not promoted to generic law without upstream verification",
    },
    "compose": {
        "name": "Jetpack Compose (runtime + ui)",
        "url": "https://android.googlesource.com/platform/frameworks/support (compose)",
        "license": "Apache-2.0",
        "provenance_class": "MOTHER",
        "provides": "declarative UI runtime: composition, AndroidComposeView, dispatchDraw contract",
        "reused": ["F-108 identity laws: R8 renames ComposeView->Lho;, AndroidComposeView->Lt4; surviving identity is the DEX hierarchy + dispatchDraw override contract (chain_overrides_method gate)",
                   "Compose execution domain treated as first-class compatibility target (never special-cased)"],
        "laws_learned": ["LAW-F108"],
        "consumers": ["dooz"],
        "evidence": "S61 R-NEW-381 record + root_registry.json",
        "limitations": "first meaningful Compose frame still blocked (dooz F-145/F-146/F-147)",
    },
    "build-toolchain": {
        "name": "Android build toolchain (aapt2 + ECJ + D8/R8)",
        "url": "Maven Central (ecj 3.36.0), r8-releases (8.3.37), Google Maven (aapt2), Sable android-34 stubs",
        "license": "Apache-2.0/EPL (per component)",
        "provenance_class": "ANALYSIS",
        "provides": "real Android build chain for source-first APK production — no handwritten ARSC/AXML writer anywhere in the repo",
        "reused": ["HelloWorld golden chain (aapt2 -> ECJ -> D8/R8 -> android-34 stubs)",
                   "snake v1.0 build (scripts/s72_w4_build_snake.sh, APK 54cf48a9)",
                   "gmdice v12 build (APK ee9f7396)",
                   "bootstrap: scripts/build/bootstrap_toolchain.sh (container-reset resilient — proven twice)"],
        "laws_learned": [],
        "tests_reused": ["rebuild fidelity: dooz x3 byte-identical 0e334abe1b10b592; snake W4 recipe byte-identical 1a419545419deb3a"],
        "consumers": ["helloworld", "androidgamesnake", "gmdice", "siggen", "blockinger"],
        "evidence": "docs/foundation/S72_WAVE4.md SOURCE block; S73 rebuild record",
        "limitations": "toolchain re-fetched after container resets (bootstrap script persists the recipe)",
    },
    "external-runtimes": {
        "name": "External emulator/runtime projects (WineDroid et al.)",
        "url": "various (surveyed)",
        "license": "varies",
        "provenance_class": "REFERENCE",
        "provides": "validation/reference comparisons only — NEVER source of truth, neverMiniAndroid behavior authority",
        "reused": ["validation matrix role: MiniAndroid behavior vs AOSP/ART/OpenJDK/AndroidX/other-runtime rows (taskbook §41)"],
        "laws_learned": [],
        "consumers": [],
        "evidence": "docs/corpus/UPSTREAM_INVENTORY.md REFERENCE class; docs/runtime/knowledge/external-runtime indexes",
        "limitations": "surveyed, not vendored; no behavior copied without upstream re-verification",
    },
    "codesearch-toolchain": {
        "name": "Code-search toolchain (zoekt + csearch/cindex + Go)",
        "url": "https://github.com/sourcegraph/zoekt",
        "license": "Apache-2.0 (per tool)",
        "provenance_class": "RESEARCH ONLY",
        "provides": "fast upstream/repo law hunting",
        "reused": ["S63 tool law: zoekt default max_trigram_count silently EXCLUDES very large files (dalvik_engine.cpp 1.2MB -> 0 hits); cap raised to 100000000",
                   "csearch per-file trigram limit (reproduced 3x); GOPROXY=direct works when module proxy stalls (Go 1.26.0)"],
        "laws_learned": [],
        "consumers": [],
        "evidence": "docs/evidence/s63_spotlight/S63_REPORT.md §4",
        "limitations": "research tooling; not part of the runtime",
    },
    "asc": {
        "name": "ASC reconnaissance (Droid ASC, MG1937/ASC)",
        "url": "external recon tooling",
        "license": "varies",
        "provenance_class": "RESEARCH ONLY",
        "provides": "reconnaissance/comparison aid for APK surface mapping (e.g. Telegram startup path)",
        "reused": ["Telegram v12 startup path mapping (EXP-042 era)"],
        "laws_learned": [],
        "consumers": ["telegram"],
        "evidence": "docs/ACHIEVEMENTS.md ASC column per app",
        "limitations": "NEVER source of truth / semantic authority — chain: ASC OBSERVED -> UPSTREAM CONFIRMED -> IMPLEMENTED -> TESTED -> OBSERVED IN APK (taskbook §43)",
    },
}

CAPABILITIES = {
    "cap-apk-pipeline": {
        "name": "APK pipeline (ZIP + ARSC + AXML + DEX parse)",
        "implemented": "src/runtime/* (apk loader, resources.arsc, binary XML, DEX)",
        "laws": ["LAW-MUTF8", "LAW-F136"],
        "tests": ["battery BATTERY GATE ALL PASS (96 stages; 92 without EXT fixture — documented count law)"],
        "consumers": ["helloworld", "tictactoe", "connectfour", "androidgamesnake", "dooz", "unote", "telegram", "gmdice", "microtimer", "fishrings", "tripeaks", "bouncy", "stopwatch", "opmt"],
        "issue": None, "status": "DONE",
    },
    "cap-dex-interpreter": {
        "name": "DEX interpreter (tagged-value semantics)",
        "implemented": "miniandroid/src/dex/dalvik_engine.cpp",
        "laws": ["LAW-F141", "LAW-THROW-DEFERRED", "LAW-F150"],
        "tests": ["fixtures 25/25 rc=0 f141-throws=0", "dooz x3 byte-identical"],
        "consumers": ["dooz", "telegram", "androidgamesnake", "gmdice", "opmt", "helloworld"],
        "issue": None, "status": "DONE",
    },
    "cap-lifecycle-dispatch": {
        "name": "Android lifecycle dispatch (Application/Activity)",
        "implemented": "src/framework lifecycle shadows + execution_engine",
        "laws": ["LAW-F118"],
        "tests": ["G07 golden lifecycle", "G08 navigation"],
        "consumers": ["helloworld", "androidgamesnake", "dooz", "gmdice", "unote", "fishrings"],
        "issue": None, "status": "DONE",
    },
    "cap-view-inflate-layout": {
        "name": "View inflate + layout subsets (RL/CL/LL/Frame)",
        "implemented": "src/framework layout shadows (F-142 RL margins + ImageView cap; F-148 CL anchors)",
        "laws": ["LAW-F148", "LAW-F142", "LAW-F137"],
        "tests": ["snake SnakePanelView EXACT 1080x780", "fixtures 25/25 pixel-SAME", "corpus 10/10 pixel-SAME"],
        "consumers": ["androidgamesnake", "fishrings", "tictactoe", "bouncy", "unote"],
        "issue": None, "status": "DONE",
    },
    "cap-measure-geometry": {
        "name": "Measure geometry (DisplayMetrics/density/applyDimension)",
        "implemented": "Resources.getDisplayMetrics device law (2.625/420) + TypedValue.applyDimension DEX bridge",
        "laws": ["LAW-F149"],
        "tests": ["buttons 197x118 = 75x45dp x2.625 EXACT", "corpus 10/10 pixel-SAME"],
        "consumers": ["androidgamesnake", "gmdice", "microtimer"],
        "issue": None, "status": "DONE",
    },
    "cap-render-software-framebuffer": {
        "name": "Software framebuffer render + per-frame SHA",
        "implemented": "renderer + canvas shadow (801 ops/frame on snake onDraw)",
        "laws": ["LAW-F108"],
        "tests": ["corpus pixel faces S73 §2 (7 meaningful apps)", "families: F-107 trace-out-of-hot-path"],
        "consumers": ["helloworld", "tictactoe", "androidgamesnake", "unote", "gmdice", "microtimer", "fishrings", "bouncy", "opmt", "tripeaks"],
        "issue": None, "status": "DONE",
    },
    "cap-input-dispatch": {
        "name": "Input dispatch (TouchDispatcher DOWN/UP + F-117 scheduled taps)",
        "implemented": "execution_engine.h/.cpp + main.cpp: --tap x,y and --tap x,y@frame (all-or-none validation)",
        "laws": ["LAW-F117"],
        "tests": ["legacy form byte-identical vs stored W4 frames", "snake 23 scheduled taps incl. START (98,839)@frame1"],
        "consumers": ["androidgamesnake", "connectfour", "tictactoe", "gmdice", "bouncy", "fishrings"],
        "issue": None, "status": "DONE",
    },
    "cap-thread-game-loop": {
        "name": "Thread game-loop family (sleep/start/frame-boundary drains/wake registry)",
        "implemented": "dalvik_engine ThreadShadow de-noop + is_thread_receiver DEX-chain law + frame-boundary drains (bounded 4/8) + wake-time registry",
        "laws": ["LAW-F150"],
        "tests": ["snake 2 ticks/frame EXACT; 88 moves; reverse-guard honored", "corpus 10/10 + fixtures 25/25 pixel-SAME post-change"],
        "consumers": ["androidgamesnake", "microtimer"],
        "issue": None, "status": "DONE",
    },
    "cap-state-change-observability": {
        "name": "State-change observability (input -> callback -> state -> render diff)",
        "implemented": "frame SHA + pixel-diff probes + trace",
        "laws": [],
        "tests": ["gmdice result-band diff (5312266e->fa1d8612)", "bouncy two-state SHA pair (4219c5116ea2->52e4ddacc8ac)", "connectfour 22/24 meaningful transitions"],
        "consumers": ["androidgamesnake", "gmdice", "connectfour", "bouncy", "fishrings"],
        "issue": None, "status": "DONE",
    },
    "cap-screenshot-quality-gate": {
        "name": "Screenshot quality gate + provenance law",
        "implemented": "tools/verify_screenshot.py metrics + scripts/s73_screenshot_gate.py (resolution/non-background/entropy/luminance/dominant colors/bounds/SHA256)",
        "laws": [],
        "tests": ["B3 gate on s73 snake key frames; Dooz reclassification is the standing negative proof (pixel count != semantic proof)"],
        "consumers": ["androidgamesnake", "dooz", "stopwatch"],
        "issue": None, "status": "DONE",
    },
    "cap-persistence-sharedprefs": {
        "name": "SharedPreferences family (getString @Nullable, defaults XML, <pkg>_preferences)",
        "implemented": "F-114 family engine implementation",
        "laws": ["LAW-F114"],
        "tests": ["pmk rc=1 NFE -> rc=0 views=179 det x3; simplestopwatch defaults=24"],
        "consumers": ["unote", "gmdice"],
        "issue": None, "status": "DONE",
    },
    "cap-secure-random": {
        "name": "SecureRandom IS-A Random bridge",
        "implemented": "law family += Ljava/security/SecureRandom in bridge_to_api",
        "laws": ["LAW-F113"],
        "tests": ["gmdice dice 6/5/3/2; battery ALL PASS; pixel diff 1,584 px result band; det x3"],
        "consumers": ["gmdice"],
        "issue": None, "status": "DONE",
    },
    "cap-ancestor-dispatch": {
        "name": "Framework ancestor dispatch (DEX superclass chain + AOSP hierarchy)",
        "implemented": "framework_ancestor_for_dispatch + bounded retry at bridge stub fallthrough (F-137)",
        "laws": ["LAW-F137"],
        "tests": ["gmdice getResources x5 / unote getWindow / dooz getApplicationContext + getClass x2 converted STUBBED->IMPLEMENTED", "battery 92/94 (EXT-01/02 environmental)"],
        "consumers": ["gmdice", "unote", "dooz"],
        "issue": None, "status": "DONE",
    },
    "cap-determinism-replay": {
        "name": "Determinism / 3-run replay protocol",
        "implemented": "deterministic engine + 3-run comparison (state/event/frame-SHA)",
        "laws": [],
        "tests": ["dooz x3 byte-identical 0e334abe1b10b592", "snake autonomous 3/3 IDENTICAL 90/90 frames", "snake W4 legacy byte-identical 1a419545419deb3a", "gmdice det x3"],
        "consumers": ["androidgamesnake", "dooz", "gmdice", "connectfour"],
        "issue": None, "status": "DONE",
    },
    "cap-autonomous-gameplay": {
        "name": "Autonomous gameplay (pixel-only vision + scheduled real taps)",
        "implemented": "scripts/s73_snake_controller.py — vision ONLY from rendered frames; actuator ONLY canonical taps; no state injection",
        "laws": ["LAW-F117", "LAW-F150", "APP-SNAKE-WRAP", "APP-SNAKE-REVERSE-GUARD"],
        "tests": ["snake GOALS_MET: 88 moves / 22 turns / 1 food capture (frame 34, growth 3->4); 3/3 byte-identical; trace+GIF+SHA256SUMS"],
        "consumers": ["androidgamesnake"],
        "issue": 13, "status": "OBSERVED",
    },
}
