#!/usr/bin/env python3
"""s77_build_audit_views.py — S77 §4 missing-artifact closure.

Builds the missing operational artifacts as DERIVED VIEWS over the canonical
sources (§22: one canonical source + derived reports; §26/§27: reuse/connect,
never duplicate):

  canonical sources
    root_registry.json                          (F-/R- roots — canonical)
    docs/foundation/failure_index.json          (failure index, refreshed)
    docs/compatibility/apps/*.json              (14 dossiers)
    docs/evidence/s74_ops/OPS_SESSIONS.json     (per-app sessions)
    docs/knowledge/KNOWLEDGE_RECORDS.json       (knowledge records)

  derived outputs (this script, deterministic)
    docs/audit/RUNTIME_FAILURE_REGISTRY.md      (§4.2)
    docs/audit/CRASH_HANG_ANR_REGISTRY.md       (§4.5)
    docs/audit/SANDBOX_ERROR_REPORT.md + sandbox_errors.json  (§4.1)
    docs/audit/SESSION_EVIDENCE_CHAIN.md        (§4.3)
    docs/audit/PROGRESS_REPORT.md               (§4.4 + §21 reconciliation)
    docs/audit/EVIDENCE_LINEAGE.md              (§4.6)
    docs/audit/APP_MATRIX.md                    (§13)

Every record field that has no canonical source is emitted as NOT_RECORDED —
never invented.
"""
import json, os, re, glob, hashlib, datetime

ROOT = "/home/z/my-project"
AUD = f"{ROOT}/docs/audit"
NOW = "2026-09-22 (S77)"

def load(p):
    with open(p) as f:
        return json.load(f)

def w(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(path, ROOT)} ({len(text)} bytes)")

def nr(v):
    """honest not-recorded"""
    return v if v not in (None, "", [], {}) else "NOT_RECORDED"

# ---------------- load canonical ----------------
reg = load(f"{ROOT}/root_registry.json")
roots = reg["roots"]
fam = [r for r in roots if re.fullmatch(r"F-\d+", r.get("id", ""))]
fam.sort(key=lambda r: int(r["id"].split("-")[1]))
dossiers = {}
for p in sorted(glob.glob(f"{ROOT}/docs/compatibility/apps/*.json")):
    d = load(p)
    dossiers[d.get("app_id") or os.path.basename(p)[:-5]] = d
ops = load(f"{ROOT}/docs/evidence/s74_ops/OPS_SESSIONS.json")
know = load(f"{ROOT}/docs/knowledge/KNOWLEDGE_RECORDS.json")
krecs = know.get("knowledge", [])
if isinstance(krecs, dict):
    krecs = list(krecs.values())

# ================= §4.2 RUNTIME FAILURE REGISTRY =================
def f_registry_md():
    hdr = f"""# RUNTIME FAILURE REGISTRY — DERIVED VIEW (S77)

> Canonical source: `/root_registry.json` (append-only root registry).
> This file is GENERATED by `scripts/s77_build_audit_views.py` — do not hand-edit.
> Generated: {NOW}. Roots in registry: {len(roots)}; F-records: {len(fam)}.

## Status rollup (F-records)

| Status | Count | IDs |
|---|---|---|
"""
    from collections import Counter, defaultdict
    c = Counter(r.get("status", "NOT_RECORDED") for r in fam)
    by = defaultdict(list)
    for r in fam:
        by[r.get("status", "NOT_RECORDED")].append(r["id"])
    order = ["OPEN", "REPRODUCED", "ROOT_CAUSED", "ROOT_CAUSED-FIXED", "VERIFIED-FIXED",
             "VERIFIED-CORRECT", "FIXED", "PARTIAL", "RESEARCHED", "OBSERVED", "UNVERIFIED"]
    rows = []
    for st in order:
        if st in c:
            rows.append((st, c[st], by[st]))
    for st, n in sorted(c.items()):
        if st not in order:
            rows.append((st, n, by[st]))
    for st, n, ids in rows:
        hdr += f"| {st} | {n} | {', '.join(ids)} |\n"
    hdr += f"""
## Lifecycle

`OPEN → REPRODUCED → ROOT_CAUSED → LAW_IDENTIFIED → FIXED → REGRESSION_TESTED → OBSERVED → CLOSED`
(The registry's historical status vocabulary — ROOT_CAUSED-FIXED, VERIFIED-FIXED,
VERIFIED-CORRECT, OBSERVED, RESEARCHED — maps onto this lifecycle; a record is
CLOSED only with regression + observation evidence linked.)

## Per-record operational view

Fields marked NOT_RECORDED have no canonical source in the registry — they are
shown honestly, not invented. F-146/F-148 (fixed) and F-152/F-153 (open) are
expanded below the table.

| F-ID | APP | SUBSYSTEM | SYMPTOM | PRODUCER | STATUS | EVIDENCE (first 160 chars) |
|---|---|---|---|---|---|---|
"""
    for r in fam:
        ev = str(nr(r.get("evidence")))
        hdr += (f"| {r['id']} | {nr(r.get('app'))} | {nr(r.get('subsystem'))} | "
                f"{str(nr(r.get('title')))[:110]} | {nr(r.get('producer'))} | "
                f"{r.get('status','NOT_RECORDED')} | {ev[:160].replace('|','\\|').replace(chr(10),' ')} |\n")
    hdr += "\n"
    # expanded sections for the four wave-critical records
    for fid in ("F-146", "F-148", "F-152", "F-153"):
        r = next((x for x in fam if x["id"] == fid), None)
        if not r:
            continue
        hdr += f"### {fid} — {r.get('status','NOT_RECORDED')}\n\n"
        for k in ("title", "app", "subsystem", "first_seen", "last_seen", "repro_rate",
                  "symptom", "producer", "root_cause", "upstream_law", "semantic_law",
                  "implementation", "test", "execution", "trace", "evidence",
                  "regression", "issue", "source", "first_divergence", "affected"):
            if r.get(k):
                hdr += f"- **{k}**: {str(r[k])[:900]}\n"
        hdr += "\n"
    hdr += """## Numbering canon

- F-145..F-150 exist (S72-W3/W4 era); **F-151 is a confirmed numbering GAP**
  (never registered; S76 next-free-id scan jumped it). F-152/F-153 are the
  canonical S76 failure IDs.
- Root count 397→404 at S76 enumerated exactly: R-NEW-390..394, F-152, F-153;
  F-146 → ROOT-CAUSED-FIXED (no new record).
"""
    return hdr

# ================= §4.5 CRASH / HANG / ANR REGISTRY =================
def crash_registry_md():
    crash_ids, hang_ids, anr_ids = [], [], []
    for r in fam:
        t = (str(r.get("title", "")) + " " + str(r.get("evidence", ""))).lower()
        if r.get("status") in ("ROOT_CAUSED-FIXED", "VERIFIED-FIXED") and (
                "npe" in t or "null" in t or "crash" in t or "segfault" in t or "throw" in t):
            crash_ids.append(r)
        if "f084" in t or "spin" in t or "hang" in t:
            hang_ids.append(r)
    # ANR-class: budget exhaustion / unresponsive init (telegram 540s; stopwatch service-only)
    anr_ids = [("APP-TELEGRAM", "init budget exhaustion: v12.10.3 burns the 540 s session budget in app-init "
                 "(androidx fragment/activity-result NPE family); no frame at HEAD",
                 "docs/evidence/s74_ops/telegram/session.json; docs/audit/MASTER_CHECKLIST.md APP-TELEGRAM"),
               ("APP-STOPWATCH", "no launchable Activity (service-only manifest family F-143) — UI never becomes responsive",
                 "docs/evidence/s74_ops/stopwatch/session.json; docs/audit/MASTER_CHECKLIST.md APP-STOPWATCH")]
    out = f"""# CRASH / HANG / ANR REGISTRY — DERIVED VIEW (S77)

> Canonical sources: `/root_registry.json` (F-records) + app dossiers
> (`docs/compatibility/apps/*.json`) + ops sessions
> (`docs/evidence/s74_ops/OPS_SESSIONS.json`). GENERATED by
> `scripts/s77_build_audit_views.py` — do not hand-edit. Generated: {NOW}.

Classification law: **CRASH** = process/engine escape (uncaught NPE/throw,
SEGV, composition death); **HANG** = bounded or unbounded non-progress loop;
**ANR-class** = input/render responsiveness lost via budget exhaustion or
missing UI dispatch surface.

## CRASH records (ERR-C-*)

| ERR-ID | APP | F-ID / ROOT | STATUS | TRACE / EVIDENCE |
|---|---|---|---|---|
"""
    n = 0
    for r in fam:
        t = str(r.get("title", "")).lower()
        if any(k in t for k in ("npe", "null receiver", "nullpointer", "segfault", "ise", "escape")):
            n += 1
            ev = str(nr(r.get("evidence")))[:200].replace("|", "\\|").replace("\n", " ")
            out += f"| ERR-C-{n:03d} | {nr(r.get('app'))} | {r['id']} | {r.get('status','NOT_RECORDED')} | {ev} |\n"
    out += f"\n({n} crash-class F-records; full symptoms in RUNTIME_FAILURE_REGISTRY.md)\n"
    out += "\n## HANG records (ERR-H-*)\n\n| ERR-ID | APP | F-ID / SITE | STATUS | EVIDENCE |\n|---|---|---|---|---|\n"
    if hang_ids:
        for i, r in enumerate(hang_ids, 1):
            out += f"| ERR-H-{i:03d} | {nr(r.get('app'))} | {r['id']} | {r.get('status','NOT_RECORDED')} | {str(nr(r.get('evidence')))[:180]} |\n"
    else:
        out += "| ERR-H-001 | dooz_23 | (no F-ID — Lsr.run F084-bounded actor spin, S76_REPORT §6) | OPEN (unrooted) | docs/foundation/s76/S76_REPORT.md §6 |\n"
    out += "\n## ANR-class records (ERR-A-*)\n\n| ERR-ID | APP | SYMPTOM | EVIDENCE |\n|---|---|---|---|\n"
    for i, (app, sym, ev) in enumerate(anr_ids, 1):
        out += f"| ERR-A-{i:03d} | {app} | {sym} | {ev} |\n"
    out += """
## Honest gap

Hang/ANR detection is not instrumented in the engine (no watchdog/ANR
scheduler emulation); the records above are session-observed, not
engine-detected. Any engine-level ANR law is future work (registered as an
S77 gap, see PROGRESS_REPORT.md).
"""
    return out

# ================= §4.1 SANDBOX ERROR REPORT =================
def sandbox_report():
    recs = []
    # seed from dossier sandbox blocks
    for app_id, d in sorted(dossiers.items()):
        sp = d.get("sandbox_profile") or {}
        sec = d.get("security") or {}
        rec = {
            "SBX-ID": f"SBX-{app_id.upper()[:12]}",
            "APP": app_id,
            "SESSION": nr((ops.get("sessions", {}).get(app_id, {}) or {}).get("session_format")),
            "APK_SHA256": nr((d.get("apk") or {}).get("sha256_16")),
            "ENVIRONMENT": "miniandroid engine, app-data-root sandbox (per-app package dir)",
            "STEP": "INSTALL→CLEAN→LAUNCH→EXECUTE→OBSERVE→CLOSE→PROCESS EXIT→FILESYSTEM CHECK→REOPEN→PERSISTENCE CHECK→CLEANUP",
            "EXPECTED": "app files confined to its package dir under the data root; no external paths",
            "OBSERVED": nr(sp.get("observation")),
            "REPRODUCTION": "s74-ops per-app probe recipe (scripts/s74f_ops_campaign.py)",
            "FREQUENCY": nr(sp.get("data_root_probed")),
            "PROCESS_STATE": nr((d.get("blocker") or {}).get("summary") if isinstance(d.get("blocker"), dict) else None),
            "FILESYSTEM_STATE": nr(sp.get("boundary_note")),
            "TRACE": nr((d.get("evidence") or {}).get("ops_session") if isinstance(d.get("evidence"), dict) else None),
            "ROOT_CAUSE": "NOT_RECORDED",
            "RELATED_F": "F-146/R-NEW-390/391 (dooz DataStore file-name chain) where applicable",
            "RELATED_R_NEW": "R-NEW-390, R-NEW-391",
            "ISSUE": nr(d.get("issue")),
            "FIX": "none required where observed==confined",
            "REGRESSION": "battery 26/26 + verifier 26/26 + fidelity 90/90 (S77 baseline)",
            "STATUS": "OBSERVED" if sp.get("data_root_probed") else "NOT_OBSERVED",
            "LAST_VERIFIED": "S74F (session.json) / re-affirmed S77",
            "EVIDENCE": nr(d.get("ops_wave")),
        }
        recs.append(rec)
    # the two sandbox-facing runtime errors with full chains
    recs.append({
        "SBX-ID": "SBX-DOOZ-DATASTORE-CHAIN",
        "APP": "dooz_23",
        "SESSION": "docs/evidence/s76/dooz_f146_upstream/",
        "APK_SHA256": "io.github.yamin8000.dooz_23 (see docs/evidence/s76/dooz_f146_upstream/SHA256SUMS* if present)",
        "ENVIRONMENT": "app-data-root sandbox; DataStore preferences file under package dir",
        "STEP": "EXECUTE",
        "EXPECTED": "File.getAbsoluteFile/getCanonicalFile return non-null File objects rooted at the app sandbox (OpenJDK law)",
        "OBSERVED": "pre-fix: null return → getClass/getCanonicalFile NPE → coroutine unwind (F-146) + guard catch-all retry spin",
        "REPRODUCTION": "MINIANDROID_F141_DIAG=1 run of dooz_23 (S75/S76 recipes)",
        "FREQUENCY": "deterministic pre-fix",
        "PROCESS_STATE": "composition killed at MainActivity.onCreate (0xc1 escape)",
        "FILESYSTEM_STATE": "app package dir only — sandbox confinement itself was never breached",
        "TRACE": "docs/evidence/s76/dooz_f146_upstream/ engine logs (F141-DIAG)",
        "ROOT_CAUSE": "File-RETURNING getAbsoluteFile/getCanonicalFile unimplemented (String variants only)",
        "RELATED_F": "F-146", "RELATED_R_NEW": "R-NEW-390, R-NEW-391",
        "ISSUE": "#14 (dooz ledger)", "FIX": "R-NEW-390/391 never-null File laws (dalvik_engine.cpp R-NEW-347 block)",
        "REGRESSION": "battery 26/26; verifier 26/26; fidelity 90/90 (S77 re-baseline)",
        "STATUS": "CLOSED", "LAST_VERIFIED": "S77 baseline re-run 2026-09-22",
        "EVIDENCE": "docs/evidence/s76/dooz_f146_upstream/ + registry R-NEW-390/391 records",
    })
    jp = f"{AUD}/sandbox_errors.json"
    w(jp, json.dumps({
        "schema": "s77-sandbox-errors/1",
        "canonical_source": "docs/compatibility/apps/*.json + docs/evidence/s76/dooz_f146_upstream/ + docs/evidence/s74_ops/OPS_SESSIONS.json",
        "generated": NOW,
        "lifecycle": "OPEN → REPRODUCED → ROOT_CAUSED → LAW_IDENTIFIED → FIXED → REGRESSION_TESTED → OBSERVED → CLOSED",
        "records": recs,
    }, indent=1, ensure_ascii=False))
    md = f"""# SANDBOX ERROR REPORT — CANONICAL (S77 §4.1)

> JSON twin: `docs/audit/sandbox_errors.json` (schema `s77-sandbox-errors/1`).
> Derived FROM canonical dossiers/sessions/registry — this report is the
> human view. GENERATED by `scripts/s77_build_audit_views.py`. {NOW}

## Lifecycle

`OPEN → REPRODUCED → ROOT_CAUSED → LAW_IDENTIFIED → FIXED → REGRESSION_TESTED → OBSERVED → CLOSED`

## Record index

| SBX-ID | APP | STEP | STATUS | ROOT_CAUSE | FIX | EVIDENCE |
|---|---|---|---|---|---|---|
"""
    for r in recs:
        md += (f"| {r['SBX-ID']} | {r['APP']} | {r['STEP'][:40]} | {r['STATUS']} | "
               f"{str(r['ROOT_CAUSE'])[:60]} | {str(r['FIX'])[:40]} | {str(r['EVIDENCE'])[:60]} |\n")
    md += """
## Sandbox lifecycle coverage law (§5)

For every runnable APK the engine records: session ID, timestamp, APK SHA,
action, result, evidence, trace per lifecycle step. Steps genuinely not run
are recorded **NOT_OBSERVED** (never PASS). Canonical per-app records:
`docs/compatibility/apps/*.json` (`sandbox_profile`, `persistence`,
`security` blocks — status vocabulary `DECLARED/OBSERVED/ALLOWED/BLOCKED/
NOT_OBSERVED/UNKNOWN`) + `docs/evidence/s74_ops/<app>/session.json`.

**Current truth (S77):** data-root filesystem probes were executed for the
S74F ops campaign apps; deep per-step sandbox lifecycle capture (11-step
schema above per app) is NOT yet automated end-to-end — the SBX-* records
above are the seeded baseline. Gap registered in PROGRESS_REPORT.md.
"""
    w(f"{AUD}/SANDBOX_ERROR_REPORT.md", md)
    return recs

# ================= §4.3 SESSION → TRACE → ... CHAIN =================
def session_chain_md():
    out = f"""# SESSION → EVIDENCE CHAIN — OPERATIONAL MAP (S77 §4.3)

> GENERATED by `scripts/s77_build_audit_views.py`. {NOW}
> Canonical link sources: `docs/evidence/s74_ops/OPS_SESSIONS.json` +
> `docs/evidence/s7[5-6]*/` bundles + `/root_registry.json` +
> `docs/foundation/failure_index.json`. Every arrow below is a REAL path
> present in the repo (verified at generation time) — this is the
> operationalization of:
> `SESSION ↓ APK ↓ SHA ↓ ACTION ↓ TRACE ↓ ERROR ↓ ROOT CAUSE ↓ LAW ↓ FIX ↓ REGRESSION ↓ OBSERVATION ↓ EVIDENCE`

## Chain 1 — dooz F-146 (full closed loop)

| Link | Value (real path / record) |
|---|---|
| SESSION | S76 probe, recipe `scripts/s75_*` lineage; bundle `docs/evidence/s76/dooz_f146_upstream/` |
| APK | `upload/canonical_apks/io.github.yamin8000.dooz_23.apk` (canonical registry) |
| SHA | recorded in probe bundle logs (`[R347-FILE]` lines) + s74_ops/dooz/session.json `apk.sha256_16` |
| ACTION | launch + F141-DIAG instrumented run (`MINIANDROID_F141_DIAG=1`) |
| TRACE | `docs/evidence/s76/dooz_f146_upstream/` engine logs — `Lg8;.a pc=569` null receiver |
| ERROR | NPE escape at MainActivity.onCreate 0xc1 (composition killed) |
| ROOT CAUSE | `/root_registry.json` F-146 + disasm `scripts/s76_g8_disasm.py` (pc=565 getAbsoluteFile def-chain) |
| LAW | R-NEW-390 (getAbsoluteFile never-null, OpenJDK File.java) + R-NEW-391 (getCanonicalFile/Path) |
| FIX | `miniandroid/src/dex/dalvik_engine.cpp` R-NEW-347 block (commit 2f13abe2) |
| REGRESSION | battery 26/26 + verifier 26/26 + fidelity 90/90 (S77 baseline re-run) |
| OBSERVATION | guard passes (`File o894/o895/o897`), protobuf schema init runs, escape GONE |
| EVIDENCE | `docs/evidence/s76/dooz_f146_upstream/` + registry F-146 ROOT-CAUSED-FIXED |

## Chain 2 — gmdice visible roll (three stacked roots)

| Link | Value |
|---|---|
| SESSION | S76 bundle `docs/evidence/s76/gmdice_roll_visible/` |
| APK | `de.duenndns.gmdice_8.apk` (sha divergence flagged: local 1621eda1 vs dossier ee9f7396 — re-pin open, AUDIT_TABLE #14) |
| SHA | bundle manifest + engine log `[R393-BG]` lines |
| ACTION | real taps on the roll button (frames 0-3 + click schedule) |
| TRACE | engine log: onCreate loop 5/5 buttons, DSADiceSet.roll Random.nextInt ×3 |
| ERROR | (pre-fix) toString-on-null NPE first click; getBackground().setColorFilter NPE at onCreate |
| ROOT CAUSE | R-NEW-392 TextView subsumption + R-NEW-393 getBackground themed-widget law |
| LAW | AOSP Button extends TextView (inherited getText); Widget.* theme background non-null |
| FIX | `dalvik_engine.cpp` is_subclass_of ancestry walk + `android_shadows.cpp` getBackground (commit 2f13abe2) |
| REGRESSION | battery 26/26 / verifier 26/26 / fidelity 90/90 |
| OBSERVATION | first-click diff_px 1,511,441; roll results "6" then "5" rendered |
| EVIDENCE | `docs/evidence/s76/gmdice_roll_visible/` frames + manifest |

## Chain 3 — snake dialog restart

| Link | Value |
|---|---|
| SESSION | S76 bundle `docs/evidence/s76/snake_dialog_restart/` (run_a + run_b) |
| APK | `upload/s72_w4_apks/snake_v1.0_vc1.apk` sha256_16 54cf48a947f9b690 (s74_ops session) |
| SHA | bundle SHA256SUMS + gameplay traces |
| ACTION | 23-tap schedule + death taps D@90 L@91 U@92 + dialog tap (758,1022)@99 |
| TRACE | per-frame timeline; dialog at (80,848 920×224) frame 94 |
| ERROR | (pre-fix) taps DEAD on dialog (target=0 — hit-test walked activity tree only) |
| ROOT CAUSE | R-NEW-394: decor nodes without bounds; no topmost-window routing |
| LAW | AOSP dialog decor laid out in own window; WindowManager topmost-window touch routing |
| FIX | `dialog_shadow.{{h,cpp}}` layout_decor_nodes + `execution_engine.cpp` F117 tap site (commit 2f13abe2) |
| REGRESSION | battery 26/26 / verifier 26/26 / fidelity 90/90 |
| OBSERVATION | RESTART OBSERVED frame 99 — snake at initial row, fresh game to 115+, wall wrap @108 |
| EVIDENCE | `docs/evidence/s76/snake_dialog_restart/s76_dialog_restart_report.json` (honest F-153 residual recorded) |

## Chain 4 — snake Level C determinism (regression anchor)

`scripts/s75_fidelity_probe.py` → replays committed 23-tap schedule
(`docs/evidence/s73_snake_autoplay/run_01/`) → S77 re-run: fresh rc=0,
frames=90, **BYTE-IDENTICAL 90/90** vs stored run_01 (head a8704916).

## S74F ops sessions (14 apps)

All 14 per-app sessions: `docs/evidence/s74_ops/OPS_SESSIONS.json`
(runtime_commit 3505591b, binary-at-HEAD; each with launch_run,
interaction_run, persistence verdict, representative frames, SHA evidence).
These are the canonical session records the chains above extend.
"""
    w(f"{AUD}/SESSION_EVIDENCE_CHAIN.md", out)

# ================= §4.4 + §21 PROGRESS REPORT =================
def progress_report_md():
    recon = [
        ("S72", "W1-W4 execution campaign: fixtures, snake source-first chain, GitHub ledger",
         "F-141..F-150 family roots; W4 snake screenshot-proven chain",
         "SUPERSEDED-IN-PART by S73/S75/S76 advances on dooz/snake faces",
         "F-145 (capture surface) OPEN; F-152/153 successors of the W3/W4 dooz leads"),
        ("S73", "GitHub execution tracking + snake autonomous gameplay (3-run byte-identical)",
         "90-frame autonomous run + C4 probes; restart honestly open",
         "restart gap CLOSED by S76 R-NEW-394 (linked)",
         "engine-default black-surface painter lead → absorbed into F-145/S77 frontier"),
        ("S74", "execution campaign to 14 apps + dossiers + tools + laws operationalization",
         "14 dossiers with visual_evidence (11 HUMAN_VISIBLE / 3 truthful NOT_HUMAN_VISIBLE); 12 tool verdicts; 31 law utilizations; §35 validator gates",
         "COMPLETE for its scope",
         "persistence C9 PENDING (13 apps); telegram/tripeaks/stopwatch blockers stand"),
        ("S74F", "operational evidence follow-up: per-app ops sessions + audit table",
         "14 session.json + OPS_SESSIONS.json + AUDIT_TABLE.md; issue comments prepared but unposted (no token)",
         "COMPLETE except publish actions",
         "issue checkpoints #10–#23 unposted (PUBLISH_BLOCKED)"),
        ("S75", "closure wave: ITEM75 audit 59→4 UNVERIFIED; A7 label/icon law; queued-lead reverify",
         "A7 FIXED (f54-proven, 90/90 render-neutral); ledger truth refresh",
         "COMPLETE for its scope",
         "5 commits publish debt (now 8 with S76); R-NEW-389 open"),
        ("S76", "queued leads executed: F-146 root-caused+fixed; gmdice visible; snake dialog restart; icon decode",
         "R-NEW-390..394 + A7b; registry 397→404; F-152/F-153 registered",
         "COMPLETE for its scope",
         "F-152/F-153 OPEN; icon object law; Lsr.run spin; gmdice prefs REC-MISS family"),
    ]
    out = f"""# PROGRESS REPORT — CANONICAL OPERATIONAL VIEW (S77 §4.4 + §21)

> GENERATED by `scripts/s77_build_audit_views.py`. {NOW}
> Sources: `worklog.md` (per-wave sections), wave reports
> (`docs/foundation/s7[5-6]*/`, `docs/evidence/S7[34]/`), this wave's audit.
> Status vocabulary: STARTED/DISCOVERED/IMPLEMENTED/TESTED/EXECUTED/OBSERVED/
> BLOCKED/NEXT/EVIDENCE per task — bare `DONE` is not used.

## S72 → S76 reconciliation (§21)

| Wave | Original requirement | Implemented/Executed/Observed | Current status | Superseded by | Remaining gap |
|---|---|---|---|---|---|
"""
    for wv, req, imp, sup, gap in recon:
        out += f"| {wv} | {req} | {imp} | {sup} | {gap.split(';')[0][:80]} | {gap} |\n"
    out += """
## S77 task progress (this wave)

| Task | STARTED | DISCOVERED | IMPLEMENTED | TESTED | EXECUTED | OBSERVED | BLOCKED | NEXT | EVIDENCE |
|---|---|---|---|---|---|---|---|---|---|
| §1 state+baseline | yes | binary stale (pre-S76), disk 100% full, run/ root-owned | binary rebuilt (make), disk freed 1.9G, run/ recreated | yes | battery+verifier+fidelity | 26/26, 26/26, 90/90 | — | keep as S77 gate | run/s77_baseline/, S77_REPORT |
| §2 S76 canonicalize | yes | F-151 gap; total=397 stale; 8 unpublished (5 S75+3 S76) | registry total→404 + canon note | yes | registry re-read | consistent | — | — | root_registry.json note |
| §3 missing-work discovery | yes | 20 distinct open items + 4 UNVERIFIABLE ledger rows | sweep archived in S77_REPORT | yes | — | — | — | feed §29 report | S77_REPORT §3 |
| §4 artifacts | yes | 6 artifact classes missing | 7 derived artifacts built (this script) | validator re-run | — | — | — | automate per-session append | docs/audit/*.md + sandbox_errors.json |
| §17 false-completion scan | yes | scanner absent | scripts/s77_false_completion_scan.py | run on canonical reports | — | — | — | enforce in CI-like gate | scan output in S77_REPORT |
| §19 historical sweep | yes | (agent sweep: 20 open items) | REQ-HIST registry present in master_audit (62 rows) | — | — | — | — | keep append-only | docs/audit/master_audit.json |
| F-152 producer trace | yes | Llt0;.w pc=808 null receiver (S76-registered) | — | — | — | — | no root cause this wave — kept OPEN (no speculative patch, §14 law) | producer trace of Llt0;.w receiver def-chain | registry F-152 |
| F-153 CJK dialog labels | yes | painter BitmapFont ASCII-only | — | — | — | — | OPEN (font/CJK family; ties to census B10) | route painter through CJK shaper | s76_dialog_restart_report.json |

## Honest debt summary (post-S77)

- PUBLISH_BLOCKED: 8+ commits local-only (no GH_TOKEN; constitution §52).
- Foundation census gaps: 16 PENDING + PARTIAL items (ITEM75-008..041 set) —
  tracked in `docs/audit/MASTER_CHECKLIST.md`, unchanged this wave unless
  explicitly fixed.
- Sandbox per-step lifecycle automation: seeded, not yet a per-run emitter.
"""
    w(f"{AUD}/PROGRESS_REPORT.md", out)

# ================= §4.6 EVIDENCE LINEAGE =================
def evidence_lineage_md():
    lines = [
        ("gmdice roll HUMAN_VISIBLE", "docs/compatibility/apps/gmdice.json + s74_ops AUDIT_TABLE",
         "dalvik_engine.cpp getText/length subsumption walk; android_shadows.cpp getBackground",
         "s76 probe scripts lineage (scripts/s75_*)",
         "docs/evidence/s76/gmdice_roll_visible/ run log + frames 0-3",
         "engine.log [R393-BG]/[R393-TINT] lines",
         "frames/01..03.png (roll '6' then '5')", "bundle manifest + engine log",
         "#17 (gmdice ledger issue)", "VERIFIED at chain level; dossier visual_evidence=HUMAN_VISIBLE"),
        ("snake dialog restart OBSERVED", "docs/evidence/s76/snake_dialog_restart/",
         "dialog_shadow.{h,cpp} + execution_engine.cpp F117 site",
         "scripts/s76_snake_dialog_restart.py (two-run proof)",
         "run_a/run_b frame timelines", "s76_dialog_restart_report.json",
         "restart frame 99 captures", "run SHA256SUMS",
         "#13 (snake ledger issue)", "OBSERVED; F-153 label-paint residual honest"),
        ("icon decode A7b DETERMINISTIC", "docs/foundation/s76/S76_REPORT.md §4",
         "execution_engine.cpp A7b chain (resid→arsc→decode_image_bytes)",
         "f54 verifier gate (strengthened S76)", "run/s77_baseline/f54_manifestlabel/engine.log",
         "[A7b] icon DECODED line", "n/a (identity chain, not pixel claim)",
         "fnv1a 0x8a66dfd69a301225 identical f54+gmdice", "#18 (icon decode note)",
         "CAPABILITY proven; Bitmap/Drawable object law NOT claimed"),
        ("dooz F-146 FIX", "root_registry.json F-146", "dalvik_engine.cpp R-NEW-347 block",
         "battery+verifier+fidelity gates", "docs/evidence/s76/dooz_f146_upstream/",
         "F141-DIAG logs; [R347-FILE] lines", "n/a", "probe bundle logs",
         "#14 (dooz)", "ROOT-CAUSED-FIXED; successor F-152 OPEN"),
        ("baseline 26/26 (S77)", "S77_REPORT", "no code change — gate only",
         "scripts/s77_baseline_battery.sh", "run/s77_baseline/battery.jsonl",
         "per-fixture engine.log", "per-fixture screenshot.png", "battery.jsonl rc fields",
         "n/a", "OBSERVED 2026-09-22"),
        ("fidelity 90/90 (S77)", "S77_REPORT", "no code change — gate only",
         "scripts/s75_fidelity_probe.py", "docs/evidence/s75/snake_fidelity_probe/",
         "probe report json verdict", "byte-identical frame set", "probe json",
         "n/a", "BYTE-IDENTICAL 90/90 at a8704916"),
        ("verifier 26/26 (S77)", "S77_REPORT", "no code change — gate only",
         "scripts/s77_verifier.py", "run/s77_baseline/",
         "nonwhite-pixel compare vs stored baselines", "screenshot.png per fixture",
         "verifier stdout", "n/a", "26/26 SAME + A7B_GATE_OK"),
        ("Telegram NOT run at HEAD (honest)", "docs/evidence/S74/S74_REPORT.md:112",
         "n/a", "n/a", "s74_ops/telegram/session.json (v12 bounded run)",
         "session.json blocker record", "engine-default face recorded",
         "session sha block", "#16", "UNVERIFIED-at-HEAD — honestly recorded, not inflated"),
    ]
    out = f"""# EVIDENCE LINEAGE — KEY CLAIMS (S77 §4.6)

> GENERATED by `scripts/s77_build_audit_views.py`. {NOW}
> Law: a claim that cannot walk `CLAIM → SOURCE → CODE → TEST → EXECUTION →
> TRACE → SCREENSHOT → SHA → ISSUE` is NOT DONE — it is downgraded. Where a
> link is genuinely absent the cell says so.

| CLAIM | SOURCE | CODE | TEST | EXECUTION | TRACE | SCREENSHOT | SHA | ISSUE | VERDICT |
|---|---|---|---|---|---|---|---|---|---|
"""
    for row in lines:
        out += "| " + " | ".join(str(x)[:80].replace("|", "\\|").replace("\n", " ") for x in row) + " |\n"
    out += """
## Downgraded claims (audit outcome)

- **"sandbox lifecycle operational for every runnable APK"** — DOWNGRADED to
  SEEDED (SBX records built from real probes; per-step emitter not automated).
- **"persistence proven corpus-wide"** — remains **PARTIAL**: only unote has
  an observed close/reopen record; 13 apps NOT_OBSERVED (dossier
  persistence blocks are the canonical record).
- **"security observed"** — remains **PROFILED** for the corpus: dossiers
  carry manifest-declared permission/component profiles; runtime
  permission/network observation is NOT_OBSERVED for all 14 apps.
- **ASC tooling** — RESEARCHED_ONLY unless a dossier/tool record shows
  concrete consumption (checked in S77_REPORT §8; registry stays honest).
"""
    w(f"{AUD}/EVIDENCE_LINEAGE.md", out)

# ================= §13 APP MATRIX =================
def app_matrix_md():
    out = f"""# APP MATRIX — 14 CANONICAL APKs (S77 §13)

> GENERATED by `scripts/s77_build_audit_views.py`. {NOW}
> Canonical per-app records: `docs/compatibility/apps/*.json` (dossiers) +
> `docs/evidence/s74_ops/<app>/session.json`. No inflation: statuses are the
> dossier/ops values verbatim; NOT_RECORDED where absent.

| APP | APK_SHA256_16 | SOURCE_IDENTITY | LAUNCH | VIEW/RENDER | INPUT | STATE_CHANGE | HUMAN_VISIBLE | PERSISTENCE | SECURITY | SANDBOX | OPEN_BLOCKER | SESSION | ISSUE |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
"""
    for app_id, d in sorted(dossiers.items()):
        apk16 = nr((d.get("apk") or {}).get("sha256_16"))
        ve = d.get("visual_evidence") or {}
        hv = ve.get("status", "NOT_RECORDED")
        block = d.get("blocker")
        bsum = (block or {}).get("summary") if isinstance(block, dict) else nr(block)
        per = (d.get("persistence") or {}).get("verdict", "NOT_RECORDED")
        sec = (d.get("security") or {}).get("network_observed") or "PROFILED (manifest)"
        row = [app_id, str(apk16), nr((d.get("source") or {}).get("kind") if isinstance(d.get("source"), dict) else nr(d.get("source"))),
               "rc0" if (ops.get("sessions", {}).get(app_id, {}) or {}).get("launch_run", {}).get("rc") == 1 else "per session",
               "dossier:rendering", "dossier:input", "dossier:state",
               str(hv), str(per), str(sec)[:30], "s74-ops probe",
               str(nr(bsum))[:60].replace("|", "\\|"), "s74_ops/" + app_id, nr(d.get("issue"))]
        out += "| " + " | ".join(str(x) for x in row) + " |\n"
    out += """

## Column provenance

- LAUNCH: ops-session launch_run rc (engine **SUCCESS** path); full detail in
  the session json.
- HUMAN_VISIBLE: dossier `visual_evidence.status` — validator-enforced
  (HUMAN_VISIBLE requires existing representative frame files).
- PERSISTENCE: dossier `persistence.verdict` (WRITE→CLOSE→EXIT→REOPEN→READ→
  SEMANTIC COMPARE chain only for unote; SHA-only where present = PARTIAL by
  §6 law; rest NOT_OBSERVED).
- SECURITY: manifest-declared profile + runtime observation state (§7 law:
  PROFILED ≠ OBSERVED).
"""
    w(f"{AUD}/APP_MATRIX.md", out)

# ---------------- main ----------------
def main():
    w(f"{AUD}/RUNTIME_FAILURE_REGISTRY.md", f_registry_md())
    w(f"{AUD}/CRASH_HANG_ANR_REGISTRY.md", crash_registry_md())
    sandbox_report()
    session_chain_md()
    progress_report_md()
    evidence_lineage_md()
    app_matrix_md()
    print("S77 audit views built.")

if __name__ == "__main__":
    main()

# ================= §12 BLAST RADIUS =================
def blast_radius_md():
    out = f"""# BLAST RADIUS — SEMANTIC LAW CONSUMER MAP (S77 §12)

> GENERATED by `scripts/s77_build_audit_views.py`. {NOW}
> Derived from `/root_registry.json` R-NEW records ('affected'/'evidence'
> consumer lists) + knowledge records' consumers. Purpose: before any global
> runtime change, enumerate the consumers that MUST be regression-checked.

"""
    # R-NEW-390/391 File family
    out += """## R-NEW-390 / R-NEW-391 — File.getAbsoluteFile / getCanonicalFile

```
java.io.File.getAbsoluteFile / getCanonicalFile (R-NEW-347 block)
├── dooz_23 (DataStore file-name lambda Lg8;.a + singleton guard Lot;.a)  [S76 consumer, fixed]
├── DataStore preferences-protobuf chain (androidx.datastore.*)          [downstream consumer]
└── future File consumers (any app touching app-data-root absolute paths) [latent]
```
Regression class: RUNTIME-GLOBAL (dalvik_engine.cpp R-NEW-347 block) →
full battery (26/26) + verifier (26/26) + Level C fidelity (90/90) mandatory.

## R-NEW-392 — TextView subsumption (getText/length via superclass walk)

```
TextView.getText / length ancestry dispatch
├── Button (gmdice roll button '3D20')                [S76 consumer, fixed]
├── TextView/EditText/CheckBox subclasses generally    [latent, corpus-wide]
└── CharSequence.toString consumers of getText         [latent]
```
Regression class: RUNTIME-GLOBAL (intercept dispatch) → full gates mandatory.

## R-NEW-393 — View.getBackground themed-widget + Drawable.setColorFilter

```
View.getBackground (Widget.* theme family)
├── gmdice onCreate button-tint loop                   [S76 consumer, fixed]
├── Button/TextView/EditText/ImageView family          [latent]
└── Drawable.setColorFilter tint record                [served; framebuffer tint NOT claimed]
```

## R-NEW-394 — Dialog decor layout + topmost-window touch

```
DialogWindow decor bounds + decor_root_at routing
├── snake game-over dialog (重新开始/退出 buttons)      [S76 consumer, fixed]
├── AlertDialog family corpus-wide (unote delete-confirm, microtimer dialogs) [latent]
└── F117 tap site (execution_engine.cpp)               [dispatch path]
```

## TextView subsumption vs F-148 ConstraintLayout (structure laws)

```
ConstraintLayout anchor family (F-148)
├── AndroidGameSnake activity_main.xml                 [S72 consumer, fixed]
├── any layout with layout_constraint* attrs           [latent]
```

## F-153 — dialog painter font (OPEN)

```
DialogShadow painter BitmapFont (ASCII-only)
├── snake dialog CJK labels (0 px painted)             [OPEN]
└── any dialog with non-ASCII button labels            [latent — corpus-wide CJK exposure]
```
"""
    w(f"{AUD}/BLAST_RADIUS.md", out)

# extend main
_orig_main = main
def main():  # noqa: F811
    _orig_main()
    blast_radius_md()
