#!/usr/bin/env python3
"""S95-FOLLOWUP part 2 — render docs/VERIFIED_EXECUTED_GAMES.md from
docs/verified_executed_games.json (generated by scripts/s96_games_audit.py)."""

import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
M = json.load(open('docs/verified_executed_games.json'))
S = M['summary']
GH = 'https://github.com/Sh-TB/MiniAndroid-Compatibility-Runtime/blob/main/'

def gh(path):
    return GH + path

def rel(p):
    """repo-relative -> file-relative link for a doc living in docs/"""
    if p.startswith('docs/'):
        return p[len('docs/'):]
    if p.startswith(('games/', 'registry/')):
        return '../' + p
    return p

def art_link(rec):
    p = rec['screenshot']['path']
    return f"[{os.path.basename(p)}]({rel(p)})"

def src_link(rec):
    up = rec['upstream']
    if up.startswith('in-house'):
        d = up.split('—')[1].strip().split(' ')[0]
        return f"[in-house source]({rel(d)}/)"
    if up.startswith('F-Droid'):
        return up + (f" · [page]({rec['fdroid']})" if rec['fdroid'] else '')
    return f"[source]({up})" + (f" · [F-Droid]({rec['fdroid']})" if rec['fdroid'] else '')

L = []
w = L.append

w('# VERIFIED EXECUTED GAMES — authoritative audit (S95-FOLLOWUP)')
w('')
w('> **Evidence wave — zero runtime changes.** This file answers, with no guessing:')
w('> *which games actually executed inside MiniAndroid, what exactly was proven,')
w('> and where the permanent evidence lives.*')
w('')
w('- Identity + status + artifact hashes come from the canonical registry')
w('  [evidence/canonical/registry.json](evidence/canonical/registry.json)')
w('  (no second competing registry — this audit **references** it).')
w('- Machine-readable index: [docs/verified_executed_games.json](verified_executed_games.json)')
w('- Generated by `scripts/s96_games_audit.py`; every curated record was')
w('  cross-checked against the registry (title/package/SHA) — mismatch = build failure.')
w('- Historical evidence is NOT modified; downgrades are recorded here only.')
w('')
w('## Evidence levels (E0–E6)')
w('')
w('| Level | Meaning |')
w('|---|---|')
for k, v in M['evidence_levels'].items():
    w(f"| {k} | {v} |")
w('')
w('**Strict status vocabulary:** `VERIFIED / TESTED / OBSERVED / PARTIAL / FAILED / BLOCKED / PENDING`.')
w('A screenshot file alone, an exit code, or an `OBSERVED` status is **never** execution proof.')
w('A game is `VERIFIED` only when repo-recorded runtime evidence supports the execution')
w('semantics (launched → real frames → interaction → state change where claimed).')
w('')
w('---')
w('')
w('## A. Headline counts')
w('')
w('| Metric | Count |')
w('|---|---|')
w(f"| Corpus titles (canonical) | **{S['corpus_titles']}** |")
w(f"| Games in corpus | **{S['games_total']}** |")
w(f"| Games with REAL execution evidence (canonical runtime artifact + session + SHA) | **{S['games_with_real_execution_evidence']}** |")
w(f"| — VERIFIED games | **{S['games_verified']}** |")
w(f"| — PARTIAL games (executed + visuals contested) | {S['games_partial']} |")
w(f"| — downgraded to OBSERVED by this audit | {S['games_downgraded']} |")
w(f"| Games executed with trace-only evidence (E3, no meaningful visual) | {S['games_observed_no_artifact']} |")
w(f"| VERIFIED games with state-change proof | **{S['verified_games_with_state_change']}** |")
w(f"| Games with meaningful screenshot proof (VERIFIED+PARTIAL) | **{S['games_with_meaningful_screenshot']}** |")
w(f"| Games with repeated-run proof (≥2 recorded executions) | **{S['games_with_repeated_run_proof']}** |")
w(f"| Games at E5 (deterministic repeated execution) | **{S['games_at_E5']}** |")
w(f"| Strongest evidence level achieved by any game | **E5** (E6 is a law-level record, not per-game) |")
w('')
w('---')
w('')
w('## B. Verification of the “22 VERIFIED” claim')
w('')
c = S['claim_22_verified']
w(f"The canonical registry contains **{c['count']}** entries with status `VERIFIED` "
  f"({c['games']} games · {c['apps']} apps · {c['fixture']} fixture). "
  f"The 12 interactive-GIF titles are **not** part of these 22 — they carry "
  f"`candidate_*` / `FRAME_CAPTURED` / `FAILED` statuses in the registry (S92 §29 "
  f"human-review gate was never executed; see inconsistency AUD-IC-6).")
w('')
w('| Category | Titles |')
w('|---|---|')
w(f"| VERIFIED games ({c['games']}) | " + ', '.join(f"`{t}`" for t in c['game_titles']) + ' |')
w(f"| VERIFIED apps ({c['apps']}) | " + ', '.join(f"`{t}`" for t in c['app_titles']) + ' |')
w(f"| VERIFIED fixture ({c['fixture']}) | " + ', '.join(f"`{t}`" for t in c['fixture_titles']) + ' |')
w('')
w('**Verdict:** the “22 VERIFIED” number is real but is **not 22 games** — it is '
  '11 games + 10 apps + 1 fixture. Interactive execution proof lives in the separate '
  '12-title GIF family (11 games + 1 app).')
w('')
w('### Evidence downgrades required (applied in this audit only)')
w('')
for d in c['downgrades']:
    w(f"- **{d['id']} — {d['title']}** (`{d['package']}`): {d['reason']}. → {d['action']}.")
w('')
w('### Classification inconsistencies recorded')
w('')
for ic in S['inconsistencies']:
    w(f"- **{ic['id']} — {ic['title']}:** {ic['detail']}")
w('')
w('---')
w('')
w('## B2. Compact game table (all games with real execution evidence)')
w('')
w('| Game | Package | Status | Evidence | State Change | Screenshot | Issue |')
w('|---|---|---|---|---|---|---|')
for rec in sorted(M['games'], key=lambda r: (r['audit_status'] != 'VERIFIED', r['title'])):
    st = rec['state_change_evidence']
    sc_txt = 'YES' if st else '—'
    w(f"| {rec['title']} | `{rec['package']}` | {rec['audit_status']} | {rec['evidence_level']} | {sc_txt} | "
      f"[{os.path.basename(rec['screenshot']['path'])}]({rel(rec['screenshot']['path'])}) | {rec['issue_status']} |")
w('')
w('---')
w('')
w('## C. VERIFIED games — full evidence records')
w('')
w('Execution protocol, state-change proof, screenshot SHA, run counts — all as recorded.')
w('')
for rec in M['games']:
    if rec['audit_status'] != 'VERIFIED':
        continue
    sc = rec['screenshot']
    apk = rec['apk_sha256'] or '— (built in-repo; zero-APK law)'
    w(f"### {rec['title']}")
    w('')
    w(f"| Field | Value |")
    w(f"|---|---|")
    w(f"| Package | `{rec['package']}` |")
    w(f"| Version | {rec['version']} |")
    w(f"| Upstream | {src_link(rec)} |")
    w(f"| APK SHA256 | `{apk}` |")
    w(f"| MiniAndroid status | **{rec['audit_status']}** (registry: `{rec['registry_status']}`) |")
    w(f"| Evidence level | **{rec['evidence_level']}** · {rec['render_level']} |")
    w(f"| Sessions | {rec['sessions']} |")
    w(f"| Execution protocol | {rec['execution_protocol']} |")
    w(f"| State-change proof | {rec['state_change_evidence'] or '— (non-interactive verification)'} |")
    w(f"| Screenshot | {art_link(rec)} · SHA256 `{sc['sha256'][:16]}…`"
      + (f" · {sc['gif_frames']} frames" if sc.get('gif_frames') else '') + ' |')
    w(f"| Recorded runs | {rec['recorded_runs']} — {rec['runs_evidence']} |")
    w(f"| GitHub issue | **{rec['issue_status']}** (permanent evidence = repo paths below; no issue invented) |")
    w(f"| Last verified commit | `{rec['last_verified_commit']}` |")
    w(f"| Known limitations | {rec['limitations']} |")
    w(f"| Ticket | " + (f"[{rec['ticket']}](TICKET_REGISTRY.json)" if rec['ticket'] else '—') + ' |')
    w(f"| Permanent evidence | " + ' · '.join(f"[{os.path.basename(p)}]({rel(p)})" for p in rec['permanent_evidence']) + ' |')
    w('')

w('---')
w('')
w('## D. PARTIAL games (executed; visual semantics contested)')
w('')
for rec in M['games']:
    if rec['audit_status'] != 'PARTIAL':
        continue
    sc = rec['screenshot']
    apk = rec['apk_sha256'] or '—'
    w(f"### {rec['title']} — PARTIAL")
    w('')
    w(f"- Package `{rec['package']}` · version {rec['version']} · APK `{apk}`")
    w(f"- Upstream: {src_link(rec)}")
    w(f"- Evidence: **{rec['evidence_level']}** · {rec['render_level']} · sessions {rec['sessions']}")
    w(f"- Interaction/state: {rec['state_change_evidence'] or 'none recorded'}")
    w(f"- Screenshot: {art_link(rec)} · SHA `{sc['sha256'][:16]}…`")
    w(f"- Why PARTIAL: {rec['limitations']}")
    w(f"- Runs: {rec['recorded_runs']} ({rec['runs_evidence']})")
    w('')
w('---')
w('')
w('## E. Executed games with trace-only evidence (E3, no meaningful visual)')
w('')
w('These 64 games DID run on MiniAndroid (launched + frames captured + session logged in the')
w('canonical registry), but the recorded frames are engine-default/blank-class or below the')
w('render threshold — per the S54 screenshot-gate law they carry **no visual claim**. Full')
w('per-title data: [verified_executed_games.json](verified_executed_games.json) → `observed_games`.')
w('')
w('| Title | Package | Registry status | Level | Session | Launched/Rendered |')
w('|---|---|---|---|---|---|')
for o in M['observed_games']:
    w(f"| {o['title']} | `{o['package']}` | {o['registry_status']} | {o['level']} | {o['session'] or '—'} | {o['launched']}/{o['rendered']} |")
w('')
w('---')
w('')
w('## F. Evidence gaps')
w('')
w('1. **Executed but evidence incomplete** — FreeKlondike, TriPeaks, OpenSudoku, Anuto TD have')
w('   L5–L10 screenshots but **no APK SHA256 recorded** in the canonical registry (identity gap).')
w('2. **Screenshot but no state change** — Anuto TD, OpenSudoku, OPMT, adnihilation, Mines,')
w('   Balance the Ball, all_in_gold, ballbreak (click probe probed=2, state_changed=0),')
w('   FreeKlondike, TriPeaks: no interaction→state proof recorded.')
w('3. **Interaction but weak visual proof** — TicTacToe Classic: click→state GIF exists (S83)')
w('   but S92 fresh-SHA graphics verify FAILED (scene/frame_output/visual) → held at PARTIAL.')
w('4. **Repeated execution missing** — TicTacToe Deluxe, FreeKlondike, TriPeaks, adnihilation,')
w('   Mines, all_in_gold, Memory: single recorded session, no repeat protocol.')
w('5. **Issue missing** — every game in this audit: **MISSING_ISSUE**. Per-title GitHub issues')
w('   were never opened; permanent evidence currently lives in repo paths only.')
w('6. **S92 §29 promotion gate never executed** — 7 GIF titles remain `candidate_*` in the')
w('   registry while ACHIEVEMENTS prints VERIFIED-INTERACTIVE (AUD-IC-6).')
w('')
w('## G. Next actions (evidence-driven queue — no runtime work in this wave)')
w('')
w('| # | Action | Converts | Why first |')
w('|---|---|---|---|')
w('| 1 | Execute the S92 §29 human-review promotion for the 7 `candidate_*` titles using existing S95 measured verdicts (hotdeath SEMANTIC_PASS, bobball/tetris/minicraft PARTIAL(0), 2048 no failing stages) | registry drift → consistency | zero new runtime work; closes AUD-IC-2/3/6 |')
w('| 2 | Record APK SHA256 for FreeKlondike / TriPeaks / OpenSudoku / Anuto TD (re-fetch + hash) | identity gap → audit-proof identity | cheap; closes gap F.1 |')
w('| 3 | Run the existing S95 tap-capture protocol on Fish Rings-class static VERIFIED titles (OpenSudoku, FreeKlondike, Anuto TD, OPMT) to add state-change proof | VERIFIED(static) → VERIFIED(interactive) | protocol already exists (`scripts/s95_capture.py`) |')
w('| 4 | x3 deterministic repeat for Snake-class GIF titles lacking it (2048, TicTacToe Deluxe, dodge, bouncy, nounours, hotdeath, bobball) | E4 → E5 | wave_c harness already supports it |')
w('| 5 | Open per-game GitHub issues for the 11 VERIFIED interactive games linking GIF + SHA + run records | MISSING_ISSUE → permanent linkable evidence | pure documentation |')
w('| 6 | GFX-002 (LinearLayout weights) then re-capture dodge + bouncy menus | PARTIAL visuals → SEMANTIC_PASS | largest measured visual fan-out (S95: dodge 3 flags, bouncy 1) |')
w('')
w('## Validation')
w('')
w('```')
w('python3 scripts/s96_games_audit.py   # rebuilds JSON + cross-checks registry/SHAs')
w('python3 scripts/s96_validate_audit.py   # link/SHA/duplicate/count gate')
w('python3 tools/verify_canonical_evidence.py')
w('python3 tools/validate_control_system.py')
w('```')
w('')

with open('docs/VERIFIED_EXECUTED_GAMES.md', 'w') as f:
    f.write('\n'.join(L))
print('OK: docs/VERIFIED_EXECUTED_GAMES.md written,', len(L), 'lines')
