/* brackets.tab.i
 * generated by gen-brackets-tab (fribidi 1.0.16)
 * from the file BidiBrackets.txt of Unicode version 16.0.0. */

#define PACKTAB_UINT8 uint8_t
#define PACKTAB_UINT16 uint16_t
#define PACKTAB_UINT32 uint32_t

/*
  generated by packtab.c version 3

  use FRIBIDI_GET_BRACKETS_DELTA(key) to access your table

  assumed sizeof(int32_t): 4
  required memory: 808
  lookups: 4
  partition shape: Brk[128][16][8][4]
  different table entries: 1 11 23 20
*/

/* *INDENT-OFF* */

static const int32_t BrkLev3[4*20] = {
#define BrkLev3_0000 0x0
  0,0,0,0,
#define BrkLev3_0028 0x4
  0,-1,0,0,
#define BrkLev3_005C 0x8
  0,-2,0,0,
#define BrkLev3_0F38 0xC
  0,0,0,-1,
#define BrkLev3_169C 0x10
  -1,0,0,0,
#define BrkLev3_2044 0x14
  0,0,-1,0,
#define BrkLev3_207C 0x18
  0,-8277,-8278,0,
#define BrkLev3_208C 0x1C
  0,-8293,-8294,0,
#define BrkLev3_2308 0x20
  0,-1,0,-1,
#define BrkLev3_2328 0x24
  0,3295,3294,0,
#define BrkLev3_2984 0x28
  -1,0,-1,0,
#define BrkLev3_298C 0x2C
  -1,0,1,0,
#define BrkLev3_2990 0x30
  -3,0,-1,0,
#define BrkLev3_FE58 0x34
  0,-65073,-65074,-64992,
#define BrkLev3_FE5C 0x38
  -64993,-52809,-52810,0,
#define BrkLev3_FF08 0x3C
  -65248,-65249,0,0,
#define BrkLev3_FF38 0x40
  0,0,0,-65248,
#define BrkLev3_FF3C 0x44
  0,-65250,0,0,
#define BrkLev3_FF5C 0x48
  0,-65250,0,-54746,
#define BrkLev3_FF60 0x4C
  -54747,0,-53078,-53079,
};

static const PACKTAB_UINT8 BrkLev2[8*23] = {
#define BrkLev2_0000 0x0
  BrkLev3_0000,  /* 0000..0003 */
  BrkLev3_0000,  /* 0004..0007 */
  BrkLev3_0000,  /* 0008..000B */
  BrkLev3_0000,  /* 000C..000F */
  BrkLev3_0000,  /* 0010..0013 */
  BrkLev3_0000,  /* 0014..0017 */
  BrkLev3_0000,  /* 0018..001B */
  BrkLev3_0000,  /* 001C..001F */
#define BrkLev2_0020 0x8
  BrkLev3_0000,  /* 0020..0023 */
  BrkLev3_0000,  /* 0024..0027 */
  BrkLev3_0028,  /* 0028..002B */
  BrkLev3_0000,  /* 002C..002F */
  BrkLev3_0000,  /* 0030..0033 */
  BrkLev3_0000,  /* 0034..0037 */
  BrkLev3_0000,  /* 0038..003B */
  BrkLev3_0000,  /* 003C..003F */
#define BrkLev2_0040 0x10
  BrkLev3_0000,  /* 0040..0043 */
  BrkLev3_0000,  /* 0044..0047 */
  BrkLev3_0000,  /* 0048..004B */
  BrkLev3_0000,  /* 004C..004F */
  BrkLev3_0000,  /* 0050..0053 */
  BrkLev3_0000,  /* 0054..0057 */
  BrkLev3_0000,  /* 0058..005B */
  BrkLev3_005C,  /* 005C..005F */
#define BrkLev2_0F20 0x18
  BrkLev3_0000,  /* 0F20..0F23 */
  BrkLev3_0000,  /* 0F24..0F27 */
  BrkLev3_0000,  /* 0F28..0F2B */
  BrkLev3_0000,  /* 0F2C..0F2F */
  BrkLev3_0000,  /* 0F30..0F33 */
  BrkLev3_0000,  /* 0F34..0F37 */
  BrkLev3_0F38,  /* 0F38..0F3B */
  BrkLev3_0028,  /* 0F3C..0F3F */
#define BrkLev2_1680 0x20
  BrkLev3_0000,  /* 1680..1683 */
  BrkLev3_0000,  /* 1684..1687 */
  BrkLev3_0000,  /* 1688..168B */
  BrkLev3_0000,  /* 168C..168F */
  BrkLev3_0000,  /* 1690..1693 */
  BrkLev3_0000,  /* 1694..1697 */
  BrkLev3_0000,  /* 1698..169B */
  BrkLev3_169C,  /* 169C..169F */
#define BrkLev2_2040 0x28
  BrkLev3_0000,  /* 2040..2043 */
  BrkLev3_2044,  /* 2044..2047 */
  BrkLev3_0000,  /* 2048..204B */
  BrkLev3_0000,  /* 204C..204F */
  BrkLev3_0000,  /* 2050..2053 */
  BrkLev3_0000,  /* 2054..2057 */
  BrkLev3_0000,  /* 2058..205B */
  BrkLev3_0000,  /* 205C..205F */
#define BrkLev2_2060 0x30
  BrkLev3_0000,  /* 2060..2063 */
  BrkLev3_0000,  /* 2064..2067 */
  BrkLev3_0000,  /* 2068..206B */
  BrkLev3_0000,  /* 206C..206F */
  BrkLev3_0000,  /* 2070..2073 */
  BrkLev3_0000,  /* 2074..2077 */
  BrkLev3_0000,  /* 2078..207B */
  BrkLev3_207C,  /* 207C..207F */
#define BrkLev2_2080 0x38
  BrkLev3_0000,  /* 2080..2083 */
  BrkLev3_0000,  /* 2084..2087 */
  BrkLev3_0000,  /* 2088..208B */
  BrkLev3_208C,  /* 208C..208F */
  BrkLev3_0000,  /* 2090..2093 */
  BrkLev3_0000,  /* 2094..2097 */
  BrkLev3_0000,  /* 2098..209B */
  BrkLev3_0000,  /* 209C..209F */
#define BrkLev2_2300 0x40
  BrkLev3_0000,  /* 2300..2303 */
  BrkLev3_0000,  /* 2304..2307 */
  BrkLev3_2308,  /* 2308..230B */
  BrkLev3_0000,  /* 230C..230F */
  BrkLev3_0000,  /* 2310..2313 */
  BrkLev3_0000,  /* 2314..2317 */
  BrkLev3_0000,  /* 2318..231B */
  BrkLev3_0000,  /* 231C..231F */
#define BrkLev2_2320 0x48
  BrkLev3_0000,  /* 2320..2323 */
  BrkLev3_0000,  /* 2324..2327 */
  BrkLev3_2328,  /* 2328..232B */
  BrkLev3_0000,  /* 232C..232F */
  BrkLev3_0000,  /* 2330..2333 */
  BrkLev3_0000,  /* 2334..2337 */
  BrkLev3_0000,  /* 2338..233B */
  BrkLev3_0000,  /* 233C..233F */
#define BrkLev2_2760 0x50
  BrkLev3_0000,  /* 2760..2763 */
  BrkLev3_0000,  /* 2764..2767 */
  BrkLev3_2308,  /* 2768..276B */
  BrkLev3_2308,  /* 276C..276F */
  BrkLev3_2308,  /* 2770..2773 */
  BrkLev3_0028,  /* 2774..2777 */
  BrkLev3_0000,  /* 2778..277B */
  BrkLev3_0000,  /* 277C..277F */
#define BrkLev2_27E0 0x58
  BrkLev3_0000,  /* 27E0..27E3 */
  BrkLev3_0F38,  /* 27E4..27E7 */
  BrkLev3_2308,  /* 27E8..27EB */
  BrkLev3_2308,  /* 27EC..27EF */
  BrkLev3_0000,  /* 27F0..27F3 */
  BrkLev3_0000,  /* 27F4..27F7 */
  BrkLev3_0000,  /* 27F8..27FB */
  BrkLev3_0000,  /* 27FC..27FF */
#define BrkLev2_2980 0x60
  BrkLev3_0000,  /* 2980..2983 */
  BrkLev3_2984,  /* 2984..2987 */
  BrkLev3_2984,  /* 2988..298B */
  BrkLev3_298C,  /* 298C..298F */
  BrkLev3_2990,  /* 2990..2993 */
  BrkLev3_2984,  /* 2994..2997 */
  BrkLev3_169C,  /* 2998..299B */
  BrkLev3_0000,  /* 299C..299F */
#define BrkLev2_29C0 0x68
  BrkLev3_0000,  /* 29C0..29C3 */
  BrkLev3_0000,  /* 29C4..29C7 */
  BrkLev3_0000,  /* 29C8..29CB */
  BrkLev3_0000,  /* 29CC..29CF */
  BrkLev3_0000,  /* 29D0..29D3 */
  BrkLev3_0000,  /* 29D4..29D7 */
  BrkLev3_2308,  /* 29D8..29DB */
  BrkLev3_0000,  /* 29DC..29DF */
#define BrkLev2_29E0 0x70
  BrkLev3_0000,  /* 29E0..29E3 */
  BrkLev3_0000,  /* 29E4..29E7 */
  BrkLev3_0000,  /* 29E8..29EB */
  BrkLev3_0000,  /* 29EC..29EF */
  BrkLev3_0000,  /* 29F0..29F3 */
  BrkLev3_0000,  /* 29F4..29F7 */
  BrkLev3_0000,  /* 29F8..29FB */
  BrkLev3_0028,  /* 29FC..29FF */
#define BrkLev2_2E20 0x78
  BrkLev3_0F38,  /* 2E20..2E23 */
  BrkLev3_2308,  /* 2E24..2E27 */
  BrkLev3_0028,  /* 2E28..2E2B */
  BrkLev3_0000,  /* 2E2C..2E2F */
  BrkLev3_0000,  /* 2E30..2E33 */
  BrkLev3_0000,  /* 2E34..2E37 */
  BrkLev3_0000,  /* 2E38..2E3B */
  BrkLev3_0000,  /* 2E3C..2E3F */
#define BrkLev2_2E40 0x80
  BrkLev3_0000,  /* 2E40..2E43 */
  BrkLev3_0000,  /* 2E44..2E47 */
  BrkLev3_0000,  /* 2E48..2E4B */
  BrkLev3_0000,  /* 2E4C..2E4F */
  BrkLev3_0000,  /* 2E50..2E53 */
  BrkLev3_2044,  /* 2E54..2E57 */
  BrkLev3_2984,  /* 2E58..2E5B */
  BrkLev3_169C,  /* 2E5C..2E5F */
#define BrkLev2_3000 0x88
  BrkLev3_0000,  /* 3000..3003 */
  BrkLev3_0000,  /* 3004..3007 */
  BrkLev3_2308,  /* 3008..300B */
  BrkLev3_2308,  /* 300C..300F */
  BrkLev3_0028,  /* 3010..3013 */
  BrkLev3_2308,  /* 3014..3017 */
  BrkLev3_2308,  /* 3018..301B */
  BrkLev3_0000,  /* 301C..301F */
#define BrkLev2_FE40 0x90
  BrkLev3_0000,  /* FE40..FE43 */
  BrkLev3_0000,  /* FE44..FE47 */
  BrkLev3_0000,  /* FE48..FE4B */
  BrkLev3_0000,  /* FE4C..FE4F */
  BrkLev3_0000,  /* FE50..FE53 */
  BrkLev3_0000,  /* FE54..FE57 */
  BrkLev3_FE58,  /* FE58..FE5B */
  BrkLev3_FE5C,  /* FE5C..FE5F */
#define BrkLev2_FF00 0x98
  BrkLev3_0000,  /* FF00..FF03 */
  BrkLev3_0000,  /* FF04..FF07 */
  BrkLev3_FF08,  /* FF08..FF0B */
  BrkLev3_0000,  /* FF0C..FF0F */
  BrkLev3_0000,  /* FF10..FF13 */
  BrkLev3_0000,  /* FF14..FF17 */
  BrkLev3_0000,  /* FF18..FF1B */
  BrkLev3_0000,  /* FF1C..FF1F */
#define BrkLev2_FF20 0xA0
  BrkLev3_0000,  /* FF20..FF23 */
  BrkLev3_0000,  /* FF24..FF27 */
  BrkLev3_0000,  /* FF28..FF2B */
  BrkLev3_0000,  /* FF2C..FF2F */
  BrkLev3_0000,  /* FF30..FF33 */
  BrkLev3_0000,  /* FF34..FF37 */
  BrkLev3_FF38,  /* FF38..FF3B */
  BrkLev3_FF3C,  /* FF3C..FF3F */
#define BrkLev2_FF40 0xA8
  BrkLev3_0000,  /* FF40..FF43 */
  BrkLev3_0000,  /* FF44..FF47 */
  BrkLev3_0000,  /* FF48..FF4B */
  BrkLev3_0000,  /* FF4C..FF4F */
  BrkLev3_0000,  /* FF50..FF53 */
  BrkLev3_0000,  /* FF54..FF57 */
  BrkLev3_FF38,  /* FF58..FF5B */
  BrkLev3_FF5C,  /* FF5C..FF5F */
#define BrkLev2_FF60 0xB0
  BrkLev3_FF60,  /* FF60..FF63 */
  BrkLev3_0000,  /* FF64..FF67 */
  BrkLev3_0000,  /* FF68..FF6B */
  BrkLev3_0000,  /* FF6C..FF6F */
  BrkLev3_0000,  /* FF70..FF73 */
  BrkLev3_0000,  /* FF74..FF77 */
  BrkLev3_0000,  /* FF78..FF7B */
  BrkLev3_0000,  /* FF7C..FF7F */
};

static const PACKTAB_UINT8 BrkLev1[16*11] = {
#define BrkLev1_0000 0x0
  BrkLev2_0000,  /* 0000..001F */
  BrkLev2_0020,  /* 0020..003F */
  BrkLev2_0040,  /* 0040..005F */
  BrkLev2_0040,  /* 0060..007F */
  BrkLev2_0000,  /* 0080..009F */
  BrkLev2_0000,  /* 00A0..00BF */
  BrkLev2_0000,  /* 00C0..00DF */
  BrkLev2_0000,  /* 00E0..00FF */
  BrkLev2_0000,  /* 0100..011F */
  BrkLev2_0000,  /* 0120..013F */
  BrkLev2_0000,  /* 0140..015F */
  BrkLev2_0000,  /* 0160..017F */
  BrkLev2_0000,  /* 0180..019F */
  BrkLev2_0000,  /* 01A0..01BF */
  BrkLev2_0000,  /* 01C0..01DF */
  BrkLev2_0000,  /* 01E0..01FF */
#define BrkLev1_0200 0x10
  BrkLev2_0000,  /* 0200..021F */
  BrkLev2_0000,  /* 0220..023F */
  BrkLev2_0000,  /* 0240..025F */
  BrkLev2_0000,  /* 0260..027F */
  BrkLev2_0000,  /* 0280..029F */
  BrkLev2_0000,  /* 02A0..02BF */
  BrkLev2_0000,  /* 02C0..02DF */
  BrkLev2_0000,  /* 02E0..02FF */
  BrkLev2_0000,  /* 0300..031F */
  BrkLev2_0000,  /* 0320..033F */
  BrkLev2_0000,  /* 0340..035F */
  BrkLev2_0000,  /* 0360..037F */
  BrkLev2_0000,  /* 0380..039F */
  BrkLev2_0000,  /* 03A0..03BF */
  BrkLev2_0000,  /* 03C0..03DF */
  BrkLev2_0000,  /* 03E0..03FF */
#define BrkLev1_0E00 0x20
  BrkLev2_0000,  /* 0E00..0E1F */
  BrkLev2_0000,  /* 0E20..0E3F */
  BrkLev2_0000,  /* 0E40..0E5F */
  BrkLev2_0000,  /* 0E60..0E7F */
  BrkLev2_0000,  /* 0E80..0E9F */
  BrkLev2_0000,  /* 0EA0..0EBF */
  BrkLev2_0000,  /* 0EC0..0EDF */
  BrkLev2_0000,  /* 0EE0..0EFF */
  BrkLev2_0000,  /* 0F00..0F1F */
  BrkLev2_0F20,  /* 0F20..0F3F */
  BrkLev2_0000,  /* 0F40..0F5F */
  BrkLev2_0000,  /* 0F60..0F7F */
  BrkLev2_0000,  /* 0F80..0F9F */
  BrkLev2_0000,  /* 0FA0..0FBF */
  BrkLev2_0000,  /* 0FC0..0FDF */
  BrkLev2_0000,  /* 0FE0..0FFF */
#define BrkLev1_1600 0x30
  BrkLev2_0000,  /* 1600..161F */
  BrkLev2_0000,  /* 1620..163F */
  BrkLev2_0000,  /* 1640..165F */
  BrkLev2_0000,  /* 1660..167F */
  BrkLev2_1680,  /* 1680..169F */
  BrkLev2_0000,  /* 16A0..16BF */
  BrkLev2_0000,  /* 16C0..16DF */
  BrkLev2_0000,  /* 16E0..16FF */
  BrkLev2_0000,  /* 1700..171F */
  BrkLev2_0000,  /* 1720..173F */
  BrkLev2_0000,  /* 1740..175F */
  BrkLev2_0000,  /* 1760..177F */
  BrkLev2_0000,  /* 1780..179F */
  BrkLev2_0000,  /* 17A0..17BF */
  BrkLev2_0000,  /* 17C0..17DF */
  BrkLev2_0000,  /* 17E0..17FF */
#define BrkLev1_2000 0x40
  BrkLev2_0000,  /* 2000..201F */
  BrkLev2_0000,  /* 2020..203F */
  BrkLev2_2040,  /* 2040..205F */
  BrkLev2_2060,  /* 2060..207F */
  BrkLev2_2080,  /* 2080..209F */
  BrkLev2_0000,  /* 20A0..20BF */
  BrkLev2_0000,  /* 20C0..20DF */
  BrkLev2_0000,  /* 20E0..20FF */
  BrkLev2_0000,  /* 2100..211F */
  BrkLev2_0000,  /* 2120..213F */
  BrkLev2_0000,  /* 2140..215F */
  BrkLev2_0000,  /* 2160..217F */
  BrkLev2_0000,  /* 2180..219F */
  BrkLev2_0000,  /* 21A0..21BF */
  BrkLev2_0000,  /* 21C0..21DF */
  BrkLev2_0000,  /* 21E0..21FF */
#define BrkLev1_2200 0x50
  BrkLev2_0000,  /* 2200..221F */
  BrkLev2_0000,  /* 2220..223F */
  BrkLev2_0000,  /* 2240..225F */
  BrkLev2_0000,  /* 2260..227F */
  BrkLev2_0000,  /* 2280..229F */
  BrkLev2_0000,  /* 22A0..22BF */
  BrkLev2_0000,  /* 22C0..22DF */
  BrkLev2_0000,  /* 22E0..22FF */
  BrkLev2_2300,  /* 2300..231F */
  BrkLev2_2320,  /* 2320..233F */
  BrkLev2_0000,  /* 2340..235F */
  BrkLev2_0000,  /* 2360..237F */
  BrkLev2_0000,  /* 2380..239F */
  BrkLev2_0000,  /* 23A0..23BF */
  BrkLev2_0000,  /* 23C0..23DF */
  BrkLev2_0000,  /* 23E0..23FF */
#define BrkLev1_2600 0x60
  BrkLev2_0000,  /* 2600..261F */
  BrkLev2_0000,  /* 2620..263F */
  BrkLev2_0000,  /* 2640..265F */
  BrkLev2_0000,  /* 2660..267F */
  BrkLev2_0000,  /* 2680..269F */
  BrkLev2_0000,  /* 26A0..26BF */
  BrkLev2_0000,  /* 26C0..26DF */
  BrkLev2_0000,  /* 26E0..26FF */
  BrkLev2_0000,  /* 2700..271F */
  BrkLev2_0000,  /* 2720..273F */
  BrkLev2_0000,  /* 2740..275F */
  BrkLev2_2760,  /* 2760..277F */
  BrkLev2_0000,  /* 2780..279F */
  BrkLev2_0000,  /* 27A0..27BF */
  BrkLev2_2040,  /* 27C0..27DF */
  BrkLev2_27E0,  /* 27E0..27FF */
#define BrkLev1_2800 0x70
  BrkLev2_0000,  /* 2800..281F */
  BrkLev2_0000,  /* 2820..283F */
  BrkLev2_0000,  /* 2840..285F */
  BrkLev2_0000,  /* 2860..287F */
  BrkLev2_0000,  /* 2880..289F */
  BrkLev2_0000,  /* 28A0..28BF */
  BrkLev2_0000,  /* 28C0..28DF */
  BrkLev2_0000,  /* 28E0..28FF */
  BrkLev2_0000,  /* 2900..291F */
  BrkLev2_0000,  /* 2920..293F */
  BrkLev2_0000,  /* 2940..295F */
  BrkLev2_0000,  /* 2960..297F */
  BrkLev2_2980,  /* 2980..299F */
  BrkLev2_0000,  /* 29A0..29BF */
  BrkLev2_29C0,  /* 29C0..29DF */
  BrkLev2_29E0,  /* 29E0..29FF */
#define BrkLev1_2E00 0x80
  BrkLev2_0000,  /* 2E00..2E1F */
  BrkLev2_2E20,  /* 2E20..2E3F */
  BrkLev2_2E40,  /* 2E40..2E5F */
  BrkLev2_0000,  /* 2E60..2E7F */
  BrkLev2_0000,  /* 2E80..2E9F */
  BrkLev2_0000,  /* 2EA0..2EBF */
  BrkLev2_0000,  /* 2EC0..2EDF */
  BrkLev2_0000,  /* 2EE0..2EFF */
  BrkLev2_0000,  /* 2F00..2F1F */
  BrkLev2_0000,  /* 2F20..2F3F */
  BrkLev2_0000,  /* 2F40..2F5F */
  BrkLev2_0000,  /* 2F60..2F7F */
  BrkLev2_0000,  /* 2F80..2F9F */
  BrkLev2_0000,  /* 2FA0..2FBF */
  BrkLev2_0000,  /* 2FC0..2FDF */
  BrkLev2_0000,  /* 2FE0..2FFF */
#define BrkLev1_3000 0x90
  BrkLev2_3000,  /* 3000..301F */
  BrkLev2_0000,  /* 3020..303F */
  BrkLev2_0000,  /* 3040..305F */
  BrkLev2_0000,  /* 3060..307F */
  BrkLev2_0000,  /* 3080..309F */
  BrkLev2_0000,  /* 30A0..30BF */
  BrkLev2_0000,  /* 30C0..30DF */
  BrkLev2_0000,  /* 30E0..30FF */
  BrkLev2_0000,  /* 3100..311F */
  BrkLev2_0000,  /* 3120..313F */
  BrkLev2_0000,  /* 3140..315F */
  BrkLev2_0000,  /* 3160..317F */
  BrkLev2_0000,  /* 3180..319F */
  BrkLev2_0000,  /* 31A0..31BF */
  BrkLev2_0000,  /* 31C0..31DF */
  BrkLev2_0000,  /* 31E0..31FF */
#define BrkLev1_FE00 0xA0
  BrkLev2_0000,  /* FE00..FE1F */
  BrkLev2_0000,  /* FE20..FE3F */
  BrkLev2_FE40,  /* FE40..FE5F */
  BrkLev2_0000,  /* FE60..FE7F */
  BrkLev2_0000,  /* FE80..FE9F */
  BrkLev2_0000,  /* FEA0..FEBF */
  BrkLev2_0000,  /* FEC0..FEDF */
  BrkLev2_0000,  /* FEE0..FEFF */
  BrkLev2_FF00,  /* FF00..FF1F */
  BrkLev2_FF20,  /* FF20..FF3F */
  BrkLev2_FF40,  /* FF40..FF5F */
  BrkLev2_FF60,  /* FF60..FF7F */
  BrkLev2_0000,  /* FF80..FF9F */
  BrkLev2_0000,  /* FFA0..FFBF */
  BrkLev2_0000,  /* FFC0..FFDF */
  BrkLev2_0000,  /* FFE0..FFFF */
};

static const PACKTAB_UINT8 BrkLev0[128*1] = {
#define BrkLev0_0000 0x0
  BrkLev1_0000,  /* 0000..01FF */
  BrkLev1_0200,  /* 0200..03FF */
  BrkLev1_0200,  /* 0400..05FF */
  BrkLev1_0200,  /* 0600..07FF */
  BrkLev1_0200,  /* 0800..09FF */
  BrkLev1_0200,  /* 0A00..0BFF */
  BrkLev1_0200,  /* 0C00..0DFF */
  BrkLev1_0E00,  /* 0E00..0FFF */
  BrkLev1_0200,  /* 1000..11FF */
  BrkLev1_0200,  /* 1200..13FF */
  BrkLev1_0200,  /* 1400..15FF */
  BrkLev1_1600,  /* 1600..17FF */
  BrkLev1_0200,  /* 1800..19FF */
  BrkLev1_0200,  /* 1A00..1BFF */
  BrkLev1_0200,  /* 1C00..1DFF */
  BrkLev1_0200,  /* 1E00..1FFF */
  BrkLev1_2000,  /* 2000..21FF */
  BrkLev1_2200,  /* 2200..23FF */
  BrkLev1_0200,  /* 2400..25FF */
  BrkLev1_2600,  /* 2600..27FF */
  BrkLev1_2800,  /* 2800..29FF */
  BrkLev1_0200,  /* 2A00..2BFF */
  BrkLev1_0200,  /* 2C00..2DFF */
  BrkLev1_2E00,  /* 2E00..2FFF */
  BrkLev1_3000,  /* 3000..31FF */
  BrkLev1_0200,  /* 3200..33FF */
  BrkLev1_0200,  /* 3400..35FF */
  BrkLev1_0200,  /* 3600..37FF */
  BrkLev1_0200,  /* 3800..39FF */
  BrkLev1_0200,  /* 3A00..3BFF */
  BrkLev1_0200,  /* 3C00..3DFF */
  BrkLev1_0200,  /* 3E00..3FFF */
  BrkLev1_0200,  /* 4000..41FF */
  BrkLev1_0200,  /* 4200..43FF */
  BrkLev1_0200,  /* 4400..45FF */
  BrkLev1_0200,  /* 4600..47FF */
  BrkLev1_0200,  /* 4800..49FF */
  BrkLev1_0200,  /* 4A00..4BFF */
  BrkLev1_0200,  /* 4C00..4DFF */
  BrkLev1_0200,  /* 4E00..4FFF */
  BrkLev1_0200,  /* 5000..51FF */
  BrkLev1_0200,  /* 5200..53FF */
  BrkLev1_0200,  /* 5400..55FF */
  BrkLev1_0200,  /* 5600..57FF */
  BrkLev1_0200,  /* 5800..59FF */
  BrkLev1_0200,  /* 5A00..5BFF */
  BrkLev1_0200,  /* 5C00..5DFF */
  BrkLev1_0200,  /* 5E00..5FFF */
  BrkLev1_0200,  /* 6000..61FF */
  BrkLev1_0200,  /* 6200..63FF */
  BrkLev1_0200,  /* 6400..65FF */
  BrkLev1_0200,  /* 6600..67FF */
  BrkLev1_0200,  /* 6800..69FF */
  BrkLev1_0200,  /* 6A00..6BFF */
  BrkLev1_0200,  /* 6C00..6DFF */
  BrkLev1_0200,  /* 6E00..6FFF */
  BrkLev1_0200,  /* 7000..71FF */
  BrkLev1_0200,  /* 7200..73FF */
  BrkLev1_0200,  /* 7400..75FF */
  BrkLev1_0200,  /* 7600..77FF */
  BrkLev1_0200,  /* 7800..79FF */
  BrkLev1_0200,  /* 7A00..7BFF */
  BrkLev1_0200,  /* 7C00..7DFF */
  BrkLev1_0200,  /* 7E00..7FFF */
  BrkLev1_0200,  /* 8000..81FF */
  BrkLev1_0200,  /* 8200..83FF */
  BrkLev1_0200,  /* 8400..85FF */
  BrkLev1_0200,  /* 8600..87FF */
  BrkLev1_0200,  /* 8800..89FF */
  BrkLev1_0200,  /* 8A00..8BFF */
  BrkLev1_0200,  /* 8C00..8DFF */
  BrkLev1_0200,  /* 8E00..8FFF */
  BrkLev1_0200,  /* 9000..91FF */
  BrkLev1_0200,  /* 9200..93FF */
  BrkLev1_0200,  /* 9400..95FF */
  BrkLev1_0200,  /* 9600..97FF */
  BrkLev1_0200,  /* 9800..99FF */
  BrkLev1_0200,  /* 9A00..9BFF */
  BrkLev1_0200,  /* 9C00..9DFF */
  BrkLev1_0200,  /* 9E00..9FFF */
  BrkLev1_0200,  /* A000..A1FF */
  BrkLev1_0200,  /* A200..A3FF */
  BrkLev1_0200,  /* A400..A5FF */
  BrkLev1_0200,  /* A600..A7FF */
  BrkLev1_0200,  /* A800..A9FF */
  BrkLev1_0200,  /* AA00..ABFF */
  BrkLev1_0200,  /* AC00..ADFF */
  BrkLev1_0200,  /* AE00..AFFF */
  BrkLev1_0200,  /* B000..B1FF */
  BrkLev1_0200,  /* B200..B3FF */
  BrkLev1_0200,  /* B400..B5FF */
  BrkLev1_0200,  /* B600..B7FF */
  BrkLev1_0200,  /* B800..B9FF */
  BrkLev1_0200,  /* BA00..BBFF */
  BrkLev1_0200,  /* BC00..BDFF */
  BrkLev1_0200,  /* BE00..BFFF */
  BrkLev1_0200,  /* C000..C1FF */
  BrkLev1_0200,  /* C200..C3FF */
  BrkLev1_0200,  /* C400..C5FF */
  BrkLev1_0200,  /* C600..C7FF */
  BrkLev1_0200,  /* C800..C9FF */
  BrkLev1_0200,  /* CA00..CBFF */
  BrkLev1_0200,  /* CC00..CDFF */
  BrkLev1_0200,  /* CE00..CFFF */
  BrkLev1_0200,  /* D000..D1FF */
  BrkLev1_0200,  /* D200..D3FF */
  BrkLev1_0200,  /* D400..D5FF */
  BrkLev1_0200,  /* D600..D7FF */
  BrkLev1_0200,  /* D800..D9FF */
  BrkLev1_0200,  /* DA00..DBFF */
  BrkLev1_0200,  /* DC00..DDFF */
  BrkLev1_0200,  /* DE00..DFFF */
  BrkLev1_0200,  /* E000..E1FF */
  BrkLev1_0200,  /* E200..E3FF */
  BrkLev1_0200,  /* E400..E5FF */
  BrkLev1_0200,  /* E600..E7FF */
  BrkLev1_0200,  /* E800..E9FF */
  BrkLev1_0200,  /* EA00..EBFF */
  BrkLev1_0200,  /* EC00..EDFF */
  BrkLev1_0200,  /* EE00..EFFF */
  BrkLev1_0200,  /* F000..F1FF */
  BrkLev1_0200,  /* F200..F3FF */
  BrkLev1_0200,  /* F400..F5FF */
  BrkLev1_0200,  /* F600..F7FF */
  BrkLev1_0200,  /* F800..F9FF */
  BrkLev1_0200,  /* FA00..FBFF */
  BrkLev1_0200,  /* FC00..FDFF */
  BrkLev1_FE00,  /* FE00..FFFF */
};

/* *INDENT-ON* */

#define FRIBIDI_GET_BRACKETS_DELTA(x) \
	((x) >= 0x10000 ? 0 :  \
	BrkLev3[((x) & 0x03) + \
	BrkLev2[((x) >> 2 & 0x07) + \
	BrkLev1[((x) >> 5 & 0x0f) + \
	BrkLev0[((x) >> 9)]]]])

#undef PACKTAB_UINT8
#undef PACKTAB_UINT16
#undef PACKTAB_UINT32

#define FRIBIDI_GET_BRACKETS(x) ((x) + FRIBIDI_GET_BRACKETS_DELTA(x))

/* End of generated brackets.tab.i */
