// AUTO-GENERATED by /home/z/my-project/scripts/gen_bitmap_font.py
// EXP-092: Bitmap Font Data for MiniAndroid Software Renderer
//
// This file contains 8x16 pixel bitmaps for all 95 printable ASCII
// characters (32..126). Each glyph is stored as 16 bytes (one per row),
// with each byte's 8 bits (MSB first) indicating which columns are dark.
//
// Generated from: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
// Do NOT edit by hand — regenerate via:
//   python3 /home/z/my-project/scripts/gen_bitmap_font.py

#pragma once

#include <cstdint>

namespace miniandroid {
namespace renderer {

// ASCII 32 = ' ' (glyph name: space)
static const uint8_t glyph_space_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0x00, // row  5
    0x00, // row  6
    0x00, // row  7
    0x00, // row  8
    0x00, // row  9
    0x00, // row 10
    0x00, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 33 = '!' (glyph name: excl)
static const uint8_t glyph_excl_bitmap[16] = {
    0x18, // row  0
    0x18, // row  1
    0x18, // row  2
    0x18, // row  3
    0x18, // row  4
    0x18, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x00, // row 11
    0x18, // row 12
    0x18, // row 13
    0x18, // row 14
    0x18, // row 15
};

// ASCII 34 = '"' (glyph name: quote)
static const uint8_t glyph_quote_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0xE7, // row  4
    0xE7, // row  5
    0xE7, // row  6
    0xE7, // row  7
    0xE7, // row  8
    0xE7, // row  9
    0xE7, // row 10
    0xE7, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 35 = '#' (glyph name: hash)
static const uint8_t glyph_hash_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x1A, // row  3
    0x1A, // row  4
    0x7F, // row  5
    0x24, // row  6
    0x24, // row  7
    0x24, // row  8
    0xFF, // row  9
    0x44, // row 10
    0x58, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 36 = '$' (glyph name: dollar)
static const uint8_t glyph_dollar_bitmap[16] = {
    0x10, // row  0
    0x7C, // row  1
    0x7C, // row  2
    0xF2, // row  3
    0x90, // row  4
    0x90, // row  5
    0x70, // row  6
    0x1E, // row  7
    0x1E, // row  8
    0x12, // row  9
    0x92, // row 10
    0x92, // row 11
    0x7E, // row 12
    0x10, // row 13
    0x10, // row 14
    0x10, // row 15
};

// ASCII 37 = '%' (glyph name: percent)
static const uint8_t glyph_percent_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x60, // row  3
    0x98, // row  4
    0x98, // row  5
    0x62, // row  6
    0x18, // row  7
    0x18, // row  8
    0x46, // row  9
    0x19, // row 10
    0x19, // row 11
    0x06, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 38 = '&' (glyph name: amp)
static const uint8_t glyph_amp_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x3C, // row  3
    0x60, // row  4
    0x60, // row  5
    0x20, // row  6
    0x78, // row  7
    0x78, // row  8
    0x59, // row  9
    0x85, // row 10
    0x42, // row 11
    0x3D, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 39 = ''' (glyph name: apos)
static const uint8_t glyph_apos_bitmap[16] = {
    0x7C, // row  0
    0x7C, // row  1
    0x7C, // row  2
    0x7C, // row  3
    0x7C, // row  4
    0x7C, // row  5
    0x7C, // row  6
    0x7C, // row  7
    0x7C, // row  8
    0x7C, // row  9
    0x7C, // row 10
    0x7C, // row 11
    0x7C, // row 12
    0x7C, // row 13
    0x7C, // row 14
    0x7C, // row 15
};

// ASCII 40 = '(' (glyph name: lparen)
static const uint8_t glyph_lparen_bitmap[16] = {
    0x18, // row  0
    0x20, // row  1
    0x20, // row  2
    0x20, // row  3
    0x20, // row  4
    0x20, // row  5
    0x20, // row  6
    0x20, // row  7
    0x20, // row  8
    0x20, // row  9
    0x20, // row 10
    0x20, // row 11
    0x20, // row 12
    0x20, // row 13
    0x20, // row 14
    0x18, // row 15
};

// ASCII 41 = ')' (glyph name: rparen)
static const uint8_t glyph_rparen_bitmap[16] = {
    0x20, // row  0
    0x18, // row  1
    0x18, // row  2
    0x18, // row  3
    0x18, // row  4
    0x18, // row  5
    0x04, // row  6
    0x04, // row  7
    0x04, // row  8
    0x04, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x18, // row 13
    0x18, // row 14
    0x20, // row 15
};

// ASCII 42 = '*' (glyph name: star)
static const uint8_t glyph_star_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x18, // row  3
    0x18, // row  4
    0xDB, // row  5
    0x3C, // row  6
    0x3C, // row  7
    0x3C, // row  8
    0x3C, // row  9
    0xDB, // row 10
    0x18, // row 11
    0x18, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 43 = '+' (glyph name: plus)
static const uint8_t glyph_plus_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x10, // row  3
    0x10, // row  4
    0x10, // row  5
    0x10, // row  6
    0xFF, // row  7
    0x10, // row  8
    0x10, // row  9
    0x10, // row 10
    0x10, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 44 = ',' (glyph name: comma)
static const uint8_t glyph_comma_bitmap[16] = {
    0x7C, // row  0
    0x7C, // row  1
    0x7C, // row  2
    0x7C, // row  3
    0x7C, // row  4
    0x7C, // row  5
    0x7C, // row  6
    0x7C, // row  7
    0x7C, // row  8
    0x7C, // row  9
    0x7C, // row 10
    0x7C, // row 11
    0x7C, // row 12
    0x7C, // row 13
    0x7C, // row 14
    0x7C, // row 15
};

// ASCII 45 = '-' (glyph name: minus)
static const uint8_t glyph_minus_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0x00, // row  5
    0xFF, // row  6
    0xFF, // row  7
    0xFF, // row  8
    0x00, // row  9
    0x00, // row 10
    0x00, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 46 = '.' (glyph name: dot)
static const uint8_t glyph_dot_bitmap[16] = {
    0xFF, // row  0
    0xFF, // row  1
    0xFF, // row  2
    0xFF, // row  3
    0xFF, // row  4
    0xFF, // row  5
    0xFF, // row  6
    0xFF, // row  7
    0xFF, // row  8
    0xFF, // row  9
    0xFF, // row 10
    0xFF, // row 11
    0xFF, // row 12
    0xFF, // row 13
    0xFF, // row 14
    0xFF, // row 15
};

// ASCII 47 = '/' (glyph name: slash)
static const uint8_t glyph_slash_bitmap[16] = {
    0x03, // row  0
    0x03, // row  1
    0x03, // row  2
    0x04, // row  3
    0x04, // row  4
    0x04, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x20, // row 10
    0x20, // row 11
    0x20, // row 12
    0xC0, // row 13
    0xC0, // row 14
    0xC0, // row 15
};

// ASCII 48 = '0' (glyph name: 0)
static const uint8_t glyph_0_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xE3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xDB, // row  7
    0xDB, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xE3, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 49 = '1' (glyph name: 1)
static const uint8_t glyph_1_bitmap[16] = {
    0x00, // row  0
    0xFC, // row  1
    0xFC, // row  2
    0x1C, // row  3
    0x1C, // row  4
    0x1C, // row  5
    0x1C, // row  6
    0x1C, // row  7
    0x1C, // row  8
    0x1C, // row  9
    0x1C, // row 10
    0x1C, // row 11
    0x1C, // row 12
    0x3F, // row 13
    0x3F, // row 14
    0x00, // row 15
};

// ASCII 50 = '2' (glyph name: 2)
static const uint8_t glyph_2_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xC7, // row  3
    0x03, // row  4
    0x03, // row  5
    0x03, // row  6
    0x04, // row  7
    0x04, // row  8
    0x18, // row  9
    0x38, // row 10
    0x38, // row 11
    0xE0, // row 12
    0xFF, // row 13
    0xFF, // row 14
    0x00, // row 15
};

// ASCII 51 = '3' (glyph name: 3)
static const uint8_t glyph_3_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xC3, // row  3
    0x03, // row  4
    0x03, // row  5
    0x07, // row  6
    0x3C, // row  7
    0x3C, // row  8
    0x03, // row  9
    0x03, // row 10
    0x03, // row 11
    0xC3, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 52 = '4' (glyph name: 4)
static const uint8_t glyph_4_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x08, // row  2
    0x18, // row  3
    0x18, // row  4
    0x18, // row  5
    0x68, // row  6
    0x88, // row  7
    0x88, // row  8
    0x88, // row  9
    0xFF, // row 10
    0x08, // row 11
    0x08, // row 12
    0x08, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 53 = '5' (glyph name: 5)
static const uint8_t glyph_5_bitmap[16] = {
    0x00, // row  0
    0xFF, // row  1
    0xFF, // row  2
    0xC0, // row  3
    0xC0, // row  4
    0xC0, // row  5
    0xFC, // row  6
    0x07, // row  7
    0x07, // row  8
    0x03, // row  9
    0x03, // row 10
    0x03, // row 11
    0xC7, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 54 = '6' (glyph name: 6)
static const uint8_t glyph_6_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xE3, // row  3
    0xC0, // row  4
    0xC0, // row  5
    0xDC, // row  6
    0xE3, // row  7
    0xE3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xE3, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 55 = '7' (glyph name: 7)
static const uint8_t glyph_7_bitmap[16] = {
    0x00, // row  0
    0xFF, // row  1
    0xFF, // row  2
    0x03, // row  3
    0x07, // row  4
    0x07, // row  5
    0x04, // row  6
    0x04, // row  7
    0x04, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x20, // row 13
    0x20, // row 14
    0x00, // row 15
};

// ASCII 56 = '8' (glyph name: 8)
static const uint8_t glyph_8_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xE3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xE3, // row  6
    0x3C, // row  7
    0x3C, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 57 = '9' (glyph name: 9)
static const uint8_t glyph_9_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC3, // row  8
    0x3F, // row  9
    0x03, // row 10
    0x03, // row 11
    0x07, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 58 = ':' (glyph name: colon)
static const uint8_t glyph_colon_bitmap[16] = {
    0x38, // row  0
    0x38, // row  1
    0x38, // row  2
    0x38, // row  3
    0x38, // row  4
    0x00, // row  5
    0x00, // row  6
    0x00, // row  7
    0x00, // row  8
    0x00, // row  9
    0x00, // row 10
    0x38, // row 11
    0x38, // row 12
    0x38, // row 13
    0x38, // row 14
    0x38, // row 15
};

// ASCII 59 = ';' (glyph name: semicolon)
static const uint8_t glyph_semicolon_bitmap[16] = {
    0x18, // row  0
    0x18, // row  1
    0x18, // row  2
    0x18, // row  3
    0x18, // row  4
    0x00, // row  5
    0x00, // row  6
    0x00, // row  7
    0x00, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x18, // row 13
    0x18, // row 14
    0x18, // row 15
};

// ASCII 60 = '<' (glyph name: lt)
static const uint8_t glyph_lt_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x07, // row  4
    0x1E, // row  5
    0x1E, // row  6
    0xE0, // row  7
    0xE0, // row  8
    0x1E, // row  9
    0x1E, // row 10
    0x07, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 61 = '=' (glyph name: eq)
static const uint8_t glyph_eq_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0x00, // row  5
    0xFF, // row  6
    0x00, // row  7
    0x00, // row  8
    0xFF, // row  9
    0x00, // row 10
    0x00, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 62 = '>' (glyph name: gt)
static const uint8_t glyph_gt_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0xC0, // row  3
    0xC0, // row  4
    0x38, // row  5
    0x07, // row  6
    0x07, // row  7
    0x07, // row  8
    0x07, // row  9
    0x38, // row 10
    0xC0, // row 11
    0xC0, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 63 = '?' (glyph name: question)
static const uint8_t glyph_question_bitmap[16] = {
    0xF8, // row  0
    0xF8, // row  1
    0x06, // row  2
    0x06, // row  3
    0x06, // row  4
    0x08, // row  5
    0x08, // row  6
    0x30, // row  7
    0x30, // row  8
    0x30, // row  9
    0x30, // row 10
    0x00, // row 11
    0x30, // row 12
    0x30, // row 13
    0x30, // row 14
    0x30, // row 15
};

// ASCII 64 = '@' (glyph name: at)
static const uint8_t glyph_at_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x3E, // row  2
    0x62, // row  3
    0x41, // row  4
    0x9F, // row  5
    0x99, // row  6
    0x99, // row  7
    0x99, // row  8
    0x9F, // row  9
    0x40, // row 10
    0x60, // row 11
    0x1E, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 65 = 'A' (glyph name: A)
static const uint8_t glyph_A_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x18, // row  3
    0x3C, // row  4
    0x24, // row  5
    0x24, // row  6
    0x26, // row  7
    0x26, // row  8
    0x42, // row  9
    0x7E, // row 10
    0x43, // row 11
    0xC1, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 66 = 'B' (glyph name: B)
static const uint8_t glyph_B_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xF8, // row  2
    0x86, // row  3
    0x86, // row  4
    0x86, // row  5
    0x86, // row  6
    0xF8, // row  7
    0xF8, // row  8
    0x86, // row  9
    0x87, // row 10
    0x86, // row 11
    0x86, // row 12
    0xFE, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 67 = 'C' (glyph name: C)
static const uint8_t glyph_C_bitmap[16] = {
    0x00, // row  0
    0x1F, // row  1
    0x1F, // row  2
    0x20, // row  3
    0xC0, // row  4
    0xC0, // row  5
    0xC0, // row  6
    0xC0, // row  7
    0xC0, // row  8
    0xC0, // row  9
    0xC0, // row 10
    0xC0, // row 11
    0x20, // row 12
    0x1F, // row 13
    0x1F, // row 14
    0x00, // row 15
};

// ASCII 68 = 'D' (glyph name: D)
static const uint8_t glyph_D_bitmap[16] = {
    0x00, // row  0
    0xFC, // row  1
    0xFC, // row  2
    0xC7, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC7, // row 12
    0xFC, // row 13
    0xFC, // row 14
    0x00, // row 15
};

// ASCII 69 = 'E' (glyph name: E)
static const uint8_t glyph_E_bitmap[16] = {
    0x00, // row  0
    0xFF, // row  1
    0xFF, // row  2
    0xC0, // row  3
    0xC0, // row  4
    0xC0, // row  5
    0xC0, // row  6
    0xFF, // row  7
    0xFF, // row  8
    0xC0, // row  9
    0xC0, // row 10
    0xC0, // row 11
    0xC0, // row 12
    0xFF, // row 13
    0xFF, // row 14
    0x00, // row 15
};

// ASCII 70 = 'F' (glyph name: F)
static const uint8_t glyph_F_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xFF, // row  2
    0xE0, // row  3
    0xE0, // row  4
    0xE0, // row  5
    0xE0, // row  6
    0xFE, // row  7
    0xFE, // row  8
    0xE0, // row  9
    0xE0, // row 10
    0xE0, // row 11
    0xE0, // row 12
    0xE0, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 71 = 'G' (glyph name: G)
static const uint8_t glyph_G_bitmap[16] = {
    0x00, // row  0
    0x3F, // row  1
    0x3F, // row  2
    0xE0, // row  3
    0xC0, // row  4
    0xC0, // row  5
    0xC0, // row  6
    0xC7, // row  7
    0xC7, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xE3, // row 12
    0x3F, // row 13
    0x3F, // row 14
    0x00, // row 15
};

// ASCII 72 = 'H' (glyph name: H)
static const uint8_t glyph_H_bitmap[16] = {
    0x00, // row  0
    0xC3, // row  1
    0xC3, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xFF, // row  7
    0xFF, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0xC3, // row 13
    0xC3, // row 14
    0x00, // row 15
};

// ASCII 73 = 'I' (glyph name: I)
static const uint8_t glyph_I_bitmap[16] = {
    0x00, // row  0
    0xFF, // row  1
    0xFF, // row  2
    0x18, // row  3
    0x18, // row  4
    0x18, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0xFF, // row 13
    0xFF, // row 14
    0x00, // row 15
};

// ASCII 74 = 'J' (glyph name: J)
static const uint8_t glyph_J_bitmap[16] = {
    0x00, // row  0
    0x3F, // row  1
    0x3F, // row  2
    0x07, // row  3
    0x07, // row  4
    0x07, // row  5
    0x07, // row  6
    0x07, // row  7
    0x07, // row  8
    0x07, // row  9
    0x07, // row 10
    0x07, // row 11
    0x04, // row 12
    0xFC, // row 13
    0xFC, // row 14
    0x00, // row 15
};

// ASCII 75 = 'K' (glyph name: K)
static const uint8_t glyph_K_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x87, // row  2
    0x8E, // row  3
    0x8E, // row  4
    0x98, // row  5
    0xF0, // row  6
    0xF0, // row  7
    0xF0, // row  8
    0x88, // row  9
    0x8E, // row 10
    0x86, // row 11
    0x86, // row 12
    0x87, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 76 = 'L' (glyph name: L)
static const uint8_t glyph_L_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x80, // row  2
    0x80, // row  3
    0x80, // row  4
    0x80, // row  5
    0x80, // row  6
    0x80, // row  7
    0x80, // row  8
    0x80, // row  9
    0x80, // row 10
    0x80, // row 11
    0x80, // row 12
    0xFF, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 77 = 'M' (glyph name: M)
static const uint8_t glyph_M_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0xC3, // row  3
    0xE3, // row  4
    0xE7, // row  5
    0xE5, // row  6
    0xDD, // row  7
    0xDD, // row  8
    0xD9, // row  9
    0xC1, // row 10
    0xC1, // row 11
    0xC1, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 78 = 'N' (glyph name: N)
static const uint8_t glyph_N_bitmap[16] = {
    0x00, // row  0
    0xE3, // row  1
    0xE3, // row  2
    0xE3, // row  3
    0xE3, // row  4
    0xE3, // row  5
    0xDB, // row  6
    0xDB, // row  7
    0xDB, // row  8
    0xC7, // row  9
    0xC7, // row 10
    0xC7, // row 11
    0xC7, // row 12
    0xC3, // row 13
    0xC3, // row 14
    0x00, // row 15
};

// ASCII 79 = 'O' (glyph name: O)
static const uint8_t glyph_O_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x78, // row  2
    0xE6, // row  3
    0xE6, // row  4
    0x86, // row  5
    0x86, // row  6
    0x87, // row  7
    0x87, // row  8
    0x86, // row  9
    0x86, // row 10
    0xE6, // row 11
    0xE6, // row 12
    0x78, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 80 = 'P' (glyph name: P)
static const uint8_t glyph_P_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xFE, // row  2
    0x86, // row  3
    0x86, // row  4
    0x87, // row  5
    0x86, // row  6
    0xFE, // row  7
    0xFE, // row  8
    0x80, // row  9
    0x80, // row 10
    0x80, // row 11
    0x80, // row 12
    0x80, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 81 = 'Q' (glyph name: Q)
static const uint8_t glyph_Q_bitmap[16] = {
    0x78, // row  0
    0xE6, // row  1
    0xE6, // row  2
    0x86, // row  3
    0x86, // row  4
    0x87, // row  5
    0x87, // row  6
    0x86, // row  7
    0x86, // row  8
    0x86, // row  9
    0xE6, // row 10
    0x78, // row 11
    0x0E, // row 12
    0x0E, // row 13
    0x06, // row 14
    0x00, // row 15
};

// ASCII 82 = 'R' (glyph name: R)
static const uint8_t glyph_R_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xF8, // row  2
    0x86, // row  3
    0x86, // row  4
    0x86, // row  5
    0x86, // row  6
    0xF8, // row  7
    0xF8, // row  8
    0x8E, // row  9
    0x86, // row 10
    0x87, // row 11
    0x87, // row 12
    0x81, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 83 = 'S' (glyph name: S)
static const uint8_t glyph_S_bitmap[16] = {
    0x00, // row  0
    0x3C, // row  1
    0x3C, // row  2
    0xC3, // row  3
    0xC0, // row  4
    0xC0, // row  5
    0xE0, // row  6
    0x3C, // row  7
    0x3C, // row  8
    0x03, // row  9
    0x03, // row 10
    0x03, // row 11
    0xC3, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 84 = 'T' (glyph name: T)
static const uint8_t glyph_T_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0xFF, // row  3
    0x18, // row  4
    0x18, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 85 = 'U' (glyph name: U)
static const uint8_t glyph_U_bitmap[16] = {
    0x00, // row  0
    0xC3, // row  1
    0xC3, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0x3C, // row 13
    0x3C, // row 14
    0x00, // row 15
};

// ASCII 86 = 'V' (glyph name: V)
static const uint8_t glyph_V_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0xC1, // row  3
    0x42, // row  4
    0x42, // row  5
    0x42, // row  6
    0x22, // row  7
    0x22, // row  8
    0x24, // row  9
    0x24, // row 10
    0x3C, // row 11
    0x18, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 87 = 'W' (glyph name: W)
static const uint8_t glyph_W_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x81, // row  3
    0x81, // row  4
    0x99, // row  5
    0x5D, // row  6
    0x45, // row  7
    0x45, // row  8
    0x66, // row  9
    0x66, // row 10
    0x66, // row 11
    0x62, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 88 = 'X' (glyph name: X)
static const uint8_t glyph_X_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x43, // row  3
    0x62, // row  4
    0x24, // row  5
    0x1C, // row  6
    0x1C, // row  7
    0x1C, // row  8
    0x3C, // row  9
    0x26, // row 10
    0x42, // row 11
    0xC1, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 89 = 'Y' (glyph name: Y)
static const uint8_t glyph_Y_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0xC3, // row  3
    0x42, // row  4
    0x26, // row  5
    0x3C, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 90 = 'Z' (glyph name: Z)
static const uint8_t glyph_Z_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xFF, // row  2
    0x06, // row  3
    0x06, // row  4
    0x0E, // row  5
    0x08, // row  6
    0x10, // row  7
    0x10, // row  8
    0x10, // row  9
    0x60, // row 10
    0x80, // row 11
    0x80, // row 12
    0xFF, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 91 = '[' (glyph name: lbracket)
static const uint8_t glyph_lbracket_bitmap[16] = {
    0x38, // row  0
    0x20, // row  1
    0x20, // row  2
    0x20, // row  3
    0x20, // row  4
    0x20, // row  5
    0x20, // row  6
    0x20, // row  7
    0x20, // row  8
    0x20, // row  9
    0x20, // row 10
    0x20, // row 11
    0x20, // row 12
    0x20, // row 13
    0x20, // row 14
    0x38, // row 15
};

// ASCII 92 = '\' (glyph name: backslash)
static const uint8_t glyph_backslash_bitmap[16] = {
    0xC0, // row  0
    0xC0, // row  1
    0xC0, // row  2
    0x20, // row  3
    0x20, // row  4
    0x20, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x04, // row 10
    0x04, // row 11
    0x04, // row 12
    0x03, // row 13
    0x03, // row 14
    0x03, // row 15
};

// ASCII 93 = ']' (glyph name: rbracket)
static const uint8_t glyph_rbracket_bitmap[16] = {
    0x3C, // row  0
    0x1C, // row  1
    0x1C, // row  2
    0x1C, // row  3
    0x1C, // row  4
    0x1C, // row  5
    0x1C, // row  6
    0x1C, // row  7
    0x1C, // row  8
    0x1C, // row  9
    0x1C, // row 10
    0x1C, // row 11
    0x1C, // row 12
    0x1C, // row 13
    0x1C, // row 14
    0x3C, // row 15
};

// ASCII 94 = '^' (glyph name: caret)
static const uint8_t glyph_caret_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0x1C, // row  5
    0x1C, // row  6
    0x24, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0x00, // row 10
    0x00, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 95 = '_' (glyph name: underscore)
static const uint8_t glyph_underscore_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0x00, // row  5
    0x00, // row  6
    0xFF, // row  7
    0x00, // row  8
    0x00, // row  9
    0x00, // row 10
    0x00, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 96 = '`' (glyph name: backtick)
static const uint8_t glyph_backtick_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0xF0, // row  4
    0xF0, // row  5
    0xF0, // row  6
    0xF0, // row  7
    0x0F, // row  8
    0x0F, // row  9
    0x0F, // row 10
    0x0F, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 97 = 'a' (glyph name: a)
static const uint8_t glyph_a_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xFC, // row  2
    0xFC, // row  3
    0x03, // row  4
    0x03, // row  5
    0x03, // row  6
    0x3F, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0x3B, // row 11
    0x3B, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 98 = 'b' (glyph name: b)
static const uint8_t glyph_b_bitmap[16] = {
    0xC0, // row  0
    0xC0, // row  1
    0xC0, // row  2
    0xC0, // row  3
    0xC0, // row  4
    0xDC, // row  5
    0xE3, // row  6
    0xE3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0xE3, // row 13
    0xFC, // row 14
    0xFC, // row 15
};

// ASCII 99 = 'c' (glyph name: c)
static const uint8_t glyph_c_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x1F, // row  2
    0x1F, // row  3
    0x20, // row  4
    0xC0, // row  5
    0xC0, // row  6
    0xC0, // row  7
    0xC0, // row  8
    0xC0, // row  9
    0x20, // row 10
    0x1F, // row 11
    0x1F, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 100 = 'd' (glyph name: d)
static const uint8_t glyph_d_bitmap[16] = {
    0x03, // row  0
    0x03, // row  1
    0x03, // row  2
    0x03, // row  3
    0x03, // row  4
    0x3F, // row  5
    0xC7, // row  6
    0xC7, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0xC7, // row 13
    0x3B, // row 14
    0x3B, // row 15
};

// ASCII 101 = 'e' (glyph name: e)
static const uint8_t glyph_e_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x78, // row  3
    0xE6, // row  4
    0xE6, // row  5
    0x86, // row  6
    0xFF, // row  7
    0x80, // row  8
    0xE6, // row  9
    0xE6, // row 10
    0x78, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 102 = 'f' (glyph name: f)
static const uint8_t glyph_f_bitmap[16] = {
    0x07, // row  0
    0x07, // row  1
    0x18, // row  2
    0x18, // row  3
    0x18, // row  4
    0xFF, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x18, // row 13
    0x18, // row 14
    0x18, // row 15
};

// ASCII 103 = 'g' (glyph name: g)
static const uint8_t glyph_g_bitmap[16] = {
    0x3F, // row  0
    0x3F, // row  1
    0xC7, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC7, // row  8
    0xC7, // row  9
    0x3B, // row 10
    0x03, // row 11
    0x03, // row 12
    0x07, // row 13
    0x3C, // row 14
    0x3C, // row 15
};

// ASCII 104 = 'h' (glyph name: h)
static const uint8_t glyph_h_bitmap[16] = {
    0xC0, // row  0
    0xC0, // row  1
    0xC0, // row  2
    0xC0, // row  3
    0xC0, // row  4
    0xDC, // row  5
    0xE3, // row  6
    0xE3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0xC3, // row 13
    0xC3, // row 14
    0xC3, // row 15
};

// ASCII 105 = 'i' (glyph name: i)
static const uint8_t glyph_i_bitmap[16] = {
    0x18, // row  0
    0x18, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0xF8, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x18, // row 13
    0xFF, // row 14
    0xFF, // row 15
};

// ASCII 106 = 'j' (glyph name: j)
static const uint8_t glyph_j_bitmap[16] = {
    0x04, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x3C, // row  4
    0x04, // row  5
    0x04, // row  6
    0x04, // row  7
    0x04, // row  8
    0x04, // row  9
    0x04, // row 10
    0x04, // row 11
    0x1C, // row 12
    0x1C, // row 13
    0x18, // row 14
    0x78, // row 15
};

// ASCII 107 = 'k' (glyph name: k)
static const uint8_t glyph_k_bitmap[16] = {
    0x00, // row  0
    0xE0, // row  1
    0xE0, // row  2
    0xE0, // row  3
    0xE0, // row  4
    0xE6, // row  5
    0xE8, // row  6
    0xF0, // row  7
    0xF0, // row  8
    0xF8, // row  9
    0xE8, // row 10
    0xE6, // row 11
    0xE6, // row 12
    0xE7, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 108 = 'l' (glyph name: l)
static const uint8_t glyph_l_bitmap[16] = {
    0xF8, // row  0
    0xF8, // row  1
    0x18, // row  2
    0x18, // row  3
    0x18, // row  4
    0x18, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x18, // row 13
    0x1F, // row 14
    0x1F, // row 15
};

// ASCII 109 = 'm' (glyph name: m)
static const uint8_t glyph_m_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0xFE, // row  3
    0x91, // row  4
    0x91, // row  5
    0x91, // row  6
    0x91, // row  7
    0x91, // row  8
    0x91, // row  9
    0x91, // row 10
    0x91, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 110 = 'n' (glyph name: n)
static const uint8_t glyph_n_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xDC, // row  2
    0xDC, // row  3
    0xE3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xC3, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 111 = 'o' (glyph name: o)
static const uint8_t glyph_o_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x3C, // row  2
    0x3C, // row  3
    0xE3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xE3, // row 10
    0x3C, // row 11
    0x3C, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 112 = 'p' (glyph name: p)
static const uint8_t glyph_p_bitmap[16] = {
    0xFC, // row  0
    0xFC, // row  1
    0xE3, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xE3, // row  8
    0xE3, // row  9
    0xFC, // row 10
    0xC0, // row 11
    0xC0, // row 12
    0xC0, // row 13
    0xC0, // row 14
    0xC0, // row 15
};

// ASCII 113 = 'q' (glyph name: q)
static const uint8_t glyph_q_bitmap[16] = {
    0x3F, // row  0
    0x3F, // row  1
    0xE7, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xE7, // row  8
    0xE7, // row  9
    0x3F, // row 10
    0x03, // row 11
    0x03, // row 12
    0x03, // row 13
    0x03, // row 14
    0x03, // row 15
};

// ASCII 114 = 'r' (glyph name: r)
static const uint8_t glyph_r_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xFF, // row  2
    0xFF, // row  3
    0xE0, // row  4
    0xC0, // row  5
    0xC0, // row  6
    0xC0, // row  7
    0xC0, // row  8
    0xC0, // row  9
    0xC0, // row 10
    0xC0, // row 11
    0xC0, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 115 = 's' (glyph name: s)
static const uint8_t glyph_s_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x3C, // row  2
    0x3C, // row  3
    0xE3, // row  4
    0xE0, // row  5
    0xE0, // row  6
    0x3C, // row  7
    0x03, // row  8
    0x03, // row  9
    0xC3, // row 10
    0x3C, // row 11
    0x3C, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 116 = 't' (glyph name: t)
static const uint8_t glyph_t_bitmap[16] = {
    0x00, // row  0
    0x18, // row  1
    0x18, // row  2
    0x18, // row  3
    0xFF, // row  4
    0xFF, // row  5
    0x18, // row  6
    0x18, // row  7
    0x18, // row  8
    0x18, // row  9
    0x18, // row 10
    0x18, // row 11
    0x18, // row 12
    0x1F, // row 13
    0x1F, // row 14
    0x00, // row 15
};

// ASCII 117 = 'u' (glyph name: u)
static const uint8_t glyph_u_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xC3, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xC3, // row  5
    0xC3, // row  6
    0xC3, // row  7
    0xC3, // row  8
    0xC3, // row  9
    0xE3, // row 10
    0x3B, // row 11
    0x3B, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 118 = 'v' (glyph name: v)
static const uint8_t glyph_v_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xC3, // row  2
    0xC3, // row  3
    0xC3, // row  4
    0xE3, // row  5
    0xE3, // row  6
    0x24, // row  7
    0x24, // row  8
    0x24, // row  9
    0x3C, // row 10
    0x18, // row 11
    0x18, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 119 = 'w' (glyph name: w)
static const uint8_t glyph_w_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x81, // row  4
    0x81, // row  5
    0x59, // row  6
    0x5A, // row  7
    0x5A, // row  8
    0x66, // row  9
    0x66, // row 10
    0x62, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 120 = 'x' (glyph name: x)
static const uint8_t glyph_x_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xC3, // row  2
    0xC3, // row  3
    0x24, // row  4
    0x3C, // row  5
    0x3C, // row  6
    0x18, // row  7
    0x3C, // row  8
    0x3C, // row  9
    0x23, // row 10
    0xC3, // row 11
    0xC3, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 121 = 'y' (glyph name: y)
static const uint8_t glyph_y_bitmap[16] = {
    0x00, // row  0
    0x87, // row  1
    0x86, // row  2
    0x86, // row  3
    0xE6, // row  4
    0x6E, // row  5
    0x68, // row  6
    0x18, // row  7
    0x18, // row  8
    0x10, // row  9
    0x10, // row 10
    0x10, // row 11
    0x10, // row 12
    0xE0, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 122 = 'z' (glyph name: z)
static const uint8_t glyph_z_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0xFF, // row  2
    0xFF, // row  3
    0x03, // row  4
    0x04, // row  5
    0x04, // row  6
    0x18, // row  7
    0x20, // row  8
    0x20, // row  9
    0x20, // row 10
    0xFF, // row 11
    0xFF, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// ASCII 123 = '{' (glyph name: lbrace)
static const uint8_t glyph_lbrace_bitmap[16] = {
    0x0E, // row  0
    0x10, // row  1
    0x10, // row  2
    0x10, // row  3
    0x10, // row  4
    0x10, // row  5
    0x10, // row  6
    0xF0, // row  7
    0xF0, // row  8
    0x10, // row  9
    0x10, // row 10
    0x10, // row 11
    0x10, // row 12
    0x10, // row 13
    0x10, // row 14
    0x0E, // row 15
};

// ASCII 124 = '|' (glyph name: pipe)
static const uint8_t glyph_pipe_bitmap[16] = {
    0x10, // row  0
    0x10, // row  1
    0x10, // row  2
    0x10, // row  3
    0x10, // row  4
    0x10, // row  5
    0x10, // row  6
    0x10, // row  7
    0x10, // row  8
    0x10, // row  9
    0x10, // row 10
    0x10, // row 11
    0x10, // row 12
    0x10, // row 13
    0x10, // row 14
    0x10, // row 15
};

// ASCII 125 = '}' (glyph name: rbrace)
static const uint8_t glyph_rbrace_bitmap[16] = {
    0xF0, // row  0
    0x10, // row  1
    0x10, // row  2
    0x10, // row  3
    0x10, // row  4
    0x10, // row  5
    0x10, // row  6
    0x0E, // row  7
    0x0E, // row  8
    0x10, // row  9
    0x10, // row 10
    0x10, // row 11
    0x10, // row 12
    0x10, // row 13
    0x10, // row 14
    0xF0, // row 15
};

// ASCII 126 = '~' (glyph name: tilde)
static const uint8_t glyph_tilde_bitmap[16] = {
    0x00, // row  0
    0x00, // row  1
    0x00, // row  2
    0x00, // row  3
    0x00, // row  4
    0x00, // row  5
    0xF8, // row  6
    0x07, // row  7
    0x07, // row  8
    0x00, // row  9
    0x00, // row 10
    0x00, // row 11
    0x00, // row 12
    0x00, // row 13
    0x00, // row 14
    0x00, // row 15
};

// Lookup table: index i (0..94) corresponds to ASCII (i+32)
// Each entry is a pointer to the bitmap data and the character.
struct BitmapGlyphEntry {
    char character;
    int width;
    int height;
    int advance;
    const uint8_t* bitmap;
};

static const BitmapGlyphEntry bitmap_font_table[95] = {
    { ' ', 8, 16, 4, glyph_space_bitmap }, // ASCII 32
    { '!', 8, 16, 3, glyph_excl_bitmap }, // ASCII 33
    { '"', 8, 16, 6, glyph_quote_bitmap }, // ASCII 34
    { '#', 8, 16, 6, glyph_hash_bitmap }, // ASCII 35
    { '$', 8, 16, 6, glyph_dollar_bitmap }, // ASCII 36
    { '%', 8, 16, 6, glyph_percent_bitmap }, // ASCII 37
    { '&', 8, 16, 6, glyph_amp_bitmap }, // ASCII 38
    { '\'', 8, 16, 3, glyph_apos_bitmap }, // ASCII 39
    { '(', 8, 16, 6, glyph_lparen_bitmap }, // ASCII 40
    { ')', 8, 16, 6, glyph_rparen_bitmap }, // ASCII 41
    { '*', 8, 16, 6, glyph_star_bitmap }, // ASCII 42
    { '+', 8, 16, 6, glyph_plus_bitmap }, // ASCII 43
    { ',', 8, 16, 3, glyph_comma_bitmap }, // ASCII 44
    { '-', 8, 16, 6, glyph_minus_bitmap }, // ASCII 45
    { '.', 8, 16, 3, glyph_dot_bitmap }, // ASCII 46
    { '/', 8, 16, 6, glyph_slash_bitmap }, // ASCII 47
    { '0', 8, 16, 7, glyph_0_bitmap }, // ASCII 48
    { '1', 8, 16, 7, glyph_1_bitmap }, // ASCII 49
    { '2', 8, 16, 7, glyph_2_bitmap }, // ASCII 50
    { '3', 8, 16, 7, glyph_3_bitmap }, // ASCII 51
    { '4', 8, 16, 7, glyph_4_bitmap }, // ASCII 52
    { '5', 8, 16, 7, glyph_5_bitmap }, // ASCII 53
    { '6', 8, 16, 7, glyph_6_bitmap }, // ASCII 54
    { '7', 8, 16, 7, glyph_7_bitmap }, // ASCII 55
    { '8', 8, 16, 7, glyph_8_bitmap }, // ASCII 56
    { '9', 8, 16, 7, glyph_9_bitmap }, // ASCII 57
    { ':', 8, 16, 3, glyph_colon_bitmap }, // ASCII 58
    { ';', 8, 16, 3, glyph_semicolon_bitmap }, // ASCII 59
    { '<', 8, 16, 6, glyph_lt_bitmap }, // ASCII 60
    { '=', 8, 16, 6, glyph_eq_bitmap }, // ASCII 61
    { '>', 8, 16, 6, glyph_gt_bitmap }, // ASCII 62
    { '?', 8, 16, 6, glyph_question_bitmap }, // ASCII 63
    { '@', 8, 16, 6, glyph_at_bitmap }, // ASCII 64
    { 'A', 8, 16, 7, glyph_A_bitmap }, // ASCII 65
    { 'B', 8, 16, 7, glyph_B_bitmap }, // ASCII 66
    { 'C', 8, 16, 7, glyph_C_bitmap }, // ASCII 67
    { 'D', 8, 16, 7, glyph_D_bitmap }, // ASCII 68
    { 'E', 8, 16, 7, glyph_E_bitmap }, // ASCII 69
    { 'F', 8, 16, 7, glyph_F_bitmap }, // ASCII 70
    { 'G', 8, 16, 7, glyph_G_bitmap }, // ASCII 71
    { 'H', 8, 16, 7, glyph_H_bitmap }, // ASCII 72
    { 'I', 8, 16, 7, glyph_I_bitmap }, // ASCII 73
    { 'J', 8, 16, 7, glyph_J_bitmap }, // ASCII 74
    { 'K', 8, 16, 7, glyph_K_bitmap }, // ASCII 75
    { 'L', 8, 16, 7, glyph_L_bitmap }, // ASCII 76
    { 'M', 8, 16, 7, glyph_M_bitmap }, // ASCII 77
    { 'N', 8, 16, 7, glyph_N_bitmap }, // ASCII 78
    { 'O', 8, 16, 7, glyph_O_bitmap }, // ASCII 79
    { 'P', 8, 16, 7, glyph_P_bitmap }, // ASCII 80
    { 'Q', 8, 16, 7, glyph_Q_bitmap }, // ASCII 81
    { 'R', 8, 16, 7, glyph_R_bitmap }, // ASCII 82
    { 'S', 8, 16, 7, glyph_S_bitmap }, // ASCII 83
    { 'T', 8, 16, 7, glyph_T_bitmap }, // ASCII 84
    { 'U', 8, 16, 7, glyph_U_bitmap }, // ASCII 85
    { 'V', 8, 16, 7, glyph_V_bitmap }, // ASCII 86
    { 'W', 8, 16, 7, glyph_W_bitmap }, // ASCII 87
    { 'X', 8, 16, 7, glyph_X_bitmap }, // ASCII 88
    { 'Y', 8, 16, 7, glyph_Y_bitmap }, // ASCII 89
    { 'Z', 8, 16, 7, glyph_Z_bitmap }, // ASCII 90
    { '[', 8, 16, 6, glyph_lbracket_bitmap }, // ASCII 91
    { '\\', 8, 16, 6, glyph_backslash_bitmap }, // ASCII 92
    { ']', 8, 16, 6, glyph_rbracket_bitmap }, // ASCII 93
    { '^', 8, 16, 6, glyph_caret_bitmap }, // ASCII 94
    { '_', 8, 16, 6, glyph_underscore_bitmap }, // ASCII 95
    { '`', 8, 16, 6, glyph_backtick_bitmap }, // ASCII 96
    { 'a', 8, 16, 7, glyph_a_bitmap }, // ASCII 97
    { 'b', 8, 16, 7, glyph_b_bitmap }, // ASCII 98
    { 'c', 8, 16, 7, glyph_c_bitmap }, // ASCII 99
    { 'd', 8, 16, 7, glyph_d_bitmap }, // ASCII 100
    { 'e', 8, 16, 7, glyph_e_bitmap }, // ASCII 101
    { 'f', 8, 16, 7, glyph_f_bitmap }, // ASCII 102
    { 'g', 8, 16, 7, glyph_g_bitmap }, // ASCII 103
    { 'h', 8, 16, 7, glyph_h_bitmap }, // ASCII 104
    { 'i', 8, 16, 7, glyph_i_bitmap }, // ASCII 105
    { 'j', 8, 16, 7, glyph_j_bitmap }, // ASCII 106
    { 'k', 8, 16, 7, glyph_k_bitmap }, // ASCII 107
    { 'l', 8, 16, 7, glyph_l_bitmap }, // ASCII 108
    { 'm', 8, 16, 7, glyph_m_bitmap }, // ASCII 109
    { 'n', 8, 16, 7, glyph_n_bitmap }, // ASCII 110
    { 'o', 8, 16, 7, glyph_o_bitmap }, // ASCII 111
    { 'p', 8, 16, 7, glyph_p_bitmap }, // ASCII 112
    { 'q', 8, 16, 7, glyph_q_bitmap }, // ASCII 113
    { 'r', 8, 16, 7, glyph_r_bitmap }, // ASCII 114
    { 's', 8, 16, 7, glyph_s_bitmap }, // ASCII 115
    { 't', 8, 16, 7, glyph_t_bitmap }, // ASCII 116
    { 'u', 8, 16, 7, glyph_u_bitmap }, // ASCII 117
    { 'v', 8, 16, 7, glyph_v_bitmap }, // ASCII 118
    { 'w', 8, 16, 7, glyph_w_bitmap }, // ASCII 119
    { 'x', 8, 16, 7, glyph_x_bitmap }, // ASCII 120
    { 'y', 8, 16, 7, glyph_y_bitmap }, // ASCII 121
    { 'z', 8, 16, 7, glyph_z_bitmap }, // ASCII 122
    { '{', 8, 16, 6, glyph_lbrace_bitmap }, // ASCII 123
    { '|', 8, 16, 3, glyph_pipe_bitmap }, // ASCII 124
    { '}', 8, 16, 6, glyph_rbrace_bitmap }, // ASCII 125
    { '~', 8, 16, 6, glyph_tilde_bitmap }, // ASCII 126
};

}  // namespace renderer
}  // namespace miniandroid
